### ISSUE TITLE
Segfault on undo

### ISSUE THREAD

**Issue by JA-Bar** [lukas-reineke/indent-blankline.nvim#100]
Hello, I love the plugin!

However, I found a case where it results in a segfault every time, and this has happened quite frequently.

To replicate, create a file, then place two statements in an indent, say two prints in a function like this:

```python
#example.py
def some_function(args):
    print("stetement above")

    print("statement below")
```

Then in normal mode place the cursor in the first print statement, press `o` to start writing below, then `enter` while in insert mode to go down one line further, then write some statement in the middle, enter normal mode, delete it with let's say: `dap` in normal mode, and then repeadetely press `u` for undo. This will result in a segfault right before the print statement is deleted.

```python
#example.py
def some_function(args):
    print("stetement above followed by an empty line")

    print("This will segfault when undone")

    print("statement below preceded by an empty line")
```

I tried to simplify the situation under which this occurs as much as I could, but this is as far as I got.

`nvim --version`
```
NVIM v0.5.0-dev+1282-gfbe18d9ca
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/john/neovim/build/config -I/home/john/neovim/src -I/home/john/neovim/.deps/usr/include -I/usr/include -I/home/john/neovim/build/src/nvim/auto -I/home/john/neovim/build/include
Compiled by root@John-Lap

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

```

And my plugin settings are:
```
vim.g.indent_blankline_show_trailing_blankline_indent = false
vim.g.indent_blankline_use_treesitter = false
vim.g.indent_blankline_char = '▏'
```

If there's a way to help I'll try to do so.

**Comment by lukas-reineke** [comment]
I can't reproduce.

Also, this does not seem to be related to this plugin.
What makes you think indent-blankline.nvim causes the issue?

**Comment by JA-Bar** [comment]
Interesting...

I simplified the case where this occurred and observed that the segfault only happened on indented code, I tried both disabling this plugin and uninstalling it, and both of the options solved the issue, so I figured it was the plugin.

Perhaps it's some weird interaction and not directly attributed to the plugin itself, maybe closing the issue and I'll try to isolate the case would be the best?

**Comment by lukas-reineke** [comment]
Keep the issue open.
segfault is 100% a bug in Neovim core, but this plugin might do something to trigger that. If it doesn't happen if you disable the plugin this might very well be the case.
It would be really helpful if you can create a small `init.lua` that will trigger the issue. So we can make sure it is not any other configuration or plugin you have.

Also make sure you have the latest version of Neovim.

**Comment by JA-Bar** [comment]
Got a container running, compiled latest version of nvim, and loaded an init.lua with only packer and the plugin. There does seem to be some weird interaction that still results in segfault.


https://user-images.githubusercontent.com/57547764/116648018-ae77fe80-a941-11eb-9a12-09e268461662.mp4

Dockerfile:
```Dockerfile
FROM ubuntu:20.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV TZ=America/Mexico_City
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get install -y ninja-build \
                       gettext \
                       libtool \
                       libtool-bin \
                       autoconf \
                       automake \
                       cmake \
                       g++ \
                       pkg-config \
                       unzip

RUN mkdir -p /home/testing/

WORKDIR /home/testing/

RUN git clone https://github.com/neovim/neovim.git

RUN cd neovim && make CMAKE_BUILD_TYPE=Release install 

COPY ./init.lua .

CMD /bin/bash
```

**Comment by lukas-reineke** [comment]
Can you share that `init.lua` file as well please?

**Comment by lukas-reineke** [comment]
Thanks.
Yeah I can reproduce it as well. This is a bug in Neovim core.

Can you open an issue there?

**Comment by JA-Bar** [comment]
[Done](https://github.com/neovim/neovim/issues/14477), first time opening an issue in Neovim, so if there's some information missing I'll be glad to provide it.

**Comment by lukas-reineke** [comment]
Looks very good, thanks for all the work

**Comment by JA-Bar** [comment]
Thank you for the plugin and the follow up!

**Comment by lukas-reineke** [comment]
https://github.com/neovim/neovim/issues/14477#issuecomment-835987927
