### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by noooxxi** [lukas-reineke/indent-blankline.nvim#102]
I'm on neovim 0.4.4-1 using pathogen and I've tried cloning it to bundle and autoload but it doesn't seem to work. What's the correct way to install it? A brief install section in the README would be handy.

**Comment by lukas-reineke** [comment]
Either, take a look at `:help package`
or use a plugin manager, like https://github.com/junegunn/vim-plug

**Comment by vibraniumdev** [comment]
I had a hard time installing for wondering if it was just a matter of typing `Plug "lukas-reineke/indent-blankline.nvim"` or another mysterious method, just because there's nothing in the Readme

**Comment by lukas-reineke** [comment]
Nothing special, same as any other plugin. `Plug "lukas-reineke/indent-blankline.nvim"` is correct

Only thing to note, if you are on Neovim 0.5, you should use the lua branch. In case of vim-plug, that would look like this `Plug 'lukas-reineke/indent-blankline.nvim', { 'branch': 'lua' }`


I will add something in the readme :+1:

**Comment by vibraniumdev** [comment]
Thanks, I'll make sure to have installed the correct version!

**Comment by davideliseo** [comment]
> Nothing special, same as any other plugin. `Plug "lukas-reineke/indent-blankline.nvim"` is correct
> 
> Only thing to note, if you are on Neovim 0.5, you should use the lua branch. In case of vim-plug, that would look like this `Plug 'lukas-reineke/indent-blankline.nvim', { 'branch': 'lua' }`
> 
> I will add something in the readme

I couldn't get this plugin to work, and this was the solution. Thanks!

**Comment by lukas-reineke** [comment]
I added install instructions to the readme now
