### ISSUE TITLE
Option to only show indents for contexts/scopes

### ISSUE THREAD

**Issue by jonatan-branting** [lukas-reineke/indent-blankline.nvim#103]
It would be nice if it was possible to only display indents that signify scopes/context, as defined per `g:indent_blankline_context_patterns`.

This would reduce arguably unnecessary noise caused by displaying indent lines.

**Comment by lukas-reineke** [comment]
You can set the `IndentBlanklineChar` highlight group to be the same as the background color.
Wouldn't that be pretty much the same?

**Comment by jonatan-branting** [comment]
No, I was thinking that *all* indent levels corresponding to a context switch could be displayed, while hiding everything else. As opposed to only showing the level you're currently at.

**Comment by lukas-reineke** [comment]
you mean like this?

![Screen Capture_select-area_20210508211023](https://user-images.githubusercontent.com/12900252/117538595-dc47fc00-b041-11eb-8b67-841bb2a15c9d.png)

**Comment by jonatan-branting** [comment]
The reverse of that actually!

Example: If you have configured ` let g:indent_blankline_context_patterns = ["for", "function"], the following code-snippet would only display the lines corresponding to those contexts, and not for each indent.

![image](https://user-images.githubusercontent.com/985954/117564042-3d0b1f00-b0aa-11eb-951e-e66ad285023d.png)

So, in this case, we would have indent-lines for the levels indicating `for` and the level indicating `function`, i.e. at column 0 and 2 only.

**Comment by lukas-reineke** [comment]
Okay, I understand now.

I won't be adding this. I don't think a lot of people would find this useful, and it would break other functionality that is already there.
