### ISSUE TITLE
Can I Get Something Like This !?

### ISSUE THREAD

**Issue by pulme** [lukas-reineke/indent-blankline.nvim#105]
https://user-images.githubusercontent.com/83711649/117438913-19b96600-af2a-11eb-9fe1-16e1cf3139e7.mp4

**Comment by lukas-reineke** [comment]
First, your indentation settings look wrong. If you use 2 space indentation, you should set `shiftwidth` to 2

To extend what is considered a context (for what part of the code the indentation gets highlighted) take a look at `:h indent_blankline_context_patterns`

**Comment by pulme** [comment]
it's slow to highlight the current backline :-( , Thanks for all things
