### ISSUE TITLE
Disable indentation on empty lines

### ISSUE THREAD

**Issue by lcrockett** [lukas-reineke/indent-blankline.nvim#108]
Using the `lua` branch the plugin works as intended. However, i'd personally prefer the indentation guide not to appear on empty lines, similar to the behaviour of `Yggdroot/indentLine`. With the exceptions being that this plugin supports treesitter, different coloured indentation guides, and context highlighting. All 3 being excellent additions.

Is it possible to disable showing indentation guides on empty lines ?

**Comment by lukas-reineke** [comment]
No sorry, I have no interest in supporting that.
I think you would be the only person to use that feature.
