### ISSUE TITLE
Visual select is incorrect when above empty line

### ISSUE THREAD

**Issue by tomaskallup** [lukas-reineke/indent-blankline.nvim#111]
The video bellow is probably better than any explanation, but with this plugin visual (line) select seems to display incorrectly. When I select a line above an empty line, the empty line is highlighted as selected and sometimes even remains "selected" after exiting visual mode.

https://user-images.githubusercontent.com/26621166/118962107-53945e80-b965-11eb-91c2-e99bf9be774c.mp4

**Comment by lukas-reineke** [comment]
duplicate of #59
