### ISSUE TITLE
Do I need extra steps to get this work after installation? (packer)

### ISSUE THREAD

**Issue by thepenguinthatwants** [lukas-reineke/indent-blankline.nvim#112]
Hi, I used packer to install this but haven't seeing any indentation lines.

        use {'lukas-reineke/indent-blankline.nvim', `opt=true,` branch = 'lua'}

Are there any additional steps that needs to be taken to get this to work?

**Comment by lukas-reineke** [comment]
First, your syntax is wrong, remove the backticks.
`use {'lukas-reineke/indent-blankline.nvim', opt=true, branch = 'lua'}`

But also, there seems to be an issue with packer and lazy loading #63
Just don't lazy load it, and it should work fine.

**Comment by thepenguinthatwants** [comment]
Thanks, so it was the lazy loading that mostly caused the problem.
