### ISSUE TITLE
How to change the cursor color in the indent area?

### ISSUE THREAD

**Issue by dennisfrostlander** [lukas-reineke/indent-blankline.nvim#115]
Could anyone please give a hint on how to change the text cursor color in the indent area?

See the example below. Sometimes I lose the track of cursor when it hides there.

![ezgif-3-4f37068ac4bb](https://user-images.githubusercontent.com/16953692/120157535-6aec0b00-c1f3-11eb-8a4f-8dedf0c83170.gif)

**Comment by lukas-reineke** [comment]
Take a look at `:h guicursor` and `:h hl-Cursor`
I'll close this issue, as it is unrelated to the plugin. If you have more questions, ask in the [neovim gitter](https://gitter.im/neovim/neovim), or on [reddit](https://gitter.im/neovim/neovim)
