### ISSUE TITLE
Context pattern per file type

### ISSUE THREAD

**Issue by HiPhish** [lukas-reineke/indent-blankline.nvim#117]
Hello,

It doesn't seem possible to specify different context patterns for different file types, even though different file types might have conflicting ideas of what constitutes a context marker. I propose configuration either through a dictionary or a buffer-local variable.

A settings dictionary might look like this:

```vim
let g:indent_blankline_context_patterns = {
    \ '': ['class', 'function', 'method'],  " Empty string means default
    \ 'python': ['^def', '^if', '^elif', '^else', '^for', '^with', '^while', '^until', '^try', '^except', '^finally'],
\}
```

To keep backwards compatibility one could use a `type` check: if the variable is a list apply it for all file types. If it is a dictionary try looking up the current file type as the key, if it not found fall back to the empty string as key. (You can use `vim.tbl_islist` in Lua).

Alternatively one could use a buffer-local variable:

```vim
" In init.vim
let g:indent_blankline_context_patterns = ['class', 'function', 'method]

" In ftplugin/python.vim
let b:indent_blankline_context_patterns = ['^def', '^if', '^elif', '^else', '^for', '^with', '^while', '^until', '^try', '^except', '^finally']
```

The latter would mean spreading the configuration over multiple files, but it would be easier to implement. Or combine both approaches.

**Comment by lukas-reineke** [comment]
I plan to add buffer local settings, there is an issue for this #96 
Just haven't had time yet.
I don't want to use a dictionary with filetypes, it's not scalable for all options.
