### ISSUE TITLE
I can not get cntinuous lines as in the demo pics

### ISSUE THREAD

**Issue by jjalonsoc** [lukas-reineke/indent-blankline.nvim#119]
Thank you for this great plugin.

I currently have this configuration:
`vim.cmd("let g:indent_blankline_char = '|'")

vim.cmd("let g:indent_blankline_char_list = ['|']")

vim.cmd("let g:indent_blankline_show_trailing_blankline_indent = v:true")

vim.cmd("let g:indent_blankline_indent_level = 10")

vim.cmd("let g:indent_blankline_use_treesitter = v:true")

vim.cmd("let g:indent_blankline_filetype_exclude = ['dashboard']")

vim.cmd("let g:indent_blankline_show_end_of_line = v:true")
`
However, I was expecting to have continuous lines, but I actually don't! I don't know what I am missing, but I can not get to have the indentation lines be continuous, and it is always looking like dashed lines between two lines.

**Comment by lukas-reineke** [comment]
When your terminal has spacing between the lines, the normal `|` char is not long enough. Try this unicode character `│`

also, you don't have to use `vim.cmd` in lua, you can define options like so `vim.g.indent_blankline_char = "│"`

**Comment by jjalonsoc** [comment]
Thanks, it works well!
