### ISSUE TITLE
Support first indent level

### ISSUE THREAD

**Issue by gbrlsnchs** [lukas-reineke/indent-blankline.nvim#12]
First of all, thanks for this awesome plugin.

It would be nice if this plugin could show an indent guide for the first indent level (just like when `g:indentLine_showFirstIndentLevel` is truthy in https://github.com/Yggdroot/indentLine). I'm not used with EOL chars, so without them there's a blank space for the first indent level.

The indent guide for the first level can be disabled for files that are indented using spaces, but for ones with tabs, which use `listchars`, there's no way to remove the first indent level.

**Comment by lukas-reineke** [comment]
I want to support this.

This can't be done with virtual text, because the linebreak counts as a character and you can't display virtual text over characters.

In theory its easy to do with conceal, but there is a bug in Vim that breaks conceal on empty lines. https://github.com/vim/vim/issues/4854
I'll add it as soon as the bug is fixed.

**Comment by gbrlsnchs** [comment]
No problem, thanks nonetheless! Actually, I'm kinda linking to use the return char for EOL... so no worries!

**Comment by ndavidpsi** [comment]
Has this been fixed?

**Comment by ratheesh** [comment]
vim/vim#4854 which corresponds to vim patch `8.2.1058` is now merged to neovim mainline (sha1: 34291eba80fd2c07cbb3e6310d684e4ac3594fc4)

Can you please implement the indentation line in blank lines when you find the time?

**Comment by lukas-reineke** [comment]
The bug was fixed, but in a way that now does not allow conceal over line endings at all.
https://github.com/vim/vim/blob/fc838d6cb0f22c77a6ee2befd034b593e1c5ea06/src/drawline.c#L1338-L1342

Which means there is still no way to implement this. Sorry.

**Comment by lukas-reineke** [comment]
with the merge of https://github.com/neovim/neovim/pull/13952 this plugin can now handle all the indent lines, blank or not

and as an extra bonus, first level indent is now finally supported as well. It's just on now, not sure if I should add an option to turn it off :thinking: 

I think we can finally close this issue

**Comment by kristijanhusak** [comment]
@lukas-reineke I think it's a good idea to allow disabling first level indent lines.

**Comment by akinsho** [comment]
Yes please would that would be good currently I'm seeing indentation markers in completely blank lines.

<img width="540" alt="Screen Shot 2021-02-22 at 17 09 06" src="https://user-images.githubusercontent.com/22454918/108743418-add17f00-7530-11eb-9091-74db581d9525.png">

**Comment by lukas-reineke** [comment]
:+1: I'll add an option

**Comment by lukas-reineke** [comment]
I added `g:indent_blankline_show_first_indent_level`
And also removed indentation on empty lines that are not part of any indentation, like akinsho's example
