### ISSUE TITLE
indents with both space and tabs hide text

### ISSUE THREAD

**Issue by ek234** [lukas-reineke/indent-blankline.nvim#120]
Consider a nonblank line containing a space followed by a tab followed by some text.

Here, utils.find_indent() returns `1, true`. that is, 1 indent and extra=true.

However, a space followed by a tab takes the same space as a tab. So, text continues after the tab. But, due to extra=true, an indent is drawn right after the tab.

Due to this, the first letter of the text is hidden. [this was a simple case; more text might be hidden in other cases]

strict tab also causes some issues.

**Comment by ek234** [comment]
There are a couple of ideas to fix this:

1. In utils.find_indent() iterate over the whitespace_string char by char. Keep a counter of space characters which is reset to 0 whenever a tab is encountered.
This is easier to understand while reading the code but doesn't look that good.

2. Otherwise, we can add variables:
> local _, 1spacetab = whitespace_string:gsub("<space><tab>", "")
> local _, 2spacetab = whitespace_string:gsub("<space><space><tab>", "")
> local _, 3spacetab = whitespace_string:gsub("<space><space><space><tab>", "")

And calculate the correct indent with these extra variables.
I, personally, would prefer this.

Let me know what you would prefer. If you want, I might be able to implement this by today or tomorrow.

**Comment by lukas-reineke** [comment]
2 will break again if you have more than one tab in the indentation, like `|␣<..>␣␣|␣<..>␣␣`

It has to be option 1.

> Keep a counter of space characters which is reset to 0 whenever a tab is encountered.

You still need to count spaces as well. Just subtract the count until the last tabstop when you encounter a tab char.
And `strict_tabs` should use the tab count until it hits the first space char.

**Comment by lukas-reineke** [comment]
Properly fixed now with #121
