### ISSUE TITLE
Please add a LICENCE

### ISSUE THREAD

**Issue by pinpox** [lukas-reineke/indent-blankline.nvim#122]
Hey,

could you add a LICENCE so that I can package this plugin for NixOS repositories? Any LICENCE would do, as long as it allows redistributing

**Comment by lukas-reineke** [comment]
It has MIT license, it's in the docs
https://github.com/lukas-reineke/indent-blankline.nvim/blob/47691a67b690ad6ebd9df67574691822d226a5b6/doc/indent_blankline.txt#L302

I can add a license file for github :+1:

**Comment by lukas-reineke** [comment]
Added the license file

**Comment by pinpox** [comment]
Thanks!
