### ISSUE TITLE
Disabling in vim-choosewin overlay

### ISSUE THREAD

**Issue by macintacos** [lukas-reineke/indent-blankline.nvim#123]
I'm wondering how I can disable blanklines from rendering in the vim-choosewin overlay? https://github.com/t9md/vim-choosewin

I've tried excluding bufnames and filetypes of "choosewin", but it doesn't seem to work. I have a feeling I'm just missing something obvious, would appreciate some help 🙂

**Comment by lukas-reineke** [comment]
It looks like vim-choosewin does not set a `filetype` or `buftype` for the overlay windows.
You'll have to open an issue there and ask if they can add it.
