### ISSUE TITLE
wrong position of lines

### ISSUE THREAD

**Issue by marbinuwusito** [lukas-reineke/indent-blankline.nvim#124]
![Screenshot_20210613_003719](https://user-images.githubusercontent.com/72583007/121797752-87b71400-cbdf-11eb-87c5-4145da9e3cc7.png)

**Comment by lukas-reineke** [comment]
Please write a proper sentence with what your problem is.

**Comment by marbinuwusito** [comment]
that is not the position that I spected :( (sorry for my bad english)

**Comment by lukas-reineke** [comment]
Thank you.
Your English is fine, no worries :+1: 

I think you are looking for `let g:indent_blankline_show_trailing_blankline_indent = v:false`?

**Comment by marbinuwusito** [comment]
not working :( I want to get the lines to left, even getting two lines, idk what I mistake
![Screenshot_20210613_011009](https://user-images.githubusercontent.com/72583007/121798578-6a387900-cbe4-11eb-9f98-f00c54e2c8f1.png)

**Comment by lukas-reineke** [comment]
Are you using the `master` or `lua` branch?

**Comment by marbinuwusito** [comment]
master

**Comment by lukas-reineke** [comment]
I see, then you have to set `let g:indent_blankline_extra_indent_level = -1` to get rid of the trailing lines.

> I want to get the lines to left

This is not possible in `master`
If you are using Neovim 0.5, you can switch to the `lua` branch. There it should just work.

**Comment by marbinuwusito** [comment]
thanks, I will test it c:

**Comment by marbinuwusito** [comment]
![Screenshot_20210613_014413](https://user-images.githubusercontent.com/72583007/121799368-ecc33780-cbe8-11eb-91b0-5af0d13efb5a.png)
