### ISSUE TITLE
Change the foreground and background colors

### ISSUE THREAD

**Issue by denstiny** [lukas-reineke/indent-blankline.nvim#125]
### I'm use With context indent highlighted by treesitter

![image](https://user-images.githubusercontent.com/57088952/121801818-f0e46900-cc6b-11eb-982d-9fe178e6ef29.png)

**Comment by denstiny** [comment]
I expect effect scope of reality only the indentation, other indentation line color is the same as the background color (I'm sorry my English is not good)

**Comment by lukas-reineke** [comment]
Not sure if I understand correctly. You want the normal indent character to be the same color as the background?
You can change the color by redefining the highlight group, for example like so `highlight IndentBlanklineChar guifg=#00ff00 gui=nocombine`

**Comment by denstiny** [comment]
> 不确定我是否理解正确。您希望普通缩进字符与背景颜色相同吗？
> 您可以通过重新定义高亮组来更改颜色，例如像这样`highlight IndentBlanklineChar guifg=#00ff00 gui=nocombine`

Can only modify the normal indentation characters highlight?

**Comment by lukas-reineke** [comment]
Take a look at `:h indent-blankline-highlights`
you can change
- `IndentBlanklineChar`
- `IndentBlanklineSpaceChar`
- `IndentBlanklineSpaceCharBlankline`
- `IndentBlanklineContextChar`

and there is also
- `g:indent_blankline_char_highlight_list`
- `g:indent_blankline_space_char_highlight_list`
- `g:indent_blankline_space_char_blankline_highlight_list`

**Comment by denstiny** [comment]
![image](https://user-images.githubusercontent.com/57088952/121873768-4a669980-cd39-11eb-89ae-58f10ef4402a.png)
Thank you for success in its place, for to such effect is to want
