### ISSUE TITLE
How to install on nvim v0.5?

### ISSUE THREAD

**Issue by genesis-algorithms** [lukas-reineke/indent-blankline.nvim#129]
Hi, as the question suggests I'm pretty new to vim/nvim world. I'm using [LunarVim](https://github.com/ChristianChiarulli/LunarVim) which uses nvim v0.5 and want to install the version of this packages that's on lua branch but don't know how. Can you help?

**Comment by lukas-reineke** [comment]
looks like LunarVim uses https://github.com/wbthomason/packer.nvim
You can set the branch like so `use {"lukas-reineke/indent-blankline.nvim", branch = "lua"}`
