### ISSUE TITLE
weird characters stuck to indentline 

### ISSUE THREAD

**Issue by siduck76** [lukas-reineke/indent-blankline.nvim#130]
Hi there!  I found some weird horizontal line blocks right to the indentline.

![image](https://user-images.githubusercontent.com/59060246/122961975-93a29300-d3a2-11eb-9bd1-9b29a2622281.png)

**Comment by lukas-reineke** [comment]
I think this is a duplicate of #59

**Comment by nysx** [comment]
I'm having the same problem. `vim.wo.colorcolumn = "99999"` didn't fix it for me. It did, however, fix another problem I had, similar to the one described in #59.
I think these are seperate issues.

**Comment by siduck76** [comment]
@nysx yes this happens only with html files sadly 

html file : <br>

![image](https://user-images.githubusercontent.com/59060246/123260846-ad171c80-d513-11eb-8120-94b8facaaed4.png)

lua file :<br>

![image](https://user-images.githubusercontent.com/59060246/123260901-bc966580-d513-11eb-9c0e-d14c59a38b37.png)

**Comment by nysx** [comment]
They seem to disappear when I enter insert mode, but reappear when I move around

**Comment by lukas-reineke** [comment]
I can't reproduce it.
Can you make a minimal config where this happens?

**Comment by nysx** [comment]
It seems to be caused by the highlights. `IndentBlanklineChar` in particular.

**Comment by siduck76** [comment]
> It seems to be caused by the highlights. `IndentBlanklineChar` in particular. However, setting the highlight for `IndentBlanklineContextChar` does not cause this issue.

yes this works but highlights dont work at all on IndentBlanklineContextChar , I cant change its guifg.

**Comment by nysx** [comment]
that's weird. I can set the highlights for it properly
![screenshot](https://user-images.githubusercontent.com/65695924/123308193-ffbafd80-d540-11eb-88ef-3a7ef2a0bdad.png)
the current context indent seems darker because I disabled IndentBlanklineChar's highlight

**Comment by siduck76** [comment]
@nysx how do I disable indentblanklinechars highlight?

**Comment by nysx** [comment]
I just commented it out. Disabled was a poor choice of word.

**Comment by nysx** [comment]
oh, wait. @siduck76 have you set `vim.g.indent_blankline_show_current_context = true` ?

**Comment by nysx** [comment]
that's weird. Did you set the highlight properly?

**Comment by siduck76** [comment]
yes

**Comment by lukas-reineke** [comment]
Can you please open a new issue if you have a problem with `indent_blankline_show_current_context` :pray: 

> It seems to be caused by the highlights.

What do you mean by this?

**Comment by siduck76** [comment]
@lukas-reineke if we set any highlight to IndentBlanklineChar  like 

hi IndentBlanklineChar  guifg=white 

this causes the issue , but we dont add any highlight for it and use IndentBlanklineContextChar then the problem gets fixed. But i wasnt able to add any highlight for it :( , it didnt work.

**Comment by lukas-reineke** [comment]
I still can't reproduce the issue.
Please create a `init.vim` or `init.lua` file that I can use to reproduce.

**Comment by siduck76** [comment]
My config : 

```      vim.g.indentLine_enabled = 1
                vim.g.indent_blankline_char = "▏"

                vim.g.indent_blankline_filetype_exclude = {"help", "terminal", "dashboard"}
                vim.g.indent_blankline_buftype_exclude = {"terminal"}

                vim.g.indent_blankline_show_trailing_blankline_indent = false
                vim.g.indent_blankline_show_first_indent_level = false 

                    hi IndentBlanklineChar guifg=#282c34```

**Comment by lukas-reineke** [comment]
I don't mean your indent blankline settings.
Please create a minimal `init.vim` file, with no other plugins/settings etc., and steps how to reproduce the issue.
I tried a lot of different things, but can't reproduce the issue at all.

**Comment by lukas-reineke** [comment]
This looks very similar. Might be the same issue?

https://github.com/nvim-treesitter/nvim-treesitter/issues/1506

**Comment by siduck76** [comment]
@lukas-reineke sorry for forgetting about this issue! I dont experience this issue anymore!
