### ISSUE TITLE
Hide indent guides in visual mode

### ISSUE THREAD

**Issue by Unoqwy** [lukas-reineke/indent-blankline.nvim#132]
Hey! I've just switched from indent-guides.nvim to this plugin and one of the first thing I notice is the indent guides are displayed even in visual mode. Is there any way to hide them (lua branch)?

**Comment by lukas-reineke** [comment]
No it's not possible.

Neovim has `virt_text_hide` which should allow this, but it's currently not working https://github.com/neovim/neovim/issues/14050#issuecomment-801536916

**Comment by Unoqwy** [comment]
Hm, `virt_text_hide=true` works in the neovim test suite, but only because `col` is always greater than 0. The reason why it doesn't work here is because `col` is 0 (if set to 1 it does, but of course everything is shifted and empty lines don't render virttext).
Now why is this happening? No clue. I couldn't find any mention of column 0 affecting virttext options in the neovim issues so either they don't know it or I have failed at searching.

**Comment by lukas-reineke** [comment]
You're right, it's only broken for `col` 0
You should comment that in the issue above, or make a new one

**Comment by Unoqwy** [comment]
Yeah, I created a new issue because it 's not really related to scrolling. See https://github.com/neovim/neovim/issues/14929.
Also, I noticed you @mentioned bfredl in your issue after creating it, should we do the same here?

**Comment by lukas-reineke** [comment]
bfredl wrote all of this virtual text code. He knows best how to fix it.
Up to you if you want to tag him, he'll probably see it anyway.

**Comment by FelipeLema** [comment]
hey, every one... I'm _seeing_ this problem with block-visual (`:help CTRL-V`) with v3 and current options:

```lua
{
    indent = {
      char = '┆',
      highlight = {"…"}
    },
    scope = {show_start = false}
}
```

**Comment by FelipeLema** [comment]
ended up using the following snippet to turn on/off indent-blanklines when exiting/entering visual mode
```lua
local saca_de_enmedio_a_indent_blankline = vim.api.nvim_create_augroup("saca_de_enmedio_a_indent_blankline",
  {clear = true})
vim.api.nvim_create_autocmd("ModeChanged",
  {
    group = saca_de_enmedio_a_indent_blankline,
    pattern = "[vV\x16]*:*", -- visual → cualquier cosa
    command = "IBLEnable",
    desc = "Habilita indent-blanklines al salir de modo visual"
  })
vim.api.nvim_create_autocmd("ModeChanged",
  {
    group = saca_de_enmedio_a_indent_blankline,
    pattern = "*:[vV\x16]*", -- cualquier cosa → visual
    command = "IBLDisable",
    desc = "Deshabilita indent-blanklines al salir de modo visual"
  })

```

**Comment by akoerner1** [comment]
This is a related question. How can I configure the plugin to never hide indent guides?

**Comment by ArjunSahlot** [comment]
> ended up using the following snippet to turn on/off indent-blanklines when exiting/entering visual mode
> 
> ```lua
> local saca_de_enmedio_a_indent_blankline = vim.api.nvim_create_augroup("saca_de_enmedio_a_indent_blankline",
>   {clear = true})
> vim.api.nvim_create_autocmd("ModeChanged",
>   {
>     group = saca_de_enmedio_a_indent_blankline,
>     pattern = "[vV\x16]*:*", -- visual → cualquier cosa
>     command = "IBLEnable",
>     desc = "Habilita indent-blanklines al salir de modo visual"
>   })
> vim.api.nvim_create_autocmd("ModeChanged",
>   {
>     group = saca_de_enmedio_a_indent_blankline,
>     pattern = "*:[vV\x16]*", -- cualquier cosa → visual
>     command = "IBLDisable",
>     desc = "Deshabilita indent-blanklines al salir de modo visual"
>   })
> ```

This is perfect!

Here's an English version I made for myself 😅:
```lua
vim.api.nvim_create_autocmd("ModeChanged", {
    group = indent_blankline_augroup,
    pattern = "[vV\x16]*:*",
    command = "IBLEnable",
    desc = "Enable indent-blankline when exiting visual mode"
})

vim.api.nvim_create_autocmd("ModeChanged", {
    group = indent_blankline_augroup,
    pattern = "*:[vV\x16]*",
    command = "IBLDisable",
    desc = "Disable indent-blankline when exiting visual mode"
})
```

**Comment by yochem** [comment]
I have the exact opposite issue. Is there a way to always show the indent lines, even on visually selected lines?

<img width="471" alt="image" src="https://github.com/user-attachments/assets/9ea4886b-1edd-4e85-a3de-4fc3f46e6cc2">
