### ISSUE TITLE
What is the configuration?

### ISSUE THREAD

**Issue by letzabelin** [lukas-reineke/indent-blankline.nvim#133]
What is the configuration in the second screenshot?https://camo.githubusercontent.com/795d0b92e1853b23f440265abcb75a8bad4d29bd9b8d1ed040885e00731d28b3/68747470733a2f2f692e696d6775722e636f6d2f56784354684d752e706e67

**Comment by lukas-reineke** [comment]
Are you on the `master` branch or the `lua` branch?

**Comment by letzabelin** [comment]
On lua branch

**Comment by Ddystopia** [comment]
Can you aslo tell, what is the configuration in the fourth [screenshot]https://camo.githubusercontent.com/443ad8d61fffb539c6fc097177ac91b225b48070f9c956ee701a3b10286285f4/68747470733a2f2f692e696d6775722e636f6d2f44756b4d5a476b2e706e67)?

**Comment by lukas-reineke** [comment]
For the first screenshot:
- set the scape character in `listchars` to `⋅`
  `set listchars=space:⋅`
- set `indent_blankline_space_char_blankline` to a normal space
  `let g:indent_blankline_space_char_blankline = " "`
- set `indent_blankline_show_end_of_line` to true
  `let g:indent_blankline_show_end_of_line = v:true`

For the second screenshot take a look here https://github.com/lukas-reineke/indent-blankline.nvim/issues/94#issuecomment-839359011

**Comment by letzabelin** [comment]
With your config, blank lines looks like on the first screen:
![Screenshot from 2021-07-04 00-46-58](https://user-images.githubusercontent.com/40225759/124367626-9f733c80-dc61-11eb-94ca-6fabccf43913.png)

If I set indent_blankline_char to `▏`, blank lines looks weird because spase after vertical line:
![Screenshot from 2021-07-04 00-47-44](https://user-images.githubusercontent.com/40225759/124367661-0690f100-dc62-11eb-8577-07597b69b85a.png)

It doesn't look like in repos example

**Comment by lukas-reineke** [comment]
Use this Unicode character instead "│"
And next time please open a new issue.

**Comment by letzabelin** [comment]
thanks, it worked
