### ISSUE TITLE
The plugin makes shadow blocks if `cursorline` is enabled

### ISSUE THREAD

**Issue by voldikss** [lukas-reineke/indent-blankline.nvim#137]
To reproduce,

With the following minimal vimrc
```vim
set rtp+=/home/dyzh/.cache/nvim/plugged/indent-blankline.nvim

set tabstop=2
set shiftwidth=2
set cursorline
hi CursorLine     ctermbg=8 guibg=#2D2C29
```

Open the  sample file which has the following content,
```javascript
const foo = async () => {
  const current = d()
  let day = get(current)

  if (current.is(day)) {
    day = day.add(1, 'day')
  }

  if (is(day)) {
    if (current.is(day)) {
      const diff = day.diff(current, 'millisecond')

      setTimeout(
        () => send(day),
        diff,
      )
    }
  }
}
```

Move the cursor from top to the bottom and to top again, there will are some shadow blocks left on the blank lines. 

![indent_blank_line](https://user-images.githubusercontent.com/20282795/124344890-d3ba0f00-dc07-11eb-9c27-562a33cf41c7.gif)

I am going to use this great plugin as NVIM 0.5 stable version being released, thank you for the development! Looking forward to see the fix of this.

**Comment by ChristianChiarulli** [comment]
https://github.com/lukas-reineke/indent-blankline.nvim/issues/59#issuecomment-806398054

**Comment by voldikss** [comment]
Thank you so much!!!
