### ISSUE TITLE
How to ignore new lines?

### ISSUE THREAD

**Issue by fuelen** [lukas-reineke/indent-blankline.nvim#139]
This is how indentLine works:
![image](https://user-images.githubusercontent.com/588762/124381281-53a8ad80-dcca-11eb-9bbb-5925ece085e5.png)
and this plugin:
![image](https://user-images.githubusercontent.com/588762/124381294-64f1ba00-dcca-11eb-956f-0558e9daeb07.png)

Is it possible to achieve the same experience?

**Comment by lukas-reineke** [comment]
No, there is no way to turn the indent guides in empty lines off.

**Comment by fuelen** [comment]
@lukas-reineke actually, it works this way if treesitter for lua is not set
![image](https://user-images.githubusercontent.com/588762/124396901-0aca1680-dd15-11eb-9468-8053ee719c75.png)

**Comment by lukas-reineke** [comment]
That should not happen.
I will probably fix that at some point
