### ISSUE TITLE
Torn line

### ISSUE THREAD

**Issue by fuelen** [lukas-reineke/indent-blankline.nvim#140]
![image](https://user-images.githubusercontent.com/588762/124396693-c8eca080-dd13-11eb-8c2d-7cdd7bd89a6d.png)

code taken from this issue -> https://github.com/lukas-reineke/indent-blankline.nvim/issues/94
```lua
-- define the highlight groups with only background colors (or leave odd empty to just show the normal background)
vim.cmd [[highlight IndentOdd guifg=NONE guibg=NONE gui=nocombine]]
vim.cmd [[highlight IndentEven guifg=NONE guibg=#0000ff gui=nocombine]]
-- and then use the highlight groups
vim.g.indent_blankline_char_highlight_list = {"IndentOdd", "IndentEven"}
vim.g.indent_blankline_space_char_highlight_list = {"IndentOdd", "IndentEven"}

-- don't show any characters
vim.g.indent_blankline_char = " "
vim.g.indent_blankline_space_char = " "

-- when using background, the trailing indent is not needed / looks wrong
vim.g.indent_blankline_show_trailing_blankline_indent = false

```

**Comment by lukas-reineke** [comment]
I can't reproduce

![Screen Capture_select-area_20210705103206](https://user-images.githubusercontent.com/12900252/124406428-519f2700-dd7c-11eb-8125-99ed8275e9a6.png)

Does it happen to all blank lines?
Does it still happen if you remove anything else from your config?

**Comment by fuelen** [comment]
yes, all blank lines.
I found, that combination of these two lines produces such behaviour:
```
vim.wo.colorcolumn = "120"
vim.opt.cursorline = true
```

**Comment by lukas-reineke** [comment]
Still can't reproduce it. Setting `colorcolumn` or `cursorline` doesn't change anything.

**Comment by fuelen** [comment]
@lukas-reineke what GUI do you use?
I'm on neovim-qt

**Comment by lukas-reineke** [comment]
I use Kitty terminal, but tried with neovim-qt now as well, and still can't reproduce the issue.

**Comment by fuelen** [comment]
try this config
```lua
vim.wo.colorcolumn = "120"

vim.opt.tabstop = 2

return require("packer").startup(
  function()
    use "wbthomason/packer.nvim"

    use {
      "nvim-treesitter/nvim-treesitter",
      config = function()
        local ts_config = require("nvim-treesitter.configs")
      
        ts_config.setup {
          ensure_installed = {
            "lua"
          },
          highlight = {
            enable = true,
            use_languagetree = true
          },
          indent = {
            enable = true
          }
        }
      end,
      run = ":TSUpdate"
    }

    use {
      "lukas-reineke/indent-blankline.nvim",
      config = function()     
        -- define the highlight groups with only background colors (or leave odd empty to just show the normal background)
        vim.cmd [[highlight IndentOdd guifg=NONE guibg=NONE gui=nocombine]]
        vim.cmd [[highlight IndentEven guifg=NONE guibg=#0000ff gui=nocombine]]
        -- and then use the highlight groups
        vim.g.indent_blankline_char_highlight_list = {"IndentOdd", "IndentEven"}
        vim.g.indent_blankline_space_char_highlight_list = {"IndentOdd", "IndentEven"}
      
        -- don't show any characters
        vim.g.indent_blankline_char = " "
        vim.g.indent_blankline_space_char = " "
      
        -- when using background, the trailing indent is not needed / looks wrong
        vim.g.indent_blankline_show_trailing_blankline_indent = false
      end,
      after = "nvim-treesitter"
    }
  end
)

```

**Comment by lukas-reineke** [comment]
`after = "nvim-treesitter"`

This is the problem. Packer doesn't lazy load the plugin correctly. There are other problems like #131 and #63. But I didn't know this happens as well.

It causes the highlight group to not be setup correctly.

You don't need to load `indent-blankline` after treesitter, just remove the `after` and it should work.

**Comment by fuelen** [comment]
In this case, there is no blue line at all.
It is present if I remove `after` from the config above, but if I remove it from my big config - blue line disappears :(
Seems like it conflicts with something else

**Comment by lukas-reineke** [comment]
Can you check what these variables are set to once everything is loaded?

`:let g:indent_blankline_char_highlight_list`
`:let g:indent_blankline_space_char_highlight_list`
`:let g:indent_blankline_space_char_blankline_highlight_list`

They should all be `["IndentOdd", "IndentEven"]`

Also check that the highlights are set correctly
`:hi IndentOdd`
`:hi IndentEven`

**Comment by fuelen** [comment]
> They should all be ["IndentOdd", "IndentEven"]

Yes, they are
```
:hi IndentOdd 
IndentOdd    xxx cleared
```
IndentEven is cleared too.


This is my config at the moment https://github.com/fuelen/nvimfiles/tree/fe1a41d519f5be073a3f6419b06fe534961307e3

**Comment by lukas-reineke** [comment]
Yeah, if they are cleared, you won't see anything.

I'd just put them into your `colorscheme.lua` file like you already have for `Whitespace`. So it is guaranteed to run after setting the color scheme.
And like I said, remove the `after = "nvim-treesitter"`

**Comment by fuelen** [comment]
Yes, now it works.
Now, I think, I can close the issue.
Thank you!
