### ISSUE TITLE
Indent replaces text when moving cursor to right

### ISSUE THREAD

**Issue by luisiacc** [lukas-reineke/indent-blankline.nvim#144]
Indent lines are covering text when moving cursor to the right, making the screen to scroll to the right as well. See on picture below, the area un inside the green lines should be text, but are covered by the indent lines.
![image](https://user-images.githubusercontent.com/31720261/124991533-c8a01e00-e00f-11eb-9f70-772e319dfc08.png)

**Comment by lukas-reineke** [comment]
This is a duplicate of #51
