### ISSUE TITLE
Doc request: how to configure the examples in the README

### ISSUE THREAD

**Issue by jc00ke** [lukas-reineke/indent-blankline.nvim#146]
I'm tryin' but failing. I'd love to see the config settings for the examples in the README. Thank you!

**Comment by lukas-reineke** [comment]
There are a couple other tickets where I explained some of them #94 #133
You can take a look if there.

I will also update the readme with all configurations for each screenshot when I have some time.

**Comment by ayamir** [comment]
Here is how I config:
```lua
function config.indent_blankline()
    vim.cmd [[highlight IndentOne guifg=#BF616A guibg=NONE gui=nocombine]]
    vim.cmd [[highlight IndentTwo guifg=#D08770 guibg=NONE gui=nocombine]]
    vim.cmd [[highlight IndentThree guifg=#EBCB8B guibg=NONE gui=nocombine]]
    vim.cmd [[highlight IndentFour guifg=#A3BE8C guibg=NONE gui=nocombine]]
    vim.cmd [[highlight IndentFive guifg=#5E81AC guibg=NONE gui=nocombine]]
    vim.cmd [[highlight IndentSix guifg=#88C0D0 guibg=NONE gui=nocombine]]
    vim.cmd [[highlight IndentSeven guifg=#B48EAD guibg=NONE gui=nocombine]]
    vim.g.indent_blankline_char = "│"
    vim.g.indent_blankline_char_highlight_list = {
        "IndentOne", "IndentTwo", "IndentThree", "IndentFour", "IndentFive",
        "IndentSix", "IndentSeven"
    }
    vim.g.indent_blankline_show_first_indent_level = true
    vim.g.indent_blankline_filetype_exclude = {
        "startify", "dashboard", "dotooagenda", "log", "fugitive", "gitcommit",
        "packer", "vimwiki", "markdown", "json", "txt", "vista", "help",
        "todoist", "NvimTree", "peekaboo", "git", "TelescopePrompt", "undotree",
        "flutterToolsOutline", "" -- for all buffers without a file type
    }
    vim.g.indent_blankline_buftype_exclude = {"terminal", "nofile"}
    vim.g.indent_blankline_show_trailing_blankline_indent = false
    vim.g.indent_blankline_show_current_context = true
    vim.g.indent_blankline_context_patterns = {
        "class", "function", "method", "block", "list_literal", "selector",
        "^if", "^table", "if_statement", "while", "for"
    }
    -- because lazy load indent-blankline so need readd this autocmd
    vim.cmd('autocmd CursorMoved * IndentBlanklineRefresh')
end
```
Effect:
![image](https://user-images.githubusercontent.com/61657399/126438112-41f5e68b-cca0-4cc6-8dc7-aba34a7d9301.png)

**Comment by lukas-reineke** [comment]
Thank you

**Comment by cinerea0** [comment]
Yeah, it would be helpful to know how to configure the [treesitter highlighting example](https://camo.githubusercontent.com/31ad18664ce43d2f2287b36a035599c3746ff87fb67535abbcdce672d4af94e1/68747470733a2f2f692e696d6775722e636f6d2f6d6b7947505a5a2e706e67) shown in the readme.

**Comment by typkrft** [comment]
@cinerea0 
> Yeah, it would be helpful to know how to configure the [treesitter highlighting example](https://camo.githubusercontent.com/31ad18664ce43d2f2287b36a035599c3746ff87fb67535abbcdce672d4af94e1/68747470733a2f2f692e696d6775722e636f6d2f6d6b7947505a5a2e706e67) shown in the readme.

You need to install TreeSitter with your plugin manager, then use `:TSInstall YOUR_LANGUAGE` to install the language parser for example `:TSInstall javascript`. You can use the 2nd config @ayamir supplied and it should start working for you.

**Comment by Edmartt** [comment]
Nice screenshots, poor documentation. The examples are not clear and where the heck this "function" needs to be? Don't think for users, nothing is obvious...
