### ISSUE TITLE
Indent line where there shouldn't be one

### ISSUE THREAD

**Issue by drzel** [lukas-reineke/indent-blankline.nvim#148]
![image](https://user-images.githubusercontent.com/8026227/125154730-cfa96680-e19e-11eb-8d80-2f926c5cea75.png)

Presumably this is a hard problem, but just in case it's not.

**Comment by lukas-reineke** [comment]
you can turn them off with `let g:indent_blankline_show_trailing_blankline_indent = v:false`

**Comment by drzel** [comment]
Yep that did the trick thanks!
