### ISSUE TITLE
Missing indent lines on wrapped graphical lines

### ISSUE THREAD

**Issue by jakewvincent** [lukas-reineke/indent-blankline.nvim#149]
On graphical lines that contain text from a wrapped logical line, the indent guides are not displayed (screenshot below). I have wrapping enabled for all filetypes and `breakindent` and `linebreak` enabled (see the relevant settings in my `init.lua` below). This is most noticeable in filetypes with lots of text on a line, e.g. LaTeX files. I looked through the documentation and didn't see anything I could do about this. Is there a way that the indent lines can be continued on the graphical lines that exist to display wrapped text?

```lua
-- In init.lua
-- For setting options
scopes = {o = vim.o,    -- o for setting global options
          b = vim.bo,   -- bo for setting buffer-scoped options
          w = vim.wo    -- wo for setting window-scoped options
}
function opt(scope, key, value)
    scopes[scope][key] = value
    if scope ~= 'o'
    then scopes['o'][key] = value
    end
end

opt('w', 'breakindent', true)       -- when wrapping, maintain indentation
opt('w', 'linebreak', true)         -- wrap at word boundaries, not mid-word
```
![Screenshot from 2021-07-16 12-50-54](https://user-images.githubusercontent.com/45184202/126004195-2fd0089f-5efc-4cc3-80a2-69231f258d37.png)

Thanks for your great plugin!

**Comment by lukas-reineke** [comment]
This is currently not possible. It's a limitation in Neovim.
There is no way to put virtual text in this area (or anything else for that matter).

I will implement this should it ever become possible, but I will close this ticket for now.

**Comment by krishnakumarg1984** [comment]
I am interested in this too.

- Just a gentle ping to know if this limitation in upstream neovim has been addressed in any recent releases since this issue was closed?

- Can you perhaps please link to the upstream bug/issue report on the Neovim GitHub repo, which is being worked on?

**Comment by krishnakumarg1984** [comment]
> This is currently not possible. It's a limitation in Neovim.
There is no way to put virtual text in this area (or anything else for that matter).

It is desirable with long wrapped prose to maintain indent lines. The OP's example was perfect. Each item within a LaTeX description list soft-wrapped  over multiple lines. When we have more than a few such list items, the sporadic presence of indent guides makes it confusing. 

May I request your help to draft a feature request with upstream neovim to somehow fix this in a future release of neovim?

**Comment by benbrastmckie** [comment]
I am also interested in this upstream nvim feature request for the same reasons. What exactly would need to change in nvim?

**Comment by lukas-reineke** [comment]
> What exactly would need to change in nvim

Sorry, I don't know too much about how nvim implements line wrapping. But this would not be a small change.
You'd need to talk to someone on the core team.
