### ISSUE TITLE
Background color mismatch in indent blanklines

### ISSUE THREAD

**Issue by rocket-engineer** [lukas-reineke/indent-blankline.nvim#15]
Hi there,
first of all: Thx a lot for your effort! I recently switched to neovim and I stumbled over this plugin. One big problem seems to be solved on my bucket list ;)

I got a little problem with your indents in blank lines. As you can see there occurs a bg color mismatch. Do you have an idea how to fix this? Maybe I have to modify my color scheme?

My setup:
neovim 0.4.3 on ArchLinux
I also use the Yggdroot/indentLine plugin.

![2](https://user-images.githubusercontent.com/3513477/80825375-89db3080-8be0-11ea-9204-1c19bd159b53.png)

**Comment by lukas-reineke** [comment]
the highlight group for the spaces is `Whitespace`
You can check to what this is set to, and where it is set with `:verbose hi Whitespace`

Not sure why it would be set to a different background color

To fix it you should be able to do this `:highlight Whitespace guibg=None ctermbg=None`

**Comment by rocket-engineer** [comment]
You are right, my Whitespace color was linked to NonText. This came from `hi clear` in my color scheme (wombat256).

I could fixed this problem by inserting `highlight Whitespace guibg=None ctermbg=None` into my color scheme file.
