### ISSUE TITLE
Any way to avoid indent guides on line breaks?

### ISSUE THREAD

**Issue by moshiur-raj** [lukas-reineke/indent-blankline.nvim#150]
![image](https://user-images.githubusercontent.com/36466700/126045810-387c60f3-5677-48bd-ad8f-48e66f77cb42.png)
How can I disable the level 3 and 4 indent guides in the two lines below printf ?

**Comment by lukas-reineke** [comment]
If you are using tabs for indentation, and spaces for the alignment of the arguments of `printf`, you can set `let g:indent_blankline_strict_tabs = v:true`. This will only show the indentation for tabs.

If you are using spaces for everything, then there is no way to do this, sorry.

**Comment by moshiur-raj** [comment]
@lukas-reineke  Thank you. I was actually using both tab and space for the alignment. Replaced those tabs with spaces.
