### ISSUE TITLE
Telescope's ivy theme shows indentation even if filetype_exclude = {"TelescopePrompt"} is set

### ISSUE THREAD

**Issue by ikerurda** [lukas-reineke/indent-blankline.nvim#164]
<img width="1792" alt="Screenshot 2021-08-04 at 7 26 52 PM" src="https://user-images.githubusercontent.com/45340417/128226548-31b68eef-f21f-4710-afbc-906b64977d9b.png">

**Comment by lukas-reineke** [comment]
The indent you see is not from the prompt buffer. It is the border buffer.
Telescope uses https://github.com/nvim-lua/popup.nvim for the floating windows, which then uses https://github.com/nvim-lua/plenary.nvim for the window border.
Here is the relevant file https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/window/border.lua

Plenary does not set a filetype on that border buffer. You can either create an issue there and ask them to add it, or you exclude all buffers with no file type from indent-blankline like so `filetype_exclude = {""}`
