### ISSUE TITLE
Hidden auto complete text

### ISSUE THREAD

**Issue by luathn** [lukas-reineke/indent-blankline.nvim#166]
I removed all my plugins and just keep: nvim-lspconfig, nvim-compe and indent-blankline.nvim. And I had this issue.
Hope you can take a look.
If you need more information, please tell me.
![Peek 2021-08-05 10-32](https://user-images.githubusercontent.com/20609495/128287433-df71e159-fc19-4666-9fdf-78b22db97493.gif)

**Comment by lukas-reineke** [comment]
Thanks for the issue. I released a fix now.
Can you check that its working?

**Comment by luathn** [comment]
It's great because you fix the error so quickly. But I don't understand why it's not stable.
![Peek 2021-08-05 11-15](https://user-images.githubusercontent.com/20609495/128290133-d54d7b7b-5930-4e6c-aba3-a0934653495f.gif)

**Comment by lukas-reineke** [comment]
hmm this is not happening for me.
Looks like a race condition with the autocommands?
I don't think there is anything else I can do about it.

**Comment by luathn** [comment]
Ok. Thank you for your support. I'll try to find why.
