### ISSUE TITLE
[Bug] indentline color changed on saving.

### ISSUE THREAD

**Issue by qvieth** [lukas-reineke/indent-blankline.nvim#169]
Uploading Screencast from 08-06-2021 08_59_30 AM.mp4…

This happens after the plugin update.

For now,  `vim.g.indent_blankline_char_highlight_list = { "Comment" }`  workaround fixes this issue for me.

**Comment by lukas-reineke** [comment]
Can you try to upload the video again?

**Comment by qvieth** [comment]
https://user-images.githubusercontent.com/71810726/128446610-96e22c99-d96a-4d61-a20f-5126fb97800a.mp4

**Comment by qvieth** [comment]
oh my bad

**Comment by qvieth** [comment]
I just notice some brackets colors are changes on saving also, set `vim.g.indent_blankline_char_highlight_list = { "Comment" }` doesn't fix that, so I'm not sure whether this is the problem of indentline itself.

**Comment by lukas-reineke** [comment]
It is not a problem with indent-blankline.

You probably have an autocommand to resource your config after you save?
My guess is something in your config clears highlight groups. Maybe your color  scheme.

You can run `require("indent_blankline.utils").reset_highlights()` to reset them for indent-blankline. But this doesn't solve your underlying issue.

**Comment by qvieth** [comment]
Yeah, you're right @lukas-reineke, the problem is the source autocommand, I'm so dump, thank you so much for the help!!
