### ISSUE TITLE
The plugin changes the last position in jumplist

### ISSUE THREAD

**Issue by voldikss** [lukas-reineke/indent-blankline.nvim#17]
First of all, thank you for the fantastic plugin!

Then comes the issue. :joy:

I have this `autocmd` in my vimrc. However, after installing this plugin, everytime I open a file it jumps to a constant position while not the last position the cursor was placed. 

```vim
augroup JumpToLastPosition
  autocmd!
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") && &filetype != 'gitcommit' |
      \ exe "normal! g`\"" |
    \ endif
augroup END
```

The plugin can change the jumplist, that should be unexpected.

**Comment by ratheesh** [comment]
I have observed one more issue. If I enable this plugin along with `bufline` of `vim-airline` plugin, I see that previous buffers are no longer valid upon nvim application restart. This issue is not observed if this plugin is disabled. 
I don't have an easy way to demonstrate this issue, I will try to demonstrate this issue with minimal configuration.

**Comment by voldikss** [comment]
Hi @ratheesh , since that's another problem, could we open a new issue for that? One issue one problem makes issue management more convient.

**Comment by voldikss** [comment]
> First of all, thank you for the fantastic plugin!
> 
> Then comes the issue. 
> 
> I have this `autocmd` in my vimrc. However, after installing this plugin, everytime I open a file it jumps to a constant position while not the last position the cursor was placed.
> 
> ```viml
> augroup JumpToLastPosition
>   autocmd!
>   autocmd BufReadPost *
>     \ if line("'\"") > 1 && line("'\"") <= line("$") && &filetype != 'gitcommit' |
>       \ exe "normal! g`\"" |
>     \ endif
> augroup END
> ```
> 
> The plugin can change the jumplist, that should be unexpected.

The issue was caused by this line.

https://github.com/lukas-reineke/indent-blankline.nvim/blob/c72e9a7932bf71225f78d2e7f14b1b62fc0464c9/plugin/indent_blankline.vim#L32

But I could not figure out how to fix it.

**Comment by lukas-reineke** [comment]
Yea I can reproduce this. It is not directly related to the jumplist
Your script uses `'"`, which is a mark set when the buffer exists.

Regardless, this plugin should set `keepjumps` as well :+1: 

I have a fix I think. I pushed an update to the develop branch, you can check if this works.

**Comment by voldikss** [comment]
Thank you @lukas-reineke . I tried develop branch and it fixs the issue. :100:

**Comment by voldikss** [comment]
Should I close this issue? Maybe you should open another issue in which @ratheesh 's issue is refered?

**Comment by lukas-reineke** [comment]
yes @ratheesh please open another Issue, I'll need more information from you.

I'll leave this fix in develop for a while to make sure closing and reopening the buffers a lot doesn't slow things down.

**Comment by ratheesh** [comment]
@lukas-reineke Sorry for the delay. Please close this issue. I will reopen issue mentioned by me in a new request.
