### ISSUE TITLE
Support irregular indentation

### ISSUE THREAD

**Issue by lukas-reineke** [lukas-reineke/indent-blankline.nvim#170]
When using indent guides for Haskell code -- see the image.

![image](https://user-images.githubusercontent.com/15617291/128443501-5f24189b-0d2d-451b-bb56-3e58f1e91b1c.png)

The only non-default settings here are `g:indent_blankline_char`, `g:indent_blankline_buftype_exclude` and `g:indent_blankline_show_trailing_blankline_indent = v:false`.

I believe this happens because this plugin simply places an indentation guide every `&shiftwidth` columns. But, as the image shows, this is not enough for typical Haskell indentation, since it can start at basically any column.

Perhaps we could look into placing the indent guide on the first non-whitespace column above? Or maybe somehow use tree-sitter to try to solve this? (note: using `g:indent_blankline_use_treesitter = 1` didn't solve this, as I understand all it does is highlight the current indentation level).

_Originally posted by @dccsillag in https://github.com/lukas-reineke/indent-blankline.nvim/issues/153#issuecomment-893943554_

**Comment by lukas-reineke** [comment]
I made this a new issue.

It's an interesting problem. I believe it could be solvable, but it's not easy.

**Comment by dccsillag** [comment]
Maybe it's worth documenting another instance of this problem (again exemplified in Haskell code): multiple indent guides where there should only be one.

![image](https://user-images.githubusercontent.com/15617291/128447810-cbc3cb82-4da4-4f7c-be92-788eac548e87.png)

**Comment by lukas-reineke** [comment]
do you have examples from other editors how it _should_ look like?

**Comment by dccsillag** [comment]
I have an idea in my head on how it should look like, but I feel like I've also seen some editor out there do it properly. I'll look for it.

**Comment by dccsillag** [comment]
Update: Just found https://github.com/DarthFennec/highlight-indent-guides, which implements this stuff in Emacs.

**Comment by 1478zhcy** [comment]
Obviously, show current context indent works well, could fully use treesitter implement all feature of this plugin?

**Comment by lukas-reineke** [comment]
It is on the list of things I want to do in the next version.
But I have much less time these days, I don't know when I'll work on it.

**Comment by lukas-reineke** [comment]
Supported in version 3
