### ISSUE TITLE
Character added to beginning of non-empty lines

### ISSUE THREAD

**Issue by MIvanchev** [lukas-reineke/indent-blankline.nvim#171]
See here:

![Problem](https://raw.githubusercontent.com/MIvanchev/images/109905a3-3c00-4bcb-9d49-2eeca38fbfd2/problem.png)

What am I doing wrong? From the 4th indentation level on the char is always shown at the beginning of the line. Also, the color is different from Yggdroot/indentLine but I guess this is easy to configure.

This is neovim-qt 0.5.0 on Windows 7 x64

**Comment by lukas-reineke** [comment]
Do you still have `Yggdroot/indentLine` installed?
If so, please remove it.

And then check what `:set shiftwidth` is set to

**Comment by MIvanchev** [comment]
Thanks, looks better now but shows the indent lines at 8 spaces apart where my shiftwidth is 2. What is it controlled by? Also I dunno if it's a good idea to have g:indent_blankline_show_first_indent_level = v:true as a default :joy:

**Comment by lukas-reineke** [comment]
The plugin uses `tabstop` when `expandtab` is off, and `shiftwidth` when it's on.
So when you indent with tabs, it's `tabstop`, when you indent with spaces it's `shiftwidth`.

**Comment by MIvanchev** [comment]
Thanks it looks great, this is a really nice plugin :)

**Comment by MIvanchev** [comment]
Sorry, last question, how to set the color of the char?

```
highlight indentblanklinechar guifg=#00ff00 gui=nocombine
```

in my `init.vim` has no effect. I initialize the plugin through

```
lua require('indent_blankline').setup({})
```

as the last line of my `init.vim`.

**Comment by MIvanchev** [comment]
I solved it now through by:

```
au VimEnter * highlight IndentBlanklineChar guifg=#00FF00 gui=nocombine
```
