### ISSUE TITLE
There must be something wrong currently.

### ISSUE THREAD

**Issue by nyngwang** [lukas-reineke/indent-blankline.nvim#174]
Case 1:

<img src="https://user-images.githubusercontent.com/24765272/130309165-c80bacad-a79d-45f7-8f27-179c8ffe714b.png" width="370"><img src="https://user-images.githubusercontent.com/24765272/130309174-3ded7152-ad82-4af3-8abd-77ad0dbd6750.png" width="370">

---

Case 2:

<img src="https://user-images.githubusercontent.com/24765272/130309242-312c5923-72c7-4562-8808-4b1e08b90fb1.png" width="370"><img src="https://user-images.githubusercontent.com/24765272/130309269-55639094-dbce-4ce1-90de-9a59ee6d6367.png" width="370">

---

This is my settings:

```
let g:indent_blankline_use_treesitter = v:true
let g:indent_blankline_enabled = v:false
let g:indent_blankline_show_current_context = v:false
" let g:indent_blankline_show_first_indent_level = v:false
let g:indent_blankline_viewport_buffer = 5
let g:indent_blankline_show_end_of_line = v:true
let g:indent_blankline_strict_tabs = v:true
" let g:indent_blankline_debug = v:true
```

And if I set `g:indent_blankline_show_first_indent_level = v:true` the plugin seems to be disabled. As you can see the `let g:indent_blankline_show_end_of_line = v:true` doesn't work too, as I didn't see any end of line mark.

**Comment by lukas-reineke** [comment]
I can't reproduce either of these issues. `show_first_indent_level` is on by default and works fine for me.

Do you have `listchars` end of line character set? If not, there is nothing to display and the plugin falls back on just the indent character.

![Screen Capture_select-area_20210821172747](https://user-images.githubusercontent.com/12900252/130315868-f020078f-43e5-4e39-82ed-7c1e6b6a8fee.png)

**Comment by nyngwang** [comment]
@lukas-reineke What If you set `g:indent_blankline_show_current_context = v:true`, would all of the indent lines disappear? About `g:indent_blankline_show_end_of_line = v:true` I expect the "light grey arrow" in your first image.

**Comment by lukas-reineke** [comment]
`show_current_context` works as excepted as well.

> I expect the "light grey arrow" in your first image.

Then you have to set that in `listchars`. The plugin takes whatever you have set as your end of line character there

![Screen Capture_select-area_20210821174930](https://user-images.githubusercontent.com/12900252/130316441-477c9c19-6d79-4f98-a198-7e0e5fa31d1a.png)

**Comment by jaydorsey** [comment]
Maybe related, but I saw similar behavior when I first installed. Looking at `:hi`, I noticed that all of my highlight groups that I created were cleared. This led me to [this stackoverflow post](https://vi.stackexchange.com/a/3356/12256)

Defining my highlight groups _after_ I set my colorscheme resolved the issue.

**Comment by lemontghe** [comment]
Hi, i tried to use the fourth example and change it to be like with no characters and only a darker background but it's showing this line in the middle..
![with](https://user-images.githubusercontent.com/21209054/133336969-8ab50343-a61b-4566-b8df-2c1fdde917ee.png)
![without](https://user-images.githubusercontent.com/21209054/133336956-7b717c1f-d66e-46e2-ba7c-42bf339090e1.png)

this one:
https://camo.githubusercontent.com/443ad8d61fffb539c6fc097177ac91b225b48070f9c956ee701a3b10286285f4/68747470733a2f2f692e696d6775722e636f6d2f44756b4d5a476b2e706e67
