### ISSUE TITLE
`blankline_buftype_exclude` does not work

### ISSUE THREAD

**Issue by lukas-reineke** [lukas-reineke/indent-blankline.nvim#175]
Hey, I have encountered the same issue trying to use neovim as manpager. Here is a minimal init.vim:
```vim
call plug#begin(stdpath('data').'/vim-plug')
Plug 'lukas-reineke/indent-blankline.nvim'
let g:indent_blankline_buftype_exclude = ['nofile']
let g:indent_blankline_filetype_exclude = ['man']
call plug#end()
```
Write that to min.vim and do `MANPAGER="nvim -u min.vim -c 'set ft=man' -" man ls`.
The output is something like:
![screenshot_548973](https://user-images.githubusercontent.com/59394665/130303299-f851d131-ec63-41f0-a42d-c84ce246c83a.png)
and after doing `:IndentBlanklineDisable` the blue lines dissapear:
![screenshot_572301](https://user-images.githubusercontent.com/59394665/130303338-d14a1abc-5ec2-4604-8b54-879dc7193fcd.png)

Interestingly, the lines do not continue far beyond the "original" buffer section:
![screenshot_594672](https://user-images.githubusercontent.com/59394665/130303412-237df1f1-0290-4b85-a51c-77c6df909a02.png)
and also doing `:IndentBlanklineToggle` actually enables them to continue:
![screenshot_140796](https://user-images.githubusercontent.com/59394665/130303598-e8c7f53a-b6c4-4cf3-b4af-d06427ea7fc2.png)

which makes me think the initial lines are just some visual artifact, but neither `:IndentBlanklineRefresh` or `:redraw!` makes them go away.

Notice that the man buffer has both `buftype=nofile` and `ft=man`, so neither of the exclusion options work correctly in this case.

_Originally posted by @piotr-machura in https://github.com/lukas-reineke/indent-blankline.nvim/issues/113#issuecomment-903013217_

**Comment by lukas-reineke** [comment]
I put this into a new issue.
I probably broke this when I fixed lazy loading. I made a PR here #176
Can you check if that works @piotr-machura

**Comment by piotr-machura** [comment]
Yep, both `g:indent_blankline_buftype_exclude` and `g:indent_blankline_filetype_exclude` work correctly now, both in the minimal example above and my [full config](https://git.sr.ht/~piotr-machura/arch-setup/tree/dots/item/.config/nvim/init.vim). Thank you so, so much.
