### ISSUE TITLE
Issue getting plugin to work

### ISSUE THREAD

**Issue by anihm136** [lukas-reineke/indent-blankline.nvim#18]
Hi. I downloaded this plugin after reading about it today, and am not able to get it working. I'm trying it with a minimal vimrc, with only `indentLine` installed (and of course this plugin!). The indent guide from `indentLine` show up fine, but the empty lines aren't filled in. 
I also tried enabling debug, which resulted in this output:
```
Error detected while processing function indent_blankline#commands#ToggleAll[1]..indent_blankline#commands#Toggle[2]..indent_blankline#commands#Disab
le:
line    3:
E121: Undefined variable: g:indent_blankline_namespace
E116: Invalid arguments for function nvim_buf_clear_namespace
```
Any idea what I'm doing wrong?

**Comment by lukas-reineke** [comment]
That error is a bug :+1: 

but its not the reason the plugin doesn't work for you.
What filetype did you try? Can you post a code example here that doesn't work?

**Comment by anihm136** [comment]
I've tried with shell and python files. Example - 
```sh
		v() {
        ¦ if [[ -n "$@" ]]; then
        ¦   vim $@
        ¦ else
        ¦   local files=$(fzf -m)
			# This line does not get an indent indicator
        ¦   local args=(`echo $files`)
			# This line does not get an indent indicator
        ¦   [ -n "$args" ] && vim "${args[@]}"
        ¦ fi
        }
```

**Comment by lukas-reineke** [comment]
python and shellscript should both work fine

can you turn debug on and see if there are any errors?

`let g:indent_blankline_debug = v:true`

open the file and check with `:messages`

**Comment by anihm136** [comment]
That's odd... It started working fine again! I didn't change anything, not even a reinstall. Looks like it's working perfectly now. I'll let you know if I face any further issues. Thanks for your help!

**Comment by Melkster** [comment]
@lukas-reineke I'm having the same issue.

This is my minimal `init.vim`:

```vim
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'Yggdroot/indentLine'
Plugin 'lukas-reineke/indent-blankline.nvim'
call vundle#end()
set conceallevel=2
```

This is the output of `:version`:

```vim
NVIM v0.5.0-540-g60c581b35
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -
Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnosti
cs-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEV
EL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/t
ravis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/s
rc/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-495222b7-1d16-4b36-9b3a-9e6dacb42070

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by lukas-reineke** [comment]
@Melkster can you please open a new issue.

set `let g:indent_blankline_debug = v:true` and see if you get any error messages.
And can you share the file that is not working?

**Comment by Melkster** [comment]
@lukas-reineke I think I figured it out. The blank line indentation bars only appear after I save the file, which I didn't try until now.

However, that feature seems to apply to any new blank line that is added; it doesn't get indentation guides until I save the file. Is that something that could be fixed? Should I create a new issue mentioning this?

I tried adding `autocmd InsertLeave * IndentBlanklineRefresh` but that doesn't seem to have any effect.

**Comment by lukas-reineke** [comment]
unsaved changes are not supported.
To generated the guides async, this plugin runs an embedded instance of neovim. For that instance to read the file, it has to be saved.
To support unsaved changes, the computation would need to happen in the main neovim instance, but that is way too slow. You would get >1 second delay every time you exit insert mode, or do any other text modifications.
