### ISSUE TITLE
[feat] Option to place line-character on the *left* of the line-column instead of the *right*

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [lukas-reineke/indent-blankline.nvim#182]
At the moment, this plugin assumes the indentation-character is located either in the center (`|`, etc) or at the far-left-edge (`⎸`) of the character-cell.

Unfortunately, the indent-guide character that ships with NerdFonts draws at the far-*right* edge of the character cell, leading to the indent-guides looking like this:

<img width="112" alt="Screen Shot 2021-08-25 at 12 54 33 PM" src="https://user-images.githubusercontent.com/200/130848797-128159b9-f257-41a7-865b-be8972d585c6.png">

One *could* ask NerdFonts to add an additional, left-aligned indent-guide character; but frankly, this seems more like it needs a solution downstream (here, and similar plugins.) I'd really like to see a toggle that basically subtracts one from the character-column in which lines are drawn, so that right-aligned drawing characters can be used! (=

(The implementation may be slightly more complex than simply subtracting one — for instance, despite the character technically being in the column *before* the function-name, it shouldn't be drawn on the same line as the function-name …)

**Comment by ELLIOTTCABLE** [comment]
Oh, this is _fantastic._

<img width="212" alt="Screen Shot 2021-08-29 at 9 16 36 PM" src="https://user-images.githubusercontent.com/200/131280268-8fdf899e-c3ad-4f66-8e5f-2a7d4843922f.png">

I'll keep it enabled for a while, and try to remember and report back if it leads to any extra weird behaviour? Although it may be hard for me to tell; my other issue with VimR, the one waiting on upstream (#181) is causing enough 'weirdness' that I may not notice anything specific to this branch!

**Comment by chancez** [comment]
I'm experiencing the issue reported due to my usage of nerd fonts (for Pauline) as well. Any updates on if this is ready for being added to a release?

**Comment by chancez** [comment]
Well I tried the mentioned branch but it doesn't seem quite right still:
<img width="280" alt="Screen Shot 2022-01-17 at 10 28 27 PM" src="https://user-images.githubusercontent.com/1400401/149882697-2b2aa69f-11de-4768-8e93-26bb677e9c4f.png">

**Comment by lukas-reineke** [comment]
I won't add this. Just shifting everything left is not an actual fix. All the underlying listchars don't match anymore. This leads to all kinds of weird behavior (as you can see in the screenshot).
The only real solution is to use a character that is rendered correctly. Nothing the plugin can do.
