### ISSUE TITLE
init.vim config: `let` ignored

### ISSUE THREAD

**Issue by DerWeh** [lukas-reineke/indent-blankline.nvim#188]
I use the following minimal configuration

```vim
" init.vim
let g:vimdir = stdpath('config')
call plug#begin(g:vimdir.'/plugged')
Plug 'lukas-reineke/indent-blankline.nvim'
call plug#end()

let g:indent_blankline_char = '│'
```

However, if I check the variable I get
```vim
:let g:indent_blankline_char
g:indent_blankline_char  | 
```

Apparently, the option `let g:indent_blankline_char = '│'` is ignored.
How can I correctly set the options from `init.vim`? Maybe an example would be good for the README, I guess I am not the only one note really familiar with lua configs yet.

**Comment by lukas-reineke** [comment]
I can't reproduce this.
Your config is correct, and it works for me.

**Comment by DerWeh** [comment]
Sorry for the trouble.
After removing the plug-in and installing again, the problem is gone now.

By now, I also found references mentioning how to use the `lua` configurations by wrapping them in

```vim
lua << EOF
...
EOF
```
