### ISSUE TITLE
Help:How to show indent line in defx?

### ISSUE THREAD

**Issue by krisfans** [lukas-reineke/indent-blankline.nvim#196]
Thanks for your work.
How can I  show indent line in a file tree plugin:[defx](https://github.com/Shougo/defx.nvim) ,
my config is this but it doesn't work.
```vim
autocmd FileType defx let g:indent_blankline_show_first_indent_level = v:true
```
expect behavior
![Snipaste_2021-09-02_11-25-09](https://user-images.githubusercontent.com/57793534/131777033-2052688b-aa1b-4590-82a5-93967c7812f2.png)

Actual behavior
![Snipaste_2021-09-02_11-25-49](https://user-images.githubusercontent.com/57793534/131777046-bcda3858-660b-4b29-86a4-cf9f70d83a3d.png)

**Comment by lukas-reineke** [comment]
You shouldn't need to do anything. It is on by default.
Maybe check what `:set shiftwidth` is set to.

defx can also show indent lines itself. I myself do it that way instead.
https://github.com/lukas-reineke/dotfiles/blob/e25ddbd9c9dd09967f9c8fd82f9e457e7c81eddb/vim/lua/plugins.lua#L205-L247

![Screen Capture_select-area_20210902143017](https://user-images.githubusercontent.com/12900252/131787201-d03c0b1f-8f98-4637-9fe1-41f70f34b8ba.png)

**Comment by krisfans** [comment]
Does this mean that the indentation value is equal to `shiftwidth`? I want to set the indentation value in defx to 2 and the other default indentation is 4. What should I do?

**Comment by krisfans** [comment]
May I need put this into my vimrc
```vim
autocmd FileType defx setlocal shiftwidth=2  tabstop=2  softtabstop=2
```

**Comment by lukas-reineke** [comment]
Yes :+1:, just this should be enough

```vim
autocmd FileType defx setlocal shiftwidth=2
```

Or you can take a look at `:help ftplugin`
