### ISSUE TITLE
auto detect indent width

### ISSUE THREAD

**Issue by xtrats** [lukas-reineke/indent-blankline.nvim#197]
Thanks for your work. It works fine when indent width == 4, but not valid when indent width == 2.
Could it detect indent width of a file automatically and show indent lines in a right way?

![indent-line](https://user-images.githubusercontent.com/5361387/131777940-c37c85a7-cd1a-498f-8698-3eddbb18eb9a.png)

**Comment by lukas-reineke** [comment]
indent-blankline uses whatever you have set as the `:help 'shiftwidth'` (or `:help 'tabstop'` if you use tabs)

tpope has a plugin to automatically set this based on what is already in the file
https://github.com/tpope/vim-sleuth

I won't add this functionality here.

**Comment by gmr458** [comment]
I found one written in Lua https://github.com/NMAC427/guess-indent.nvim
