### ISSUE TITLE
Lua files have a line in front for no reason with treesitter enabled

### ISSUE THREAD

**Issue by jacekjarosz55** [lukas-reineke/indent-blankline.nvim#206]
![test.lua](https://user-images.githubusercontent.com/72438686/132028760-5bcf48a2-f2c7-4be7-a1de-bc7bbff2e352.png)

it doesn't happen with any other languages

![test.cpp](https://user-images.githubusercontent.com/72438686/132028837-92f6cc39-c4e0-4279-b4eb-e3865d247f02.png)

**Comment by jacekjarosz55** [comment]
alright i figured it out, you need to have lua installed in treesitter, but what if there was a way to not use treesitter if its not installed for the current buffer?

**Comment by lukas-reineke** [comment]
The plugin does fall back to the normal indent mode when treesitter can't do indent for the current filetype
