### ISSUE TITLE
Handle the case where a `tabstop` is multiple indent levels

### ISSUE THREAD

**Issue by zeertzjq** [lukas-reineke/indent-blankline.nvim#208]
Some projects (e.g. Vim) use a tab to mean multiple indent levels (`tabstop` is a multiple of `shiftwidth`). `noexpandtab` doesn't necessary mean tabs are used for indentation either. For example, C source files of Vim  uses `ts=8 sts=4 sw=4 noet`: 4 spaces for each indent level, and convert 8 spaces to a tab.

**Comment by lukas-reineke** [comment]
I didn't think anyone would use `noexpandtab` when indenting with spaces.

The plugin handles all kinds of mixed indentation now, it should just use the correct value for each whitespace, and not make any assumptions of the whole file.
Shouldn't be too difficult to change, I'll see when I have some time.

**Comment by zeertzjq** [comment]
I think the problem is that this plugin always treats tab as one indent level, whereas in some projects (e.g. Vim) a tab can mean multiple indent levels. I'm changing the title to be more specific.

**Comment by kokoteen** [comment]
don't know if this is the same problem, and i didn't want to create separate issue if it was. so, my expectation was that in diff scopes indentline would be highlighted, but it seems it doesn't work like that. here is the python code. it has the same behaviour in bash and c/cpp
![image](https://user-images.githubusercontent.com/36460995/135614675-bbae1c9e-1352-4d9c-b4b1-af5e515eccbb.png)

**Comment by lukas-reineke** [comment]
@kokoteen this is unrelated.

You probably want to take a look at `:help g:indent_blankline_context_patterns`

If this doesn't solve it, please open a new issue.

**Comment by lukas-reineke** [comment]
Fixed with version 3
