### ISSUE TITLE
Error: ... Attempt to call field 'setup' (a `nil`) value

### ISSUE THREAD

**Issue by Pocco81** [lukas-reineke/indent-blankline.nvim#209]
Today I tried configuring indent-blankline in lua, but it seems like you forgot to return `setup()` under `lua/indent_blankline/init.lua`? or perhaps I'm doing something wrong?

Error:
![image](https://user-images.githubusercontent.com/58336662/132109073-4905b5fa-0033-4934-82c0-67f6a05c4ba1.png)

Packer config:
![image](https://user-images.githubusercontent.com/58336662/132109079-e9154a80-0375-4648-9eb9-3d290d32d80b.png)

**Comment by lukas-reineke** [comment]
You need to use the `config` instead of `setup` hook in packer.
`setup` runs before the plugin is loaded.
`config` runs after the plugin is loaded.
The naming is a bit confusing.

```lua
use {
	"lukas-reineke/indent-blankline.nvim",
    config = function()
		require "indent_blankline".setup()
	end,
}
```

**Comment by Pocco81** [comment]
Damn... Excuse the noise.
