### ISSUE TITLE
How did you get the eol character virtual text?

### ISSUE THREAD

**Issue by PitcherTear22** [lukas-reineke/indent-blankline.nvim#21]
I'm talking about this
![image](https://user-images.githubusercontent.com/36493671/87697034-3cb63600-c7af-11ea-9c57-344d66518940.png)

**Comment by lukas-reineke** [comment]
This is done with `:h listchars`

The end of line character is set like this `set listchars=eol:↴`

**Comment by PitcherTear22** [comment]
Ok, I have set
```vim
set listchars=eol:↴,tab:<->,space:·
```
And I have nothing like this, but `:list` shows the correct characters
![Screenshot from 2020-07-17 17-27-47](https://user-images.githubusercontent.com/36493671/87783985-219d0200-c853-11ea-81d6-88d0f14daf14.png)

**Comment by lukas-reineke** [comment]
did you try `:set list`? I think it defaults to off

**Comment by PitcherTear22** [comment]
It works now, thanks
