### ISSUE TITLE
[nvim] indent-blankline defaults to two spaces instead of four

### ISSUE THREAD

**Issue by Delta-official** [lukas-reineke/indent-blankline.nvim#215]
Title explains it all, here's a screenshot
![Знімок екрана  о 16 23 19](https://user-images.githubusercontent.com/64544951/133091331-dd59e91c-d351-4e83-b6bb-ce78962ea458.png)
and here's my init.vim (shortened to only have needed info)
```vim
call plug#begin(stdpath('data') . '/plugged')
" ...
Plug 'lukas-reineke/indent-blankline.nvim'
let g:indentLine_char='¦'
let g:indent_blankline_space_char=' '
let g:show_end_of_line=v:true
set listchars=tab:→\ ,eol:,nbsp:␣,trail:•,space:•
set list
" ...
call plug#end()
" ...
set cindent
set cino="4"
set shiftwidth=4
```

**Comment by lukas-reineke** [comment]
The plugin uses `shiftwidth` if the file is indent with spaces, or `tabstop` if it is indented with tabs.
Can you check what those values are set to inside the file with `:set shiftwidth`, or `:set tabstop`?

**Comment by Delta-official** [comment]
it's set to shiftwidth 4

**Comment by lukas-reineke** [comment]
And the file is not indented with tabs?

**Comment by Delta-official** [comment]
no, it is indented with spaces

**Comment by Delta-official** [comment]
huh, i opened a file i edited with nvim in vscode, and for some reason the 2 spaces became 8
![Знімок екрана  о 21 38 24](https://user-images.githubusercontent.com/64544951/133314846-d0689e12-76ab-480e-b2b3-72bac94d1a5e.png)

**Comment by lukas-reineke** [comment]
The only way 4 spaces can become 8 is if the file is indented with tabs.

Can you copy paste the code here?

**Comment by Delta-official** [comment]
https://user-images.githubusercontent.com/64544951/133470696-0dfa153a-d720-432c-b755-b37572193648.mov
int main() {
                f
}

**Comment by lukas-reineke** [comment]
The file is clearly indented with tabs. `cat` converts a tab into 8 spaces.
You can confirm with `:!cat --show-tabs main.c`

Something is probably overwriting your settings for c files.
Can you run `:echo &expandtab` and `:echo &tabstop` inside the c file?

**Comment by Delta-official** [comment]
i did and the result was `1` and `4`, just like in the settings
also for some reason blankline displays the 4 space indent correctly, this is strange...

**Comment by lukas-reineke** [comment]
Maybe `vartabstop` is set? That is currently not supported.

Otherwise I'm out of ideas. Try to remove stuff from your `init.vim` until you find what is causing the issue.

**Comment by Delta-official** [comment]
this is very strange, now it indents with spaces, i guess i'll close this issue as the problem seems to be resolved
