### ISSUE TITLE
Background example not working

### ISSUE THREAD

**Issue by lukas-reineke** [lukas-reineke/indent-blankline.nvim#216]
Hi, i tried to use the fourth example and change it to be like with no characters and only a darker background but it's showing this line in the middle..
![with](https://user-images.githubusercontent.com/21209054/133336969-8ab50343-a61b-4566-b8df-2c1fdde917ee.png)
![without](https://user-images.githubusercontent.com/21209054/133336956-7b717c1f-d66e-46e2-ba7c-42bf339090e1.png)

this one:
https://camo.githubusercontent.com/443ad8d61fffb539c6fc097177ac91b225b48070f9c956ee701a3b10286285f4/68747470733a2f2f692e696d6775722e636f6d2f44756b4d5a476b2e706e67

_Originally posted by @lemontghe in https://github.com/lukas-reineke/indent-blankline.nvim/issues/174#issuecomment-919531617_

**Comment by lukas-reineke** [comment]
The readme was wrong. I updated the example

**Comment by lemontghe** [comment]
> Hi, i tried to use the fourth example and change it to be like with no characters and only a darker background but it's showing this line in the middle..
> ![with](https://user-images.githubusercontent.com/21209054/133336969-8ab50343-a61b-4566-b8df-2c1fdde917ee.png)
> ![without](https://user-images.githubusercontent.com/21209054/133336956-7b717c1f-d66e-46e2-ba7c-42bf339090e1.png)
> 
> this one:
> https://camo.githubusercontent.com/443ad8d61fffb539c6fc097177ac91b225b48070f9c956ee701a3b10286285f4/68747470733a2f2f692e696d6775722e636f6d2f44756b4d5a476b2e706e67
> 
> _Originally posted by @lemontghe in [#174 (comment)](https://github.com/lukas-reineke/indent-blankline.nvim/issues/174#issuecomment-919531617)_

thanks, also you have to make the first bg to none to be the default background of colorscheme
![before](https://user-images.githubusercontent.com/21209054/133539366-49a5834d-f356-48e3-bf8a-8dabca1b018e.png)
![after](https://user-images.githubusercontent.com/21209054/133539373-28e4118e-d92e-4028-939e-76248a2bf59d.png)
.

**Comment by lukas-reineke** [comment]
> you have to make the first bg to none to be the default background of colorscheme

That's user preference. I think with the example like this, everyone understands how to customize the colors.
In the example screenshot #1f1f1f is the background color, so it doesn't make a difference.
