### ISSUE TITLE
E5108: Key not found: indent_blankline_space_char_blankline  

### ISSUE THREAD

**Issue by wookayin** [lukas-reineke/indent-blankline.nvim#219]
Error:

```
E5108: Error executing lua ...gged/indent-blankline.nvim/lua/indent_blankline/init.lua:45: Key not found: indent_blankline_space_char_blankline  
```

The commit bc35145 (#190) removed such `g:indent_blankline_space_char` or `g:indent_blankline_space_char_blankline` option, but it is still referenced in `init.lua`. Therefore a vimrc that does not configure this removed(?) variable (and that didn't have lua-based configs) will raise such an error.

```
│ 41     vim.g.indent_blankline_space_char_blankline = o(                                                                      
│ 42     ┊   options.space_char_blankline,                                                                                     
│ 43     ┊   vim.g.indent_blankline_space_char_blankline,                                                                      
│ 44     ┊   vim.g.indent_blankline_space_char                                                                                 
│ 45     )                
```

**Comment by wookayin** [comment]
It looks like it is due to a changed behavior of `vim.g.xxxx` -- which returns `nil` for missing key but in some earlier neovim version (not sure through when) it was raising a KeyError.

**Comment by lukas-reineke** [comment]
Thanks

This was probably a bad merge, the variable was initialized twice.
