### ISSUE TITLE
show end of line not working

### ISSUE THREAD

**Issue by vuongkienthanh** [lukas-reineke/indent-blankline.nvim#222]
This is my config: 
```
use {
    'lukas-reineke/indent-blankline.nvim',
    config = function()
      vim.opt.listchars = {
        space = "⋅",
        eol = "↴",
      }
      require("indent_blankline").setup {
        char = "┆",
        show_end_of_line = true,
        space_char_blankline = " ",
      }
    end
  }
```
I already checked `:set listchars` and it has those 2 variables. The indent char is displayed correctly. With above setting, show_end_of_line and space (as in readme) don't work as expected.

**Comment by lukas-reineke** [comment]
I can't reproduce, this config works fine for me.

Can you try to create a full minimal `init.lua` file that reproduces the issue?

**Comment by amazingefren** [comment]
I was having the same issue

``` vim
set list
```
or in lua
``` lua
vim.opt.list = true
```
fixed it for me

**Comment by lukas-reineke** [comment]
Yes, `list` needs to be set. The plugin mirrors what normal Neovim does.
When you don't have `list` set, you don't see end of line characters.

I added this to the readme to make it more clear.

**Comment by vuongkienthanh** [comment]
yes it works now thks
