### ISSUE TITLE
[question] its possible to adjust the color of 	show_current_context = true ?

### ISSUE THREAD

**Issue by alexzanderr** [lukas-reineke/indent-blankline.nvim#223]
as you can see
![image](https://user-images.githubusercontent.com/54772464/134050833-cb5a0c74-3634-4e21-b674-887cb50b4597.png)

the current context indent line color is green. can i change this color?
or its just based on the theme?

**Comment by amazingefren** [comment]
that would be 
```
:hi IndentBlanklineContextChar
```
it can be defined by a theme if set, however, you can also simply override it using 
``` lua
vim.cmd[[highlight IndentBlanklineIndent1 guifg=#COLOR]]
```
P.S: You can have it more accurately highlight the correct context by setting `context_patterns` option in your configuration

**Comment by lukas-reineke** [comment]
Thanks @amazingefren
That is all correct.

Just one small addition, you should add `gui=nocombine` to the highlight group, or the character inherits things like italic if the surrounding code is a comment etc.

```lua
vim.cmd[[highlight IndentBlanklineIndent1 guifg=#COLOR gui=nocombine]]
```

**Comment by amazingefren** [comment]
@lukas-reineke updated previous comment with correct highlight group! accidentally used the example with the wrong highlight group

**Comment by amazingefren** [comment]
if you used: `highlight IndentBlanklineIndent1 guifg=#COLOR gui=nocombine`
there is a typo (incorrect highlight group)
if you used `guifg=#COLOR` you hadn't actually assigned a color to it
try:
``` lua
vim.cmd[[highlight IndentBlanklineContextChar guifg=#ff0000 gui=nocombine]]
```
in which `#ff0000` is HEX for red

**Comment by alexzanderr** [comment]
works now. thanks.

also, please take a look at that demo.

**Comment by alexzanderr** [comment]
also.
![image](https://user-images.githubusercontent.com/54772464/134233024-6dced1af-08e3-43a6-b70c-73b32c5d9dd6.png)
here that function is inside a class. the plugin highlighted correctly. but when moving around in that function to the location of `if` and inside `if`, the highlight doesnt work, its not applied

![image](https://user-images.githubusercontent.com/54772464/134233216-ad7814c3-4c14-4424-8079-3b60c2bf8bd4.png)

look where my cursor is. inside that `if`, the indent line just near the if should be highlithed.

now i came to conclusion that this plugin only takes into consideration the `def`s and `class`es for current context highlighting.

**Comment by amazingefren** [comment]
@alexzanderr 
that is because you have to define context_patterns, it should be a [array](https://www.lua.org/pil/11.1.html) of strings
for example:
``` lua
require('indent_blankline').setup {
  -- ... your config
  context_patterns = {
    "def",
    "class",
    "return",
    "function",
    "method",
    "^if",
    "^while",
    "jsx_element",
    "^for",
    -- ... and you can add more
  }
}
```

**Comment by alexzanderr** [comment]
now it works.
![image](https://user-images.githubusercontent.com/54772464/134234381-d6a8d766-4b9b-43af-854a-860feff2851e.png)

but wait a second.

do you notice that there is long line between `pass` and `x = 3`, is it normal?
i guess only the indent line under the second for is respecting format, but the above one is not right.

is there a way to delete that extra line? or to specify a level of indentation? or to ignore that extra space between lines?

**Comment by alexzanderr** [comment]
btw. please update `readme` with these
```lua
  context_patterns = {
    "def",
    "class",
    "return",
    "function",
    "method",
    "^if",
    "^while",
    "jsx_element",
    "^for",
    -- ... and you can add more
  }
```
and if there is more configuration ... please update readme.

**Comment by amazingefren** [comment]
@alexzanderr 
as for the extra indentline appearing, I don't believe that is this plugins fault.
The plugin is working as intended and creating a indentline where (treesitter?) is saying there should be an indent there.
You can test this, if you go to your line with `pass` and hit `o`, it will create a new line indented over when it shouldn't, as for a fix i'm not exactly sure.

for the context_patterns configuration, it is not defined by the plugin solely, it should be defined by [treesitter](https://tree-sitter.github.io/tree-sitter/) so all available configuration options should be with its parser
example: [javascript](https://github.com/tree-sitter/tree-sitter-javascript/blob/master/src/node-types.json)

**Comment by amazingefren** [comment]
@alexzanderr 
Python -------------

https://user-images.githubusercontent.com/48777455/134237295-0cb97acb-56ba-4582-bdec-dcb08a04d9c2.mp4

Typescript ---------

https://user-images.githubusercontent.com/48777455/134237313-58ce1476-2674-4c0c-b735-115f85a247f2.mp4

Check out how hitting `o` (create a new line) automatically is automatically indenting over when it *shouldn't?* be

When this plugin is notified that there is a indentation, it will place it (as it should be doing). 

Compare that to the typescript example above in which the line only appears before I define x (when `let x=` before `10` is added) but then proceeds to properly indent after declaration to the correct indent level

**Comment by alexzanderr** [comment]
![image](https://user-images.githubusercontent.com/54772464/134238412-283e1b88-64e1-4bbd-8404-dc925faaf9da.png)

i see yours its working fine with the above lines

**Comment by alexzanderr** [comment]
> @alexzanderr
> Python -------------
> python_demo.mp4
> 
> Typescript ---------
> typescript_demo.mp4
> 
> Check out how hitting `o` (create a new line) automatically is automatically indenting over when it _shouldn't?_ be
> 
> When this plugin is notified that there is a indentation, it will place it (as it should be doing).
> 
> Compare that to the typescript example above in which the line only appears before I define x (when `let x=` before `10` is added) but then proceeds to properly indent after declaration to the correct indent level

i dont know what to say to this...

so its tree-sitter's fault?

**Comment by Daxtorim** [comment]
@alexzanderr I think what you want is `show_trailing_blankline_indent = false`. That option defaults to `true` and will do what it says, add an *additional* indent guide to blank lines.

**Comment by amazingefren** [comment]
@alexzanderr 
I don't know exactly what the fault is, what I do know is that when you see the extra indent line, that is because something ( i was assuming treesitter ) was essentially telling this plugin that there will be an indentation level there.

https://user-images.githubusercontent.com/48777455/134240284-1ae2a0ed-04b0-4f1a-92d5-cb37d512eef5.mp4

**Comment by Daxtorim** [comment]
@alexzanderr @amazingefren
Tested this myself now and it is exactly what I said above. It's an option of this plugin.

`let g:indent_blankline_show_trailing_blankline_indent = v:true`:
![image](https://user-images.githubusercontent.com/72616153/134241239-c55767ce-37f2-496b-98bd-b124867f9e44.png)

`let g:indent_blankline_show_trailing_blankline_indent = v:false`:
![image](https://user-images.githubusercontent.com/72616153/134241272-8824ecc0-5885-4aba-886b-f41307a696c5.png)

**Comment by amazingefren** [comment]
@Daxtorim 
the video above is with `show_trailing_blankline_indent = false`
without changing my configuration at all if I copy your example code it looks exactly the same, the issue is partly unrelated

![python_demo_3](https://user-images.githubusercontent.com/48777455/134242264-90c5478a-4aa5-4421-a728-9d9b81c5041f.png)

the lines he is seeing are not trailing lines, they are showing the indentation level

**Comment by alexzanderr** [comment]
> show_trailing_blankline_indent = false

wow. now its so `perfect`
![image](https://user-images.githubusercontent.com/54772464/134243638-10e81e11-ed77-428d-beb3-31d4e389aaca.png)

thank you so much man.

**Comment by alexzanderr** [comment]
> @alexzanderr @amazingefren
> Tested this myself now and it is exactly what I said above. It's an option of this plugin.
> 
> `let g:indent_blankline_show_trailing_blankline_indent = v:true`:
> ![image](https://user-images.githubusercontent.com/72616153/134241239-c55767ce-37f2-496b-98bd-b124867f9e44.png)
> 
> `let g:indent_blankline_show_trailing_blankline_indent = v:false`:
> ![image](https://user-images.githubusercontent.com/72616153/134241272-8824ecc0-5885-4aba-886b-f41307a696c5.png)

@amazingefren @Daxtorim i really like that you copied my stupid template code format with:
```python
def some_function():
   "asdasd"
```
i really laughed!!

**Comment by amazingefren** [comment]
@alexzanderr
wait am I tripping balls or did my indentation level mask your trailing lines, can do me a favor and upload a screen shot of the new config with this code? \\/

![134234381-d6a8d766-4b9b-43af-854a-860feff2851e](https://user-images.githubusercontent.com/48777455/134244238-a8fa57ad-2ff9-4f9e-b10b-e791c6ae051b.png)

**Comment by alexzanderr** [comment]
haha, omg you make me laugh.

here is the photo:
![image](https://user-images.githubusercontent.com/54772464/134244614-1ac9d02e-57ed-401d-8bff-ddc51ee03bf6.png)

this is how it should look like (it already looks like this, its perfect)

**Comment by alexzanderr** [comment]
@lukas-reineke do you have discord?

**Comment by amazingefren** [comment]
holy shit it was, I don't know what was causing mine to parse an extra indentation level (making it look exactly like yours)  while yours were actually trailing lines (which I had already disabled)

it had completely misinterpreted it as indentation lines rather than trailing lines so my bad

**Comment by alexzanderr** [comment]
> however I am currently transitioning to dvorak

why ?
you didnt answer my question: do you have discord? we can talk there.

**Comment by amazingefren** [comment]
didn't realize you mean to tag me
I don't use discord frequently but you can add me `efrentheroker#1273`

Also, close this thread if your issue has been resolved

**Comment by alexzanderr** [comment]
done. thanks

**Comment by lukas-reineke** [comment]
Thanks for the help @amazingefren  and @Daxtorim :heart: 

To clear up some confusion, I call the last indent of a blank line the trailing indent.
And you can turn this one on or off, because people have different preferences here.
This is unrelated to treesitter, works the same if you don't have treesitter enabled.
Should look just like https://github.com/lukas-reineke/indent-blankline.nvim/issues/223#issuecomment-924351878

But as you can see in that screenshot as well, treesitter sometimes gets the indentation wrong and adds more than there should be.
I myself have treesitter turned off for this. The other implementation does not make these mistakes, it always looks good (but is not always semantically correct)

> do you have discord?

No, just twitter and reddit. If you want to chat either is fine.

**Comment by alexzanderr** [comment]
lets chat then
