### ISSUE TITLE
Conflict with cursorline

### ISSUE THREAD

**Issue by fritzrehde** [lukas-reineke/indent-blankline.nvim#225]
![Screen Shot 2021-09-22 at 20 57 36](https://user-images.githubusercontent.com/80471265/134405207-5426b12d-dcbd-4968-a583-b749e8a4a4f9.png)
When navigating through a file with "set cursorline" enabled in my config, marks of the same color as the cursorline appear once the cursor has crossed those lines.

**Comment by lukas-reineke** [comment]
This is a duplicate of #59
You can take a look there for a workaround
