### ISSUE TITLE
Incorrect indent guides with treesitter enabled

### ISSUE THREAD

**Issue by Big-Tree** [lukas-reineke/indent-blankline.nvim#226]
When tree sitter is enabled there are indent lines on lines 91-97 which should not be there.  Strangely these indent lines are not highlighted like the lines above.

init.vim indent-blankline settings:
```
let g:indent_blankline_use_treesitter = v:true
let g:indent_blankline_show_current_context = v:true
```

Treesitter enabled:
![Screenshot_2021-09-22_21-39-41](https://user-images.githubusercontent.com/12074010/134418825-2242f0f0-dc55-40e8-83b3-2d768c34a27e.png)
Treesitter disabled:
![Screenshot_2021-09-22_21-40-14](https://user-images.githubusercontent.com/12074010/134418839-b6616759-53ea-4400-a3c9-b5b89020eb7e.png)

**Comment by lukas-reineke** [comment]
Treesitter indentation for python isn't that great.
You can open an issue there https://github.com/tree-sitter/tree-sitter-python

This plugin just takes the value that treesitter returns. Nothing I can do here to fix this.
