### ISSUE TITLE
Plugin does not work.

### ISSUE THREAD

**Issue by dominikduda** [lukas-reineke/indent-blankline.nvim#23]
My nvim:
```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-oa960Y/neovim-0.5.0+ubuntu1+git202008171349-161cdba1e-00e710ec6=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-oa960Y/neovim-0.5.0+ubuntu1+git202008171349-161cdba1e-00e710ec6/build/config -I/build/neovim-oa960Y/neovim-0.5.0+ubuntu1+git202008171349-161cdba1e-00e710ec6/src -I/build/neovim-oa960Y/neovim-0.5.0+ubuntu1+git202008171349-161cdba1e-00e710ec6/.deps/usr/include -I/usr/include -I/build/neovim-oa960Y/neovim-0.5.0+ubuntu1+git202008171349-161cdba1e-00e710ec6/build/src/nvim/auto -I/build/neovim-oa960Y/neovim-0.5.0+ubuntu1+git202008171349-161cdba1e-00e710ec6/build/include
Compiled by buildd@lcy01-amd64-026

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
Here is part of my `vimrc` containing plug install: https://gist.github.com/dominikduda/7369b764aa54002f1d749c97b69a0832#file-vimrc-L124
Here is the plugin config: https://gist.github.com/dominikduda/7369b764aa54002f1d749c97b69a0832#file-vimrc-L1187

Thats how it looks like:
![image](https://user-images.githubusercontent.com/14922999/90783907-f64d7d00-e300-11ea-8fa2-fd5a6e8f6be6.png)

Am I doing something wrong? It does not work out of the box for me, neither I see anything wrong with the config.

**Comment by lukas-reineke** [comment]
Don't call refresh on `CursorMoved`, the plugin processes the file that is saved to disk. Refreshing on every cursor movement is just unnecessary load.

It still should work though. Can you try setting `let g:indent_blankline_debug = v:true` and see if you get any error message?

**Comment by dominikduda** [comment]
No error messages occur.

Plugin commands exist, so it is properly installed, but does nothing.

Any further ideas?

**Comment by dominikduda** [comment]
`echo &indentexpr` prints `GetVimIndent()`
I'll test the plugin with all other plugins disabled later today.

**Comment by lukas-reineke** [comment]
sorry for the late response, I had a couple days off.

it prints `GetVimIndent()` for the javascript file you posted? Thats wrong, that would mean it's trying to indent it as vimscript.

To make sure its not an issue with the indent expression settings, can you try it manually?
You need to set `v:lnum` to the line number you want to check `let v:lnum = 123` and then run `execute('echon '. &indentexpr)`
this should print the number of spaces indentation should be for that line. Thats what the plugin uses.

**Comment by syyyr** [comment]
Hi, I'm also unable to get the plugin running. I tried running this with just indentLine and this plugin installed through vim packages.
```
$ ls -la ~/.local/share/nvim/site/pack/bundle/start 
total 16
drwxr-xr-x 4 vk vk 4096  1. zář 15.26 .
drwxr-xr-x 4 vk vk 4096  1. zář 15.25 ..
drwxr-xr-x 5 vk vk 4096  1. zář 15.25 indent-blankline.nvim
drwxr-xr-x 5 vk vk 4096  1. zář 15.26 indentLine
```

If I then run vim without any other config (via `vim -u NORC`) indentLine works fine, but indent-blankline doesn't. Maybe I'm missing something? This is how it looks:
![image](https://user-images.githubusercontent.com/17759291/91857579-5e3c8580-ec68-11ea-9022-2f7c55f8ebbf.png)

My nvim version:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std
=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HA
S_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by lukas-reineke** [comment]
@syyyr are you saving the file? And can you use a filetype that has an indent expression to test.
Just random text will not work.

**Comment by syyyr** [comment]
I thought that when `indentexpr` is empty, `cindent()` is used. But anyway, I tried using the `vim` filetype, which has an `indentexpr` set and also save the file, but still no luck :/
![image](https://user-images.githubusercontent.com/17759291/91957044-d016dc80-ed05-11ea-829a-bb92e264fc68.png)

I also tried to use the test suggestion with `let v:lnum = 4` and `execute('echon '. &indentexpr)` and that gave me 16, so should that should work correctly.

**Comment by lukas-reineke** [comment]
> I thought that when indentexpr is empty, cindent() is used.

it is, I thought cindent will not work for just random text, but it does :+1: your first example should work.

Have you set `let g:indent_blankline_debug = v:true` and checked if there is any error with `:messages`?

Can you also check if the embedded nvim instance is running?
`:echo jobpid(g:indent_blankline_nvim_instance)` should get you the pid, or an error like `Invalid channel id`

**Comment by syyyr** [comment]
Aha!, `:echo jobpid(g:indent_blankline_nvim_instance)` does give me some number, but `:echo nvim_get_namespaces()` gives me just empty curly braces.

With `let g:indent_blankline_debug = v:true`, `:messages` shows nothing.

**Comment by lukas-reineke** [comment]
hmm, no namespace means the callback is never called. Something inside the embedded instance is going wrong.
Still no idea what that could be though.. everything is wrapped in a try catch.

Just to make sure, can you edit the file `autoload/indent_blankline/embedded.vim`, and add `throw 'foo'` as line 4? First line inside the try catch block
then check that you get the error message

**Comment by syyyr** [comment]
I tested, and I got no error message unfortunately.

**Comment by lukas-reineke** [comment]
so it never even calls the embedded instance

what does `:echo filereadable(expand('%'))` return?

**Comment by syyyr** [comment]
`:echo filereadable(expand('%'))` says "1".

I tried some debugging and found out that in `indent_blankline#Init` if I put a throw statement just before `jobstart`, I get an error, however, if I put it right after, nothing appears, so it seems to me that the `jobstart` function blocks? I'm not sure how it works.

**Comment by lukas-reineke** [comment]
`jobstart` should not block by desgin.

what OS are you on?

**Comment by syyyr** [comment]
Hmm, that's weird, if I remove the try-catch block altogether, the throw statement gets through. I'm not sure why I don't get any error message even though I have `let g:indent_blankline_debug = v:true`. So `jobstart` isn't blocking, it's just that maybe after the job gets started, debugging messages stop working? I'm not sure. But yeah, the problem probably isn't with `jobstart`, sorry for the confusion.

I'm using Arch Linux, and my neovim is from the official repositories.

**Comment by lukas-reineke** [comment]
very weird.. jobstart should not change anything about the debug messages

I'm on arch too, same neovim version so thats not the problem.

lets check if the embedded instance of neovim is alive. `:echon rpcrequest(g:indent_blankline_nvim_instance, 'nvim_eval', '"hello"')` this should send a rpc message and return `hello` back

**Comment by syyyr** [comment]
I tried `:echon rpcrequest(g:indent_blankline_nvim_instance, 'nvim_eval', '"hello"')` and nvim just blocks and nothing happens, I had to kill it. So I guess the emdedded instance crashes.

**Comment by lukas-reineke** [comment]
yea looks like the embedded instance is crashing.

Can you try to start an embedded instance in a completely clean neovim? no plugins or config at all.
Just do

```
:let nvim = jobstart(['nvim', '--embed'], {'rpc': v:true})
:echo rpcrequest(nvim, 'nvim_eval', '"Hello " . "world!"')
```

**Comment by syyyr** [comment]
Okay, I tried what you suggested and `--headless` indeed made a difference: without `--headless` I got a "Hello world!", but with `--headless` nvim just hangs and nothing happens.

**Comment by syyyr** [comment]
Okaaayy, I found the issue. Apparently I left some sort of a remainder for headless nvim UIs from when I was configuring *firenvim* and that crashed headless UIs. Sorry 😅

The plugin works for me now. Thank you :)

**Comment by lukas-reineke** [comment]
awesome! glad you got it to work :tada:

**Comment by subnut** [comment]
@lukas-reineke I'm also on Arch Linux, same neovim version, but running `:echo jobpid(g:indent_blankline_nvim_instance)` shows -
```
E121: Undefined variable: g:indent_blankline_nvim_instance
E116: Invalid arguments for function jobpid
```
i.e. the instance isn't even starting :confused: 

Also `:echo filereadable(expand('%'))` returns `1` and I am testing this in a file that has already been saved.
I also use `indentLine` plugin..
