### ISSUE TITLE
Is it possible to get rid of indent lines if there's no nesting?

### ISSUE THREAD

**Issue by ziombo** [lukas-reineke/indent-blankline.nvim#231]
![image](https://user-images.githubusercontent.com/15613606/134762111-27293f1b-0e04-4596-9b5d-e2ac5c3c594e.png)
Using this function as an example, is it possible to show the vertical lines only for nesting purposes instead of marking every tab with a line?

**Comment by lukas-reineke** [comment]
Yes, you can set ':help g:indent_blankline_max_indent_increase' to 1.  

This will only show the indent if the indent is 1 more than the previous line.

**Comment by ziombo** [comment]
Perfect, exactly what I needed. Thanks
