### ISSUE TITLE
Extra space listchars shown on blanklines

### ISSUE THREAD

**Issue by HumblePresent** [lukas-reineke/indent-blankline.nvim#236]
I recently updated this plugin and I am now seeing an issue where extra space characters are shown on blank lines where there aren't actually any spaces. The screenshot below shows an example of the issue
![blankline_bug](https://user-images.githubusercontent.com/60856003/134815457-91d01146-75e4-4da2-a47d-cb0b9eb1ceef.png)
The blank lines seem to show leading space characters but there are not actually any spaces there.

**Comment by HumblePresent** [comment]
I have done some further testing and tracked the issue down to this commit: 0cbd4a4a551daec02090dd7c78a9c7520cfcb756

**Comment by lukas-reineke** [comment]
Thanks

I pushed a fix
