### ISSUE TITLE
Add versioning tags

### ISSUE THREAD

**Issue by ljmf00** [lukas-reineke/indent-blankline.nvim#239]
It is desired for the end user to have a stable release of the plugin. This way the user can specify on the vim package managers to use a specific version instead of relying on a commit. This can be useful to bump patch versions from https://semver.org/ . Please consider doing periodic release

**Comment by lukas-reineke** [comment]
I should add tags :+1: 

The plugin already follows semver (almost) and I do periodic releases. Everything on master is considered stable. There should be no breaking changes (almost).

**Comment by lukas-reineke** [comment]
I added all tags and created versions back to 2.0.0
https://github.com/lukas-reineke/indent-blankline.nvim/releases
