### ISSUE TITLE
[Feat Req.] Rainbow indent level only on current context

### ISSUE THREAD

**Issue by shaksiper** [lukas-reineke/indent-blankline.nvim#240]
First of all, i must say, this is an excellent plugin and i love every bit of it.
But I have just a tiny request:
Current context option works great, but is it possible to make it rainbow only on current context like VScode does.

Highlighting the current context, based on treesitter, but with different colour on each indentation level.
I ma not sure if it is already possible with the current options, but I haven't been able to reproduce this effect.
So a little bit help would be great. If it is not possible due to other factors. It is not a big deal.

**Comment by lukas-reineke** [comment]
Can you post a screenshot of how it looks like in VSCode? I am not 100% sure I understand.

**Comment by shaksiper** [comment]
Ah sorry about confusion, here's how it looks in vscode
![Untitled](https://user-images.githubusercontent.com/79347616/135083152-cb0aa173-1285-43f3-88b8-ddd1762963c1.png)

**Comment by lukas-reineke** [comment]
This is already supported.
You need to set `:help g:indent_blankline_context_highlight_list`

for example like this

```lua
vim.cmd [[highlight IndentBlanklineIndent1 guifg=#E06C75 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent2 guifg=#E5C07B gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent3 guifg=#98C379 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent4 guifg=#56B6C2 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent5 guifg=#61AFEF gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent6 guifg=#C678DD gui=nocombine]]

require("indent_blankline").setup {
    context_highlight_list = {
        "IndentBlanklineIndent1",
        "IndentBlanklineIndent2",
        "IndentBlanklineIndent3",
        "IndentBlanklineIndent4",
        "IndentBlanklineIndent5",
        "IndentBlanklineIndent6",
    },
    show_current_context = true,
}
```

**Comment by shaksiper** [comment]
off I am sorry, i must have missed that option. 
Now everything is set.
