### ISSUE TITLE
Syntax highlighting breaks with show_current_context

### ISSUE THREAD

**Issue by jordanisaacs** [lukas-reineke/indent-blankline.nvim#247]
When `show_current_context` is enabled syntax highlighting is weirdly broken.

Opening a file with `nvim filename` results in syntax highlighting not working for the current buffer. However, subsequent buffers have working syntax highlighting. Closing and reopening that first buffer results in syntax highlighting activating.

Opening neovim with `nvim` and then opening a file results in syntax highlighting working.

The only thing that changed in my config from when it works to when it breaks is changing `show_current_context = false` to `show_current_context = true`. My guess it has something to do with treesitter interactions and loading?

**Comment by lukas-reineke** [comment]
Thanks, I release a fix
