### ISSUE TITLE
Doesn't work on a .tsx file

### ISSUE THREAD

**Issue by AnatoleLucet** [lukas-reineke/indent-blankline.nvim#25]
Hey :wave:, the plugin works fine on any js/ts file but doesn't on tsx files. I'm kind of a vim newbie so I don't really know what info to give, but feel free to ask me.

Many thanks for this plugin!

**Comment by lukas-reineke** [comment]
It should work fine with `tsx`
Can you check a couple things?

1. what is `:set indentexpr` set to?
2. set `let g:indent_blankline_debug = v:true` in your `init.vim` and see if you get any errors in a `tsx` file with `:messages`

**Comment by AnatoleLucet** [comment]
> what is :set indentexpr set to?

**Comment by AnatoleLucet** [comment]
> what is :set indentexpr set to?

`GetTsxIndent()`

> set let g:indent_blankline_debug = v:true in your init.vim and see if you get any errors in a tsx file with :messages

I don't see any message

**Comment by lukas-reineke** [comment]
`GetTsxIndent()` is not default. Can you check what plugin provides this? `:verbose set indentexpr`

**Comment by AnatoleLucet** [comment]
Seem like it's `yats`

![](https://user-images.githubusercontent.com/35486736/95184619-e8c45780-07c7-11eb-9b6f-4ede82df3aac.png)

**Comment by lukas-reineke** [comment]
hm I'm using `yats` as well with no problems.
Can you share the file that doesn't work?

Can you also run this `:echon rpcrequest(g:indent_blankline_nvim_instance, 'nvim_eval', '"hello"')`? It should print `hello` when everything is okay

**Comment by AnatoleLucet** [comment]
`:echon rpcrequest(g:indent_blankline_nvim_instance, 'nvim_eval', '"hello"')` froze my terminal.

It seems like it doesn't work only if the file is under my project's scope. I'll try to investigate on that.

**Comment by lukas-reineke** [comment]
sounds a lot like what happened in this issue https://github.com/lukas-reineke/indent-blankline.nvim/issues/23#issuecomment-685736837

**Comment by lukas-reineke** [comment]
Alternatively, if you use Neovim 0.5, you can use the `lua` branch. That doesn't use the embedded instance anymore.
It'll become the default once 0.5 is released. It's a lot more stable. And way faster too.

**Comment by AnatoleLucet** [comment]
Yes, I do use nvim 0.5. I've tried with the `lua` branch but when I launch nvim I get this error:
![](https://user-images.githubusercontent.com/35486736/95188286-7ace5f00-07cc-11eb-8f40-e58ef913c170.png)

**Comment by lukas-reineke** [comment]
your 0.5 is not up to date, `vim.b` got merged a couple of months ago https://github.com/neovim/neovim/pull/12268

I'm on `NVIM v0.5.0-672-gd8e6a0396`, that version or anything newer should work

**Comment by AnatoleLucet** [comment]
Indeed. It's working! Thanks for your help
