### ISSUE TITLE
[Feature Request] indent_start_level option

### ISSUE THREAD

**Issue by yutkat** [lukas-reineke/indent-blankline.nvim#253]
I only want to show the indent line if the indent is deeper than the threshold.

indent-guides.nvim has this option as indent_start_level. https://github.com/glepnir/indent-guides.nvim

I hope you will consider adding such an option!

**Comment by lukas-reineke** [comment]
I have nothing against adding this option, but it is not that easy to do.
I personally don't think it is that useful, so I will probably not implement it myself.
Happy for PRs if someone else wants to do it.
