### ISSUE TITLE
won't display space for blankline

### ISSUE THREAD

**Issue by stumash** [lukas-reineke/indent-blankline.nvim#254]
Here's my config
```vim
set lcs=space:·,tab:→\ ,eol:↵
hi NonText ctermfg=0 guifg=#282828
hi SpecialKey ctermfg=0 guifg=#222222
set list
```

```lua
vim.cmd [[highlight IndentBlanklineIndent1 guibg=#1f1f1f guifg=#383838 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent2 guibg=#1a1a1a guifg=#383838 gui=nocombine]]

require("indent_blankline").setup {
    char = "·",
    char_highlight_list = {
        "IndentBlanklineIndent1",
        "IndentBlanklineIndent2",
    },
    space_char_blankline = " ",
    space_char_highlight_list = {
        "IndentBlanklineIndent1",
        "IndentBlanklineIndent2",
    },
    show_trailing_blankline_indent = false,
}
```

Here's what it looks like
![image](https://user-images.githubusercontent.com/13181078/136594596-38d289a6-92bc-4eaf-94ea-6ca5bd162f6d.png)

It's still displaying a dot (weirdly, not two) on the blank lines, even though I set the `space_char_blankline = " "`

Any idea what's going on?

**Comment by stumash** [comment]
it's not a bad feature request come to think of it

**Comment by Daxtorim** [comment]
I'm not sure if a `char_blankline` would be particularly useful as a user defined setting. To me it looks like what you really want is to disable the indent `char` completely and only rely on the highlighting of the background. 

What I mean is something so you can set `char = ""` and it will just not insert any indent `char` at all and just use the underlying whitespace (or lack thereof) to display `listchars`. I'll do some testing...
