### ISSUE TITLE
Makes vim pretty slow on big files

### ISSUE THREAD

**Issue by AnatoleLucet** [lukas-reineke/indent-blankline.nvim#26]
Hey, so after #25 I've been able to use this plugin for a couple of weeks. The only real issue ("real" because I've encountered other issues like the indents indicators not showing up, but it's not that awkward) is that it slows nvim down a lot when writing on big files (I'm testing on a +60000 lines js file (don't ask me why this file exists in the first place, because I have no idea)).

Try to open a big file with this plugin enabled and you should see what I'm talking about. Feel free to ask me any more info :slightly_smiling_face:

**Comment by lukas-reineke** [comment]
> +60000 lines

:fearful: 

If you are on neovim nightly you can try the lua branch. That should be a lot faster.
But with a file that big even that might not be enough.

**Comment by AnatoleLucet** [comment]
I'm already using the lua branch :eyes:

**Comment by lukas-reineke** [comment]
Then your best bet is probably to overwrite the autogroup to only update the indent guides on save. The part that is slow is setting the virtual text, everything else is async.
The only way to optimize that would be to keep a cache to check against first in memory. But that would make the delay longer. And I think I prefer shorter delay over support for massive files

Put this in `after/plugin/foo.vim` (name of the file doesn't matter)
Or `after/ftplugin/javascript.vim` for only js
That overwrites the autogroup set from the plugin, so it only updates when you save.

```
augroup IndentBlanklineAutogroup
    autocmd!
    autocmd OptionSet shiftwidth,tabstop IndentBlanklineRefresh
    autocmd FileChangedShellPost,Syntax * IndentBlanklineRefresh
augroup END
```

**Comment by AnatoleLucet** [comment]
Yep, it seems to work, thanks. Can this possibly be only active on big files (ex +5000 lines)?

**Comment by lukas-reineke** [comment]
sure, just call a function that checks the current line count

```
function! s:IndentBlanklineLinecount()
    if nvim_buf_line_count(0) < 5000
        IndentBlanklineRefresh
    endif
endfunction

augroup IndentBlanklineAutogroup
    autocmd!
    autocmd OptionSet shiftwidth,tabstop IndentBlanklineRefresh
    autocmd FileChangedShellPost,Syntax * IndentBlanklineRefresh
    autocmd TextChanged,TextChangedI * call s:IndentBlanklineLinecount()
augroup END
```

**Comment by AnatoleLucet** [comment]
Great! Thanks
