### ISSUE TITLE
Current context not work for new line(new code), I miss something?

### ISSUE THREAD

**Issue by yyangdid** [lukas-reineke/indent-blankline.nvim#268]
Neovim version: v0.5.1

System: openSUSE x64

Everything is ok when opening the file. When adding new code to the file, the indent line highlight not work for new line.
there is a gif(need to click the picture with the mouse to play it in the new tab):

![aaa (2)](https://user-images.githubusercontent.com/10922667/137756528-6c632858-ef4f-4205-bb90-ad8966531fb0.gif)

this is my config:
``` vim
call plug#begin(stdpath('config') . '/plugged')
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'lukas-reineke/indent-blankline.nvim' 
call plug#end()

lua << EOF
vim.g.indent_blankline_show_current_context = true
vim.g.indent_blankline_use_treesitter = 1
vim.g.indent_blankline_context_patterns = {
  'class',
  'function',
  'method',
  '^if',
  '^while',
  '^typedef',
  '^for',
  '^object',
  '^table',
  'block',
  'arguments',
  'typedef',
  'while',
  '^public',
  'return',
  'if_statement',
  'else_clause',
  'jsx_element',
  'jsx_self_closing_element',
  'try_statement',
  'catch_clause',
  'import_statement',
  'labeled_statement'
}
vim.g.indent_blankline_buftype_exclude = {"terminal"}
vim.g.indent_blankline_show_trailing_blankline_indent = false

vim.cmd [[highlight IndentBlanklineIndent1 guifg=#E06C75 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent2 guifg=#E5C07B gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent3 guifg=#98C379 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent4 guifg=#56B6C2 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent5 guifg=#61AFEF gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent6 guifg=#C678DD gui=nocombine]]

require("indent_blankline").setup {
  context_highlight_list = {
    "IndentBlanklineIndent1",
    "IndentBlanklineIndent2",
    "IndentBlanklineIndent3",
    "IndentBlanklineIndent4",
    "IndentBlanklineIndent5",
    "IndentBlanklineIndent6",
  },
  show_current_context = true,
}
EOF
augroup IndentBlanklineContextAutogroup
    autocmd!
    autocmd CursorMoved * IndentBlanklineRefresh
augroup END

**Comment by goingtosleep** [comment]
> fixed! +1

@yyangdid How did you fix it? I encountered this in Python. But run:
```
:lua print(require "indent_blankline.utils".get_current_context(vim.g.indent_blankline_context_patterns))
```
shows `false`. The treesitter seems to not update the newly pasted code. Updated neovim and treesitter but still not working. A workaround is to run `:e` but that will mess up the folding 😖

**Comment by yyangdid** [comment]
I haven't used nvim for some time, I can't remember how it was solved at that time.

In fact, I've converted to VSCode + remote-ssh.

But I backed up my nvim configuration, you can check these two config files:
- indent-blankline config: [indentblankline.lua](https://github.com/yyangdid/nvim_configs_archive/blob/master/lua/plugins/configs/indentblankline.lua)
- treesitter config: [treesitter.lua](https://github.com/yyangdid/nvim_configs_archive/blob/master/lua/plugins/configs/treesitter.lua)

I hope it helps, good luck.
