### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by romgrk** [lukas-reineke/indent-blankline.nvim#27]
Hi,

I tried the plugin but it made the CPU usage go quite high. I was wondering why you don't just update the indents for the current viewport instead of the whole file? I've been using a modified version of the script you posted in a few places, here it is: https://github.com/romgrk/nvim/blob/master/plugin/indent-lines.vim

It makes use of the new https://github.com/neovim/neovim/pull/13117, but even without that you could always update the indent lines for +- the viewport's height (a scroll of more than that will move the cursor).

**Comment by lukas-reineke** [comment]
ohh nice job with `WinScrolled` :clap: 

I'll look into that!
You should try the `lua` branch, it should be much faster and less CPU intensive than the vimscript version.

**Comment by romgrk** [comment]
Is it still using the technique of starting a hidden neovim instance?

**Comment by lukas-reineke** [comment]
> Is it still using the technique of starting a hidden neovim instance?

No it's not. I gave up on using `indentexpr` because it's so slow.
That way I could write it 100% in lua. In some edgecases it is not as good as `indentexpr`, but the performance boost makes it worth it imo.

**Comment by lukas-reineke** [comment]
It works way better than I though :partying_face: this is really nice, thanks.
Pushed it to the lua branch.
I won't update the old implementation.
