### ISSUE TITLE
the context patterns highlight only works with javascript?

### ISSUE THREAD

**Issue by hrqmonteiro** [lukas-reineke/indent-blankline.nvim#271]
I have this set as my context_patterns:

```
g.indent_blankline_context_patterns = { 'class', 'return', 'function', 'method', '^if', '^while', 'jsx_element', '^for', '^object', '^table', 'block',
    'arguments', 'if_statement', 'else_clause', 'jsx_element', 'jsx_self_closing_element', 'try_statement',
    'catch_clause', 'import_statement', 'operation_type' }
```

And with js/ts it works okay highlighting the current context:

![indent](https://user-images.githubusercontent.com/17055027/138204659-06d60ee3-2bbc-4977-b9db-e62995c80e79.png)

But it doesn't work with any other language?

I work with Ruby and Rust also, and in neither of them it works:

![indent2](https://user-images.githubusercontent.com/17055027/138204722-69401123-8087-4d47-9d15-5a1a9f8d936a.png)
![indent3](https://user-images.githubusercontent.com/17055027/138204762-d8b326a3-ac07-4615-ae6e-af70fb3c99da.png)

Is there something i'm missing? Shouldn't it work with all of them?

**Comment by ievgenii-shepeliuk** [comment]
The same issue is with JSON/YAML. Maybe those formats can be added, since they are quite common ?

**Comment by ievgenii-shepeliuk** [comment]
@lukas-reineke i clearly understand your point about pain of supporting dozens of programming languages.

But in case of `JSON` / `YAML` / `XML` - it makes a lot of sense to add support into the plugin, since it's very likely that most of vim/nvim users are editing configs more often then writing a code in programming language :)

**Comment by hrqmonteiro** [comment]
> Each treesitter grammar defines their own names for things. An if block in JavaScript for example is `if_statement`, but in ruby it is just `if`.
> 
> This is also why the default value for the pattern is so small, I don't want to have to maintain a massive list for every language.
> 
> You can use `TSPlayground` to see how each language you use calls things.
> 
> Also note, `indent_blankline_context_patterns` are lua patterns, you can do stuff like `^if` and it will match both `if` and `if_statement`

I have '^if' on my config file and it still doesn't work with Ruby. Even if i remove it and put just 'if' it doesn't work. Why?

**Comment by lukas-reineke** [comment]
> I have '^if' on my config file and it still doesn't work with Ruby. Even if i remove it and put just 'if' it doesn't work. Why?

This works fine for me. It is just called `if` in ruby.
Can you make a minimal `init.vim` or `init.lua` that reproduces this?

**Comment by dzintars** [comment]
[hrsh7th/nvim-cmp](https://github.com/hrsh7th/nvim-cmp) is a great example, how core "engine" is separated from extensions. Mby that could be done there as well? Some community repo similar to https://github.com/DefinitelyTyped/DefinitelyTyped where people can add and support languages?

**Comment by lukas-reineke** [comment]
I decided to just add better defaults now.
If there are still cases that are not covered, please open PRs
