### ISSUE TITLE
Does not respect g:indent_blankline_filetype

### ISSUE THREAD

**Issue by sQVe** [lukas-reineke/indent-blankline.nvim#28]
Hey :wave:,

I want to use this plugin for specific filetypes but whenever I set `g:indent_blankline_filetype` it never shows indent guides on blank lines. I've replicated this on the `master` and `lua` branch.

**Comment by lukas-reineke** [comment]
There was a bug in the `lua` branch, I pushed a fix now.

`master` works fine for me, what filetype did you use?

**Comment by sQVe** [comment]
Ah, might have missed clearing `plugged` or something when switching branches. Just tried the `lua` branch and it does indeed work. 

Cheers for the quick fix :tada:. Closing.
