### ISSUE TITLE
How do I get connected dotted lines as my indent line?

### ISSUE THREAD

**Issue by adamstuck** [lukas-reineke/indent-blankline.nvim#282]
Do you have a longer version of the dotted line character?

> using both indent-blankline.nvim and indentLine on neovim 0.5

If you are on neovim 0.5, you should use the lua branch of indent-blankline.nvim and not use indentLine at all.
It is not needed anymore.

For your problem, if your terminal emulator has line spacing, the normal ascii vertical line doesn't connect.
You can either turn of line spacing in your terminal, or use a different character that is longer. I use this one `│`

_Originally posted by @lukas-reineke in https://github.com/lukas-reineke/indent-blankline.nvim/issues/97#issuecomment-824491778_

**Comment by bryant-the-coder** [comment]
Hi, same problem here. But I am using Command Prompt. How can I solve this problem?

My config
``` 
vim.opt.termguicolors = true
vim.cmd [[highlight IndentBlanklineIndent1 guifg=#E06C75 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent2 guifg=#E5C07B gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent3 guifg=#98C379 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent4 guifg=#56B6C2 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent5 guifg=#61AFEF gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent6 guifg=#C678DD gui=nocombine]]

vim.opt.list = true
vim.opt.listchars:append("space: ")
vim.opt.listchars:append("eol: ")

require("indent_blankline").setup {
    indentLine_enabled = 1,
    space_char_blankline = " ",
    char_highlight_list = {
        "IndentBlanklineIndent1",
        "IndentBlanklineIndent2",
        "IndentBlanklineIndent3",
        "IndentBlanklineIndent4",
        "IndentBlanklineIndent5",
        "IndentBlanklineIndent6",
    },
    filetype_exclude = {
         "help",
         "terminal",
         "dashboard",
         "packer",
         "lspinfo",
         "TelescopePrompt",
         "TelescopeResults",
      },
    buftype_exclude = {"terminal"},
    show_trailing_blankline_indent = false,

}
```

**Comment by lukas-reineke** [comment]
Same answer. patch/switch your font, or switch your terminal emulator.

**Comment by bryant-the-coder** [comment]
I am using nerdfont. Is that wrong? My theme is tokyonight

**Comment by lukas-reineke** [comment]
The theme, and all of Neovim, is not related to this.
This is just how your terminal displays your font. Specifically the [box drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character).
Some terminals, like Kitty, handle them differently so they always look good, regardless of what font you are using. But not all terminals do that.
If yours doesn't, you can either patch these characters in your font, use a different font, or use a terminal that does.
