### ISSUE TITLE
How to disable with dashboard-nvim?

### ISSUE THREAD

**Issue by ghost** [lukas-reineke/indent-blankline.nvim#284]
I'm using [dashboard-nvim](https://github.com/glepnir/dashboard-nvim) and I haven't been able to figure out how to disable blankline while using it. 

This is what what I have tried.

```lua
require("indent_blankline").setup {
  buftype_exclude = { "terminal", "[No Name]", "dashboard" },
....
}
```

Can anyone give me some pointers?

Thanks!

**Comment by agentzhao** [comment]
How do I find the name of the buftype for :LspInfo and the ui for nvim-lsp-installer?

**Comment by lukas-reineke** [comment]
You run `:set buftype` in the buffer. It will print what it is set to.
`LspInfo` is `nofile`

**Comment by Gaarco** [comment]
I'm trying to disable it for Packer but doesn't seem to work, this is my config:
```lua
require("indent_blankline").setup({
    indent_blankline_use_treesitter = true,
    indent_blankline_buftype_exclude = { "terminal", "prompt", "nofile", "help" },
    indent_blankline_filetype_exclude = { "packer", "lspinfo" },
    show_end_of_line = true,
    show_current_context = true,
    show_current_context_start = true,
    space_char_blankline = " ",
})
```
buftype of packer should be `nofile` and filetype should be `packer`, but I'm still seeing indentations and spaces.

**Comment by lukas-reineke** [comment]
> I'm still seeing spaces and new line character (but no indentations)

Those characters are not from indent-blankline.nvim. They are a buildin feature, see `:help 'listchars'` and `:help 'list'`
To turn them off, use `:set nolist`.
To change the setting only for some buffers, like packer, you should use an ftplugin. You can read how this works in `:help ftplugin`
