### ISSUE TITLE
Indentation stays when moving horizontally

### ISSUE THREAD

**Issue by ikerurda** [lukas-reineke/indent-blankline.nvim#285]
As you can see in the following video, the indentation stays even when scrolling horizontally

Also, is there a highlight group for the eof char?

https://user-images.githubusercontent.com/45340417/138881999-4a915d3e-1808-4401-ba33-381d0cc610a6.mov

**Comment by shaeinst** [comment]
@lukas-reineke
it was working fine but things got out of hand  now 😄.
`nvim --version`              
```NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```
config is very basic just `packer`, `plenary.nvim`, `nvim-web-devicons` and `indent-blankline.nvim`


https://user-images.githubusercontent.com/41078534/195004490-0994c2b7-9761-4edc-b662-1d4b0e7f307f.mp4

**Comment by lukas-reineke** [comment]
please create a new issue for this, with full config and steps to reproduce
