### ISSUE TITLE
Integration with IndentLine?

### ISSUE THREAD

**Issue by ZacharyRizer** [lukas-reineke/indent-blankline.nvim#29]
First off, thank you so much for finally fixing the incredibly annoying indent line issue on blank lines! Do you think there is any hope of combining these two plugins into one? It just seems slightly silly to have two separate plugins that essentially do one thing.

**Comment by lukas-reineke** [comment]
Before I made this plugin, I asked if there was interest to add this to IndentLine diretly, and never got a response https://github.com/Yggdroot/indentLine/issues/275

I rewrote the whole plugin in lua now, so I think it is very unlikely that the 2 will merge.

Nvim is working on extending virtual text to work everywhere. Once that is done, I hope this plugin will be able to completely replace IndentLine.

**Comment by ZacharyRizer** [comment]
Ah, that makes sense. Well here's to hoping that Neovim fully implements the virtual text in the way that you need!
