### ISSUE TITLE
filetype exclude question

### ISSUE THREAD

**Issue by rodhash** [lukas-reineke/indent-blankline.nvim#295]
Hi

I'm trying to find out what kind of floaterm popup cmp-nvim or perhaps lspsaga use so that I can add it to the exclude list (g:indent_blankline_filetype_exclude)

Here is a quick demo showing the popup / floaterm with the indentline char included in the beggining of the lines.

I can't find what filetype is that floaterm, any suggestion?

https://user-images.githubusercontent.com/29671981/140246487-c62e71b9-f2c5-4ae4-8588-353eedf1e68e.mp4

I suspect this might not be the right repo to ask this but I was wondering if someone faced something similar already while updating the exclude list.

Thanks

**Comment by lukas-reineke** [comment]
Sorry, I don't use lspsaga. I don't know.
You'll have to take a look at that repo.
