### ISSUE TITLE
New features requirement...

### ISSUE THREAD

**Issue by lee-shun** [lukas-reineke/indent-blankline.nvim#296]
Hi!

I am using this plug with neovim, I like it so much....

But, beyond the "scope-wise" indent line, could you make it possible to draw the line under the scope "beginning"?

as something below:
![image](https://user-images.githubusercontent.com/46647235/140249110-e527b3df-8278-4fd6-9333-0ad9686e7309.png)

**Comment by lukas-reineke** [comment]
I don't know of a way to do this.
The only thing I can think of is updating the syntax highlight of that line to support underline. But that is slow, super messy, and the underline would be the same color as the character. I don't want to go this route.
So for now at least, I won't add this.

**Comment by lee-shun** [comment]
Ok, thank you for your reply!

**Comment by elianiva** [comment]
It's possible to do it using extmark, but it will be limited to terminal that supports `guisp` for it to be in different colour, which, I don't think there's a lot of options out there.

<details>
<summary> diff </summary>

```diff
diff --git a/lua/indent_blankline/init.lua b/lua/indent_blankline/init.lua
index 7eed34d..567a9e9 100644
--- a/lua/indent_blankline/init.lua
+++ b/lua/indent_blankline/init.lua
@@ -503,6 +503,25 @@ local refresh = function(scroll)
                 )
                 vim.schedule_wrap(function()
                     utils.clear_line_indent(bufnr, i + offset)
+
+                    if context_start then
+                        local line = vim.api.nvim_buf_get_lines(bufnr, context_start - 1, context_start, false)[1]
+                        local _, line_offset = string.find(line, "^%s*")
+                        xpcall(
+                            vim.api.nvim_buf_set_extmark,
+                            utils.error_handler,
+                            bufnr,
+                            vim.g.indent_blankline_namespace,
+                            context_start - 1,
+                            line_offset,
+                            {
+                                end_col = #line,
+                                hl_group = "Asdf",
+                                priority = 10000,
+                            }
+                        )
+                    end
+
                     xpcall(
                         vim.api.nvim_buf_set_extmark,
                         utils.error_handler,
```

</details>

https://user-images.githubusercontent.com/51877647/140487422-b7dfd736-fab9-4416-8ef6-01f8ea4ea576.mp4

**Comment by lee-shun** [comment]
That's exactly what I waaaaaant! Thanks!

**Comment by lukas-reineke** [comment]
Thanks @elianiva I didn't know about `guisp`.
And using extmarks for the highlight makes a lot of sense.
I made a PR

**Comment by shaksiper** [comment]
I am getting underline under the blank line char as well. Is this an expected behavior?
![image](https://user-images.githubusercontent.com/79347616/140603390-dde06175-a4c8-41f1-8749-61e08f7a7e83.png)

**Comment by lukas-reineke** [comment]
@shaksiper no this should not happen. Can you open a new issue and share your config?

**Comment by nyngwang** [comment]
How to change the color of the underline?
