### ISSUE TITLE
Indent Char underline by context_start

### ISSUE THREAD

**Issue by shaksiper** [lukas-reineke/indent-blankline.nvim#305]
The problem:
![image](https://user-images.githubusercontent.com/79347616/140606369-41ef38b8-1703-4cf2-b438-8cf4428aedef.png)
With the recent context_start option, the line is underlined. But the indent char is also underlined with it.
Here is my config. I normally use this settings except without comments. I tried to provide minimal config that still gives this behaviour. 
```
-- vim.opt.list = true
-- vim.opt.listchars:append("trail:⋅")
-- vim.opt.listchars:append("tab:▸ ")
require("indent_blankline").setup {
    -- enabled = true,
    -- filetype_exclude = {'startify'},
    -- buftype_exclude = {"terminal", 'nofile'},
    -- use_treesitter = false,
    show_current_context = true,
    -- show_trailing_blankline_indent = true,
    -- char_list = { '│', '┊', '┆', '¦', '|', '⋅'},
    show_current_context_start = true,
    -- context_highlight_list = {
    --     "IndentBlanklineIndent1",
    --     "IndentBlanklineIndent2",
    --     "IndentBlanklineIndent3",
    --     "IndentBlanklineIndent4",
    --     "IndentBlanklineIndent5",
    --     "IndentBlanklineIndent6",
    -- },
    context_patterns = {
        "class",
        "function",
        "method",
        "table",
        'condition',
        'body',
        'import',
        "func_literal",
        "block",
        "try",
        "except",
        "argument_list",
        "object",
        "element",
    },
}
vim.cmd [[highlight IndentBlanklineIndent1 guifg=#56B6C2 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent2 guifg=#E5C07B gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent3 guifg=#98C379 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent4 guifg=#E06C75 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent5 guifg=#61AFEF gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent6 guifg=#C678DD gui=nocombine]]
```

**Comment by lukas-reineke** [comment]
I still cannot reproduce this.
What version of Neovim are you using?

**Comment by shaksiper** [comment]
I'm on 0.6
NVIM v0.6.0-dev+516-g4a618b00b
Build type: Debug
LuaJIT 2.1.0-beta3

**Comment by shaksiper** [comment]
This is probably about the colorscheme that I am using, which is rose-pine.
I didn't think that might be the case because changing highlighting didn't do anything but now that I switch to tokyonight it seems to go away. 
So I think i should open an issue with the color scheme maintainer to adapt to this change.

**Comment by lukas-reineke** [comment]
I'm on 0.6 as well, that shouldn't be the problem.
Is this the color scheme you are using https://github.com/iandwelker/rose-pine-vim ?
I installed it, but it still doesn't happen for me.

It's probably an easy fix. [I made a branch](https://github.com/lukas-reineke/indent-blankline.nvim/tree/bugfix/move-context-start-extmark-after-indent), can you check if that fixes it?
I would still like to understand why it happens.

**Comment by shaksiper** [comment]
That branch indeed fixed it. But it is bizarre that it happens.
What might be the cause that it happens with me?

**Comment by lukas-reineke** [comment]
I really don't know why it happens.
But I released the fix now. It is more "correct" anyways. I was just lazy because I thought it doesn't make a difference.
