### ISSUE TITLE
show_current_context_start removes italics on affected line

### ISSUE THREAD

**Issue by timtyrrell** [lukas-reineke/indent-blankline.nvim#306]
I noticed the `show_current_context_start` setting will make italic text "normal". Screenshot below shows the affected line with the line below as how it looks when not underlined.

<img width="196" alt="Screen Shot 2021-11-06 at 1 31 54 PM" src="https://user-images.githubusercontent.com/100535/140621761-d0ef3231-5b3b-45a2-8993-77b7ed3bc969.png">

I am using the latest Kitty terminal. I was able to reproduce it inside and outside of tmux. Not sure if this is helpful information, but I noticed when I trigger the spellchecker, which adds undercurls to my buffer, it _does not_ remove the italic, which I would expect this feature to not do, as well.

`~/.config/nvim/mini.vim` below
```
set nocompatible
filetype plugin indent on
syntax on
set hidden

let mapleader = ','

call plug#begin('~/.config/nvim/plugged')

Plug 'lukas-reineke/indent-blankline.nvim'
Plug 'folke/tokyonight.nvim'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

call plug#end()

let g:tokyonight_style = "night"
let g:tokyonight_italic_functions = 1
let g:tokyonight_italic_variables = 0
colorscheme tokyonight

set colorcolumn=99999
if &diff
    let g:indent_blankline_enabled = v:false
endif
let g:indent_blankline_use_treesitter = v:true
set list listchars=tab:→\ ,space:⋅,trail:•,nbsp:␣,extends:▶,precedes:◀
let g:indent_blankline_char = '▏'
let g:indent_blankline_show_first_indent_level = v:true
let g:indent_blankline_show_trailing_blankline_indent = v:false
let g:indent_blankline_show_current_context = v:true
let g:indent_blankline_show_current_context_start = v:true
let g:indent_blankline_context_patterns = [ 'declaration', 'expression', 'pattern', 'primary_expression', 'statement', 'switch_body' ,'def', 'class', 'return', 'function', 'method', '^if', '^while', 'jsx_element', '^for', '^object', '^table', 'block', 'arguments', 'else_clause', '^jsx', 'try_statement', 'catch_clause', 'import_statement', 'operation_type' ]

lua << EOF

require('nvim-treesitter.configs').setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
  },
  indent = {
    enable = true
  },
}

EOF
```

**Comment by lukas-reineke** [comment]
Can you try updating the plugin? I fixed this in https://github.com/lukas-reineke/indent-blankline.nvim/releases/tag/v2.10.1

**Comment by timtyrrell** [comment]
Thanks for taking a look so quickly. I tried with the `v2.10.1` tag and also latest which is `9dab64554c6249eb31a0bf3e689e0d36d6998fb8` and I still am able to reproduce with the `~/.config/nvim/mini.vim` provided.

**Comment by lukas-reineke** [comment]
I missed one with the last fix..
should be good now

**Comment by timtyrrell** [comment]
You got it, fixed!
