### ISSUE TITLE
Does not work with lazy-loaded with vim-plug

### ISSUE THREAD

**Issue by danielfalbo** [lukas-reineke/indent-blankline.nvim#31]
I have
```vim
Plug 'Yggdroot/indentLine', {
            \ 'for': ['html', 'css'] }                  " Indent guides
Plug 'lukas-reineke/indent-blankline.nvim', {
            \ 'for': ['html', 'css'] }                  " Indent guides on empty lines
```
in my `init.vim`.
When I start editing an HTML file, `indentLine` is loaded correctly and works as expected while `indent-blankline` is loaded (in fact all the commands are available) but I can't see the indent guides in the blank lines.
Running `:IndentBlanklineDisableAll` and `:IndentBlanklineEnableAll` or `:IndentBlanklineRefresh` does not solve the problem.
If I disable the lazy-loading, `indent-blankline` works fine.

Great plugin btw : )

**Comment by lukas-reineke** [comment]
The way Plug lazy loads is not compatible with this plugin.

Please either use `g:indent_blankline_filetype = ['html', 'css']` or use the new `lua` branch.
The `lua` branch should work with Plug, but needs nvim 0.5

**Comment by danielfalbo** [comment]
Thank you much! Do you plan on moving the lua implementation to the default branch?

**Comment by lukas-reineke** [comment]
> Thank you much! Do you plan on moving the lua implementation to the default branch?

yes, once nvim 0.5 is officially released
