### ISSUE TITLE
`show_current_context_start` begins in the middle of the word in Lua files

### ISSUE THREAD

**Issue by Gelio** [lukas-reineke/indent-blankline.nvim#310]
For me, the `show_current_context_start` underline highlight starts shifted a few characters into the word in Lua files:
![image](https://user-images.githubusercontent.com/889383/140643266-47e123ea-c2e1-44cd-adb7-0ce485d726c4.png)
![image](https://user-images.githubusercontent.com/889383/140643272-c096f0c0-68b6-4cd8-b98d-55e021b64180.png)

`shiftwidth` is correctly set to `2`

This only happens in Lua files, as far as I can tell. TypeScript and JSON are fine:
![image](https://user-images.githubusercontent.com/889383/140643287-406668cd-6fa2-4254-a7d4-e325116a9223.png)

**Comment by lukas-reineke** [comment]
Thanks for the issue. Should be fixed now

**Comment by Gelio** [comment]
Thanks for a quick fix, both this and https://github.com/lukas-reineke/indent-blankline.nvim/issues/311 are fixed now :rocket:
