### ISSUE TITLE
Failed to switch to window

### ISSUE THREAD

**Issue by henriquehbr** [lukas-reineke/indent-blankline.nvim#316]
I'm currently working on the [`ataraxis.lua`](https://github.com/henriquehbr/ataraxis.lua) plugin, which is basically a distraction-free mode, the way it works, is by creating 2 buffers on each side of the editor

Whenever i try to use `indent-blankline.nvim` with it, i receive the following error message:

```
Error detected while processing /home/hbr/.local/share/nvim/site/pack/paqs/start/indent-blankline.nvim/plugin/i
ndent_blankline.vim:
line   31:
E5108: Error executing lua .../indent-blankline.nvim/lua/indent_blankline/commands.lua:8: Failed to switch to w
indow 1002
```

I'm not sure if it's something related to the order that these plugins must be loaded, but i had no luck trying to figure it out, any clue of what might be happening?

> Thme same issue also happened with [`stabilize.nvim`](https://github.com/luukvbaal/stabilize.nvim) on luukvbaal/stabilize.nvim#5, the fix for that one was basically adding `BufEnter` to `eventignore`

**Comment by lukas-reineke** [comment]
On `VimEnter` indent-blankline runs refresh on all windows. So when you open Neovim, all open windows have indent lines.
It also saves the current window you are in, and returns you there after it's done. But by that error it looks like at that point the window doesn't exist anymore.

It's probably not a good idea to ignore `VimEnter`. Not sure how to fix it without knowing what your plugin is doing.

**Comment by luukvbaal** [comment]
I'm doing something similar, as in looping over the currently open windows. I'm thinking it might make sense to first
* check `vim.api.nvim_win_is_valid()`
* check if the target window buffer name is empty, i.e. `vim.api.nvim_buf_get_name(vim.api.nvim_win_get_buf(<win>)) == ""`


If either of those is true I think for both your and mine plugin you wont have to handle it. Should avoid problems with these distraction free plugins, got another report today https://github.com/luukvbaal/stabilize.nvim/issues/7.

**Comment by luukvbaal** [comment]
But otherwise I think it would indeed be good practice to indeed add `WinEnter,Bufenter` to `eventignore` during such a loop, unless you rely on those yourself.

**Comment by lukas-reineke** [comment]
Both of this makes sense :+1:
