### ISSUE TITLE
Indent lines change color when using `:PackerCompile`

### ISSUE THREAD

**Issue by JeanMertz** [lukas-reineke/indent-blankline.nvim#317]
It's hard to know _why_ this happens, but when I'm configuring my `plugins.lua` configuration file, and run `:PackerCompile` (or `:PackerSync`, which also does the compilation step), the indentation lines all change to a white colour, and remain that way until I restart Nvim.

The white indentation lines also show up if I switch to a different file afterwards.

I haven't seen it happen in any other cases.

**Comment by lukas-reineke** [comment]
`PackerCompile` probably reloads your color scheme, which clears all highlight groups.
You can do something like this to reset the colors again.

```vim
autocmd User PackerComplete,PackerCompileDone lua require("indent_blankline.utils").reset_highlights()
```

This should normally happen on `ColorScheme` anyway. But packer does some magic I don't fully understand.

**Comment by JeanMertz** [comment]
Thanks @lukas-reineke, that works brilliantly.
