### ISSUE TITLE
Unable to configure indent-blankline

### ISSUE THREAD

**Issue by hsheikhali1** [lukas-reineke/indent-blankline.nvim#319]
Recently re-did my config and updated to Neovim 0.6 and I noticed that now I can't require the plugin to configure it :/ but it was installed and the default settings work?
<img width="1324" alt="Screen Shot 2021-11-11 at 10 18 01 PM" src="https://user-images.githubusercontent.com/14851850/141403302-18126592-818f-4e82-8b58-3c8a62f31492.png">

<img width="1321" alt="Screen Shot 2021-11-11 at 10 17 33 PM" src="https://user-images.githubusercontent.com/14851850/141403311-f9fb4a04-6394-46b7-9813-446f04867566.png">

**Comment by lukas-reineke** [comment]
From the error message, it looks like you are trying to require `indent-blankline` with a `-`. It should be `indent_blankline` with a `_`.

The first screenshot looks correct, maybe you just need to re-compile packer?

**Comment by Rem0ld** [comment]
I can't get to configure indent_blankline but I don't understand why, I get this error:
(It's mixed with treesitter but I also tried in init.vim or in a .lua file but I still get this error)

> 
> Erreur détectée en traitant /Users/pielov/.config/nvim/after/plugin/treesitter.rc.vim :
> ligne   46 :
> E5108: Error executing lua ...Cellar/neovim/0.5.0/share/nvim/runtime/lua/vim/_meta.lua:170: E474: Inv
> alid argument
> 
> 

``` vim
lua <<EOF

vim.opt.list = true
vim.opt.listchars:append("space:⋅")
vim.opt.listchars:append("eol:↴")

require("indent_blankline").setup {
show_end_of_line = true,
space_char_blankline = " ",
}

require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {},
  },
  indent = {
    enable = false,
    disable = {},
  },
  ensure_installed = {
    "tsx",
    "toml",
    "fish",
    "php",
    "json",
    "yaml",
    "swift",
    "html",
    "scss"
  },
  rainbow = {
    enable =true,
    extended_mode = true,
    max_file_lines = nil
    }
}

local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.tsx.used_by = { "javascript", "typescript.tsx" }
EOF

```

**Comment by lukas-reineke** [comment]
@Rem0ld try updating Neovim.
If this doesn't help, please make a new Issue and remove anything that is unrelated from your config

**Comment by lukas-reineke** [comment]
closing because this is old
please open a new issue when you still have problems
