### ISSUE TITLE
very goode👍

### ISSUE THREAD

**Issue by heguohui2018** [lukas-reineke/indent-blankline.nvim#32]
How to set it to make the character list display more, the middle part feels weird,

<img width="1220" alt="Screen Shot 2020-12-18 at 2 29 26 PM" src="https://user-images.githubusercontent.com/35359288/102582450-95fb0a80-413d-11eb-8671-43098e07f518.png">

<img width="1010" alt="Screen Shot 2020-12-18 at 2 28 48 PM" src="https://user-images.githubusercontent.com/35359288/102582457-9a272800-413d-11eb-85f0-5cb3c637c301.png">

**Comment by lukas-reineke** [comment]
you need to install https://github.com/Yggdroot/indentLine as well
