### ISSUE TITLE
Indent line blending issue

### ISSUE THREAD

**Issue by Iamafnan** [lukas-reineke/indent-blankline.nvim#322]
My indentline config file looks like this after installation 
![IMG_20211119_212859](https://user-images.githubusercontent.com/80388154/142663379-18991653-991f-438e-add2-46d9c96d26d0.jpg)

Any solution??

**Comment by lukas-reineke** [comment]
It looks like `:set shiftwidth` set wrong.
Can you check what it is set to? It should match the number of spaces you use to indent.

**Comment by Iamafnan** [comment]
I have set that to 8

**Comment by lukas-reineke** [comment]
And the code is indented with 4 spaces.
Set it to 4 and it should be fixed

**Comment by Iamafnan** [comment]
Thanks
