### ISSUE TITLE
Setting IndentBlanklineContextChar highlights

### ISSUE THREAD

**Issue by axieax** [lukas-reineke/indent-blankline.nvim#323]
Hello, I'm struggling to override the default highlight colour for show_current_context. As can be seen in my config, I am setting the appropriate highlight group. However, the colours do not appear unless I explicitly run the command again manually (:highlight IndentBlanklineContextChar guifg=#C678DD gui=nocombine) once nvim loads. Not sure if this is due to Packer being annoying, or if reset_highlights isn't working properly.
My configuration can be found [here](https://github.com/axieax/dotconfig/blob/9fb59089298ff4e8c119b8597b9809d26f5dd263/nvim/lua/plugins/indentline.lua#L1)
Thanks!

VimEnter:
![image](https://user-images.githubusercontent.com/62098008/142665554-7a0aa62c-f83a-4338-860e-4ab8986a54e8.png)

Manual highlight (expected behaviour):
![image](https://user-images.githubusercontent.com/62098008/142665640-aff6268d-eaac-4bde-8e10-15434275125b.png)

**Comment by lukas-reineke** [comment]
Most color schemes reset all highlight groups when they load.
Can you try to set the highlight group after you load your color scheme?

**Comment by axieax** [comment]
Unfortunately I've tried that already but it still doesn't work :(

**Comment by lukas-reineke** [comment]
It gets overwritten somewhere, that's the only explanation.
You can check where it was last set with `:verbose highlight IndentBlanklineContextChar`

**Comment by axieax** [comment]
I've tried manually setting it after applying any colorschemes, as well as at the end of my nvim config, yet it still does not seem to work. The verbose command also says `Last set from anonymous :source`, which may or may not be Packer.

**Comment by lukas-reineke** [comment]
You could try to run an autocommand after the color scheme is set with `autocmd ColorScheme *`

But sorry, I can't really help you with this, you need to debug your config.
This is not a bug of the plugin.

**Comment by axieax** [comment]
Thanks for the help! Unfortunately, the autocmd didn't work, but it turns out that my material.nvim theme overrode its highlights.
