### ISSUE TITLE
Turn off current context start for current line

### ISSUE THREAD

**Issue by pjcj** [lukas-reineke/indent-blankline.nvim#325]
I like the current context work - thanks!

One part I find a little off is highlighting the current context start when the cursor is on that line.  I wonder whether it would be possible to (optionally?) disable the current context start highighting when the cursor is on that line?

**Comment by lukas-reineke** [comment]
I made a PR to implement this.
I'll leave it as a PR for now, I want to see if I can come up with a better name.
`g:indent_blankline_disable_current_context_start_on_current_line` is a bit much.

**Comment by pjcj** [comment]
Thank you!

You're right, the variable is a bit of a mouthful.  I'm not sure whether I have any better suggestions.

One option might be to make `g:indent_blankline_show_current_context_start` into a string "enum" type: `always`, `never` & `not_current_line` or something.  It could even be combined with `g:indent_blankline_show_current_context`.  But this is quite a change from the current API.  There's a certain simplicity about using booleans but some of that is lost if the variable only has meaning based on the value of another variable.

The other small change which comes to mind is to use `g:indent_blankline_show_current_context_start_on_current_line` which is slightly shorter, matches the main variable and keeps the boolean in the positive sense which often aids in understanding.  But it's not much of an improvement, and it would need the default value to be true, so it's a tradeoff.

**Comment by lukas-reineke** [comment]
Enum would be nice, but I don't want to break backwards compatibility. And supporting both enum and boolean makes it more complex.

> keeps the boolean in the positive sense

that's a really good point :+1:
