### ISSUE TITLE
Possible to implement colorcolumn using same technique

### ISSUE THREAD

**Issue by francium** [lukas-reineke/indent-blankline.nvim#327]
![image](https://user-images.githubusercontent.com/15352422/143489378-381b6ab1-4134-48ee-887b-5eb5b4eaeaec.png)
I use this in my vim config to add vertical columns, but they're blocky.

I'm asking this without in depth knowledge of vim plugin or the vim API; perhaps you may be able to suggest if this is possible or not:

Is it possible to use the techniques from this plugin to implement something like `colorcolumn` but with much nicer thin lines?

Similar to
![image](https://user-images.githubusercontent.com/15352422/143489714-0a713ad5-bf21-4fae-ac8f-2a4c38ea23d0.png)

**Comment by lukas-reineke** [comment]
yeah should be possible

sounds interesting, I'll see if I can build something.

**Comment by lukas-reineke** [comment]
I made it https://github.com/lukas-reineke/virt-column.nvim

**Comment by francium** [comment]
![image](https://user-images.githubusercontent.com/15352422/143612443-d677941c-e5af-45d2-b049-51a78e1a1fba.png)

Really amazing and works really well. Thank you.
