### ISSUE TITLE
Visual block selection doesn't begin at start of line

### ISSUE THREAD

**Issue by GBeauregard** [lukas-reineke/indent-blankline.nvim#328]
I get a problem similar to https://github.com/lukas-reineke/indent-blankline.nvim/issues/41 but it seems to be specific to certain color schemes. I can't see anything in working color schemes that are making it work so I was hoping you could provide insight on if this is a bug (in blankline or the color scheme) or if color schemes need to implement something special to get this working right and what that special something is so I can customize it.

f.ex. the following vimrc doesn't work in neovim 0.5.1 and kitty 0.23.1 (displays behavior similar to the above bug where visual block selections don't show where the indent is located):
```vim
call plug#begin()
Plug 'lukas-reineke/indent-blankline.nvim'
Plug 'overcache/NeoSolarized'
call plug#end()
set termguicolors
syntax enable
set background=dark
colorscheme NeoSolarized
```

**Comment by lukas-reineke** [comment]
`NeoSolarized` sets the `Visual` highlight group to `gui=reverse`
Virtualtext does not support that yet, I think.

You can change it to normal colors.
For example `:highlight Visual guibg=#839496 gui=None guifg=#002b36`

**Comment by GBeauregard** [comment]
Thanks, that works!

I couldn't find anything that looked like a relevant bug in neovim; do we need to file one?

**Comment by lukas-reineke** [comment]
I was wrong, virtual text does support this.
But the plugin turns mixing of gui attributes off on purpose. This is so the indent guides don't inherent things like underline or italic.

You could overwrite the highlight groups to remove this, but it will then not look good with the above cases.

```vim
highlight IndentBlanklineChar gui=None
highlight IndentBlanklineSpaceChar gui=None
highlight IndentBlanklineSpaceCharBlankline gui=None
highlight IndentBlanklineContextChar gui=None
```

**Comment by GBeauregard** [comment]
Thanks for the workarounds; I appreciate it. If there's not a way for you to only allow mixing certain attributes commonly used for theming, does it make sense to request this from neovim?

**Comment by lukas-reineke** [comment]
> does it make sense to request this from neovim?

Doesn't hurt to ask.
Probably the best way to support this would be to add negative gui options. Like `noitalic`
So a highlight group can set this, all gui options get combined, but `noitalic` overwrites if the underlying highlight group had `italic`
