### ISSUE TITLE
Question: What colorscheme are you using in the demo pictures? 

### ISSUE THREAD

**Issue by ndavidpsi** [lukas-reineke/indent-blankline.nvim#33]

**Comment by lukas-reineke** [comment]
my own https://github.com/lukas-reineke/onedark.nvim/blob/master/lua/onedark.lua

It's basically one-dark, but with darker background colors

**Comment by ndavidpsi** [comment]
thanks!
I really prefer colorschemes with really dark bg colors. I am currently using code-dark with black background
