### ISSUE TITLE
context and indent issues

### ISSUE THREAD

**Issue by y1rn** [lukas-reineke/indent-blankline.nvim#330]
1.can not highlight current context.

![image](https://user-images.githubusercontent.com/70128797/144974529-4211d067-28c5-48ce-950c-0e24b4741ece.png)

context config: 
```
  context_patterns = {
    "class", "function", "method", "block", "list_literal", "selector",
    "^if", "^table", "if_statement", "while", "for",  "type", "var",
    "import", "declaration", "expression", "pattern", "primary_expression",
    "statement", "switch_body"
  },
```

2.empty line indent issue:

![image](https://user-images.githubusercontent.com/70128797/144974927-5f2709c8-f448-4899-8341-b5da00039b3d.png)

**Comment by lukas-reineke** [comment]
> 1.can not highlight current context.

I think you want to add `body` to `context_patterns`. You can see what kind of type the node has with https://github.com/nvim-treesitter/playground

> 2.empty line indent issue

I assume you are using `let g:indent_blankline_use_treesitter=v:true`? Treesitter calculates the indent like this. You can open an issue about this here https://github.com/tree-sitter/tree-sitter-go or not use treesitter for the indent (I actually recommend this)

**Comment by y1rn** [comment]
> > 1.can not highlight current context.
> 
> I think you want to add `body` to `context_patterns`. You can see what kind of type the node has with https://github.com/nvim-treesitter/playground
> 
> > 2.empty line indent issue
> 
> I assume you are using `let g:indent_blankline_use_treesitter=v:true`? Treesitter calculates the indent like this. You can open an issue about this here https://github.com/tree-sitter/tree-sitter-go or not use treesitter for the indent (I actually recommend this)

thx,  it work with ```literal_value```
