### ISSUE TITLE
Feature request: only enable this plugin on some specific filetypes

### ISSUE THREAD

**Issue by PascalZh** [lukas-reineke/indent-blankline.nvim#335]
![image](https://user-images.githubusercontent.com/32212800/145706023-10fabc3b-94d3-4f68-ad44-31224b7cf1f0.png)

It's enabled even in the help window.

**Comment by lukas-reineke** [comment]
You can already do this with `:help g:indent_blankline_filetype` and `:help g:indent_blankline_filetype_exclude`

**Comment by PascalZh** [comment]
> You can already do this with `:help g:indent_blankline_filetype` and `:help g:indent_blankline_filetype_exclude`

Thank you, but should there be some default settings?

**Comment by lukas-reineke** [comment]
It might have been better to have `help` as a default value. But this would be a breaking change now that I don't want to do.
