### ISSUE TITLE
Indent guides don't show up

### ISSUE THREAD

**Issue by LoadingBG** [lukas-reineke/indent-blankline.nvim#338]
Indentation guides don't show up at all:
![image](https://user-images.githubusercontent.com/51295058/147154082-39edec49-b545-4c20-97ee-c67cfe08959d.png)
It seems like the commands don't do anything - `:IndentBlanklineDisable` + `:IndentBlanklineEnable` doesn't work, nor does `:IndentBlanklineRefresh`

---
Here's my config (using packer.nvim):
```lua
use {
   "lukas-reineke/indent-blankline.nvim",
   --requires = "nvim-treesitter",
   --after = { "theme", "nvim-treesitter" },
   --after = "theme",
   --after = "nvim-treesitter",
   config = function()
      require("indent_blankline").setup {
         use_treesitter = true,
         show_current_context = true,
         context_patterns = {
            "class", "function", "method", "block", "list_literal", "selector",
            "^if", "^table", "if_statement", "while", "for",
         },
         filetype_exclude = { "help", "terminal", "packer", "NvimTree" },
         buftype_exclude = { "terminal" },
      }
   end
}
```
The comments are what I've tried to do to get the plugin working (`theme` is https://github.com/monsonjeremy/onedark.nvim)

---
Neovim version:
```
NVIM-QT v0.2.17.9999
Build type: Release
Compilation: -Wall -Wextra -Wno-unused-parameter -Wunused-variable -std=c++11
Qt Version: 5.15.2

NVIM v0.6.0-dev+600-gf71be1f87
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Features: -acl +iconv +tui
```
OS: Windows 10 Pro Version 20H2 Build 19042.1415

**Comment by lukas-reineke** [comment]
Your config looks fine. Are you getting any errors?

Also, can you check the output of `:highlight IndentBlanklineChar`

**Comment by LoadingBG** [comment]
![image](https://user-images.githubusercontent.com/51295058/147215124-ff57887b-eafe-44fe-ab62-af5ab56ea28b.png)
Looks right to me, also there are no errors.

**Comment by LoadingBG** [comment]
I updated neovim to the stable version so now it's
```
NVIM-QT v0.2.16.1
Build type: Release
Compilation: -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
Qt Version: 5.11.3

NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Features: -acl +iconv +tue
```
Still no indentation guides

**Comment by lukas-reineke** [comment]
Can you check the output of `:lua print(vim.inspect(vim.api.nvim_buf_get_extmarks(0, vim.g.indent_blankline_namespace, 0, -1, {})))`

**Comment by LoadingBG** [comment]
It's `{}`

**Comment by lukas-reineke** [comment]
What is the output of `:lua print(vim.b.__indent_blankline_active)`?

**Comment by LoadingBG** [comment]
`true`

**Comment by lukas-reineke** [comment]
Everything looks correct. Sorry I don't have any other ideas. Something in your setup is causing a problem.
If you can make a minimal init.lua that reproduces this, I can debug further.

**Comment by LoadingBG** [comment]
Seems to be working with just this plugin enabled, I'll try to pinpoint the issue. Thanks.
