### ISSUE TITLE
how to hide indentline in telescope preview window?

### ISSUE THREAD

**Issue by siduck** [lukas-reineke/indent-blankline.nvim#339]
i have telescopeResults and telescopePrompt excluded in my config already, indentline by default doesnt show on the preview window BUT it does start showing them when i cycle backwards in telescope i.e (Ctr + p) brings the indentline :c

 
https://user-images.githubusercontent.com/59060246/147361411-7231bba0-1a0f-4b70-93e6-4068947b6041.mp4

**Comment by lukas-reineke** [comment]
I can't reproduce this with the default telescope config.
Can you share yours?

**Comment by siduck** [comment]
https://paste.sh/jFLOSIZq#b16vmqEEVN9MaLZ3gftWJgFO 

I use telescope-fzf-native.nvim for sorter

**Comment by lukas-reineke** [comment]
Looks like telescope doesn't set any filetype for the  preview window.
You can add `""` to the excluded filetypes, and it should be gone.

**Comment by siduck** [comment]
> Looks like telescope doesn't set any filetype for the preview window. You can add `""` to the excluded filetypes, and it should be gone.

thanks a lot!
