### ISSUE TITLE
indent-blankline doesn't seem to have any effect on empty lines

### ISSUE THREAD

**Issue by ndavidpsi** [lukas-reineke/indent-blankline.nvim#34]
The main reason I wanted to use indent-blankline was to fill empty lines but it isn't doing that. I'm using indent-Blankline with indentLine as well. Did I configure something wrong or?

**Comment by ndavidpsi** [comment]
![IMG_20201223_192442](https://user-images.githubusercontent.com/73792104/103031544-f16e3380-4555-11eb-9b6d-afd666dd330c.jpg)

**Comment by ndavidpsi** [comment]
I probably configured something wrong. Can I see the code for obtaining the **With custom `listchars` and `g:indent_blankline_space_char`** screenshot example in the `readme`

**Comment by lukas-reineke** [comment]
yeah looks like something is not working.
Can you set `let g:indent_blankline_debug = v:true` and see if you get any errors?

**Comment by ndavidpsi** [comment]
I don't seem to get any errors. Here is a screenshot of my config:
![1](https://user-images.githubusercontent.com/73792104/103086766-55880a80-45dd-11eb-8ddd-9b66955597c9.PNG)

**Comment by ndavidpsi** [comment]
I'll explain some lines. 
Line 10 is from this issue https://github.com/Yggdroot/indentLine/issues/315
Lines 2 and 1 is a map I did for completely toggle indent lines, I also use  `LeadingSpaceToggle` because if I don't all spaces appear with the `g:indentLine_leadingSpaceChar` symbol and only works normally after toggling at least once (I don't know if it is a bug or not but it doesn't seem like it, `LeadingSpaceToggle` solves it for me)

**Comment by lukas-reineke** [comment]
Okay, can you give me a bit more information? What's the output of these:

`:echo g:indent_blankline_namespace`
`:echo jobpid(g:indent_blankline_nvim_instance)`
`:echon rpcrequest(g:indent_blankline_nvim_instance, 'nvim_eval', '"hello"')`

**Comment by ndavidpsi** [comment]
weird...

- `:echo g:indent_blankline_namespace` outputs:
**E121: Undefined variable: g:indent_blankline_namespace**
- `:echo jobpid(g:indent_blankline_nvim_instance)` outputs:
**E121: Undefined variable: g:indent_blankline_nvim_instance**
**E116: Invalid arguments for function jobpid**
- `:echon rpcrequest(g:indent_blankline_nvim_instance, 'nvim_eval', '"hello"')` outputs:
**E121: Undefined variable: g:indent_blankline_nvim_instance**
**E116: Invalid arguments for function rpcrequest**

**Comment by lukas-reineke** [comment]
Okay, so the plugin is never even initialized.
Can you run `:IndentBlanklineRefresh` manually and see what happens? Then try the above again

**Comment by ndavidpsi** [comment]
Same output...

**Comment by lukas-reineke** [comment]
What is the output of `echo indent_blankline#BufferEnabled()`

**Comment by ndavidpsi** [comment]
v:true

**Comment by lukas-reineke** [comment]
What is the output of `echo len(nvim_list_uis())` and `echo g:indent_blankline_enabled`?

**Comment by ndavidpsi** [comment]
`echo len(nvim_list_uis())` outputs **1**
`echo g:indent_blankline_enabled` outputs **0**

**Comment by lukas-reineke** [comment]
> echo g:indent_blankline_enabled outputs 0

that would be why then
I didn't see that in your config, `g:indentLine_enabled` will set this too.
0 means false. So the plugin is turned off. Try setting `let g:indentLine_enabled=1` in your config

**Comment by ndavidpsi** [comment]
The thing is I want it disabled by default and then toggle it when I want to. Is it possible?

**Comment by lukas-reineke** [comment]
you can disable it by default as well.
`let g:indentLine_enabled=0` disables it globally, and there is no way to toggle it on or off globally.
But you could disable it per buffer, and then turn it on/off per buffer.

this should be all you need

```vim
augroup AutogroupDisableIndentline
    autocmd!
    autocmd Syntax * IndentBlanklineDisable
augroup END
```

**Comment by ndavidpsi** [comment]
So now my config looks like this:
```
" --- For indentLine and indentBlankLine --------------------------------"
autocmd VimEnter * if bufname('%') == '' | IndentLinesDisable | endif
let g:indentLine_enabled = 1
let g:indentLine_char = '¦'
let g:indentLine_leadingSpaceEnabled = 1
let g:indentLine_leadingSpaceChar = '·'
let g:indentLine_showFirstIndentLevel = 1
let g:indentLine_color_gui = '#444444'
let g:indentLine_bgcolor_gui = 'NONE'
let g:indent_blankline_debug = v:true
nnoremap <silent><leader>i :LeadingSpaceToggle<CR>
      \:IndentBlanklineToggleAll<CR>
```

But the issue of not filling the lines persists and I got an error when I source my `init.vim`:
**indent-blankline encountered an error...92: Not an editor command: viminit.vim**

**Comment by lukas-reineke** [comment]
can you show me your whole config?

**Comment by ndavidpsi** [comment]
Here is what I get now when I do the commands you asked me before...

- `:echo g:indent_blankline_namespace` outputs: **3**
- `:echo jobpid(g:indent_blankline_nvim_instance)` outputs:
**E900: Invalid channel id**
**0**
- `:echon rpcrequest(g:indent_blankline_nvim_instance, 'nvim_eval', '"hello"')` outputs:
**Error invoking 'nvim_eval' on channel 33:**
**Invalid channel: 330**
- `:echo len(nvim_list_uis())` outputs: **1**
- `:echo g:indent_blankline_enabled` outputs: **1**

**Comment by ndavidpsi** [comment]
> 
> 
> can you show me your whole config?

the whole init.vim?

**Comment by lukas-reineke** [comment]
> the whole init.vim?

yes
the `Vim:E492: Not an editor command: viminit.vim` error is very likely due to some configuration

**Comment by ndavidpsi** [comment]
Alright, here it is https://github.com/sp1n0r/configs/blob/main/init.vim

**Comment by lukas-reineke** [comment]
hm yeah I don't see anything either.
Maybe the abbreviations, but they shouldn't.
```vim
cabbrev init e ~/AppData/Local/nvim/init.vim
cabbrev ginit e ~/AppData/Local/nvim/ginit.vim
```

But I see you are using treesitter? So you are on nvim 0.5?
If so, you can use the `lua` branch of this plugins instead. It's a lot more stable.

**Comment by ndavidpsi** [comment]
> 
> 
> hm yeah I don't see anything either.
> Maybe the abbreviations, but they shouldn't.
> 
> ```viml
> cabbrev init e ~/AppData/Local/nvim/init.vim
> cabbrev ginit e ~/AppData/Local/nvim/ginit.vim
> ```

Yeah this shouldn't cause any issue.
> 
> But I see you are using treesitter? So you are on nvim 0.5?
> If so, you can use the `lua` branch of this plugins instead. It's a lot more stable.

Yup, got one of the latest nvim nightly versions. How to I get that 'lua' branch? I thought I was using that.

**Comment by ndavidpsi** [comment]
Do I have to change my `init.vim` to `init.lua`?

**Comment by lukas-reineke** [comment]
> Do I have to change my `init.vim` to `init.lua`?

no, just change the plug call to this `Plug 'lukas-reineke/indent-blankline.nvim', { 'branch': 'lua' }`

**Comment by ndavidpsi** [comment]
Cool. Not on my pc anymore. I'll let you know the result in an hour or so

**Comment by ndavidpsi** [comment]
I think it is working fine now. There is only a problem that I'd like to fix in indent-blankline.nvim in order to leave the indentLine plugin altogether.

![1](https://user-images.githubusercontent.com/73792104/103095104-53cb4080-45f7-11eb-9966-8730af33fec6.PNG)

**Comment by ndavidpsi** [comment]
Other thing. I changed my config in order to use standalone indent-blankline.nvim but it doesn't seem to be working in my init.vim.
![1](https://user-images.githubusercontent.com/73792104/103096028-79a61480-45fa-11eb-8c06-2948826f1eec.PNG)
But it works in help files. That got me thinking. I use these settings in my init.vim, could it be related?
```
set tabstop=2 softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
```

**Comment by ndavidpsi** [comment]
I should probably close the issue though. The original problem seems to be solved

**Comment by lukas-reineke** [comment]
>  in order to leave the indentLine plugin altogether

this plugin only fills in empty lines, you need both. At least until neovim supports better virtual text

#12 is currently not possible. I hoped the bugfix will allow conceal on line endings, but it doesn't.

**Comment by ndavidpsi** [comment]
Oh that's unfortunate. I'll continue to use both then, and I'll probably disable the first level. Nonetheless I think it's a great plugin and has a lot of potential since it is compatible with lua
