### ISSUE TITLE
How to disable indent-blankline in Nvim tree

### ISSUE THREAD

**Issue by hsheikhali1** [lukas-reineke/indent-blankline.nvim#340]
How do I disable indent blank line in buffers line nvim?
<img width="1292" alt="Screen Shot 2021-12-24 at 7 58 55 PM" src="https://user-images.githubusercontent.com/14851850/147375207-90246ebd-0eb5-4e78-ab66-00ef9d6dc985.png">

**Comment by lukas-reineke** [comment]
You can set filetypes to exclude with `:help g:indent_blankline_filetype_exclude`
For Nvim tree I think it is `NvimTree`

**Comment by hsheikhali1** [comment]
I've tried this many times. doesn't register .

**Comment by lukas-reineke** [comment]
I am very confident that `indent_blankline_filetype_exclude` works correctly. If you find a bug there, please create a minimal init.lua to reproduce it.

I don't use NvimTree, so I can't really help you with that, maybe open an issue in that repo.

**Comment by lolix-notepad** [comment]
Hello @hsheikhali1, if you still having the problem try to use in your lua file settings:

```lua
vim.g.indent_blankline_filetype_exclude = {'NvimTree'}
```

or for vimscript:
```vim
let g:indent_blankline_filetype_exclude = ['NvimTree']
```

Explanation: the `NvimTree` is the file type and you can get it calling this `:lua print(vim.bo.filetype)` to get the file type of the current buffer where the mouse is.

NOTE: the file type is case sensitive.

**Comment by Dsantra92** [comment]
> Explanation: the `NvimTree` is the file type and you can get it calling this `:lua print(vim.bo.filetype)` to get the file type of the current buffer where the cursor is.
> NOTE: the file type is case sensitive.

It will be helpful for non-expert vim users like me, to have this information in the plugin's man page.

**Comment by lukas-reineke** [comment]
`filetype` itself is already documented by (neo)vim itself. And the indent-blankline documentation links to it.

![Screen Capture_select-area_20220103162354](https://user-images.githubusercontent.com/12900252/147907232-0ade15fd-05e7-4b22-8b8c-c1ff879ef077.png)

You can put the cursor on `filetype` and hit `ctrl-]`. This will jump you to the documentation for `filetype`.
