### ISSUE TITLE
Disable blankline in a specific split?

### ISSUE THREAD

**Issue by sebffischer** [lukas-reineke/indent-blankline.nvim#341]
First of all, thank you for this great Plugin!

I use the plugin Nvim-R to send R-Code from by buffers to a R REPL that is open in a Vim Split. 
I would like to disable indent-blankline in this specific split (the one which runs the REPL). 
Is this possible? If so, how?

Thanks in advance!

**Comment by lukas-reineke** [comment]
You can exclude filetypes and buftypes with `:help g:indent_blankline_filetype` and `:help g:indent_blankline_filetype_exclude`
You have to check nvim-r to see what that plugin uses.

**Comment by sebffischer** [comment]
thanks!
