### ISSUE TITLE
EOL char highlight is wrong

### ISSUE THREAD

**Issue by Mofiqul** [lukas-reineke/indent-blankline.nvim#344]
I can not change the `eol` char highlight. It does not respect the highlights of `Whitespace` or `Label`

![Screenshot from 2022-01-01 23-50-25](https://user-images.githubusercontent.com/23612580/147857531-194d8380-85d4-4e7d-a1ec-d1e4b83bfe49.png)
### Neovim Version
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by lukas-reineke** [comment]
This is not related to indent-blankline. Those EOL characters are a built-in feature.
The highlight group for them is `NonText`
