### ISSUE TITLE
Display one less component on blank lines

### ISSUE THREAD

**Issue by Saecki** [lukas-reineke/indent-blankline.nvim#345]
First of all thanks for the plugin.

I would love an option to display one less component on blank lines.
That is how indentation guides work in IntelliJ and VSCode. And I honestly think it makes more sense.

Especially with `use_treesitter` enabled the trailing component feels out of place (See first image).

Currently:
![image](https://user-images.githubusercontent.com/43008152/147900754-cca71836-21a9-435f-9736-52fa896405c8.png)

Expected:
![image](https://user-images.githubusercontent.com/43008152/147900775-539bfe66-1550-4e37-afc5-3d117a568479.png)

I just added a `-1` so it isn't in shape for a PR.
When I have some time I might try to get a grip of the config options and actually implement this.

**Comment by lukas-reineke** [comment]
This is already an option `:help g:indent_blankline_show_trailing_blankline_indent`

**Comment by Saecki** [comment]
Oops, sorry for bothering you
