### ISSUE TITLE
Only show indent lines for current context?

### ISSUE THREAD

**Issue by lougreenwood** [lukas-reineke/indent-blankline.nvim#348]
I would like to highlight the current context block, but hide all other indent lines.

Basically https://github.com/lukas-reineke/indent-blankline.nvim#with-context-indent-highlighted-by-treesitter - but only the pink indent line - all the other grey lines would not be displayed (I find them distracting and just want to see the current block's indent)

Is this possible?

**Comment by lukas-reineke** [comment]
Yes you can. Just set `:help g:indent_blankline_char` to an empty string, and `:help g:indent_blankline_context_char` to the indent char.

```lua
require("indent_blankline").setup {
    char = "",
    context_char = "│",
    show_current_context = true,
    show_current_context_start = true,
}
```

**Comment by lougreenwood** [comment]
Perfect, thanks @lukas-reineke
