### ISSUE TITLE
Turn off eol symbol if code is sent to qtconsole

### ISSUE THREAD

**Issue by da0bi** [lukas-reineke/indent-blankline.nvim#354]
Hi. I am using following setup https://www.blog.gambitaccepted.com/2020/04/26/neovim-qtconsole-setup/ to pass my python code into a qtconsole. However, it won't work if my eol symbol is activated (applied your 'Simple' setup example). So the question is, if there is a simple command like ':set noeol' to deactivate the eol symbol before passing it on?

**Comment by lukas-reineke** [comment]
What exactly won't work? eol should have nothing to do with this.

**Comment by da0bi** [comment]
The code (with the eol symbol) I pass on to the qtconsole doesn't show up and hence is also not executed. If I change the indent-blankline config to not show the eol symbol at all, everything works fine. So I guess the eol symbols are passed on as 'normal' code text to the qtconsole which can't process those.

**Comment by lukas-reineke** [comment]
Can you share your config to reproduce this?

The eol symbol is not added as normal text, no api that interacts with the buffer text will return this. I am very confident that this is some other issue.

**Comment by da0bi** [comment]
Hi. Put all my neovim config files to https://github.com/da0bi/nvim. All the config files of the individual packages I import in ./lua/packages.lua are stored in ./lua/packages/. The config files indent_blankline.lua and ipy.lua are the ones of the directly involved packages ( yours and bfredl/nvim-ipy). Thx for your help!

**Comment by lukas-reineke** [comment]
I can't reproduce the issue.
And `nvim-ipy` just uses `getline` to get the buffer text.

https://github.com/bfredl/nvim-ipy/blob/50a938a7b24a327dd72284e11a5405875917f29b/plugin/ipy.vim#L44
https://github.com/bfredl/nvim-ipy/blob/50a938a7b24a327dd72284e11a5405875917f29b/plugin/ipy.vim#L107

`getline` does not return virtual text or listchars. You can test that yourself with just running `:echo getline(0, 100)`

I don't see any way this is related to eol chars, or indent-blankline in general.

**Comment by da0bi** [comment]
Ok - weird, then I need to check again my config files. However, thx for your help and sorry for the inconvenience. cheers, daniel
