### ISSUE TITLE
A quick way to disable this plugin for copy/pasting text

### ISSUE THREAD

**Issue by theairbend3r** [lukas-reineke/indent-blankline.nvim#355]
Is there a way to quickly turn on/off this plugin for copying text? Currently, the indent lines are copied too.

I was thinking of something equivalent to `:set nonumber`. 

What do you think?

**Comment by lukas-reineke** [comment]
You mean when selecting with the mouse?
You should `:set mouse=a` in vim, so selecting is handled by vim, and not you terminal. This way you don't copy things like numbers, listchars and also indent lines.

But there is also a way to turn the plugin on and off, with `:IndentBlanklineDisable`, `:IndentBlanklineEnable` and `IndentBlanklineToggle`
