### ISSUE TITLE
show_end_of_line = false     not working

### ISSUE THREAD

**Issue by djalan** [lukas-reineke/indent-blankline.nvim#356]
The boolean `show_end_of_line = false` does not work. The parameter seems to be controlled by opt.list and opt.listchars:append.

This might be related to this issue https://github.com/lukas-reineke/indent-blankline.nvim/issues/354

```lua
-- indent-blankline config file

vim.opt.list = true
vim.opt.listchars:append("eol:↴")

require("indent_blankline").setup {
    show_end_of_line = false,
    space_char_blankline = " ",
}

```

**Comment by lukas-reineke** [comment]
The indent-blankline option `show_end_of_line` only is for deciding if end of line characters are overwritten with indent lines or not.
To turn the end of line characters themselves on or off you have to use the native functionality with `opt.list` and `opt.listchars`. This is working as intended.
