### ISSUE TITLE
How to remove the underlining of the line?

### ISSUE THREAD

**Issue by hrqmonteiro** [lukas-reineke/indent-blankline.nvim#357]
![print](https://user-images.githubusercontent.com/17055027/152240979-0f803486-6d7a-439d-8e35-b6032a48a9a7.png)

I don´t want this horizontal underline on the context, just the vertical lines. How to remove it?

**Comment by lukas-reineke** [comment]
You set `show_current_context_start = false`. Or you can remove that line, it is not on by default. You turn it on with `show_current_context_start = true`

**Comment by MIvanchev** [comment]
OK, thanks, is there a possibility of using other set of highlights for the cursorline?

**Comment by Leandros** [comment]
@lukas-reineke @MIvanchev: That's something I'd like to know, as well. Currently I'm using the same color for the highlight of the cursorline as well as the indentguides: 
![image](https://user-images.githubusercontent.com/396475/153606677-7f134961-ac0c-44e6-84ba-176ccd853105.png)

This creates the issue that the guides are not shown for the current line. 

Would it be possible to simply invert the color of the indentguide, for example?

**Comment by MIvanchev** [comment]
@Leandros hey, nice to see another solarized user :) While there is no highlight for the cursorline indent guides, I could recommend to you the color I use for indent guides: `hi IndentBlock guifg=#234854 gui=nocombine`. It highlights nicely in the cursorline as well.

**Comment by Leandros** [comment]
@MIvanchev: That looks great, thank you!

**Comment by kitesi** [comment]
For anyone one in the future, it is now 

```
require('ibl').setup({
	scope = {
		show_start = false
	}
})
```
