### ISSUE TITLE
Cursorline highlight begins after indent block?

### ISSUE THREAD

**Issue by MIvanchev** [lukas-reineke/indent-blankline.nvim#358]
Hey, I'm having an issue that my cursorline begins after the indent instead of col 0, here's my config

```
" Add the color scheme at the ColorScheme event, otherwise
" it'd be cleared
augroup colors
  au!
  au ColorScheme * hi IndentBlock guibg=#06313c gui=nocombine
augroup END

lua << EOF
require("indent_blankline").setup {
  -- for example, context is off by default, use this to turn it on
  -- show_current_context = true,
  --show_current_context_start = true,
  char = "",
  char_highlight_list = {"Normal", "IndentBlock"},
  space_char_highlight_list = {"Normal", "IndentBlock"},
  show_trailing_blankline_indent = false
}
EOF
```
And here is what it results in:

![Issue](https://raw.githubusercontent.com/MIvanchev/images/bb83c1f1-3aa1-4f48-992c-382f1e50e297/image.png)

Notice how in line 3 the highlight begins from column 5. This neovim-qt btw.

**Comment by lukas-reineke** [comment]
This is a limitation of Neovim. Virtual text takes priority over the cursor line.
There is no way that I know of to work around this.

You can use `None` instead of `Normal`, so you have the cursor line at least for the part of the indent blocks that are the same color as the background.

**Comment by MIvanchev** [comment]
So is there a possibility to use separate sets of highlights for the cursorline?

**Comment by lukas-reineke** [comment]
No there isn't. There is only `CursorLine`
