### ISSUE TITLE
Indentline Misposition for 2-space Indentation

### ISSUE THREAD

**Issue by Bekaboo** [lukas-reineke/indent-blankline.nvim#359]
For 2-space indentaiton, the indentline overlaps with that of the upper level.

Current:
![图片](https://user-images.githubusercontent.com/76579810/152579457-f6c5cd5f-4b44-4b98-82b0-963da7857b4c.png)

Expected (notice the green indent line):
![图片](https://user-images.githubusercontent.com/76579810/152579550-acbb8f45-5ab3-4cf2-989d-22151eaa2e36.png)

**Comment by lukas-reineke** [comment]
Do you have `shiftwidth` set to 2?

**Comment by Bekaboo** [comment]
> Do you have `shiftwidth` set to 2?

Thanks! This solves the problem.
