### ISSUE TITLE
Don't show guides for trailing whitespace?

### ISSUE THREAD

**Issue by MIvanchev** [lukas-reineke/indent-blankline.nvim#360]
Would there be an option not to show indent guides if the rest of the line consists of whitespace only?

![Image](https://raw.githubusercontent.com/MIvanchev/images/dca26a8e83348f9abae7aecb78e51dabd458acc2/image.png)

**Comment by lukas-reineke** [comment]
There is no specific setting for ignoring trailing whitespace.
But you can set `max_indent_increase` to 1, this should have the same effect.
