### ISSUE TITLE
indent won't show if html is formatted with 2space indent

### ISSUE THREAD

**Issue by shaeinst** [lukas-reineke/indent-blankline.nvim#361]
![image](https://user-images.githubusercontent.com/41078534/154485374-05be9fe2-96b3-4b53-9d03-e43590f419d1.png)

**Comment by lukas-reineke** [comment]
Have you set `shiftwidth` (for spaces) or `tabstop` (for tabs) to 2?

**Comment by shaeinst** [comment]
``` lua
shiftwidth = 4
tabstop = 4
```
#### if values are set to 2, indent shows correctly for code with 2unit space.
#### if values are set to 4, indent shows correctly for code with 4unit space.

i think this behavior should be auto handle by  plugin itself.

**Comment by lukas-reineke** [comment]
> this behavior should be auto handle by plugin itself.

No, the plugin uses what you have set.
If you automatically want to set `shiftwidth` and `tabstop`, you can use something like https://github.com/tpope/vim-sleuth

**Comment by lukas-reineke** [comment]
Irregular indentation is currently not supported. There is an issue for this #170
But it requires a lot of rework.
