### ISSUE TITLE
Remove indent guide on empty lines

### ISSUE THREAD

**Issue by BrandonBlankerLim-it** [lukas-reineke/indent-blankline.nvim#362]
![image](https://user-images.githubusercontent.com/97938520/155048371-96852121-6d19-45dd-91a4-a55de5f32dc4.png)

See line 47, that's an empty line and the `|` shouldnt appear.
Using default config and tabs as indentation character with no `expandtab`

**Comment by lukas-reineke** [comment]
I cannot reproduce this.

Can you make a minimal init.lua and a code example for which this happens?

**Comment by lukas-reineke** [comment]
Can you also share the code from the screenshot? Or any code snipped where this happens

**Comment by BrandonBlankerLim-it** [comment]
Happens on any code for me, lua or cpp code are what I've tested it with.

**Comment by lukas-reineke** [comment]
Thank you, I can reproduce.

This happens because of `vim.g.indent_blankline_use_treesitter = true`.
Treesitter indent isn't that great yet. Sometimes it makes these mistakes.

You can open an issue in the treesitter grammar repo. It's a bug there, not in indent-blankline.

I don't use treesitter for this myself, because of these issues. The default algorithm built into indent-blankline usually does a better job.
It should work fine if you do `vim.g.indent_blankline_use_treesitter = false`

**Comment by BrandonBlankerLim-it** [comment]
Thank you! Im new to neovim, still migrating from vim.

**Comment by chalmagean** [comment]
Hi @lukas-reineke,

Not sure if I'm missing something, but I can still see indents on blank lines.

![CleanShot 2022-12-03 at 10 01 44](https://user-images.githubusercontent.com/8421/205431156-106e3d96-fbfd-4919-9c4a-d63015376bee.png)

**Comment by chalmagean** [comment]
> You have trailing whitespace on that line

Yes. Exactly. I don't want to see indent guides there.

**Comment by chalmagean** [comment]
> @chalmagean
> 
> What's your config look like? Did you `vim.g.indent_blankline_use_treesitter = false`?

Is that different from the setup block? I thought that by putting it there, it was the same thing.

**Comment by lukas-reineke** [comment]
> Yes. Exactly. I don't want to see indent guides there.

There is no way to turn this off. I explicitly don't hide it, so you don't miss it and can remove it. It's a feature not a bug.

> Is that different from the setup block? I thought that by putting it there, it was the same thing.

Yes, it's the same thing

**Comment by chalmagean** [comment]
> There is no way to turn this off. I explicitly don't hide it, so you don't miss it and can remove it. It's a feature not a bug.

I don't see the point of having both a dot to indicate whitespace, and the indent guide.
