### ISSUE TITLE
Wrong indents when using ':set list' on neovim 0.5

### ISSUE THREAD

**Issue by ibhagwan** [lukas-reineke/indent-blankline.nvim#363]
Only happens with neovim `0.5`, works properly with any version >= `0.5.1` (tested, `0.6`, `0.6.1` and `0.7` nightly):

![Peek 2022-02-23 11-36](https://user-images.githubusercontent.com/59988195/155394837-2287c4a1-e69e-4e82-878a-26129a045fd1.gif)

**Comment by lukas-reineke** [comment]
Thank you for the issue.
0.5 is pretty outdated, this isn't super high priority for me. I will try to see why it is not working, but I'm not sure when I'll have time.

**Comment by ibhagwan** [comment]
> Thank you for the issue.
> 0.5 is pretty outdated, this isn't super high priority for me. I will try to see why it is not working, but I'm not sure when I'll have time.

I don’t use 0.5 regularly, I only got to it as I test my code with different neovim versions and thought you’d like to know, not critical at all.
