### ISSUE TITLE
Blank line not working

### ISSUE THREAD

**Issue by VoltairedesChamps** [lukas-reineke/indent-blankline.nvim#37]
Hello,

I am unable to get the default setting  for indent-blankline.nvim
I am running it on alacritty windows.
Got the lattest build to make it run NVIM v0.5.0-dev+1069 and the lua plugin. ( as seen in an other issue ).
I even tested his configuration but nothing happened.
I just want the default configuration as shown in the screenshot
Thanks in advance !

![image](https://user-images.githubusercontent.com/70516313/107124718-dd805600-68a5-11eb-8cd5-cd52b9b5859e.png)

![image](https://user-images.githubusercontent.com/70516313/107124688-ad38b780-68a5-11eb-904f-8ccecc1178c3.png)

**Comment by lukas-reineke** [comment]
It looks like its working fine?
This plugin only fills in empty lines (for now)
To get the rest of the indentation as well, you need https://github.com/Yggdroot/indentLine

**Comment by VoltairedesChamps** [comment]
My bad, i thought the indentLine plugin was optional. ( even if i have it ) 
Can i still get the init.vim command to get this style please ? 
![image](https://user-images.githubusercontent.com/70516313/107196783-59d47f80-69f3-11eb-8979-5a06fa4861b0.png)
Thanks have a nice day

**Comment by lukas-reineke** [comment]
Once you install https://github.com/Yggdroot/indentLine it should look like the screenshot.
If it doesn't, its an issue with indentLine
