### ISSUE TITLE
Indentation doesn't work for ":"

### ISSUE THREAD

**Issue by rawat9** [lukas-reineke/indent-blankline.nvim#372]
Any possible way to fix this?

![indentLine](https://user-images.githubusercontent.com/64035803/158036226-2758ef32-8ecf-4efd-977e-af7893f192da.gif)

**Comment by lukas-reineke** [comment]
indent-blankline just draws the indent guides, it does not change how the code is indented.

This is not related to this plugin, sorry I can't help you with that.
