### ISSUE TITLE
characters disappear with treesitter enabled

### ISSUE THREAD

**Issue by robbyki** [lukas-reineke/indent-blankline.nvim#373]
trying to troubleshoot why I keep getting a messed up blanking out of characters with lua files as soon as I enable treesitter with the below config. Works fine if I disable treesitter. Also noticed that the characters show up for a second when file in opened before disappearing. 

![image](https://user-images.githubusercontent.com/1027357/158071637-8570fc24-d9c4-485a-9f7e-585e5f9440fb.png)

**Comment by robbyki** [comment]
Seems to be solved if I first format the file.

**Comment by lukas-reineke** [comment]
If you enable treesitter, indent-blankline will put the indent guides where treesitter tells it to. If your actual code is not indented correctly, this might happen.

TBH I recommend turning off treesitter for indent-blankline. The default algorithm does a better job in most cases, including this.
