### ISSUE TITLE
Context is no longer highlighted when top of context is no longer in view

### ISSUE THREAD

**Issue by lars-vc** [lukas-reineke/indent-blankline.nvim#374]
When the top of the context goes out of view the tab line is no longer highlighted, e.g.
![image](https://user-images.githubusercontent.com/57136208/158842084-8f3f00d1-b650-41c1-8e65-f99d4e7c310f.png)
The first tabline should be highlighted. I do fear that this is a limitation (with treesitter or maybe even vim in general) that can't be fixed :/.
But who knows I am just doing something wrong, my config:
```lua
require("indent_blankline").setup {
    show_current_context = true,
    show_current_context_start = true,
}
```

**Comment by lukas-reineke** [comment]
This is done for performance. By default, the plugin looks 10 lines above your viewport to generate indentation and the context.
You can set this to a higher number with `g:indent_blankline_viewport_buffer`, but high numbers might make cause some lag.
