### ISSUE TITLE
It does not work in the c file 

### ISSUE THREAD

**Issue by XXiaoA** [lukas-reineke/indent-blankline.nvim#375]
in `.py` file it can works 
![IMG_20220320_112442](https://user-images.githubusercontent.com/62557596/159146714-48708008-c1a5-4de8-826c-d6f7a5bf7015.jpg)

but in `.c` file it cann't
![IMG_20220320_112510](https://user-images.githubusercontent.com/62557596/159146728-224c8307-d2c8-4f7f-b491-f5ee6931c464.jpg)

here is my config
![IMG_20220320_112748](https://user-images.githubusercontent.com/62557596/159146768-41404f32-34d8-4ec9-9a4a-4fe949abaff0.jpg)

type `nvim -v` shows
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by lukas-reineke** [comment]
I can't reproduce, it works fine for me.
Can you try to update the plugin?

![Screen Capture_select-area_20220322102824](https://user-images.githubusercontent.com/12900252/159389229-a00cb3b7-4dd0-43bb-a9f1-cdd758a3ee96.png)

**Comment by XXiaoA** [comment]
> I can't reproduce, it works fine for me.
> Can you try to update the plugin?
> 
> ![Screen Capture_select-area_20220322102824](https://user-images.githubusercontent.com/12900252/159389229-a00cb3b7-4dd0-43bb-a9f1-cdd758a3ee96.png)
> 

I have solved the problem. When I installed treesitter's c language support, it worked fine. Thanks
