### ISSUE TITLE
Line width

### ISSUE THREAD

**Issue by ahmed-rezk-dev** [lukas-reineke/indent-blankline.nvim#376]
Is there is any way to add line width to be wider?

**Comment by lukas-reineke** [comment]
You mean the indent line?

You can set it to any character you want with `:help g:indent_blankline_char`

This one should be thicker than the default `┃`
`require("indent_blankline").setup { char = "┃" }`

**Comment by karimlevallois** [comment]
I think the issue is when you maybe add padding to the rows in the terminal, you can end up with indentation lines that don’t connect to one another.

**Comment by lukas-reineke** [comment]
> I think the issue is when you maybe add padding to the rows in the terminal, you can end up with indentation lines that don’t connect to one another.

That depends on the terminal. Kitty for example handles this correctly.

**Comment by teddywaweru** [comment]
@karimlevallois  you can try using the [unicode version](https://codepoints.net/U+258F) for this. [ ▏] . It should connect through the rows
