### ISSUE TITLE
Allow customization of the indent character list for blank lines (similarly to `indent_blankline_space_char_blankline`)

### ISSUE THREAD

**Issue by Dettorer** [lukas-reineke/indent-blankline.nvim#377]
There already is `indent_blankline_space_char_blankline` to help differentiate the marking between blank lines and regular ones, would it be possible to implement `indent_blankline_char_list_blankline` and `indent_blankline_char_blankline`? With such a setting I would for example keep `indent_blankline_char` to its default value `'|'` and set `indent_blankline_char_blankline` to `'┆'`.

**Comment by lukas-reineke** [comment]
sure, why not

I made a PR #378, is this what you were thinking of?

**Comment by Dettorer** [comment]
Excellent! That is exactly what I had in mind. I tested it with following settings:

```vim
let g:indent_blankline_show_trailing_blankline_indent = v:false
let g:indent_blankline_char_blankline = '┆'
```
![blankline_char_blankline](https://user-images.githubusercontent.com/2761682/160104237-4a21bd56-c4a6-48b0-aae1-5b702b461793.png)
