### ISSUE TITLE
Exclude filetype

### ISSUE THREAD

**Issue by Mte90** [lukas-reineke/indent-blankline.nvim#38]
indentline has this feature, I use to not add indents line in those cases:

`let g:indentLine_fileTypeExclude = ['help', 'chadtree', 'startify', 'fzf', 'tagbar']`

**Comment by lukas-reineke** [comment]
That already exists. Is it not working for you?

either, `indent_blankline_filetype_exclude` or `g:indentLine_fileTypeExclude` should exclude filetypes.

**Comment by Mte90** [comment]
Dammit I read the docs but I didn't saw that -.-'
