### ISSUE TITLE
`char_blankline` overridden when `show_current_context` is active

### ISSUE THREAD

**Issue by cooperuser** [lukas-reineke/indent-blankline.nvim#382]
I really enjoy this new feature (#378)! I didn't know it was something I wanted until I tried it out 😂 
I hope the title is pretty self-explanatory, but I'll provide some screenshots to better illustrate the problem.
> (also, brief aside, I have my `char` and `char_blankline` swapped from what was mentioned in #377)

## How things look normally
![image](https://user-images.githubusercontent.com/21961037/160255305-311d85dc-b993-44cc-b2ef-437373e0573d.png)

## Notice how some of the `char_blankline`s appear as normal `char`s now
![image](https://user-images.githubusercontent.com/21961037/160255310-bebfd857-660f-40d6-8bac-9aea4d3fda13.png)

## Same here, but in the outer context
![image](https://user-images.githubusercontent.com/21961037/160255315-f9da3e13-4073-49c6-83a2-cbcba4125a93.png)

If I have some time I'll look into fixing this myself as I assume its a pretty straightforward fix, but I assume @lukas-reineke already knows exactly where and how to apply the fix for this 🙃 

Really appreciate the work you do! ❤️

**Comment by cooperuser** [comment]
Update:

I looked through the code and I believe I've figured out how to add it on my own, so expect a pull request soon.

**Comment by karimlevallois** [comment]
@cooperuser Would you mind sharing your config?

**Comment by cooperuser** [comment]
@karimlevallois [Here](https://github.com/cooperdots/nvim/blob/main/lua/cooper/indent.lua) is my config for this plugin, and you can find my entire `nvim` config in that repo, [cooperdots/nvim](https://github.com/cooperdots/nvim) 👍

**Comment by karimlevallois** [comment]
> @karimlevallois [Here](https://github.com/cooperdots/nvim/blob/main/lua/cooper/indent.lua) is my config for this plugin, and you can find my entire `nvim` config in that repo, [cooperdots/nvim](https://github.com/cooperdots/nvim) 👍 

Awesome, thanks very much!
