### ISSUE TITLE
Start screen

### ISSUE THREAD

**Issue by g0J0na** [lukas-reineke/indent-blankline.nvim#386]
How do i hide indent in startup screen ? I'm using alpha-nvim
![Screenshot from 2022-03-28 18-32-40](https://user-images.githubusercontent.com/90030004/160389953-34cb082c-c35d-418e-ae86-3a76a54e0160.png)
![Screenshot from 2022-03-28 18-33-06](https://user-images.githubusercontent.com/90030004/160389962-84f2456f-fc9d-4980-90b2-fd12275e1ae4.png)

**Comment by karimlevallois** [comment]
You have to add

filetype_exclude = {"alpha"}

**Comment by g0J0na** [comment]
> 

thank you , it worked!
