### ISSUE TITLE
Issue getting plugin to work properly

### ISSUE THREAD

**Issue by jswent** [lukas-reineke/indent-blankline.nvim#388]
I'm just gonna start off by saying I'm quite new to lua with nvim so if I am doing something extremely stupid please forgive me. Okay now on to the actual issue.

For some reason when I call my config file for the plugin, the plugin refuses to work. I have tried this with multiple different config files and the only way I am able to get the plugin to work is if I use it without a config file. 

packages.lua (inside .config/nvim/lua folder)
`use {
    'lukas-reineke/indent-blankline.nvim', 
    config = [[require('config.indent-blankline')]]
  }`

However when I just call this
`use { 'lukas-reineke/indent-blankline.nvim' }`
It works perfectly. Here is my config file:

indent-blankline.lua (inside .config/nvim/lua/config folder)
```
require("indent_blankline").setup({
  char = "▏",
  show_end_of_line = false,
  disable_with_nolist = true,
  buftype_exclude = { "terminal" },
  filetype_exclude = { "help", "git", "markdown", "snippets", "text", "gitconfig", "alpha" },
})

vim.cmd([[
function! Should_activate_indentblankline() abort
  if index(g:indent_blankline_filetype_exclude, &filetype) == -1
    IndentBlanklineEnable
  endif
endfunction
augroup indent_blankline
  autocmd!
  autocmd InsertEnter * IndentBlanklineDisable
  autocmd InsertLeave * call Should_activate_indentblankline()
augroup END
]])
```

This has been frustrating me for the better part of today, so I turn it over to the experts. Thanks for your help!

**Comment by lukas-reineke** [comment]
In lua `[[something]]` is just a string. It is the same as doing `"something"`.
It should be `use { 'lukas-reineke/indent-blankline.nvim', config = require('config.indent-blankline') }`

Next, in lua you a file/model works similar to a function. It returns something, by default that is `nill`.
`config` expects a function, but your required config file returns `nill`.

You need to wrap everything in `config.indent-blankline` inside a fucntion, and return that.

```lua
return function()
  require("indent_blankline").setup({
    char = "▏",
    show_end_of_line = false,
    disable_with_nolist = true,
    buftype_exclude = { "terminal" },
    filetype_exclude = { "help", "git", "markdown", "snippets", "text", "gitconfig", "alpha" },
  })

  vim.cmd([[
    function! Should_activate_indentblankline() abort
      if index(g:indent_blankline_filetype_exclude, &filetype) == -1
        IndentBlanklineEnable
      endif
    endfunction
    augroup indent_blankline
      autocmd!
      autocmd InsertEnter * IndentBlanklineDisable
      autocmd InsertLeave * call Should_activate_indentblankline()
    augroup END
  ]])
end
```

**Comment by jswent** [comment]
Thank you, this fixed my issue!
