### ISSUE TITLE
Support non-blank lines

### ISSUE THREAD

**Issue by nifoc** [lukas-reineke/indent-blankline.nvim#39]
Just opening this to make sure that you're aware 🙂

The `overlay` display mode for virtual text was just merged into `HEAD`: https://github.com/neovim/neovim/pull/13952

This should allow for virtual text to be displayed *anywhere*, even on lines that are not blank.

> The primary use cases of this display modes would be indent guides as well as EasyMotion style hints. Abusing the indent area for "sign" like display is also possible.

**Comment by lukas-reineke** [comment]
:tada: :tada: 
I pushed an update to the lua branch to remove the IndentLine dependency

**Comment by nifoc** [comment]
That was super quick, thank you!

Installed it and it appears to be working flawlessly. I guess this can already be closed?

**Comment by jmlucjav** [comment]
I was waiting for this to be done to set this up...one question that is not clear, do I need to install indentLine if I use the Lua branch? Is it recommended? What do I loose if I don't install indentLine?

**Comment by lkhphuc** [comment]
![Screenshot 2021-02-23 at 00 38 44](https://user-images.githubusercontent.com/12573521/108788256-7cc46f00-756f-11eb-814a-423be8b66d0a.png)
 
Hi I tried this today with the nvim HEAD. This is the default setting without the other indentLine plugin. Not sure what the problem is.

**Comment by lukas-reineke** [comment]
> do I need to install indentLine if I use the Lua branch

No, not needed anymore

> This is the default setting without the other indentLine plugin

that looks broken, can you try to create a way for me to reproduce?

**Comment by lkhphuc** [comment]
Platform: MacOS
Nvim: `NVIM v0.5.0-dev+nightly-45-g9d5f84280`
init.vim:
```
call plug#begin('~/.local/share/nvim/plugged')
" Plug 'Yggdroot/indentLine'
Plug 'lukas-reineke/indent-blankline.nvim', {'branch': 'lua' }
call plug#end()
```
![Screenshot 2021-02-23 at 10 26 52](https://user-images.githubusercontent.com/12573521/108831133-a60deb00-75c1-11eb-95b8-8adea36d6662.png)

**Comment by lukas-reineke** [comment]
I made a new issue for lkhphuc problem
