### ISSUE TITLE
Enabling indent-blankline.nvim disables CursorHold autocmd's from spawning diagnostic hover window.

### ISSUE THREAD

**Issue by bbaserdem** [lukas-reineke/indent-blankline.nvim#398]
I have been using nvim-lspconfig; and specifically [this page](https://github.com/neovim/nvim-lspconfig/wiki/UI-customization) to hook diagnostic hover windows on cursor on a symbol with LSP warning.

Even when the relevant autocmd is set, and confirmed to set, (hooks to CursorHold) if indent-blankline.nvim is loaded the autocmd won't activate.

The only problem is with the autocmd triggering; as giving a command to launch diagnostic info on hover menu works just fine.

I confirmed with disabling all my other plugins and enabling them one by one; and this is purely a indent-blankline.nvim issue.

**Comment by lukas-reineke** [comment]
I can't reproduce this.
Can you share the exact code you are using?

**Comment by bbaserdem** [comment]
I'll try to reproduce using a minimal init.lua; and return back with my report. My configuration is [here](https://github.com/bbaserdem/dotfiles/tree/master/nvim) (relevant config for [indent-blankline](https://github.com/bbaserdem/dotfiles/blob/master/nvim/lua/plugin-configs/indent_blankline-config.lua) and [nvim-cmp](https://github.com/bbaserdem/dotfiles/blob/master/nvim/lua/plugin-configs/cmp-config.lua)) but it is very fragmented.

**Comment by bbaserdem** [comment]
This is incredibly weird; but I tried replicating with a minimal config but failed. Also; re-enabling indentline in my config, I have no issues anymore with diagnostic popups so I have no idea what went wrong. I'll close this issue; sorry for rising a false flag.
