### ISSUE TITLE
How to enable underline for all blocks/scopes?

### ISSUE THREAD

**Issue by omar2205** [lukas-reineke/indent-blankline.nvim#399]

**Comment by lukas-reineke** [comment]
Please write a description, I do not understand what you mean.

**Comment by omar2205** [comment]
Sorry, I thought I was clear. 

Currently, the horizontal lines only appear inside functions (for me at least in JS files). I want it to show up inside objects for example.

![image](https://user-images.githubusercontent.com/1373867/164965578-00035b70-ae86-4bd6-a6c1-25c882ec4990.png)

Line 1 is underlined, but line 3 isn't.

**Comment by lukas-reineke** [comment]
That is not the default behavior.
Do you have any configuration for indent-blankline?

**Comment by omar2205** [comment]
```lua
require("indent_blankline").setup {
  space_char_blankline = " ",
  show_current_context = true,
  show_current_context_start = true,
}

```

**Comment by lukas-reineke** [comment]
That looks okay.
What version of indent-blankline are you using?

**Comment by omar2205** [comment]
2.17.0

Also, is it possible to work without brackets? In elixir function block for example?

JS
![image](https://user-images.githubusercontent.com/1373867/165047819-441036ef-44fb-4287-8ca3-7cefbd1961c5.png)

Elixir
![image](https://user-images.githubusercontent.com/1373867/165048228-c7f43881-11c2-4a33-9233-ae3998f7222d.png)

**Comment by lukas-reineke** [comment]
It has nothing to do with brackets, it uses treesitter and compares it against `g:indent_blankline_context_patterns`

Your Javascript/Typescript example should work. It works fine for me.
![Screen Capture_select-area_20220425173053](https://user-images.githubusercontent.com/12900252/165051240-e6ab5377-99fe-43a4-bb1d-26d293f4dfa4.png)

The default patterns don't have support for elixir yet. I can add that. It needs a `do_block` pattern.
