### ISSUE TITLE
Problems with wilder and coc

### ISSUE THREAD

**Issue by chriztheanvill** [lukas-reineke/indent-blankline.nvim#400]
Hi.
Starting yesterday to use Coc instead of Cmp and LSP, also installed wilder. And constantly closes neovim.
Also, once, before neovim closes, shows me an error with wilder and the problem was kind of format and shim. So I disabled indent-blankline and stops the problems.

This is my config of indent:
```
-- Path ~/.config/nvim/lua/pluggins.lua
-- use "lukas-reineke/indent-blankline.nvim" -- Now its disabled

-- Path ~/.config/nvim/lua/user/indent.lua
vim.opt.list = true
vim.opt.listchars:append("space:⋅")
-- vim.opt.listchars:append("eol:↴")

require("indent_blankline").setup {
	space_char_blankline = " ",
	show_current_context = true,
	show_current_context_start = true,
}
```

**Comment by lukas-reineke** [comment]
There is nothing wrong with your config.
Without some more information, I can't help you.

Do you have the error message? Or a way to reproduce this?

**Comment by chriztheanvill** [comment]
Using cmp does not have issues, but Im having issues with cmp, so I've changed to coc.
With coc, has issues: segmentation default.
I thought if should be something with: vim.opt, this variable should not be only for the current buffer? I am a newer in lua and neovim.

**Comment by chriztheanvill** [comment]
Yes, I enabled again indent-blankline, and just for moving the cursos up and down, neovim breaks:

![image](https://user-images.githubusercontent.com/37992958/165199265-400f248e-2a6b-48f2-b259-9f8071b75db4.png)

**Comment by lukas-reineke** [comment]
A segmentation fault is a bug in Neovim core. You should open an issue there.

**Comment by avalonv** [comment]
Completely off-topic @chriztheanvill but what extension are you using to display those tabs/buffers in that screenshot? Would you mind sharing the config? Thanks.
