### ISSUE TITLE
Use it for colorcolumn

### ISSUE THREAD

**Issue by rafaeldtinoco** [lukas-reineke/indent-blankline.nvim#402]
Sorry if this is a stupid question, I would like to know if I can use this plugin as a "column" line (I have "set colorcolumn=80,90,100" in my vimrc, for example, but it is not as cool as having this thin line). 

Thanks for this amazing plugin!

**Comment by lukas-reineke** [comment]
I actually have a different plugin for that https://github.com/lukas-reineke/virt-column.nvim

**Comment by rafaeldtinoco** [comment]
Thanks a lot!!!
