### ISSUE TITLE
text is corrupt when this plugin is on

### ISSUE THREAD

**Issue by 010penetrator** [lukas-reineke/indent-blankline.nvim#404]
```
$ cat 1234.sh 
echo Final aim $str
if [ -n "$str" ]
	then
			# Run
			$TERMINAL &> /dev/null &
      notify-send new_TERMINAL
    # Raise
	else wmctrl -i -a $str
fi
```

When I open this file with the plugin loaded, I see this 
![2022-05-01-205556_2560x1440_scrot](https://user-images.githubusercontent.com/11810102/166158427-24de5f61-a3e6-48bc-b906-7c839ae386cd.png)

Though the buffer content itself is not corrupt, only the render is. I can copy and paste lines to other buffer and see they are correct 

![2022-05-01-210413_621x392_scrot](https://user-images.githubusercontent.com/11810102/166158719-afd0b3de-2193-4016-b057-7621a0c66096.png)

**Comment by lukas-reineke** [comment]
Your file is mixed indentation with spaces and tabs. And `shiftwidth` and `tabstop` are not set to the same value.

Either, format your file correctly (and also set `expandtab` if you want to use spaces, or `noexpandtab` if you want to use tabs), or at least set them to the same value.

**Comment by 010penetrator** [comment]
I understand it. But still when someone happens to have such not very sane settings, perhaps accidentally, he doesn't expect the text to be hidden.
