### ISSUE TITLE
Option to use locals.scm for highlighting the current context

### ISSUE THREAD

**Issue by minijackson** [lukas-reineke/indent-blankline.nvim#406]
Hello, and thanks for this amazing plugin, it works great!

I sometimes am editing files in a descriptive language, or a non-imperative/traditional language, where the default value `indent_blankline_context_patterns` doesn't apply well. I could modify it to satisfy my needs for each of those language, but I thought it would be nice if we could leverage the `locals.scm` queries, just as [treesitter-refactor does](https://github.com/nvim-treesitter/nvim-treesitter-refactor/blob/master/lua/nvim-treesitter-refactor/highlight_current_scope.lua). It would allow us to use queries managed and updated upstream, and maybe have more coherence with other treesitter tools.

Thanks again!

**Comment by lukas-reineke** [comment]
I like this :+1: 

I think some people will still prefer more granular control with pattern though. I'll probably add an option to switch between the two.

**Comment by lukas-reineke** [comment]
Version 2.18.0 now implements this with `use_treesitter_scope`
