### ISSUE TITLE
scripts when writing

### ISSUE THREAD

**Issue by Cris-lml007** [lukas-reineke/indent-blankline.nvim#407]
How can I get this removed:  
![image](https://user-images.githubusercontent.com/83845332/166803323-b8545421-f261-491f-bf5a-47f3a1f9b4fb.png)

it makes me very uncomfortable to see lines of scripts when I write.

**Comment by lukas-reineke** [comment]
You have trailing whitespace. Just remove the spaces, and the indent lines will also not show up.

**Comment by Cris-lml007** [comment]
> Tienes espacios en blanco finales. Simplemente retire los espacios y las líneas de sangría tampoco aparecerán.

I put the spaces to be able to show the scripts, what I want is to remove those scripts even if there are spaces, the truth is that they make me very uncomfortable and distracting when it comes to coding.

**Comment by lukas-reineke** [comment]
I don't understand. If you want them completely gone, why not uninstall the plugin?

**Comment by Cris-lml007** [comment]
> No entiendo. Si quieres que se vayan por completo, ¿por qué no desinstalar el complemento??

I do not want it to go completely, it is a great complement, it helps a lot, but when writing code moments I see that there is a script then I say: "I wrote badly?"and I realize it is the plugin. if you can't ok i can live with it :)

**Comment by lukas-reineke** [comment]
Then I still don't really understand what you want.

When do you not want to see them?

**Comment by Cris-lml007** [comment]
> Then I still don't really understand what you want.
> 
> When do you not want to see them?

Well, what I want is not to see them when it is in insert mode, I feel as if I am wrong to tapas but then when trying to delete I remember that it is the plugin, nothing more, because then the truth is a fantastic complement

**Comment by lukas-reineke** [comment]
Okay, I understand now :+1: 

There is no option for this, but you could overwrite the autogroup.

If you put this in your config _after_ loading indent-blankline, it should not update from insert mode anymore.
```vim
augroup IndentBlanklineAutogroup
    autocmd!
    autocmd OptionSet list,shiftwidth,tabstop,expandtab IndentBlanklineRefresh
    autocmd FileChangedShellPost,TextChanged,CompleteChanged,BufWinEnter,Filetype * IndentBlanklineRefresh
    autocmd WinScrolled * IndentBlanklineRefreshScroll
    autocmd ColorScheme * lua require("indent_blankline.utils").reset_highlights()
    autocmd VimEnter * lua require("indent_blankline").init()
augroup END
```

**Comment by Cris-lml007** [comment]
> Okay, I understand now +1
> 
> There is no option for this, but you could overwrite the autogroup.
> 
> If you put this in your config _after_ loading indent-blankline, it should not update from insert mode anymore.
> 
> ```viml
> augroup IndentBlanklineAutogroup
>     autocmd!
>     autocmd OptionSet list,shiftwidth,tabstop,expandtab IndentBlanklineRefresh
>     autocmd FileChangedShellPost,TextChanged,CompleteChanged,BufWinEnter,Filetype * IndentBlanklineRefresh
>     autocmd WinScrolled * IndentBlanklineRefreshScroll
>     autocmd ColorScheme * lua require("indent_blankline.utils").reset_highlights()
>     autocmd VimEnter * lua require("indent_blankline").init()
> augroup END
> ```

I put it at the end of my init.vim but there are no changes.

**Comment by lukas-reineke** [comment]
hm yeah.. I thought it would work, but it doesn't.
Sorry then, I don't think there is an easy way to do this, other than overwriting the autogroup directly in `plugin/indent_blankline.vim`

**Comment by Cris-lml007** [comment]
ok, also thank you very much for trying to help me
