### ISSUE TITLE
Custom background highlight doesn't work

### ISSUE THREAD

**Issue by NullVoxPopuli** [lukas-reineke/indent-blankline.nvim#408]
README says to:
```lua
vim.opt.termguicolors = true
vim.cmd [[highlight IndentBlanklineIndent1 guibg=#1f1f1f gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent2 guibg=#1a1a1a gui=nocombine]]

require("indent_blankline").setup {
    char = "",
    char_highlight_list = {
        "IndentBlanklineIndent1",
        "IndentBlanklineIndent2",
    },
    space_char_highlight_list = {
        "IndentBlanklineIndent1",
        "IndentBlanklineIndent2",
    },
    show_trailing_blankline_indent = false,
}
```

but:

![image](https://user-images.githubusercontent.com/199018/167034005-7803dda2-a573-4c66-a6b5-d143e277616b.png)

The only option I seem to have success with is `char`

**Comment by NullVoxPopuli** [comment]
same with the color demo? 
![image](https://user-images.githubusercontent.com/199018/167034943-48079d0e-ccda-404b-b2fd-0688d7e27294.png)

**Comment by NullVoxPopuli** [comment]
```
❯ nvim -v
NVIM v0.8.0-dev+95-g07660193a

```

**Comment by lukas-reineke** [comment]
Your config works fine for me. Maybe your highlight groups get overwritten or reset? This usually happens when you load your color scheme after setting them.
You can check with `:verbose highlight IndentBlanklineIndent1`
