### ISSUE TITLE
Visual Selection

### ISSUE THREAD

**Issue by lynndylanhurley** [lukas-reineke/indent-blankline.nvim#41]
### Expected behavior:

1. Visual selection should begin at start of line
2. Background of indent guide character should be transparent

This screenshot shows how the visual selection should look:
<img width="789" alt="Screen Shot 2021-02-22 at 12 17 12 PM" src="https://user-images.githubusercontent.com/468037/108773650-4c0b1800-7524-11eb-8407-02103fd255a6.png">

### Actual behavior:

This is how it looks:
<img width="790" alt="Screen Shot 2021-02-22 at 12 16 00 PM" src="https://user-images.githubusercontent.com/468037/108751435-d1cc9a80-7507-11eb-8fb9-6ee99e107ab1.png">

**Comment by lukas-reineke** [comment]
not something I can fix here, but I created an issue in Neovim https://github.com/neovim/neovim/issues/13994

**Comment by thallium** [comment]
Background of cursor line and some of "list chars" also get covered. Due to the same reason?

**Comment by lukas-reineke** [comment]
cursor line and color column is the same issue.

But list chars is not, what list chars are getting covered that you would like to see?

**Comment by thallium** [comment]
end of line.

**Comment by lukas-reineke** [comment]
I made a new issue for that https://github.com/lukas-reineke/indent-blankline.nvim/issues/49

**Comment by alnj** [comment]
I prefer the behavior on the second screenshot (being able to see indent lines while selecting).
However, on my desktop with the latest nvim release I get the behaviour from the first screenshot.

**Comment by lukas-reineke** [comment]
fixed by https://github.com/lukas-reineke/indent-blankline.nvim/pull/56

**Comment by GBeauregard** [comment]
@lukas-reineke I can't seem to get this working right on some color schemes. Do color schemes need to specifically support indent-blankline somehow to get the block highlight working?

f.ex. this doesn't work:
```vim
call plug#begin()
Plug 'lukas-reineke/indent-blankline.nvim'
Plug 'overcache/NeoSolarized'
call plug#end()
set termguicolors
syntax enable
set background=dark
colorscheme NeoSolarized
```
