### ISSUE TITLE
Disable indentation guides in diffview

### ISSUE THREAD

**Issue by Tummetott** [lukas-reineke/indent-blankline.nvim#413]
Hello, 

I'm using [this](https://github.com/sindrets/diffview.nvim) plugin for a better diff mode experience in nvim. The plugins has several hooks in order to change some buffer local settings when inside a diff view. I use the `diff_buf_win_enter` hook to disable line-wrap, listchars, relative numbers and I would also like to disable indentation guides.

```lua
require'diffview'.setup({
    hooks = {
       diff_buf_win_enter = function()

            -- Turn off line wrapping and list chars and relative numbers
            vim.opt_local.wrap = false
            vim.opt_local.list = false
            vim.opt_local.relativenumber = false

            -- Disable indentation guides
            require("indent_blankline.commands").disable()
        end,
    }
})
```

However, disabling the indentation guides is not working. The hook itself works and the disable command is executed. The plugin thinks that it's in state "disabled" but the indentation guides are still shown. I can verify this with the following: I have to execute`:IndentBlanklineToggle` twice in the local buffer in order to turn off the indent guides (first toggle to turn them on again, second to turn them off, but this time lines are actually hidden).

Could some explain me why this is not working?
Thanks x Tummetott

**Comment by lukas-reineke** [comment]
This should work, and it works for me when I run `:lua require("indent_blankline.commands").disable()` directly.
Not sure if diffview does anything special here, but I can't think of a reason why it wouldn't work.

**Comment by Tummetott** [comment]
yes it works when I run the command like you at the cmd prompt after opening a diffview. But it has no effekt when the command is executed within the hook ... I don't get it. I'll open a issue at the diffview repo

**Comment by lukas-reineke** [comment]
What [sindrets](https://github.com/sindrets) wrote makes sense. Can you try this PR and see if it fixes the problem?

https://github.com/lukas-reineke/indent-blankline.nvim/pull/415

**Comment by Tummetott** [comment]
Yep that solves the issue. Amazing!

**Comment by lukas-reineke** [comment]
:+1: I'll release it tomorrow

**Comment by lukas-reineke** [comment]
Sorry for the delay, I forgot about this :sweat_smile: 

It's released now
