### ISSUE TITLE
pressing { in a lua file in insert mode with TS enabled does not work

### ISSUE THREAD

**Issue by kimusan** [lukas-reineke/indent-blankline.nvim#414]
I was changing my lua config to add indent-blankline.nvim as plugin. After reloading the lines showed up just fine, BUT when I wanted to add another config and pressed {    (curley bracet - altgr-7 in my keyboard layout) it just moved to normal mode and moved the cursor to the front of the line. 

I tried disabling treesitter for the buffer, and then I could write { just fine. 

Since treesitter is normally working for me, I then disabled the indent-blankline   plugin instead, and now the problem was gone. 

My configuration is made like the one at the end of the readme where it shows how to get context from treesitter. 
Not sure why this happens, but it makes it quite impossible to use.

**Comment by kimusan** [comment]
It is mapped like this, but it seems to somehow conflict with your plugin. I cant explain it either. 

![image](https://user-images.githubusercontent.com/1150049/167890818-ef73963f-b8f9-44e2-bbe2-f560b0ceaed1.png)

**Comment by lukas-reineke** [comment]
I took a look at autopairs, but nothing stands out to me.
Can you try to make a minimal init.lua that reproduces the problem? It's hard to debug without.
