### ISSUE TITLE
Provide a configurable key to set minimum number of lines in indented block of code to draw the indent-guides

### ISSUE THREAD

**Issue by krishnakumarg1984** [lukas-reineke/indent-blankline.nvim#416]
Hi,

Thank you for developing this awesome plugin. I'd like to request an important feature.

Can `indent-blankline` provide a configurable key to set that there must be at least _x_ lines within an indented block, in order for a guide-line to be drawn for that particular indented block?

It is visually distracting (i.e. too cluttered/noisy) to have indent-guides drawn even with just a single line inside the indented block of code (example situations are 1: when you have just a 2-line C++ function, or  2: a single line packer config line for a plugin in `init.lua` etc.).

**Comment by lukas-reineke** [comment]
I don't really consider this an important feature. And to make this efficient would be pretty complex. The logic for this part is already not super straightforward, I'd like to avoid adding even more.

I won't work on this, sorry.

If someone makes a PR I might consider merging it, but I am not sure.

**Comment by krishnakumarg1984** [comment]
Thank you. To aid visibility for community uptake, would it be okay if I could ask for this issue to be left open with a `needs-help` or `won't-fix` label
