### ISSUE TITLE
[Question] The line extends further than it should

### ISSUE THREAD

**Issue by akim-13** [lukas-reineke/indent-blankline.nvim#417]
# Issue
I would like the line to only highlight the appropriate code blocks (*if statements, loops, etc*). Currently the indent line is displayed even between the statements which don't have indentation *(e.g. lines 96-98 below)*, however if a single space is inserted at the beginning, it starts to behave as expected. Is there a way to make this behaviour persistent without including a space in each blank line?
# Current behaviour
![indent_line_empty](https://user-images.githubusercontent.com/77539913/168298083-bbceb700-9b2f-4e45-8f14-a5c7e1cc2507.png)
# Desired behaviour
![indent_line_spaces](https://user-images.githubusercontent.com/77539913/168298080-8c7baefd-5e1e-4c23-8637-ddd59452c61c.png)
# Config
Here is my minimal [config file](https://github.com/akim-13/neovim/blob/master/lua/rc/indentline.lua).

**Comment by lukas-reineke** [comment]
You can turn this off with `:help g:indent_blankline_show_trailing_blankline_indent`

**Comment by akim-13** [comment]
Thank you! I was looking through the settings trying to find a solution, but somehow missed this one ¯\_(ツ)_/¯
