### ISSUE TITLE
Is able to add corner icon as nvim-tree do?

### ISSUE THREAD

**Issue by cstsunfu** [lukas-reineke/indent-blankline.nvim#419]
![image](https://user-images.githubusercontent.com/24812659/168659102-852edb79-0fca-425c-bbe6-ba52ce5cf732.png)

In nvim-tree.lua, we can set renderer.indent_markers.icons.conrer to change the indent line corner icon. Could this plugin provide this feature?
```
            renderer = {
                indent_markers = {
                    enable = true,
                    icons = {
                        corner = "└ ",
                        edge = "│ ",
                        none = "  ",
                    },
                }
            },

```

**Comment by lukas-reineke** [comment]
I am not against adding this, but this would be pretty difficult to do with the current logic.
If someone wants to make a PR I'd be happy to merge it.

**Comment by lukas-reineke** [comment]
Scope in v3 now supports both start and end

**Comment by konosubakonoakua** [comment]
> Scope in v3 now supports both start and end

I can only see highlights on start and end, can we custom the virtual text char like neo-tree now?

**Comment by MartenBE** [comment]
I am struggling with this also, is there an update on this?

**Comment by MartenBE** [comment]
Or @lukas-reineke if you could elaborate how you achieved this:

![Image](https://github.com/user-attachments/assets/29cfb2b9-5380-4e37-902e-b35800efe974)

That would also be greatly appreciated. I just get this, which looks "off":

![Image](https://github.com/user-attachments/assets/7485d01c-a132-41e8-bdc5-0aed8dab2fb3)
