### ISSUE TITLE
some thoughts/unexpected behavior

### ISSUE THREAD

**Issue by rudotriton** [lukas-reineke/indent-blankline.nvim#42]
I saw the reddit post and I've been playing around with it for a while now and I'm close to really liking it. I imagined I could replicate something that I had with indent rainbow in vscode:

![Screenshot 2021-02-22](https://user-images.githubusercontent.com/14181026/108766823-49c5af80-755e-11eb-9954-319ae9c4f034.png)

And I think the closest I can get is something like this?:

![Screenshot 2021-02-22](https://user-images.githubusercontent.com/14181026/108772081-3bc75d00-7565-11eb-8228-ac52b485059a.png)

---

![Screenshot 2021-02-22](https://user-images.githubusercontent.com/14181026/108771440-54834300-7564-11eb-9d83-64dd981120b6.png)

- I don't think I can turn off the `a`s on just the even/empty lines, because having them seems to be the selling point of this plugin. I don't mind them too much inside functions, but anywhere else, like line 15, it looks as if I have trailing whitespace there or a connection to something above even though it's a single function.
- there always seems to be a 3 wide void before the `let`. _I realized that setting a space in listchars fills it, but it also marks every other space._
- the first color group is 5 wide instead of 4?

Something else I noticed is that `indent_blankline_space_char_blankline_highlight_list` doesn't seem to have any effect. `indent_blankline_space_char_blankline_highlight` does work though.

I'm not sure how much customization you want to offer with this plugin, judging by the number of options available it looks like a good amount.

Other than that, I think you have a really nice plugin here

**Comment by lukas-reineke** [comment]
Very good points

I didn't think about highlighting and the empty last block and big first block.
It makes much more sense to create the indent [char, whitespace] now instead of [whitespace, char] like it was before.
I think I can fix all of your issues.

**Comment by lukas-reineke** [comment]
> indent_blankline_show_first_indent_levelindent_blankline_show_first_indent_level

this should be fixed now.

> I don't think I can turn off the as on just the even/empty lines

I removed indentation on empty lines that are not part of deeper indentation.
I also added `g:indent_blankline_show_first_indent_level` to turn of indent guides on the first column in all cases

> there always seems to be a 3 wide void before the let
this should be fixed now

> the first color group is 5 wide instead of 4?
this should be fixed as well

As a bonus, I added `g:indent_blankline_show_trailing_blankline_indent`
You can turn that off if you just want to use background highlights, they should all line up now

Thanks for the issue :rocket: let me know if anything else is not working

**Comment by rudotriton** [comment]
Amazing, I really like the changes and I can get it working exactly how I would like.

Some things I see, neither of which affect me, and ignore if something is intentional, but:

- if `g:indent_blankline_space_char_highlight_list` is set then its variation: `g:indent_blankline_space_char_blankline_highlight_list`, or non-list, won't overrule it and the colors set to be used on indent lines are also used for empty line. It's good for not having to set multiple variables, but by setting them, maybe you'd expect them to be considered.
- trailing colors are not in sync:

![Screenshot 2021-02-23](https://user-images.githubusercontent.com/14181026/108841682-d618b680-75e0-11eb-8853-77af71222688.png)

**Comment by lukas-reineke** [comment]
hm I can't reproduce the `g:indent_blankline_space_char_highlight_list` issue, if I set this.
```
let g:indent_blankline_space_char_highlight_list = ['DiffDelete', 'markdownFirstHeadline']
let g:indent_blankline_space_char_blankline_highlight_list = []
```

I get no highlight for the blank lines like I would expect.


For the out of sync bug, thank you. I pushed a fix now

**Comment by rudotriton** [comment]
The first one may have been my misunderstanding with something, I can't repro it either now.

The trailing indents are in sync now which is really sweet, however with `let g:indent_blankline_show_first_indent_level = v:false`, they lose their styling completely. Likely not intentional, maybe indexing something that is not in the list? Doesn't seem to depend on the list length though.

![Screen Shot 2021-02-25](https://user-images.githubusercontent.com/14181026/109073229-c55e6280-76fe-11eb-8a8d-b3e4d760fb1b.png)

![Screen Shot 2021-02-25](https://user-images.githubusercontent.com/14181026/109073285-d6a76f00-76fe-11eb-8740-da4747e094b5.png)

**Comment by lukas-reineke** [comment]
Good catch. When calculating the index I forgot that the first pair could be only whitespace.
So the index become a float.
Pushed a fix, thank you.

**Comment by rudotriton** [comment]
Amazing! I believe these issues are done now 👏
