### ISSUE TITLE
More accurate indentation

### ISSUE THREAD

**Issue by xbladesub** [lukas-reineke/indent-blankline.nvim#421]
Is there any way to not show indent between properties?
Example what I want (android studio):

<img width="1512" alt="Screen Shot 2022-05-20 at 9 51 02 PM" src="https://user-images.githubusercontent.com/45129790/169542900-2a723ae1-1f21-4bb9-b383-9214640a9a4e.png">

**Comment by lukas-reineke** [comment]
I think you are looking for `:help g:indent_blankline_show_trailing_blankline_indent`
