### ISSUE TITLE
Indent virtual text doesn't line up correctly in all neovim GUI

### ISSUE THREAD

**Issue by green726** [lukas-reineke/indent-blankline.nvim#422]
The indented line virtual text does not line up properly in neovim GUIs.

What happens (screenshot is in neovim-qt):
![neovim-qt not working properly](https://user-images.githubusercontent.com/59667714/169553427-d8993c30-63cc-4658-8c95-b77b76241881.png)

What it should be (terminal neovim):
![neovim working correctly](https://user-images.githubusercontent.com/59667714/169553488-1ae6b8e9-2aec-4120-8bc3-70dea91819c5.png)

I also tested this in goneovim, nvui, neovide, and nvim-gtk and had the same issue in all of them. 

This is on linux (endeavouros with gnome on wayland) but also occured on windows. My font is SpaceMono Nerd Font.
Below is my indent-blanline config

````lua
local indent_blankline_styles = {
	"│",
	"▏",
	"¦",
	"┆",
	"│",
	"⎸",
	"|",
}

vim.g.indent_blankline_char = indent_blankline_styles[1]

-- Disable indent-blankline on these pages.
vim.g.indent_blankline_filetype_exclude = {
	"help",
	"terminal",
	"dashboard",
	"paq",
	"lsp-installer",
	"lspinfo",
	"vista_kind",
	"alpha",
}
vim.g.indent_blankline_buftype_exclude = { "terminal" }

vim.g.indent_blankline_use_treesitter = true
vim.g.indent_blankline_show_trailing_blankline_indent = true
vim.g.indent_blankline_show_first_indent_level = true
-- vim.g.indent_blankline_context_char = indent_blankline_styles[1]
vim.cmd("autocmd CursorMoved * IndentBlanklineRefresh")

require("indent_blankline").setup({
	--show_current_context = true,
	--show_current_context_start = true,
})
````

EDIT: I reinstalled the jetbrainsmono nerd font from the AUR and now this issue is gone, but only with that font. I am guessing that this is an issue with the fonts and not this plugin?

**Comment by lukas-reineke** [comment]
Yes, this depends on the font you use.
Some terminals patch your font automatically to make this look better. That might be why the font works there.
