### ISSUE TITLE
Error when opening the first file: Invalid buffer id: 1

### ISSUE THREAD

**Issue by smartding** [lukas-reineke/indent-blankline.nvim#424]
The error happens when I open the first file from "kyazdani42/nvim-tree.lua" or "nvim-telescope/telescope.nvim" after launching neovim.

A dozen errors messages shows up, but indent-blankline still works. And the error doesn't happen later on when I open the second or third file.

```
Error executing vim.schedule lua callback: ...tart/indent-blankline.nvim/lua/indent_blankline/init.lua:652: Invalid buffer id: 1
stack traceback:
        [C]: in function 'nvim_buf_get_var'
        ...tart/indent-blankline.nvim/lua/indent_blankline/init.lua:652: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...tart/indent-blankline.nvim/lua/indent_blankline/init.lua:652: Invalid buffer id: 1
stack traceback:
        [C]: in function 'nvim_buf_get_var'
        ...tart/indent-blankline.nvim/lua/indent_blankline/init.lua:652: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...tart/indent-blankline.nvim/lua/indent_blankline/init.lua:652: Invalid buffer id: 1
stack traceback:
        [C]: in function 'nvim_buf_get_var'
        ...tart/indent-blankline.nvim/lua/indent_blankline/init.lua:652: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

The error doesn't happen when I open the first file with "e: path/to/file" or from recent files in "mhinz/vim-startify".

My Environment:

1. gentoo linux
2. neovim at commit: 9e1ee9fb1d7, somewhere after 0.7.0 tag
3. indent-blankline at latest commit:  9eda5143

**Comment by lukas-reineke** [comment]
Can you test if https://github.com/lukas-reineke/indent-blankline.nvim/pull/425 fixes this?

**Comment by smartding** [comment]
> Can you test if #425 fixes this?

Yes, it's fixed.
Thanks, that's really fast.

**Comment by mcmillion** [comment]
It looks like this is back? I'm on `42fe62e` and I'm seeing it again on 0.7.0

**Comment by smartding** [comment]
I'm getting the error again too.
The error message is: indent-blankline: Invalid buffer id: 1

**Comment by lukas-reineke** [comment]
Something else is causing the same error.
https://github.com/lukas-reineke/indent-blankline.nvim/issues/448

I think I'll just filter out that error.

**Comment by lukas-reineke** [comment]
Released a fix

**Comment by smartding** [comment]
> Released a fix

Just pulled the update, the issue is fixed
