### ISSUE TITLE
How to display the first icon of TAB and blankline at sametime

### ISSUE THREAD

**Issue by invokermoon** [lukas-reineke/indent-blankline.nvim#427]
Background:
My code style is to use spaces instead of tabs, so generally I make tabs highlighted or shown.
<img width="339" alt="image" src="https://user-images.githubusercontent.com/12377225/170566887-12a3536e-963a-4501-88a8-eaa4e5bc9406.png">

So i can see the TAB directly. And i can format this line;
But when I used the backline plugin, I found that no matter how I configured listchars, it couldn't meet my needs.
I'm stupid, please help me.

Here is my configuration, and what i wanted is that at same time:
I want to see the blankline in the code. 
And i can see TAB's first icon when there is a tab.

**-- option 2
vim.opt.termguicolors = true
vim.cmd [[highlight IndentBlanklineIndent1 guifg=#E06C75 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent2 guifg=#E5C07B gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent3 guifg=#98C379 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent4 guifg=#56B6C2 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent5 guifg=#61AFEF gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent6 guifg=#C678DD gui=nocombine]]

vim.opt.list = true
vim.opt.listchars = {
   tab = ">-",
   trail = "-",
   nbsp = "+",
}

require("indent_blankline").setup {
   space_char_blankline = " ",

   show_current_context = true,
   show_current_context_start = true,
}**

**Comment by lukas-reineke** [comment]
> And i can see TAB's _first_ icon when there is a tab.

You can't see the first tab icon, the indent line takes priority. But you can see the rest of the tab character, so you can still tell the difference.
This is with your configuration

![Screen Capture_select-area_20220527104326](https://user-images.githubusercontent.com/12900252/170612164-d9147f3d-305f-4f9a-ad1a-f650c4a4dbeb.png)

**Comment by lukas-reineke** [comment]
No sorry. I don't really see how this is useful, and it would require a lot of changes.
If your buffer is indented with only tabs, you would not see anything of this plugin.
If your buffer is indented with spaces, that option wouldn't change anything.
And if the buffer is mixed, you should just format it, so it is not mixed. If it is to show the places where it is mixed, the current solution does that already.
