### ISSUE TITLE
Is it possible to show lines per scope?

### ISSUE THREAD

**Issue by Nimmidev** [lukas-reineke/indent-blankline.nvim#428]
What i mean by that is the following:

![question](https://user-images.githubusercontent.com/21009721/171049404-adb8052d-2d9d-42e3-b580-e120361e2d40.png)

By default with only `show_first_indent_level` set to `false` the lines have gaps within a scope if the line is blank as seen in the first picture. 

If i set  `use_treesitter` to `true` the indentation of the blank line is now detected. But it has the indentation line one level deeper than i like as seen in the second picture at the top, two times in the middle and the bottom.

Is it somehow possible to have continuous lines such as with treesitter but with one indentation level less on blank lines.

My ideal scenario can be seen in picture three.

**Comment by lukas-reineke** [comment]
Can you share your whole config for the first picture? That should never happen.

To answer your question, you want to set `show_trailing_blankline_indent` to false

**Comment by Nimmidev** [comment]
While trying to get `show_current_context` working i stumbled over it again.
With the following config i get the blank line issue:

```
require("indent_blankline").setup {
    use_treesitter = true,
    use_treesitter_scope = true
}
```

**Comment by lukas-reineke** [comment]
I still can't reproduce it.

**Comment by Nimmidev** [comment]
Update: It seems that only `use_treesitter = true` is enough to cause this issue.

Maybe its not directly a problem with the plugin itself but rather with treesitter.

I am gonna investigate this further. It could also be that another plugin is causing issues.
Here are some additional infos that could be helpful:

NVim:
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
```

Plugins:
```
call plug#begin('~/.vim/plugged')

" lsp
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/lsp-status.nvim'

" cmp
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/cmp-cmdline'
Plug 'hrsh7th/nvim-cmp'

" luasnip snippet engine
Plug 'L3MON4D3/LuaSnip'
Plug 'saadparwaiz1/cmp_luasnip'

" theme/visuals
Plug 'mhartington/oceanic-next'
Plug 'kyazdani42/nvim-web-devicons'
Plug 'jackguo380/vim-lsp-cxx-highlight'
Plug 'lukas-reineke/indent-blankline.nvim'

" telescope
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-telescope/telescope-fzf-native.nvim'

" file type support
Plug 'udalov/kotlin-vim'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && npm install' }

" other
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'preservim/vimux'
Plug 'folke/trouble.nvim'

call plug#end()
```
