### ISSUE TITLE
show_current_context breaks indent display

### ISSUE THREAD

**Issue by NoXPhasma** [lukas-reineke/indent-blankline.nvim#429]
Whenever I enable `show_current_context` no indent line will be shown. The Plugin still displays whitespace though.

Version: NVIM v0.7.0

This is my config:
```
vim.opt.list = true
vim.opt.listchars:append("space:⋅")
vim.opt.termguicolors = true
vim.cmd[[highlight IndentBlanklineIndent1 guifg=#ff0000 gui=nocombine]]
require("indent_blankline").setup {
    space_char_blankline = " ",
    show_current_context = true,
    show_current_context_start = true,
}
```
![grafik](https://user-images.githubusercontent.com/7719590/171053571-146d5d6f-65d1-47f1-991b-8ae093909c07.png)

When disabled it works:
```
vim.opt.list = true
vim.opt.listchars:append("space:⋅")
vim.opt.termguicolors = true
vim.cmd[[highlight IndentBlanklineIndent1 guifg=#ff0000 gui=nocombine]]
require("indent_blankline").setup {
    space_char_blankline = " ",
    --show_current_context = true,
    show_current_context_start = true,
}
```
![grafik](https://user-images.githubusercontent.com/7719590/171053674-46475ffa-80aa-4543-b251-faa56f5b5ea6.png)

My complete config: https://gist.github.com/NoXPhasma/92ed107a4cdc91c433bb19b688b47491

**Comment by lukas-reineke** [comment]
I can't reproduce this.
Can you make a minimal init.lua and the steps to cause this?

**Comment by NoXPhasma** [comment]
I can reproduce it just with this small `init.lua`:

```lua
vim.cmd [[packadd vim-packager]]
require('packager').setup(function(packager)
  packager.add('lukas-reineke/indent-blankline.nvim')
end)

vim.opt.list = true
vim.opt.listchars:append("space:⋅")
vim.opt.termguicolors = true
vim.cmd[[highlight IndentBlanklineIndent1 guifg=#ff0000 gui=nocombine]]
require("indent_blankline").setup {
    space_char_blankline = " ",
    show_current_context = true,
    show_current_context_start = true,
}
```

**Comment by lukas-reineke** [comment]
I see. The current context feature requires https://github.com/nvim-treesitter/nvim-treesitter. It breaks if that is not installed.

I'll update the documentation to make this more clear, and also maybe add some logging instead of silently breaking.

**Comment by NoXPhasma** [comment]
Thank you, that fixed.
