### ISSUE TITLE
Weird behavior in multiline statements of c files

### ISSUE THREAD

**Issue by ratheesh** [lukas-reineke/indent-blankline.nvim#43]
With the latest NVIM head(`NVIM v0.5.0-dev+1108-g0450e155d`) and latest plugin, I observe weird behavior with the plugin for `C` filetypes

vim config
```vim
call plug#begin('~/.vim/plugged')

Plug 'lukas-reineke/indent-blankline.nvim', { 'branch': 'lua'  }

call plug#end()

filetype plugin indent on
filetype plugin on

let g:indent_blankline_char = '¦'
let g:indent_blankline_char_highlight = 'NonText'
let g:indent_blankline_extra_indent_level = -1
let g:indent_blankline_show_first_indent_level = 0
let g:indentLine_fileTypeExclude = ['help', 'chadtree', 'startify', 'fzf', 'tagbar']
```

Without plugin
![nvim_blankline_expected](https://user-images.githubusercontent.com/70958/108842991-1a677f00-7600-11eb-8adf-3f9304f018f6.jpg)

With Plugin
![nvim_blankline_issue](https://user-images.githubusercontent.com/70958/108843026-26ebd780-7600-11eb-9f5b-393bcdd535e0.jpg)

**Comment by lukas-reineke** [comment]
This is because you are mixing tabs and spaces for indentation

I don't write a lot of C, is that normal?
I'll have to think a bit about how to fix this

**Comment by ratheesh** [comment]
@lukas-reineke 
Setting 
```vim
let g:indent_blankline_strict_tabs = 1
```
does not work

**Comment by ratheesh** [comment]
This is working! Thank you.
