### ISSUE TITLE
Set highlight specific to an element defined in `context_patterns`

### ISSUE THREAD

**Issue by tobealive** [lukas-reineke/indent-blankline.nvim#435]
Is it possible to set a highlight color for the indent line which is specific to an element that is added to the  `context_patterns`?

E.g., when doing frontend, one won't come around to code some html here and there. For this I would like to keep the context_pattern `element` enabled (which is responsible for having the indent line highlighted in markup) but  have it in a less dominant color. 

I know an issue section is not a technical support corner just for asking questions. But going through the readme and options, not finding something on this, this issue might be more of a feature request than just a question.

**Comment by lukas-reineke** [comment]
There is an option for this `:help g:indent_blankline_context_pattern_highlight`

**Comment by tobealive** [comment]
Merci m8, works like a charm ❤️.

if one wants to have it 'lualized':
`vim.g.indent_blankline_context_pattern_highlight = { element = 'LineNr' }`

but lsp will probably scream at you when you are using it with a keyword like `function` instead of element

**Comment by lukas-reineke** [comment]
From lua you should pass the arguments to the setup function

```lua
require("indent_blankline").setup {
    context_pattern_highlight = {
        element = "LineNr",
    },
}
```

if you want to use `function`, you have to do it like this

```lua
require("indent_blankline").setup {
    context_pattern_highlight = {
        ["function"] = "LineNr",
    },
}
```
