### ISSUE TITLE
Showing context is broken if the scope is too long

### ISSUE THREAD

**Issue by rockyzhang24** [lukas-reineke/indent-blankline.nvim#436]
The minimal config is shown below
```lua
require("indent_blankline").setup {
  use_treesitter = true,
  show_current_context = true,
  show_current_context_start = false,
  use_treesitter_scope = true,
}
```

Then we use a lua file as an example. Define an empty function first. Then we continue to press <ENTER> key in INSERT mode in the function body to make it long enough, and in the meantime we can observe the highlight indent line showing the context is gone. If we `gg` to jump to the function signature, the indent line showing the context is highlighted as expected, however, if we `G` to jump to the end, the context line will not be highlighted, and even when we move cursor upward.

```lua
-- test.lua
local function test()
-- continue to press <ENTER> key
end
```

A short demo below.

https://user-images.githubusercontent.com/11582667/173172758-c900ed47-6cef-4242-ba1e-8d45b51f9985.mov

Thank you very much.

**Comment by lukas-reineke** [comment]
take a look at https://github.com/lukas-reineke/indent-blankline.nvim/issues/374#issuecomment-1071929850

**Comment by rockyzhang24** [comment]
Great. I went through the issues but didn't find it. Thank you so much.
