### ISSUE TITLE
Indent not working

### ISSUE THREAD

**Issue by alessiorapisarda** [lukas-reineke/indent-blankline.nvim#438]
Hello, I recently updated Neovim after not using it for a while and I noticed that the indents from this plugin are not working

![Screenshot from 2022-06-13 11-01-05](https://user-images.githubusercontent.com/46760131/173319513-4a85e51c-2740-4a1c-a075-e07e9f547a10.png)

What could be the issue? At first treesitter was not installed but after installing it the situation has not changed.

**Comment by lukas-reineke** [comment]
what is `shiftwidth` set to?

**Comment by alessiorapisarda** [comment]
> what is `shiftwidth` set to?

It is not set, but I tried to set it to 2 and nothing has changed

**Comment by alessiorapisarda** [comment]
I've also tried removing almost every plugin I had but still with no luck
![Screenshot from 2022-06-14 11-58-02](https://user-images.githubusercontent.com/46760131/173550579-90af2dcd-13ae-4a73-86d7-5fe43c2b2aa5.png)

These are my settings:

`local set = vim.opt
set.fileencoding = "utf-8"
set.incsearch = true
set.hlsearch = true
set.ignorecase = true
set.smartcase = true
set.number = true
set.relativenumber = false
set.hidden = true
set.cursorline = true
set.confirm = true
set.showmode = false
set.showcmd = true
set.cmdheight = 1
set.laststatus = 3
set.timeoutlen = 300
set.updatetime = 300
set.scrolloff = 2
set.mouse = "a"
set.clipboard = "unnamedplus"
set.swapfile = false
set.undofile = true
set.backup = false
set.wrap = false
set.splitbelow = true
set.splitright = true
set.wrap = false
set.termguicolors = true
set.smartindent = true
set.completeopt = { "menuone", "noselect" }
set.signcolumn = "yes"

vim.g.do_filetype_lua = 1 -- use filetype.lua
vim.g.did_load_filetypes = 0 -- don't use filetype.vim`
