### ISSUE TITLE
Jumping the cursor to CurrentContextStart

### ISSUE THREAD

**Issue by siduck** [lukas-reineke/indent-blankline.nvim#439]
Hi, is there a way through pressing a mapping will get me on the CurrentContextStart

![image](https://user-images.githubusercontent.com/59060246/174066780-beb07706-0d1c-4bca-9ed9-ed3d3d9d3999.png)

For example the cursor's below and in the scope of the vim.api... stuff then I press a mapping and the cursor jumps to the CurrentContextStart

**Comment by lukas-reineke** [comment]
I don't want to add any keymaps to the plugin, but you can make this pretty easily.

```lua
vim.keymap.set("n", "<space>i", function()
    local ok, start = require("indent_blankline.utils").get_current_context(
        vim.g.indent_blankline_context_patterns,
        vim.g.indent_blankline_use_treesitter_scope
    )
    if not ok then
        return
    end
    vim.api.nvim_win_set_cursor(vim.api.nvim_get_current_win(), { start, 0 })
    vim.cmd [[normal! _]]
end)
```

**Comment by siduck** [comment]
thx it works good!

**Comment by evertonse** [comment]
> I don't want to add any keymaps to the plugin, but you can make this pretty easily.
> 
> ```lua
> vim.keymap.set("n", "<space>i", function()
>     local ok, start = require("indent_blankline.utils").get_current_context(
>         vim.g.indent_blankline_context_patterns,
>         vim.g.indent_blankline_use_treesitter_scope
>     )
>     if not ok then
>         return
>     end
>     vim.api.nvim_win_set_cursor(vim.api.nvim_get_current_win(), { start, 0 })
>     vim.cmd [[normal! _]]
> end)
> ```

Is there any way to do this on current version of indent-blankline?

**Comment by lukas-reineke** [comment]
Yeah you can still do this

```lua
vim.keymap.set("n", "<space>i", function()
    local bufnr = vim.api.nvim_get_current_buf()
    local config = require("ibl.config").get_config(bufnr)
    local scope = require("ibl.scope").get(bufnr, config)
    if scope then
        local row, column = scope:start()
        vim.api.nvim_win_set_cursor(vim.api.nvim_get_current_win(), { row + 1, column })
    end
end)
```
