### ISSUE TITLE
indent guides cover text

### ISSUE THREAD

**Issue by lukas-reineke** [lukas-reineke/indent-blankline.nvim#44]
Platform: MacOS
Nvim: `NVIM v0.5.0-dev+nightly-45-g9d5f84280` or `NVIM v0.5.0-dev+nightly-46-g0450e155d`
init.vim:
```
call plug#begin('~/.local/share/nvim/plugged')
" Plug 'Yggdroot/indentLine'
Plug 'lukas-reineke/indent-blankline.nvim', {'branch': 'lua' }
call plug#end()
```
![Screenshot 2021-02-23 at 10 26 52](https://user-images.githubusercontent.com/12573521/108831133-a60deb00-75c1-11eb-95b8-8adea36d6662.png)

_Originally posted by @lkhphuc in https://github.com/lukas-reineke/indent-blankline.nvim/issues/39#issuecomment-784097844_

**Comment by lukas-reineke** [comment]
can you please also share the text you edit.
And make sure you are on the latest version of the plugin, I fixed a couple issues

**Comment by lkhphuc** [comment]
Thanks. Conceal doesn't cover text anymore.
But I don't know why conceal doesn't work on non-blank line like this.
All default setting and I just open the help file.
![Screenshot 2021-02-23 at 15 25 28](https://user-images.githubusercontent.com/12573521/108865662-5d6b2780-75eb-11eb-9f8c-72a3d437f154.png)

**Comment by Cold-Oats** [comment]
Are you using the lua branch of indent-blankline? 

To use the lua branch with vim plug, use: 

    Plug 'lukas-reineke/indent-blankline.nvim', {'branch': 'lua'}

**Comment by lukas-reineke** [comment]
Sorry I can't reproduce that.
Do you have anything else in your init.vim?

**Comment by lkhphuc** [comment]
Thank you, that was a problem with Vim-plug. Everything's fine now, you can close this one.
