### ISSUE TITLE
[Feature] Make indent line priority configurable

### ISSUE THREAD

**Issue by akinsho** [lukas-reineke/indent-blankline.nvim#441]
Hi,

I recently started using `nvim-ufo` a folding/fold-relate plugin that adds extmarks to folds and overlays text on the folded line, so it appears like a normal syntax highlighted line. This unfortunately clashes with this plugin, as this plugin has the indent line extmark priority set quite low, so they are overridden. See https://github.com/kevinhwang91/nvim-ufo/issues/19 where the exact lines were identified where a configurable priority would need to go then a user could bump this up, so it works well for this use case.

**Comment by lukas-reineke** [comment]
Made a PR

I want to merge #431, and implement #430 for the next release as well, but you can start using that branch.
I'll probably release it sometime this week

**Comment by akinsho** [comment]
Just switched over to the PR branch, and it works like a charm, thanks @lukas-reineke 👍🏿

**Comment by MariaSolOs** [comment]
I'm now having a similar issue with [Copilot](https://github.com/zbirenbaum/copilot.lua/issues/191) 😿. I know that this isn't this plugin's fault, but @lukas-reineke do you know if there's something I can configure in `indent-blankline` to fix the issue?
