### ISSUE TITLE
Unable to get the plugin indent-blankline to work

### ISSUE THREAD

**Issue by lcheylus** [lukas-reineke/indent-blankline.nvim#443]
Neovim v0.7.0 on Debian Linux testing/amd64 with [packer](https://github.com/wbthomason/packer.nvim) to manage plugins.

I try to setup and configure ident-blankline plugin with my configuration but impossible to have it functionnal : the indentation chars (`|` by default) are never displayed (tests with C, Go, Lua and Python files).

In a first try, I try a simple setup with `packer` : 
`use { 'lukas-reineke/indent-blankline.nvim', config = require('indent_blankline').setup() }`

I tried too configuration with or without `treesitter` plugin => same issue. Same if I use a more complete configuration : 
```
require('indent_blankline').setup({
  enabled = true,
  char = '▏',
  context_char = '▏',
  show_first_indent_level = true,
  show_current_context = true,
  show_current_context_start = true
})
```

Please, could you help me to find what is the source of this issue ? I would really like to use your plugin with my Neovim configuration.

**Comment by lcheylus** [comment]
Yes, the plugin is installed correctly, verified with `:PackerStatus`. Retry several times by removing then reinstalling it.

Nothing happens if I run command like `:IndentBlanklineEnable` or _:IndentBlanklineToggle_

**Comment by lukas-reineke** [comment]
Can you share your whole config?

**Comment by lcheylus** [comment]
A simple Neovim configuration in Lua to reproduce my issue (`init.lua` and `lua/plugins.lua` for Packer) : https://gist.github.com/lcheylus/18e6b305711c71ba1fdc5bd1885e4fab

**Comment by lcheylus** [comment]
After some tests and debug, I fix this issue : Neovim (version 0.7.0) must be compiled with LuaJIT for your plugin to work correctly.

I used a version of Neovim 0.7.0 without LuaJIT (only Lua 5.1) and in this case, the IndentBlankline plugin does not work => no char displayed for indentation.

**Comment by lukas-reineke** [comment]
Right, that makes sense.
LuaJIT is required. I'll add this to the documentation.

**Comment by lcheylus** [comment]
OK, I changed the title of my issue accordingly.
