### ISSUE TITLE
Feature idea-Link indent level chars to chars from text in buffer

### ISSUE THREAD

**Issue by McAuleyPenney** [lukas-reineke/indent-blankline.nvim#45]
Big fan of indent-blankline, thank you for what you've made!

Just wanted to throw this out there as an idea, not trying to make a pushy demand.

I like indent guides for coding. I'd like to be able to link the indent guide characters that indent-blanklike provides to specific types of indenting. In the photo that I've included, there are indent guides placed inside of the comment block, between two lines that do not share brackets (the array initialization and the example comment underneath it, and in the line underneath the example array initialization, where I've created a sloppy example of indentation that one might use when a list of parameters are too long for one line. 

What Id like to be able to do is produce indent guides only between certain characters, such as curly braces for example.

Again, just throwing that out there! Thanks for reading!

![example](https://user-images.githubusercontent.com/59481467/108872548-8376d480-75b7-11eb-9215-c252a22ee530.png)

**Comment by lukas-reineke** [comment]
Interesting idea, but that would be pretty complicated to do.
I'll think about it!

You can get something similar now if you use tabs for indentation and spaces for the alignment.
I added an option `g:indent_blankline_strict_tabs`, if you turn that on, if there is a tab in a line, only tabs are used to calculate the indentation level.
Would look something like this

![Screen Capture_select-area_20210224115546](https://user-images.githubusercontent.com/12900252/108941022-ac6e9680-7697-11eb-8909-4ff58042f2d0.png)

All indentation is tabs, but the wrapped `"example"` is aligned with spaces

**Comment by McAuleyPenney** [comment]
I had an idea about about this. Would it be possible to extend the plugins ability to recognize context to the placement of guides? I personally dislike having guides for functions and methods but really enjoy them for conditionals and loops, as examples.

**Comment by lukas-reineke** [comment]
While possible, I won't add that.
It would be a lot of work, and I don't think a lot of people would use it.
