### ISSUE TITLE
Question: keep indentline continuous on empty lines

### ISSUE THREAD

**Issue by kishikaisei** [lukas-reineke/indent-blankline.nvim#450]
I would like to know if it is possible to have the indentline continuous even on empty lines, not as seen in the screenshot:
![image](https://user-images.githubusercontent.com/1894123/176306745-173f3796-57a3-45b9-b6c6-7a87a567cc3d.png)

**Comment by lukas-reineke** [comment]
That should not happen. Can you share your config?

**Comment by kishikaisei** [comment]
Sure, this is my config: https://gitlab.com/kishikaisei/nvim
This is the indentline part: https://gitlab.com/kishikaisei/nvim/-/blob/master/lua/user/config/indentline.lua
And this is where I used to have the listchar: https://gitlab.com/kishikaisei/nvim/-/blob/master/lua/user/options.lua

**Comment by lukas-reineke** [comment]
Can you try setting `use_treesitter` to false?

**Comment by kishikaisei** [comment]
Without the use of treesitter, it is better:
![image](https://user-images.githubusercontent.com/1894123/176370449-ae31c4d6-2401-4673-aa37-f792a89b8142.png)

**Comment by lukas-reineke** [comment]
Yeah then this is a problem with the treesitter grammar for the language you are using.
Treesitter thinks there should be no indentation.

I don't really recommend using treesitter for this. Sometimes it works okay, but for the most part the built-in algorithm does a better job.

For the end of line characters you still have, you explicitly turn those on with `show_end_of_line`. Set that to false if you don't want them.
