### ISSUE TITLE
Request: add `listchars` to `OptionSet` autocmd

### ISSUE THREAD

**Issue by qubidt** [lukas-reineke/indent-blankline.nvim#452]
Currently, `OptionSet list` has an autocmd to refresh the plugin but `OptionSet listchars` does not: 

https://github.com/lukas-reineke/indent-blankline.nvim/blob/4a58fe6e9854ccfe6c6b0f59abb7cb8301e23025/plugin/indent_blankline.vim#L33-L35

Causing the UI to appear, until the cursor is moved, as if `set listchars=...` had not completed. Could `listchars` be added as an option that triggers the refresh?

**Comment by lukas-reineke** [comment]
I'll add this in the next release

**Comment by lukas-reineke** [comment]
Fixed in https://github.com/lukas-reineke/indent-blankline.nvim/releases/tag/v2.20.0
