### ISSUE TITLE
 highlighted Current_Context_Start moves the indentline a little bit 

### ISSUE THREAD

**Issue by siduck** [lukas-reineke/indent-blankline.nvim#454]
The indentline looks normal now 

![image](https://user-images.githubusercontent.com/59060246/178492856-be3611bd-d379-43f3-8748-65dcee1312f9.png)

But when the cursor goes into some scope + ContextStart gets highlighted then the indentline moves a lil towards right

![image](https://user-images.githubusercontent.com/59060246/178493105-765746d9-bed5-44c9-9b0d-4173991247ea.png)

**Comment by lukas-reineke** [comment]
By default, it uses the same unicode character for the normal indent char and the content indent char.
Did you set a different character? Or maybe the highlight group you use for the context indent char is bold or italic?
