### ISSUE TITLE
How to change indent line?

### ISSUE THREAD

**Issue by vanarok** [lukas-reineke/indent-blankline.nvim#458]
![2022-07-13T22:31:20,117225126+04:00](https://user-images.githubusercontent.com/6105977/178805745-da0ace9e-989b-4daf-964a-95e2b1b4b040.png)

**Comment by lukas-reineke** [comment]
It should be 

```lua
require("indent_blankline").setup {
    char = "|",
}
```

All configuration options are the same in vimscript and lua, lua just does not have the `indent_blankline_` prefix. So it would be `indent_blankline_foo` in vimscript, and `foo` in lua.
