### ISSUE TITLE
Setting `IndentBlanklineContextStart` Color

### ISSUE THREAD

**Issue by johnallen3d** [lukas-reineke/indent-blankline.nvim#459]
I'm trying out the new underline setting in `kitty` (thanks to [this post](https://www.reddit.com/r/neovim/comments/w500vi/kitty_nightly_now_has_a_modify_font_option/) for the heads up).  🤘

I'm struggling with setting the underline color though (I'd like it to match the indent line color).

<img width="750" alt="CleanShot 2022-07-23 at 14 11 00@2x" src="https://user-images.githubusercontent.com/184915/180617685-c69d837c-2a8b-4fbc-b8aa-94a76e6a9e13.png">

Here's the configuration I've tried

```lua
vim.cmd([[highlight IndentBlanklineContextStart guifg=#F5C2E7 gui=underline]])

require("indent_blankline").setup({
	space_char_blankline = " ",
	show_current_context = true,
	show_current_context_start = true,
})
```

In case it matters I'm using the [Catppuccin colorscheme](https://github.com/catppuccin/nvim) which [doesn't appear to set this  highlight](https://github.com/catppuccin/nvim/blob/4f88948b7b5c160908b4e4e90befd45d01d96e64/lua/catppuccin/groups/integrations/indent_blankline.lua#L9).

**Comment by lukas-reineke** [comment]
To set the color of the underline you need to use `guisp` instead of `guifg`
`:help highlight-guisp`

**Comment by johnallen3d** [comment]
Thanks @lukas-reineke, setting `guisp` (🤦‍♂️) _after_ loading my colorscheme did the trick.

Thanks for the great plugin!
