### ISSUE TITLE
No indent on blank line if `show_first_indent_level = v:false`

### ISSUE THREAD

**Issue by lkhphuc** [lukas-reineke/indent-blankline.nvim#46]
On branch `lua`.
![Screenshot 2021-02-24 at 10 24 53](https://user-images.githubusercontent.com/12573521/108986881-8a224c00-768a-11eb-9138-e5956a4b3ca8.png)
![Screenshot 2021-02-24 at 10 25 36](https://user-images.githubusercontent.com/12573521/108986953-a32afd00-768a-11eb-820f-b262a4a740e5.png)

**Comment by lukas-reineke** [comment]
Sorry, can't reproduce this one either.
Does it happen with no other config?
Also can you paste the text you are editing

**Comment by lkhphuc** [comment]
Sorry just pull the lastest update and somehow it's working now. I tested yesterday with a minimal config.
