### ISSUE TITLE
How do I integrate with other plugins (nvim-ufo)?

### ISSUE THREAD

**Issue by B4mbus** [lukas-reineke/indent-blankline.nvim#465]
I use nvim-ufo to get nicer folds, but indent-blankline doesn't work inside it.
![image](https://user-images.githubusercontent.com/75364377/183108992-bc4688fe-372a-4277-8568-5367de093c0e.png)

Here's my config
```lua
require 'indent_blankline'.setup {
  space_char_blankline = ' ',
  show_current_context = true,
  show_current_context_start = true,
}
```

**Comment by lukas-reineke** [comment]
The ufo preview window is not a real buffer with filetype. It is just the section of the fold with applied highlight.
indent-blankline by default does not run on buffers without filetype.

You can force it to run with a function like this.

```lua
function()
    local winid = require("ufo").peekFoldedLinesUnderCursor()
    local bufnr = vim.api.nvim_win_get_buf(winid)
    vim.api.nvim_buf_set_var(bufnr, "indent_blankline_enabled", true)
    require("indent_blankline.commands").refresh(true)
end
```
