### ISSUE TITLE
Is able to set highlight color of indent line of current context according to indent level?

### ISSUE THREAD

**Issue by doubleChu** [lukas-reineke/indent-blankline.nvim#467]
After 'highlight IndentBlanklineContextChar' is set, the color of context indent line is always the same, can I set a highlight group to make it highlight the indent line based on the indent level? 
Just like what `indent_blankline_char_highlight_list` does, but only highlights the indent line of the current context, and the color can vary.

**Comment by lukas-reineke** [comment]
Sorry, this is currently not supported.

It shouldn't be too hard, I'll consider adding this in the future.

**Comment by otherJL0** [comment]
Had the same question, thanks for clarifying!

**Comment by antoniotrkdz** [comment]
I would also make use of this feature! Thank you!

**Comment by nfwyst** [comment]
im waiting for this feature, thanks!

**Comment by lukas-reineke** [comment]
This is now supported in version 3
