### ISSUE TITLE
Conflict with LuaSnip

### ISSUE THREAD

**Issue by matthewsia98** [lukas-reineke/indent-blankline.nvim#468]
Indent line draws over text from LuaSnip in Insert mode.
Happens regardless of  whether use_treesitter is true or false.

Insert Mode
![image](https://user-images.githubusercontent.com/71731492/184467806-89ad271b-da30-4479-b15c-186dbd242658.png)

Normal Mode
![image](https://user-images.githubusercontent.com/71731492/184467762-a64d6500-4e8b-4ef4-a640-325f1858c401.png)

**Comment by lukas-reineke** [comment]
Can you share the snippet to cause this please

**Comment by matthewsia98** [comment]
Here is the snippet. This only happens with single characters. As soon as you type the second character, the problem disappears.

![image](https://user-images.githubusercontent.com/71731492/184563372-07728848-4f5a-4a34-a230-8ffcb17f1cad.png)

![image](https://user-images.githubusercontent.com/71731492/184563530-e7a660cc-5004-4ab7-9984-564d989aa8db.png)

**Comment by lukas-reineke** [comment]
Please post the actual code, not a screenshot

**Comment by matthewsia98** [comment]
```
local ls = require('luasnip')
local s = ls.s
local i = ls.insert_node
local t = ls.text_node
local c = ls.choice_node
local f = ls.function_node
local d = ls.dynamic_node
local sn = ls.sn
local rep = require('luasnip.extras').rep
local fmt = require('luasnip.extras.fmt').fmt


return {
    s('rep', fmt([[
        Input: {}
            {} Repeat 1
            {} Repeat 2
        ]],
        {
            i(1),
            rep(1),
            rep(1)
        })
    ),
}
```

**Comment by lukas-reineke** [comment]
I can't reproduce this. It works fine for me.

https://user-images.githubusercontent.com/12900252/184568807-b965cdbe-470c-4363-b70b-e334d34aeef2.mp4

**Comment by matthewsia98** [comment]
Sorry, figured it out.
I had to disable treesitter indentation.
Everything works fine now.
