### ISSUE TITLE
Incorrect lines in C

### ISSUE THREAD

**Issue by r4v10l1** [lukas-reineke/indent-blankline.nvim#469]
When editing a header file the lines seem incorrect. I am not sure if it is supposed to be like this or if there is a setting. I am using the default configuration.

![image](https://user-images.githubusercontent.com/29655971/184476307-45d093fd-dd6a-4fe2-835e-911eff93936e.png)

When using `Yggdroot/indentLine` (The only thing missing on this plugin, like many other people said, is a line at line 70):

![image](https://user-images.githubusercontent.com/29655971/184476354-6bf09418-c9b5-4e42-8e41-0d8ae06925b8.png)

Sorry if this has been asked before.

**Comment by lukas-reineke** [comment]
This is an option `:help g:indent_blankline_show_trailing_blankline_indent`

**Comment by anthony-S93** [comment]
@r4v10l1 
This can be resolved. I can confirm this. You need to do two things: 1) set `indent_blankline_show_trailing_blankline_indent = false` 2) Make sure you do **not** use tree-sitter.  If you set `use_treesitter = true` in your config file, then you need to comment that line out.

**Comment by r4v10l1** [comment]
It works perfectly now. Thank you. 👍🏻 

![image](https://user-images.githubusercontent.com/29655971/184682894-02d37123-bc15-49d3-a326-01a98924c9d0.png)
