### ISSUE TITLE
Indent lines are not showing

### ISSUE THREAD

**Issue by jlbas** [lukas-reineke/indent-blankline.nvim#47]
After installing from the lua branch, I am unable to see any indent lines. I was previously using  Yggdroot/indentLine, but removed it before installing indent-blankline.nvim. Running the commands have no effect (Disable/Enable/Refresh/Toggle). Currently on nvim v0.5.0-dev+1102-g595f6e4d6.

![no_indent_lines](https://user-images.githubusercontent.com/35406425/109015844-8dfea000-7683-11eb-86b2-608b0a8c4264.png)

**Comment by wren** [comment]
I'm having the same problem on `NVIM v0.5.0-dev+971e0ca90`.

Uninstalled both plugins, commenting out all related settings, put indent-blankline back, and still nothing.

**Comment by jlbas** [comment]
Just updated to nvim v0.5.0-dev+1109-g6b7cc45c4 and the plugin is working as intended.

![indent_lines](https://user-images.githubusercontent.com/35406425/109062565-17c76100-76b6-11eb-8272-8658909f79dd.png)
