### ISSUE TITLE
The identation lines go over the CursorLine color and I have random things at the side

### ISSUE THREAD

**Issue by diniamo** [lukas-reineke/indent-blankline.nvim#471]
I hope it doesn't need further explanation:
![image](https://user-images.githubusercontent.com/55629891/185075760-b0149617-4fb0-420d-8b28-4dc86394ba98.png)

I don't know what else I'm supposed to set, this is what I have for the cursorline config:
```lua
o.cursorline = true
vim.cmd('hi CursorLine guibg=#0c1012 gui=nocombine')
```

My other issue is these numbers, and lines appearing the on left side of the editor:
![image](https://user-images.githubusercontent.com/55629891/185091177-bec68149-7114-42d9-802b-aed649a54a5c.png)

**Comment by lukas-reineke** [comment]
Do you just want to fix the indent line background color overwriting the cursorline color, or do you not want to see indent lines at all for the curent line?

The numbers on the side is because of `:help 'foldcolumn'`, that is unrelated to indent-blankline

**Comment by diniamo** [comment]
I want to fix the indent line background color.

Oh huh, I should have realized, thank you.

**Comment by diniamo** [comment]
Do I not need the `gui=nocombine` thing?

**Comment by lukas-reineke** [comment]
You do need it. But if you just update the highlight group to remove the background, it should already be set.
It depends in what order things are happening.

To be save, you can also just set everything like in the doc example.

**Comment by diniamo** [comment]
Hmm okay, thank you very much, I managed to fix it.
