### ISSUE TITLE
How do I show indent lines instead of eol?

### ISSUE THREAD

**Issue by UtkarshVerma** [lukas-reineke/indent-blankline.nvim#476]
![image](https://user-images.githubusercontent.com/31820255/187184727-82b1c29d-bdc8-4ae6-998e-a9ecdbb7ce33.png)

On empty lines, I want to avoid showing the eol character as it breaks the guidelines. Can this be done?

**Comment by lukas-reineke** [comment]
They are not shown by default. Have you turned them on with `:help g:indent_blankline_show_end_of_line`?

**Comment by UtkarshVerma** [comment]
Yeah, it was enabled. Thanks for pointing it out. It works as expected after disabling.
