### ISSUE TITLE
What font do you use for the demo?

### ISSUE THREAD

**Issue by nappalm** [lukas-reineke/indent-blankline.nvim#477]
![image](https://user-images.githubusercontent.com/35016608/187814922-24557851-371b-4aa0-a113-230db1e67eac.png)

**Comment by lukas-reineke** [comment]
There are 3 different fonts in this screenshot.

Normal and bold are Fira Code.
Italic is Hasklig. (in green)
Bold italic is Input Mono Condensed. (in orange)
