### ISSUE TITLE
Missing Indent Lines Between Curly Braces.

### ISSUE THREAD

**Issue by anthony-S93** [lukas-reineke/indent-blankline.nvim#479]
![Screenshot_2022-09-03_02-51-51](https://user-images.githubusercontent.com/69449791/188218977-dd779f0e-f3a1-415a-b47e-78fc9af64f5a.jpg)

The indent lines seem to only appear between the space delimited by two braces. 

For languages that don't require braces to define blocks, the plugin works just fine. Here is some sample python code: 

![Screenshot_2022-09-03_02-53-30](https://user-images.githubusercontent.com/69449791/188219209-a3087622-3309-4f11-b92a-cbb99f167bb7.jpg)

To make sure that it's not some other plugin messing with the indents, I went ahead and set up a completely clean copy of neovim with the following minimal config: 

`init.lua`:
```lua
vim.opt.number = true
vim.opt.syntax = 'on'
vim.opt.mouse = 'a'

require("plugins")
```

`plugins.lua`:

```lua
--Plugin management

local packer = require('packer')
local plugins = packer.startup({
    function()
        local use  = packer.use
        use "wbthomason/packer.nvim"

        use
        {
            "lukas-reineke/indent-blankline.nvim",
            config = function()
                require("indent_blankline").setup({
                    show_trailing_blankline_indent = false,
                })
            end,
        }
    end,
    config = { --Packer.nvim's config
        display = {
            open_fn = require('packer.util').float,
        },
    }
})
return plugins
```
The result is pretty much the same: 

![Screenshot_2022-09-03_03-43-55](https://user-images.githubusercontent.com/69449791/188226547-0477184d-1182-41e1-98a6-cdedda15307c.jpg)

The problem only occurred when braces are involved. Without braces, everything worked just fine. Here's some python code: 

![Screenshot_2022-09-03_03-51-34](https://user-images.githubusercontent.com/69449791/188226876-bd19945c-c6a9-46c5-aa13-f09d848658fc.jpg)

**Comment by lukas-reineke** [comment]
You have to set `shiftwidth` for spaces, and `tabstop` for tabs.

**Comment by anthony-S93** [comment]
It turns out that I accidentally removed `vim.opt.expandtab` setting when I switched over from `init.vim` to `init.lua`
