### ISSUE TITLE
Is there any options can change `│` to another char like `¦` ?

### ISSUE THREAD

**Issue by NEX-S** [lukas-reineke/indent-blankline.nvim#480]
https://github.com/lukas-reineke/indent-blankline.nvim/blob/db7cbcb40cc00fc5d6074d7569fb37197705e7f6/lua/indent_blankline/init.lua#L27

**Comment by lukas-reineke** [comment]
It will effect the context char as well, unless that is explicitly set with `:help vim.g.indent_blankline_context_char`
