### ISSUE TITLE
How to achieve the effect in the image diagram

### ISSUE THREAD

**Issue by joeleemacus** [lukas-reineke/indent-blankline.nvim#481]
<img width="136" alt="2022-09-22_17-36" src="https://user-images.githubusercontent.com/71259902/191714222-b095d011-9aff-4adb-b68e-1d3808d7f3b6.png">
like this, i try to edit the "char = {'─', '─', '╭', '│', '╰', '─', '>'}", but it didn't work

**Comment by lukas-reineke** [comment]
There is currently no way to do this, that screenshot is not indent-blankline

There is a ticket #419 that is kind of this? I might add this in the next version

**Comment by louisrc3ys** [comment]
> 
yeah i know, that's other plugin, but it some defects, I just like this display way, thanks! I'll be be continuing attention>

**Comment by shellRaining** [comment]
> > 
> 
> yeah i know, that's other plugin, but it some defects, I just like this display way, thanks! I'll be be continuing attention>

the plugin [hlchunk.nvim](https://github.com/shellRaining/hlchunk.nvim) and [nvim-hlchunk](https://github.com/yaocccc/nvim-hlchunk)  have this feature

**Comment by xanmodlouis** [comment]
> > > 
> 
> > 
> 
> > yeah i know, that's other plugin, but it some defects, I just like this display way, thanks! I'll be be continuing attention>
> 
> 
> 
> the plugin [hlchunk.nvim](https://github.com/shellRaining/hlchunk.nvim) and [nvim-hlchunk](https://github.com/yaocccc/nvim-hlchunk)  have this feature

Thank you

**Comment by serhez** [comment]
I would love seeing this feature too!

**Comment by lukas-reineke** [comment]
Scope in version 3 supports start and end
