### ISSUE TITLE
Listchars display issues when changing options for non-current window

### ISSUE THREAD

**Issue by stevearc** [lukas-reineke/indent-blankline.nvim#482]
This was originally reported as a bug on aerial.nvim in https://github.com/stevearc/aerial.nvim/issues/150. I've discovered that this is because aerial opens a window as a vsplit and then sets window options on it while focused on a different window. Likely this has something to do with the fact that the autocmd on OptionSet doesn't take into account the window that had the option set, and instead assumes it was the current window.

https://github.com/lukas-reineke/indent-blankline.nvim/blob/db7cbcb40cc00fc5d6074d7569fb37197705e7f6/plugin/indent_blankline.vim#L35

I haven't looked deeply enough into IndentBlanklineRefresh to know why the refresh causes the display issue, but I have a minimal init.lua file:

```lua
-- Install packer
local install_path = vim.fn.stdpath 'data' .. '/site/pack/packer/start/packer.nvim'
local is_bootstrap = false
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  is_bootstrap = true
  vim.fn.execute('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
  vim.cmd [[packadd packer.nvim]]
end

-- stylua: ignore start
require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use 'lukas-reineke/indent-blankline.nvim'
  if is_bootstrap then
    require('packer').sync()
  end
end)
-- stylua: ignore end

if is_bootstrap then
  print '=================================='
  print '    Plugins are being installed'
  print '    Wait until Packer completes,'
  print '       then restart nvim'
  print '=================================='
  return
end

vim.o.list = true
vim.opt.listchars:append("space:⋅")
vim.o.splitright = true

require("indent_blankline").setup({})
vim.api.nvim_create_user_command('Test', function()
  local winid = vim.api.nvim_get_current_win()
  vim.cmd('vsplit')
  local new_win = vim.api.nvim_get_current_win()
  vim.api.nvim_set_current_win(winid)
  vim.api.nvim_win_set_option(new_win, 'list', false)
end, {})

-- This exists for demonstration purposes
for index, value in ipairs({}) do
    if index == value then
        print(index)
    end
end
```

After opening the file:
<img width="388" alt="Screen Shot 2022-09-25 at 7 36 14 AM" src="https://user-images.githubusercontent.com/506791/192149375-1e008d6a-12c7-467b-8ca2-2226c3d55201.png">

After running `:Test`
<img width="392" alt="Screen Shot 2022-09-25 at 7 36 27 AM" src="https://user-images.githubusercontent.com/506791/192149380-9446dc98-6788-4c24-ae89-88d09572d54f.png">

You can see that some of the listchars on the print line have stopped rendering

**Comment by lukas-reineke** [comment]
Refreshing a not active buffer is currently not supported. It leads to issues like this. This will be a lot of work to fix, I don't think I will do it in v2.
But I plan to design this better in version 3.

**Comment by lukas-reineke** [comment]
Should be fixed with version 3
