### ISSUE TITLE
show_current_context is not accurate with Rust

### ISSUE THREAD

**Issue by mike-lloyd03** [lukas-reineke/indent-blankline.nvim#485]
My config:
```lua
vim.cmd([[highlight IndentBlanklineContextChar guifg=#61afef gui=nocombine]])
require("indent_blankline").setup({
    space_char_blankline = " ",
    show_current_context = true,
    show_current_context_start = false,
})
```
With `show_current_context` enabled and the cursor inside a nested block, only the outer block highlights. I haven't noticed this with lua or python. Just in Rust.

![Screenshot_20221001_123316](https://user-images.githubusercontent.com/49411532/193425409-aad02ef3-12c7-4e4f-aacd-12233fb49f8f.png)

**Comment by lukas-reineke** [comment]
By default, the scope is set by `:help g:indent_blankline_context_patterns`. You can go over the treesitter types you want added, and write patterns for them. I'd be happy to merge a PR to update them as well.

But the whole system is not that great. For a while now treesitter itself supports the concept of scopes, which works much better. You can use that in indent-blankline with `use_treesitter_scope = true`. This should fix your issue.

**Comment by mike-lloyd03** [comment]
Ahh that's the config parameter I was missing. Works much better now. Thank you.
