### ISSUE TITLE
Lazy loading with packer

### ISSUE THREAD

**Issue by mosheavni** [lukas-reineke/indent-blankline.nvim#486]
I'm trying to lazy load indent-blankline.nvim using packer:

```lua
...
  use {
    'nvim-treesitter/nvim-treesitter',
    run = ':TSUpdate',
    event = 'BufRead',
    cmd = {
      'TSInstall',
      'TSBufEnable',
      'TSBufDisable',
      'TSEnable',
      'TSDisable',
      'TSModuleInfo',
    },
    config = "require('user.plugins.treesitter')",
  }

  use {
    'lukas-reineke/indent-blankline.nvim',
    config = "require('user.plugins.indentlines')",
    event = 'BufWinEnter',
    after = 'nvim-treesitter',
  }
...
```

my indent line config is this:

```lua
----------------------
-- indent_blankline --
----------------------
local status_ok_indent_blankline, indent_blankline = pcall(require, 'indent_blankline')
if not status_ok_indent_blankline then
  return
end
indent_blankline.setup {
  char = '┊',
  filetype_exclude = {
    'NvimTree',
    'TelescopePrompt',
    'TelescopeResults',
    'alpha',
    'help',
    'lspinfo',
    'mason.nvim',
    'nvchad_cheatsheet',
    'packer',
    'terminal',
    '',
  },
  buftype_exclude = { 'terminal' },
  show_trailing_blankline_indent = false,
  show_first_indent_level = false,
  show_current_context = true,
  show_current_context_start = true,
  space_char_blankline = ' ',
}
```

When entering vim, I get this notification:

```
indent-blankline  WARN nvim-treesitter not found. Context will not work
```

Any ideas why?
How to achieve lazy loading?
Thanks.

**Comment by lukas-reineke** [comment]
Not sure, this is more a question for packer. This error just means that when `indent-blankline` was loaded, `nvim-treesitter` was not available.

But I would question the point of doing this in the first place. You can't start Neovim without a window, so with `BufWinEnter` you still load indent-blankline on startup. You don't get any benefit from doing this.

**Comment by rstacruz** [comment]
I agree that `BufWinEnter` might not be the best event to put a lazyload hook into.

In any case, it might be worth adding `module = "nvim-treesitter"` to the treesitter plugin's definition so it can be loaded on demand by doing `require("nvim-treesitter")`.

**Comment by towry** [comment]
Add option to disable this annoying message would be great!

**Comment by lukas-reineke** [comment]
If you get the message it means your config is wrong and not going to work.
Fix the problem with your config and you won't get the message.

**Comment by towry** [comment]
> If you get the message it means your config is wrong and not going to work. Fix the problem with your config and you won't get the message.

**This error only happens if `show_current_context` is on.** 

I don't know if this plugin's **other features** depends on treesitter, if it does, than it should be in the doc, and I will enable this plugin only when treesitter is available.

Otherwise, `show_current_context` is optional, if it works, great, if it doesn't, fine, just don't emit errors. I like the `show_current_context` doesn't mean i have to adjust a lot of configs to make it work in all cases.

**Comment by lukas-reineke** [comment]
The whole plugin does not require treesitter. But `show_current_context` does, and it says so in the docs.

https://github.com/lukas-reineke/indent-blankline.nvim/blob/c4c203c3e8a595bc333abaf168fcb10c13ed5fb7/doc/indent_blankline.txt#L464-L470

If you turn `show_current_context` on, you explicitly opt-in to use treesitter. If it is not available then, you get an error.
This behavior will not change.
