### ISSUE TITLE
Add Feature: customize the symbols at the top and bottom of the range?

### ISSUE THREAD

**Issue by NEX-S** [lukas-reineke/indent-blankline.nvim#487]
Can indent-blankline add a feature that can customize the symbols at the top and bottom of the range?

for example:

> line '153' and line '163' 's indent sign can be customized. 
![image](https://user-images.githubusercontent.com/97107165/193622011-4f69cd16-e1c0-4800-bf60-8d8332dfda16.png)

If this feature can be implemented, that would be awesome!!!

**Comment by lukas-reineke** [comment]
There is already an issue for this here #419
