### ISSUE TITLE
Is it possible to set the colour of `show_current_context_start`?

### ISSUE THREAD

**Issue by DMunkei** [lukas-reineke/indent-blankline.nvim#488]
I would like to change the colour colour of the underline and vertical line. Is it possible to pass a colour value?

**Comment by lukas-reineke** [comment]
Yes you can, `:help hl-IndentBlanklineContextStart` for the start underline, and `:help hl-IndentBlanklineContextChar` for the vertical line.

**Comment by DMunkei** [comment]
I'm not sure where i pass this the autocommand inside of the setup function?
```lua
vim.cmd [[highlight IndentBlanklineContextStart guisp=#FF0000 gui=underline]]
require("indent_blankline").setup{
    space_char_blankline = " ",
    show_current_context = true,
    show_current_context_start = true,
}
```

**Comment by lukas-reineke** [comment]
You mean the `vim.cmd`? This is not an autocommand, it's just executing vimscript from lua.
You can put this anywhere in your config. The only important thing is to put it after your color scheme, because most color schemes clear all highlighting.
