### ISSUE TITLE
IndentBlanklineContextStart underline colour is not respected under tmux

### ISSUE THREAD

**Issue by HawkinsT** [lukas-reineke/indent-blankline.nvim#490]
Setting a colour for `IndentBlanklineContextStart` via `highlight IndentBlanklineContextStart guisp=#C678DD gui=underline` doesn't work when in tmux. I've tested this in both kitty and alacrity and have tried playing around with my tmux settings (e.g. to try to overwrite this via `setulc`). No matter what colour is specified the underline colour will be the same as the text colour it's underlining if I'm in a tmux session (but works as intended outside of tmux), e.g.

![blankline](https://user-images.githubusercontent.com/29347540/195723142-6e3b713a-33a2-4e46-9147-392f9ccef803.png)

I am able to set the underline colour in other cases in neovim just fine, just not for `IndentBlanklineContextStart` which leads me to believe that it's a bug in this package, although I'm unfortunately not able to diagnose the problem beyond this.

**Comment by lukas-reineke** [comment]
> I am able to set the underline colour in other cases in neovim just fine

That is very weird. I don't do anything special with the underlines.

Try setting this in your tmux config

```
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
```

**Comment by HawkinsT** [comment]
Huh, I had this exact line in my tmux config last night and it wasn't working. I was pretty sure I detached from the previous tmux session, re-sourced config correctly etc. but I must have done something wrong as after a reboot it's now working in tmux with this line in both kitty and alacrity. Sorry for the confusion, but thanks a lot for your assistance (and all your work on this great plugin)!

**Comment by pythops** [comment]
I'm having the same issue. I'm using alacritty + tmux.
@lukas-reineke 
the setting you suggested does not work :disappointed_relieved: 
any other solution ?
Thanks :pray: 

here is my config
```
lua <<EOF
vim.opt.list = true
vim.opt.listchars:append "eol:↴"

vim.cmd [[highlight IndentBlanklineContextStart guisp=#B16286 gui=underline]]
vim.cmd [[highlight IndentBlanklineContextChar guifg=#B16286 gui=nocombine]]

require("indent_blankline").setup {
    space_char_blankline = " ",
    show_current_context = true,
    show_current_context_start = true,
}
EOF
```

**Comment by lukas-reineke** [comment]
indent-blankline is not doing anything special. It just uses a highlight group with underline. If it doesn't work, it's a problem with Neovim, Tmux and Alacritty.
I don't really have any advice other than what I posted above, sorry.
