### ISSUE TITLE
Remove extra indentation lines for newlines

### ISSUE THREAD

**Issue by rocket-engineer** [lukas-reineke/indent-blankline.nvim#491]
Hello,

for C++ I use clang-format as formatter. I usually get indentations like this:
![problem_indent-blanklines_1](https://user-images.githubusercontent.com/3513477/196146407-c02752b8-d7c2-44ca-a0a8-c6b63542f022.png)

Is it possible to remove the extra indentation for newlines? `use_treesitter` is enabled in my config.
![problem_indent-blanklines_1b](https://user-images.githubusercontent.com/3513477/196146466-b0b49909-ac5c-47f9-b16c-c2741956f5f4.png)

Or is this related to https://github.com/lukas-reineke/indent-blankline.nvim/issues/170 (Support irregular indentation)?

**Comment by lukas-reineke** [comment]
You can set `:help g:indent_blankline_max_indent_increase` to 1, that should give you what you want.
