### ISSUE TITLE
Highlight separate code block in C (context highlighting)

### ISSUE THREAD

**Issue by rocket-engineer** [lukas-reineke/indent-blankline.nvim#492]
Hello,

is it possible to highlight this context:
![problem_indent-blanklines_2](https://user-images.githubusercontent.com/3513477/196149960-6f2b91b8-a1e1-48c3-a7a3-00dcc10c03d3.png)

My config:
`indent_blankline.setup({
  enabled          = true,
  use_treesitter   = true,
  char = '▏',
  show_first_indent_level        = false,
  show_trailing_blankline_indent = false,
  show_current_context           = true,
  show_current_context_start     = false,
  context_patterns = {
    "function",
    "class",
    "method",
    "block",
    "arguments",
    "^table",
    "^if",
    "^while",
    "^for",
    "^object",
    "^table",
  },
})`

**Comment by lukas-reineke** [comment]
Take a look at #485, the answer is the same
