### ISSUE TITLE
Switch Statements current_context not highlighting

### ISSUE THREAD

**Issue by Xemptuous** [lukas-reineke/indent-blankline.nvim#494]
I noticed this in c++, but also tested it in python's match:

when having `show_current_context = true`, colors don't get affected by switch case statements. Not sure if this is by design or not, but I figured it was worth asking. If's, While's and For's still highlight properly when inside of case's, but the switch indent itself and the cases are ignored with highlighting.

With large switch-case statements, it would be helpful for the proper indentation to be highlighted.

**Comment by lukas-reineke** [comment]
Take a look at my comment here https://github.com/lukas-reineke/indent-blankline.nvim/issues/485#issuecomment-1264518353
