### ISSUE TITLE
Invalid node type at position 3524 for language typescript

### ISSUE THREAD

**Issue by ziombo** [lukas-reineke/indent-blankline.nvim#496]
After updating to the newest nightly version, I've been getting this error, which I believe comes from indent-blankline.

`Error executing vim.schedule lua callback: ...root/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 3524 for language typescript
stack traceback:
        [C]: in function '_ts_parse_query'
        ...root/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: in function 'get_query'
        ...r/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:52: in function 'new'
        ...ashfs-root/usr/share/nvim/runtime/lua/vim/treesitter.lua:45: in function '_create_parser'
        ...ashfs-root/usr/share/nvim/runtime/lua/vim/treesitter.lua:96: in function 'get_parser'
        ...ker/start/nvim-treesitter/lua/nvim-treesitter/indent.lua:65: in function 'get_indent'
        ...tart/indent-blankline.nvim/lua/indent_blankline/init.lua:466: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>`

Things I tried so far: updating indent-blankline, updating Treesitter and reinstalling the typescript parser, but the error still persists.

**Comment by lukas-reineke** [comment]
I can't reproduce this. And indent-blankline does not add any queries, this is an issue with treesitter and the typescript parser.
Sorry, I can't help you with this. Maybe try the typescript parser repo.
