### ISSUE TITLE
breaking lines

### ISSUE THREAD

**Issue by edr3x** [lukas-reineke/indent-blankline.nvim#499]
It shows this on the README file
![image](https://user-images.githubusercontent.com/45848083/201011329-949fcbac-0c42-43e5-b08c-bdc21bf718a7.png)
but when i try the same setting it looks like this
![image](https://user-images.githubusercontent.com/45848083/201011434-1b978cd6-a999-43f2-ae9b-814a80ce0fe2.png)
the lines are breaking and the underline is wrong
I am using Alacritty Terminal Emulator

**Comment by lukas-reineke** [comment]
indent-blankline uses underscore to draw this line. How the underscore looks like depends on your terminal emulator.
I don't use Alacritty, I can't help you with that, sorry.

**Comment by edr3x** [comment]
sorry for super late reply @twiclo but NO, i couldn't find the solution, i just got used to not having highlighted line.
