### ISSUE TITLE
Default highlight is changed to Comment

### ISSUE THREAD

**Issue by zegervdv** [lukas-reineke/indent-blankline.nvim#50]
The documentation still mentions `Conceal` as default value for `g:indent_blankline_char_highlight`, however the value seems to be `Comment`.

Combined with italics for comments this gave a weird result ;)

**Comment by lukas-reineke** [comment]
I forgot to update the documentation :+1: 

Also italics is a good point, maybe Comment isn't that great of a default. I'll change it to also be Whitespace.
