### ISSUE TITLE
Add support for `vim.opt.listchars:append "tab:"`

### ISSUE THREAD

**Issue by hinell** [lukas-reineke/indent-blankline.nvim#502]
```lua
vim.opt.listchars:append "tab:⇢"
```

I request to add support for the tab character, ust like in VS Code. Thanks!

![image](https://user-images.githubusercontent.com/8136158/202904502-3401aeda-9e39-46c4-8dc4-0d5139b52bbe.png)

**Comment by lukas-reineke** [comment]
you can already do this by setting `:help g:indent_blankline_char` to an empty string and using built in `listchars`
