### ISSUE TITLE
[Feature Request] Show Listchar base on expandtab option

### ISSUE THREAD

**Issue by chunleng** [lukas-reineke/indent-blankline.nvim#503]
Thank you for all the work in this plugin, I have tried to use many other indent line plugin and by far, this is no doubt the best.

# Problem I have

I sometimes encounter files with irregular tabs and spaces or my editor decided to use a setting that conflicts with the original intent. Using the character to indent is nice, but sometimes it hides away the irregular tabs and spaces inside these lines.

# Proposal

Maybe, `indent-blankline` can perform the following logic:

- if `et`, read the line lead for tab and render the tab as it is
- if `noet`, read the line lead for space and render the space as it is

**Comment by lukas-reineke** [comment]
Yeah, there is currently no way to differentiate the indent char for tabs and spaces. You can set `listchars` to be more than 1 character, to see tabs.
And you can set `:help g:indent_blankline_strict_tabs` to help with this a bit, but only for mixed indent on the same line.

I plan to fundamentally refactor this, and allow different characters for spaces and tabs. But this is a lot of work. I will do this in version 3.

**Comment by ryuheechul** [comment]
In the meantime, I made a workaround inspired by the comment above.
```lua
vim.opt.listchars:append 'tab: →'
vim.opt.tabstop = 2 

-- rendered results
-- │→→→→→→→│→→→→→→→double indented # with tabstop = 8 (default)
-- │→│→double indented             # with tabstop = 2
```
Which works best with `tabstop = 2` and here is [my change](https://github.com/ryuheechul/dotfiles/commit/a76059c3884ffe9fe0b2ae9862ee5970a87bd869) to it.

**Comment by lukas-reineke** [comment]
This is now handled better in version 3.
