### ISSUE TITLE
feat: Set `IndentBlanklineContextStart` with `context_highlight_list`

### ISSUE THREAD

**Issue by daephx** [lukas-reineke/indent-blankline.nvim#504]
I use [TSRainbow](https://github.com/p00f/nvim-ts-rainbow) for parenthesis and set indent_blankline to use `rainbowcol{1,7}` highlights for `context_highlight_list`. 
I want to have the underline for the `current_context_start` to also match these values.

Example in Neovim:
![mstsc_FWg47g5qTK](https://user-images.githubusercontent.com/36192863/203508311-853c9bb9-6f83-455c-8987-f81113d5f28a.gif)

Example in VSCode:
![Code_wvtYJOkOGX](https://user-images.githubusercontent.com/36192863/203472726-40b35037-d398-4356-9a86-3219aa35ccef.gif)

<details>
<summary><code>lua/plugins/indent_blankline.lua</code></summary>

```lua
-- indent-blankline.nvim | Indent guides for Neovim
-- https://github.com/lukas-reineke/indent-blankline.nvim
local indent_blankline_ok, indent_blankline = pcall(require, 'indent_blankline')
if not indent_blankline_ok then
  return
end

-- Apply plugin settings
indent_blankline.setup({
  enabled = true,
  use_treesitter = true,
  char_highlight = 'LineNr',
  space_char_blankline = ' ',
  show_current_context = true,
  show_current_context_start = true,
  show_end_of_line = false,
  show_first_indent_level = true,
  show_trailing_blankline_indent = false,
  context_highlight_list = {
    'rainbowcol1',
    'rainbowcol2',
    'rainbowcol3',
    'rainbowcol4',
    'rainbowcol5',
    'rainbowcol6',
    'rainbowcol7',
  },
  buftype_exclude = {
    'quickfix',
    'help',
    'nofile',
    'prompt',
    'terminal',
  },
  filetype_exclude = {
    '',
    'NvimTree',
    'Trouble',
    'dashboard',
    'fugitive*',
    'git*',
    'help',
    'lspinfo',
    'mason',
    'packer',
  },
})
```

</details>

**Comment by lukas-reineke** [comment]
I should add this :+1:
I'll try to find some time

**Comment by daephx** [comment]
Glad you're up for it, take all the time you need!

**Comment by tan-wei** [comment]
Hmm. [TSRainbow](https://github.com/p00f/nvim-ts-rainbow)  now archived. Any other alternatives?

**Comment by daephx** [comment]
I'm now using [hiphish/rainbow-delimiters.nvim](https://github.com/hiphish/rainbow-delimiters.nvim) with no issues.

**Comment by tan-wei** [comment]
> @tan-wei I'm now using [hiphish/rainbow-delimiters.nvim](https://github.com/hiphish/rainbow-delimiters.nvim) with no major issues. Just have to change the `context_highlight_list` to match the appropriate highlight groups.

Thanks!

**Comment by lukas-reineke** [comment]
Now supported, see `:help hooks.builtin.scope_highlight_from_extmark`
