### ISSUE TITLE
Indent signs are placed relative to window instead of buffer

### ISSUE THREAD

**Issue by ytian81** [lukas-reineke/indent-blankline.nvim#51]
When I move right along a very long line, the indent signs still show on window.

![indent](https://user-images.githubusercontent.com/14842664/109694129-4bcfd580-7b3f-11eb-8f94-55acd82f1a6d.gif)

**Comment by lukas-reineke** [comment]
thanks
I created an issue in Neovim https://github.com/neovim/neovim/issues/14050

**Comment by experiacc** [comment]
is this issue fixed yet ??

**Comment by andersevenrud** [comment]
Still waiting for upstream changes it seems @experiacc :/

**Comment by experiacc** [comment]
thanks for the quick update 😄

**Comment by fuelen** [comment]
I'm not sure, but seems like it is related.
I use f-person/git-blame.nvim plugin and when the line is empty, then some text from git-blame is hidden behind the indent-blankline. On the screenshot below, the letter `Y` is hidden
![image](https://user-images.githubusercontent.com/588762/124721832-1fbfc900-df12-11eb-9b2f-86f99e5e920d.png)

**Comment by lukas-reineke** [comment]
> I use f-person/git-blame.nvim plugin and when the line is empty, then some text from git-blame is hidden behind the indent-blankline. 

It is not related, please open a new issue.

**Comment by AndOrangutan** [comment]
There is still no fix for this, right? Love the plugin, this just kinda irks me.

**Comment by andersevenrud** [comment]
@AndOrangutan Still awaiting upstream fix in neovim for this.

**Comment by AndOrangutan** [comment]
@andersevenrud  Thanks,

**Comment by WhyNotHugo** [comment]
Would using `nvim_buf_set_extmark` instead of `nvim_buf_set_virtual_text` help work around this issue?

I've an impression that it does, and also solves this unrelated issue: https://github.com/lewis6991/gitsigns.nvim/issues/197

**Comment by lukas-reineke** [comment]
I am already using `nvim_buf_set_extmark`, and it does not solve either of these issues.

see #142 for more information about priority. TLDR priority does not apply to virtual text

**Comment by romgrk-comparative** [comment]
Can you do a workaround with the `WinScrolled` event? Horizontal scroll is a PITA to get but it's possible in lua by ffi'ing into neovim internals:

https://github.com/romgrk/nvim-treesitter-context/blob/d4cc374f0deb9545f193fa2ae44daf3fbe292718/lua/treesitter-context.lua#L16-L17
https://github.com/romgrk/nvim-treesitter-context/blob/d4cc374f0deb9545f193fa2ae44daf3fbe292718/lua/treesitter-context.lua#L158

**Comment by lukas-reineke** [comment]
This does work!! Thank you
But `curwin_col_off` is not the right function. That just gives you the side column width.
I need `curwin->w_leftcol`.

I added my own function into Neovim to try this out, and it works. I can make the indent guides scroll horizontally.
Now the only question is how do I get `curwin->w_leftcol` without a custom function. I am not good in C, is there a way to make FFI get that somehow? :thinking:

**Comment by romgrk** [comment]
You need to provide the definitions, then you can access with `ffi.C.curwin.w_leftcol`.
But it looks like this: https://gist.github.com/romgrk/7e05acf632158d9556a2cee6ed25dec4
This is much more ugly than I expected :|

Note that the definitions in that gist are cropped just after `w_leftcol`, have some pointers set as just `void*` to avoid defining everything, and will break if the structure layout changes upstream. Ideally, it would need to be provided by neovim as an API function.

**Comment by lukas-reineke** [comment]
Thank you, but yeah that is not really scalable :disappointed: 

I created an issue https://github.com/neovim/neovim/issues/15247, maybe we can get an API for this.

**Comment by romgrk** [comment]
Yo I just remembered you can access that through `winsaveview()`.

![Screenshot from 2021-08-03 03-53-39](https://user-images.githubusercontent.com/1423607/127978929-89e57a01-d454-4268-9ab3-aba4d34fc6bb.png)

Probably nice to have a neovim API for it anyway though.

**Comment by lukas-reineke** [comment]
Nice!
Yeah, having the API would be good anyway, but this means it will actually work with Neovim 0.5 as well :+1:

**Comment by lukas-reineke** [comment]
Fix is merged :tada: 
Thank you @romgrk

**Comment by kutsan** [comment]
Thank you @lukas-reineke, @romgrk!! I was waiting for this one.
