### ISSUE TITLE
show_context setting not working?

### ISSUE THREAD

**Issue by SiddidMandi** [lukas-reineke/indent-blankline.nvim#510]
Hi, cool plugin.
```
vim.opt.list=true
vim.g.show_current_context=true
vim.g.show_current_context_start=true
show_current_context=true
show_current_context_start=true
vim.cmd[[
let g:indent_bankline_current_context=1
let g:indent_bankline_current_context_start=1
]]
```
I have all this in my vim config and treesitter installed. I installed all my plugins manually, and they all seem to work. I even tested each of these settings individually to see if they 'clash', the context still doesn't show. 
And what does 
```
require("indent_blankline").setup {
} 
```
Mean? Is it related to packer plugin manager or something? This may not be an issue but my lack of competency but I don' know where else to ask this question.

**Comment by lukas-reineke** [comment]
You can set indent-blankline plugin settings from global variables, this is `vim.g.indent_bankline_show_current_context = true` in lua, or `let g:indent_bankline_show_current_context = v:true` in vimscript. This is the old way to do it.

You can also use the `require("indent_blankline").setup` function to do the same. With this method, you just pass them in the first argument.

```lua
require("indent_blankline").setup {
  show_current_context = true,
}
```

This is the preferred method to set options now. The old way is just there for backwards compatibility and will be removed in the future.

Every way you put it in your config has some mistake. Copy my example and it should work.
