### ISSUE TITLE
Scrolling/typing becomes slow when large parts are commented

### ISSUE THREAD

**Issue by sdressler** [lukas-reineke/indent-blankline.nvim#512]
Not sure if this is an issue with the plugin or treesitter itself, but profiling directed me to your plugin and hence I'm filing it here.

I use NeoVim 0.9.0-dev-2957 and Go LSP and your plugin. When having large blocks of code comments, scrolling and typing become very slow. This happens on Go files with e.g. 100 lines of code and commenting out more than (ballpark) 2/3 of it. Becomes worse the larger the file gets.

Profiling while typing and scrolling shows:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
  348   0.163315             <SNR>47_try()
    2   0.071145   0.053030  gitgutter#all()
  348   0.056579   0.052512  <SNR>33_Highlight_Matching_Pair()
    6   0.048939   0.005576  signature#sign#Refresh()
[...]

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
  348              0.163315  <SNR>47_try()
    2   0.071145   0.053030  gitgutter#all()
  348   0.056579   0.052512  <SNR>33_Highlight_Matching_Pair()
   12              0.020151  signature#mark#GetList()
[...]
```

and

```
FUNCTION  <SNR>47_try()
    Defined: ~/.local/share/nvim/site/pack/packer/start/indent-blankline.nvim/plugin/indent_blankline.vim:7
Called 348 times
Total time:   0.163315
 Self time:   0.163315

count  total (s)   self (s)
  348              0.000333     try
  348              0.161154         execute a:cmd
                                catch /E12/
                                    return
  348              0.000376     endtry
```

Test file for the profile above [is here](https://gist.github.com/sdressler/fa1f2b375d68f9c83625bd2024c26f7b).

Edit w more info: the moment I remove the `*/` (line 66), everything becomes normal, speed-wise.

**Comment by lukas-reineke** [comment]
This is a problem/limitation of treesitter. I don't think there is anything I can do to fix this here.

Treesitter is optional in indent-blankline, you can turn off the features that require it. That's the best I can suggest, sorry

**Comment by Congee** [comment]
https://github.com/lukas-reineke/indent-blankline.nvim/blob/29be0919b91fb59eca9e90690d76014233392bef/lua/ibl/init.lua#L118

There already is some code to deal with bursting events. Changing the current threshold 50 to 10 results in smoother scrolling for me. Is it possible to make this threshold configurable?
