### ISSUE TITLE
Can I hide EOL characters displayed in the first indentation level of a blankline?

### ISSUE THREAD

**Issue by carlosdr02** [lukas-reineke/indent-blankline.nvim#513]
Is there a way to hide EOL characters in blanklines?

![image](https://user-images.githubusercontent.com/80007185/208376759-d93cd190-4eae-4294-bffa-da2f0c051bc2.png)

Ideally, I'd want nothing in 1 because we are outside of a scope and the normal indent character ('|') in 2. Is this possible or am I tripping?

In other words, only show the EOL character when the current line is not a blank line.

**Comment by lukas-reineke** [comment]
This is off by default, you probably turned this on with `:help g:indent_blankline_show_end_of_line`

Just remove that from your config

**Comment by carlosdr02** [comment]
@lukas-reineke Toggling `show_end_of_line` does nothing for me, idk why. The only way I can disable the EOL chars is setting `vim.opt.list` to `false`, but that disables EOL chars on lines that are not blank, obviously, and I don't want that.

**Comment by lukas-reineke** [comment]
please share a full config and example to reproduce this

**Comment by carlosdr02** [comment]
@lukas-reineke

```
vim.opt.list = true
vim.opt.listchars:append "eol:↴"

require("indent_blankline").setup {
    show_trailing_blankline_indent = false
}
```

**Comment by lukas-reineke** [comment]
This does not reproduce the issue.

**Comment by JDl337** [comment]
`show_end_of_line` only affects EOL chars when the indent guide is being drawn. On completely empty lines it has no effect. 

Eg: with `show_end_of_line` set to `false`:
![image](https://user-images.githubusercontent.com/126777940/227226068-0adae155-16c7-4656-9d4d-9a81d237439b.png)

with `show_end_of_line` set to `true`:
![image](https://user-images.githubusercontent.com/126777940/227226450-461e15c9-f81e-4017-8b7e-0908932394b8.png)

The second line is unaffected.

**Comment by lukas-reineke** [comment]
> On completely empty lines it has no effect.

Correct, because those don't come from indent-blankline. They are the built-in listchar for eol. `:help lcs-eol`
