### ISSUE TITLE
show_current_content_start  = true, doesn't work

### ISSUE THREAD

**Issue by JuanZoran** [lukas-reineke/indent-blankline.nvim#516]
![image](https://user-images.githubusercontent.com/107862700/209044520-b296c8a0-f568-4e6e-a165-5c27907311f2.png)
I am sorry for taking an issue with this, I just don't know whether this is a bug:
the image shows all my configurations for this plugin and the show_current_content_start seems doesn't work

**Comment by lukas-reineke** [comment]
Can you check what `:hi IndentBlanklineContextStart` is set to?

**Comment by JuanZoran** [comment]
Thank you for answer

**Comment by JuanZoran** [comment]
It works well now
