### ISSUE TITLE
Current scope doesn't work in vue html block

### ISSUE THREAD

**Issue by rwxmad** [lukas-reineke/indent-blankline.nvim#517]
![Снимок экрана 2022-12-26 в 14 31 13](https://user-images.githubusercontent.com/30772868/209544298-28040347-1ddf-437d-b83f-b6e34797f591.png)

**Comment by lukas-reineke** [comment]
Please take a look at this comment https://github.com/lukas-reineke/indent-blankline.nvim/issues/485#issuecomment-1264518353
