### ISSUE TITLE
The plugin works in .tsx file, but not working on .ts file

### ISSUE THREAD

**Issue by hudy9x** [lukas-reineke/indent-blankline.nvim#518]
As you can see the image below, the plugin works on `src/App.tsx` file. But not in `files.ts` file

![image](https://user-images.githubusercontent.com/95471659/209939335-3c10ec65-6b72-4d4c-ad43-4c7d2a86de24.png)

Here is my config

```lua
vim.opt.list = true
vim.opt.listchars:append "space:⋅"
vim.opt.listchars:append "eol:↴"
vim.cmd [[highlight IndentBlanklineChar guifg=#323232 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineSpaceChar guifg=#f0f0f02e gui=nocombine]]
vim.cmd [[highlight IndentBlanklineContextChar guifg=#00FF00 gui=nocombine]]

require("indent_blankline").setup {
  space_char_blankline = " ",
  show_current_context = true,
  show_current_context_start = true,
}
```

I read your document to find some configs like `filetypes` or something. However, found nothing.

**Comment by lukas-reineke** [comment]
What does not work? I can see indent guides for both filetypes.

**Comment by hudy9x** [comment]
In .tsx file, it works, you can see the green line in below image

![image](https://user-images.githubusercontent.com/95471659/210716633-2f3ccc30-5c36-428b-a089-2bdb4d6f056d.png)

But in .ts file, the green line not displayed

![image](https://user-images.githubusercontent.com/95471659/210716782-c61ef28d-3410-445f-879c-aab08f762498.png)

**Comment by lukas-reineke** [comment]
ah you mean the context.
Please take a look at this https://github.com/lukas-reineke/indent-blankline.nvim/issues/485#issuecomment-1264518353
