### ISSUE TITLE
indent lines are not shown consistently for empty lines between different code sections on the same level

### ISSUE THREAD

**Issue by hopezh** [lukas-reineke/indent-blankline.nvim#519]
As shown in the image below, the indent line is not shown for empty lines between different sections of code at the same level, e.g. line 7, 9, 24, etc. However, it is shown for such empty lines in other places, such as line 14, 18, 20, 22, 38, etc. 
<img width="807" alt="Screenshot 2022-12-29 at 9 08 04 PM" src="https://user-images.githubusercontent.com/23435810/209958055-671f22c5-5431-4090-8e24-45593cd53255.png">

The indent lines shown for the same code in vscode are far more consistent, as shown below. 
<img width="722" alt="Screenshot 2022-12-29 at 9 10 17 PM" src="https://user-images.githubusercontent.com/23435810/209958088-cce6f24e-2cb8-40ec-a993-a1e4e67e2c89.png">

May I ask if this inconsistency is related to some of the settings of indent-blankline.nvim?

**Comment by lukas-reineke** [comment]
can you share the configuration for indent-blankline you are using?

**Comment by hopezh** [comment]
> can you share the configuration for indent-blankline you are using?

Here it is: 

```
require("indent_blankline").setup {
    -- for example, context is off by default, use this to turn it on
    show_current_context = true,
    show_current_context_start = false,

    context_patterns = {
      "class", "return", "function", "method", "^if", "^while", "jsx_element", "^for", "^object",
      "^table", "block", "arguments", "if_statement", "else_clause", "jsx_element",
      "jsx_self_closing_element", "try_statement", "catch_clause", "import_statement",
      "operation_type"
    }
}
```

**Comment by lukas-reineke** [comment]
I can't reproduce this. Do you maybe have trailing whitespace on those lines?

**Comment by hopezh** [comment]
> I can't reproduce this. Do you maybe have trailing whitespace on those lines?

I don't have trailing whitespace in those lines, otherwise, nvim lsp will give me a warning. 

Interestingly, adding whitespaces at the beginning of the empty lines will make those vertical indent lines go away, showing code block in the same way as vscode.

**Comment by sabah1994** [comment]
![Screenshot from 2023-01-08 12-51-29](https://user-images.githubusercontent.com/73726199/211197034-ef3bf9aa-8075-403b-9365-a42e8c7bf612.png)

I have got same issue, I am using default settings. 
require("indent_blankline").setup {}

**Comment by lukas-reineke** [comment]
@sabah1994 this is the expected result. You can turn on or off the trailing indent guide with `:help g:indent_blankline_show_trailing_blankline_indent`
That is not the issue here.

**Comment by lukas-reineke** [comment]
@hopezh can you share the code from the screenshot?

**Comment by sabah1994** [comment]
@lukas-reineke thanks man

**Comment by hopezh** [comment]
> @hopezh can you share the code from the screenshot?

As requested. Thanks. 

```
require("indent_blankline").setup {
    -- for example, context is off by default, use this to turn it on
    show_current_context = true,
    show_current_context_start = false,

    context_patterns = {
      "class", "return", "function", "method", "^if", "^while", "jsx_element", "^for", "^object",
      "^table", "block", "arguments", "if_statement", "else_clause", "jsx_element",
      "jsx_self_closing_element", "try_statement", "catch_clause", "import_statement",
      "operation_type"
    }
}
```

**Comment by gruvw** [comment]
I have the exact same issue

**Comment by lukas-reineke** [comment]
please reopen if this is still an issue in version 3
