### ISSUE TITLE
the indent line display on nvim-tree too.

### ISSUE THREAD

**Issue by adrianmak** [lukas-reineke/indent-blankline.nvim#520]
is it possible to exclude it ?

**Comment by adrianmak** [comment]
![Screenshot 2022-12-31 105040](https://user-images.githubusercontent.com/1168716/210122810-251ef326-dd9a-4134-90b8-f12aa274e0f9.png)

**Comment by yolong-lin** [comment]
This is a feature of nvim-tree, not an issue of indent-blankline.

```
require('nvim-tree').setup {
  renderer = {
    indent_marker = { enable = false }
  }
}
```
