### ISSUE TITLE
function to exclude use_treesitter on some file types?

### ISSUE THREAD

**Issue by y0nei** [lukas-reineke/indent-blankline.nvim#522]
Im aware that treesitter for python is a bit buggy and im not asking for a fix, i want to have some function that will make the use_treesitter option to be off for some file types like .py file.

i have found that keeping that option off when editing a python file results in good indentation, exactly the same as vscode

but having this option on (in combination with `show_trailing_blankline_indent = false`) results in faulty indentation like in lua:
![image](https://user-images.githubusercontent.com/23276734/211174951-e0793dc4-ae4c-4cb0-934e-b575e5d0b98e.png)

somewhat related to: #226 #362

**Comment by y0nei** [comment]
### Context
current configuration:
```lua
require("indent_blankline").setup {
    char = "▏",
    context_char = "▎",
    show_trailing_blankline_indent = false,
    show_current_context = true,
    show_current_context_start = true,
    use_treesitter = true,
}
```
`use_treesitter:` on
![image](https://user-images.githubusercontent.com/23276734/211174808-4d747b62-95b3-4108-bed6-e994f4fc0796.png)
`use_treesitter:` off
![image](https://user-images.githubusercontent.com/23276734/211174836-3759ddf2-3cbd-473d-870d-879f18426c0c.png)

**Comment by lukas-reineke** [comment]
I might consider adding this.
But TBH, just turning treesitter indent off should give you better results in most filetypes, not just Python.

**Comment by y0nei** [comment]
> I might consider adding this. But TBH, just turning treesitter indent off should give you better results in most filetypes, not just Python.

treesitter on
![image](https://user-images.githubusercontent.com/23276734/211439117-6791feb1-759f-417b-8ff7-8744e3db315a.png)
treesitter off
![image](https://user-images.githubusercontent.com/23276734/211439194-36e9bc76-e347-4e15-996b-e90683397b93.png)

eh not really, (lua file)

**Comment by y0nei** [comment]
> I might consider adding this. But TBH, just turning treesitter indent off should give you better results in most filetypes, not just Python.

wouldnt it be possible to toggle this option on/off by cheching what filetype is the buffer in neovim?

**Comment by shasherazi** [comment]
Hi, did anyone find any solution to this yet?

**Comment by lukas-reineke** [comment]
> wouldnt it be possible to toggle this option on/off by cheching what filetype is the buffer in neovim?

You can change (almost) any option of indent-blankline global, per tab, and per buffer.
So if you want to turn off treesitter only for Python, add `vim.b.indent_blankline_use_treesitter =  false` to `ftplugin/python.lua`

I think this is a good enough solution, I won't add a dedicated option for excluding filetypes for treesitter.
