### ISSUE TITLE
Indent line looks "centered" in column in iTerm

### ISSUE THREAD

**Issue by joshweinmann** [lukas-reineke/indent-blankline.nvim#523]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/35538626/211424798-1ebd8d36-1490-4d58-bccd-fce5daf4c06c.png">

`require('indent_blankline').setup {
  space_char_blankline = ' ',
  show_trailing_blankline_indent = false,
  use_treesitter = true,
  use_treesitter_scope = true,
}`

Hello, I'm having an issue where the indent lines appear to be off just a tad to the right almost like they are centered in the column. I wasn't able to find anything in the docs or anyone else with this issue. The same thing happens when I use pass no options to the setup function.

Thanks

**Comment by joshweinmann** [comment]
I should also mention I can sort of fix the issue by using the left aligned line character https://www.compart.com/en/unicode/U+23B8#:~:text=Unicode%20Character%20%E2%80%9C%E2%8E%B8%E2%80%9D%20(U%2B23B8) as the "char" but the lines do not connect like the default

**Comment by lukas-reineke** [comment]
This is how the default character looks like. I chose it because it works with most fonts.
You can try this one instead `▎`, this one should connect.

**Comment by joshweinmann** [comment]
Gotcha. Looks good. Thanks
