### ISSUE TITLE
Toggle guides on/off function requires manual cursor move to see update

### ISSUE THREAD

**Issue by smprather** [lukas-reineke/indent-blankline.nvim#524]
I do a lot of nvim-in-terminal copy/paste. I don't want to pick up the guides when doing this. So I wrote a function to toggle them on/off. It almost works, except I have to manually move the cursor after the toggle to get a redraw with the updates. I've tried using various varieties of execute "normal! jk" and redraw. Nothing works directly from the function. I always have to move the cursor to get the update.

Neovim v0.8.1
Thanks!
--Myles

(In fact, I am toggling them off to do this copy/paste)
```vim
let g:indent_blankline_on = 1
function! s:IndentBlanklineToggle() abort
    if g:indent_blankline_on
        let g:indent_blankline_on = 0
        let g:indent_blankline_char=""
        let g:indent_blankline_show_current_context = v:false
        let g:indent_blankline_show_current_context_start = v:false
        execute "normal! j"
        redraw
        execute "normal! k"
    else
        let g:indent_blankline_on = 1
        let g:indent_blankline_char="|"
        let g:indent_blankline_show_current_context = v:true
        let g:indent_blankline_show_current_context_start = v:true
        execute "normal! j"
        redraw
        execute "normal! k"
    endif
endfunction
```

**Comment by lukas-reineke** [comment]
This is built in, you don't have to write your own function `:help IndentBlanklineToggle`

**Comment by Grazfather** [comment]
This command seems to have been dropped in v3. Could we get it back?
