### ISSUE TITLE
Indent guides replaced by fold characters while using `inc-rename.nvim`

### ISSUE THREAD

**Issue by UtkarshVerma** [lukas-reineke/indent-blankline.nvim#525]
I use [`inc-rename.nvim`](https://github.com/smjonas/inc-rename.nvim) and I noticed that the guidelines are not visible during the rename. Here's a short video.

https://user-images.githubusercontent.com/31820255/212982864-52a62b18-895d-4470-a0ed-7a8a4bf8b45c.mp4

If a tab character was used for indenting, then I would see a tab fold character instead. Is there any way I can fix this?

**Comment by lukas-reineke** [comment]
inc-rename.nvim probably overwrites the whole line. This would need to be fixed there.
