### ISSUE TITLE
Incorrect default value in docs for indent_blankline_char_blankline

### ISSUE THREAD

**Issue by fuelen** [lukas-reineke/indent-blankline.nvim#526]
Actually, I don't know what is incorrect, maybe that's a bug in code :slightly_smiling_face: 
https://github.com/lukas-reineke/indent-blankline.nvim/blob/c4c203c3e8a595bc333abaf168fcb10c13ed5fb7/doc/indent_blankline.txt#L165-L171
Looks like it defaults to `g:indent_blankline_char` in practice, as it works as intended only when I explicitly specify in config
```
char_blankline = ""
```

**Comment by lukas-reineke** [comment]
:+1: default is `g:indent_blankline_char`
