### ISSUE TITLE
Python insert mode show context errors

### ISSUE THREAD

**Issue by zippeurfou** [lukas-reineke/indent-blankline.nvim#528]
Hey there,
thanks so much for making this plugin @lukas-reineke. 
So I am having some issues having the highlight being correct in the insert mode.
It is hard to explain so I made a video.
Here is my configuration using lazy.nvim:
```
  {'lukas-reineke/indent-blankline.nvim',
    config = function()
      require("indent_blankline").setup({
        show_current_context = true,
        show_current_context_start = true,
        char = '┊',
        show_trailing_blankline_indent = true,
        -- space_char_blankline = " ",
        use_treesitter=false,
      })
    end,
  },
```
I have added comments in the video so you can follow along what I am seeing that is odd.
https://www.loom.com/share/24301822818047798569b77caa797902
The summary is as follow:
- In insert mode the context do not get highlighted unless I use `(,[,{` followed by a character.
I am using `use_treesitter=false` but I tried with it set to true and it did not change anything.
I also do not have lsp installed. Could that solve the issue?

Side question not related, Is there a way for me to have lower alpha/higher transparency for the char?

**Comment by lukas-reineke** [comment]
Treesitter just does not know the context yet while you are still typing.
You can try `:help g:indent_blankline_use_treesitter_scope`, this might give you a better result.

> Side question not related, Is there a way for me to have lower alpha/higher transparency for the char?

There is no alpha value for highlight groups. But you can change the color to be darker.

**Comment by zippeurfou** [comment]
Thanks @lukas-reineke,
> You can try :help g:indent_blankline_use_treesitter_scope, this might give you a better result.
It does indeed help when I am in the insert mode but then in normal mode it creates problem with bad highlight of the context in python.
Is there a way for me to just enable it in insert mode?

**Comment by lukas-reineke** [comment]
> Is there a way for me to just enable it in insert mode?

No, this is not supported.
I plan to make this more configurable in v3
