### ISSUE TITLE
Toggeling 'current context' during runtime

### ISSUE THREAD

**Issue by tummetott** [lukas-reineke/indent-blankline.nvim#529]
Hello,
I normally have `show_current_context` and `use_treesitter` disabled because of the performance implications for huge files.
However, I'd love to enable it from time to time. I wrote the following functions which I mapped to shortcuts in order to get this behaviour:

```lua
local function_guides_enabled = false

local enable_function_guides = function()
    require('indent_blankline.commands').enable()
    vim.g.indent_blankline_char = ''
    vim.g.indent_blankline_context_char = '│'
    local group = vim.api.nvim_create_augroup(
        'IndentBlanklineContextAutogroup',
        { clear = true }
    )
    vim.api.nvim_create_autocmd({'CursorMoved', 'CursorMovedI'}, {
        callback = function()
            vim.cmd('IndentBlanklineRefresh')
        end,
        group = group,
    })
    vim.cmd('IndentBlanklineRefresh')
    function_guides_enabled = true
end

local disable_function_guides = function()
    vim.g.indent_blankline_char = '│'
    vim.cmd('autocmd! IndentBlanklineContextAutogroup')
    vim.cmd('IndentBlanklineRefresh')
    function_guides_enabled = false
end

local toggle_function_guides = function()
    if function_guides_enabled then
        disable_function_guides()
    else
        enable_function_guides()
    end
end
```

However this only works when
```lua
use_treesitter = true
show_current_context = true
```
is set inside the `setup()` function. It has the benefit that whenever I disable function guides, the `CursorMoved` autocmd is deleted and the performance is a bit better. But unfortunately, treesitter is still queried when I scroll and the `WinScrolled` event is fired. Ideally I'd like to have two ex commads `IndentBlanklineEnableCurrentContext` and `IndentBlanklineDisableCurrentContext` (or `IndentBlanklineEnableFunctionGuides` and `IndentBlanklineDisableFunctionGuides`) which enable/disable the current context feature AND treesitter completly.

I already had a glimpse at your codebase but I guess I'm too much novice for a PR 😄

**Comment by lukas-reineke** [comment]
`use_treesitter` is not related to the context. This option is for calculating the indent level. (the naming isn't great because of backwards compatibility)
You can remove that.

I think all you need to do is add `vim.g.indent_blankline_show_current_context = true` to your function.
If you pass it in setup, it will create the autocommand. If you want to control this yourself, just set the variable in your function.

**Comment by tummetott** [comment]
That solves it perfectly thanks!
