### ISSUE TITLE
issue: context not working with certain syntax.

### ISSUE THREAD

**Issue by segfaulty1** [lukas-reineke/indent-blankline.nvim#530]
my setup:
```lua
blankline.setup{
  show_current_context = true,
  show_current_context_start = true,

  show_end_of_line = true, -- shows the char specified at the bellow lines
  space_char_blankline = " ",

  char_highlight_list = {
    "IndentBlanklineIndent2",
    "IndentBlanklineIndent1",
    "IndentBlanklineIndent4",
    "IndentBlanklineIndent3",
  }
}

vim.opt.list = true
vim.opt.listchars:append "eol:↴" 
vim.opt.listchars:append "space:."

vim.opt.termguicolors = true
vim.cmd [[highlight IndentBlanklineIndent2 guifg=#E5C07B gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent1 guifg=#E06C75 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent4 guifg=#56B6C2 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent3 guifg=#98C379 gui=nocombine]]
```

maybe the problem in treesitter idk how to debug this. but here is a visual version of the problem.
I think it's dependent on indentations:

[context start working]
<img src="https://cdn.discordapp.com/attachments/1001395159897997346/1066813035144028171/blankline-context-working.png" alt="indent-blankline context working">
[context start not working]
<img src="https://cdn.discordapp.com/attachments/1001395159897997346/1066813142446899231/blankline-context-not-working.png" alt="indent-blankline context not working">

**Comment by lukas-reineke** [comment]
please take a look here https://github.com/lukas-reineke/indent-blankline.nvim/issues/485#issuecomment-1264518353
