### ISSUE TITLE
`nvim-ufo` folds hide guidelines if `show_current_context = true`

### ISSUE THREAD

**Issue by UtkarshVerma** [lukas-reineke/indent-blankline.nvim#534]
If I try to enable the `show_current_context` option, then the guidelines are hidden for folds by [`nvim-ufo`](https://github.com/kevinhwang91/nvim-ufo):
![image](https://user-images.githubusercontent.com/31820255/215321265-72322493-e324-4d8f-a1dc-d2ed0048885f.png)

This is loosely related to https://github.com/lukas-reineke/indent-blankline.nvim/issues/441 where the fix was to set a higher priority for the characters. But that fix doesn't work with this option.

**Comment by lukas-reineke** [comment]
I don't use nvim-ufo, can you share a config to set this up?

**Comment by UtkarshVerma** [comment]
Sure, here's my config for nvim-ufo:

```lua
vim.o.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
vim.o.foldlevelstart = 99

-- passed options
    opts = {
      provider_selector = function()
        return { "treesitter", "indent" }
      end,
    },
```

Here are my configuration opts for indent-blankline:

```lua
opts = {
    char = "│",
    filetype_exclude = { "help", "alpha", "dashboard", "neo-tree", "Trouble", "lazy" },
    show_trailing_blankline_indent = false,
    char = "▏",
    context_char = "▏",
    char_priority = 50,
    show_current_context = true,
}
```

**Comment by UtkarshVerma** [comment]
@nyngwang I can still reproduce this, even after clearing out my session files.

**Comment by elliotwesoff** [comment]
I'm having this issue too without nvim-ufo. If you fold some code and then reopen it, the lines won't show. Although, it seems like it only breaks for some commands. `zc` and `zo` will still show the lines, but `zM` and then `zR` do not.

**Comment by llllvvuu** [comment]
The behavior I see with stock folds (no plugin) is that on initial load, after the first time opening the fold, the unfolded content does not have guide lines. But pressing `hjkl` in any direction makes them show up. So maybe it is some kind of event listener that's not being triggered by the fold open.

**Comment by lukas-reineke** [comment]
> So maybe it is some kind of event listener that's not being triggered by the fold open.

Yes, because that event listener does not exist. Neovim doesn't have any way to listen on open fold. This has been discussed in #449

But that is not the original issue, I believe

**Comment by nyngwang** [comment]
Now I believe the problem just emerged again at https://github.com/neovim/neovim/commit/70da793:

<img src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/24765272/c3da98cd-65be-442a-8855-a09c9c10e9ca" width="500">

**Comment by MariaSolOs** [comment]
I'm also having this issue, and I set `show_current_context = false` so I don't think that's the issue. I'm also using `nvim-ufo`.

**Comment by nyngwang** [comment]
@MariaSolOs What's your first line of `nvim -v`?

**Comment by MariaSolOs** [comment]
@nyngwang It's NVIM v0.10.0-dev-544+gd3e035257-Homebrew.

Also, what do you mean by "recreating the session files"? (sorry neovim newbie here)

This is the relevant config:
```lua
-- Whitespace and indentation guides.
return {
    {
        'lukas-reineke/indent-blankline.nvim',
        event = { 'BufReadPost', 'BufNewFile' },
        opts = {
            show_trailing_blankline_indent = false,
            char_priority = 12,
        },
        init = function()
            vim.g.indent_blankline_char_priority = 12
        end,
    },
}
```

**Comment by nyngwang** [comment]
> t's NVIM v0.10.0-dev-544+gd3e035257-Homebrew.

So the postfix `Homebrew` is the first clue we got. homebrew version is probably some commits late than the real `HEAD`. Like me check this first, as it's possible that `d3e035257` might come before [`4229bbe`](https://github.com/lukas-reineke/indent-blankline.nvim/issues/534#issuecomment-1568498137) as stated.

**Comment by MariaSolOs** [comment]
@nyngwang I just updated `neovim` and I think I should be at the tippy top of main: `NVIM v0.10.0-dev-580+gb697c0cd4-Homebrew`.

I'm still seeing this :(
<img width="598" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/62502207/1fc571bb-2e5d-464c-99e6-ee1f100e9b23">

**Comment by nyngwang** [comment]
Now let's check your `hlgroup`s. What's your `:message` output of these:

- `hi IndentBlanklineChar`
- `hi IndentBlanklineSpaceChar`
- `hi IndentBlanklineContextChar`
- `hi IndentBlanklineContextStart`

In my case, I have the following `autocmd` on `ColorScheme`:

```lua
  use {
    'lukas-reineke/indent-blankline.nvim',
    init = function ()
      vim.api.nvim_create_autocmd({ 'ColorScheme' }, {
        group = curfile_augroup,
        callback = function ()
          vim.cmd([[
            hi IndentBlanklineChar gui=nocombine guifg=#444C55
            hi IndentBlanklineSpaceChar gui=nocombine guifg=#444C55
            hi IndentBlanklineContextChar gui=nocombine guifg=#FB5E2A
            " NOTE: don't use `gui=nocombine` here to have correct coloring of gitsigns.nvim.
            hi IndentBlanklineContextStart gui=underline guisp=#FB5E2A
          ]])
        end,
      })
    end,
```

**Comment by MariaSolOs** [comment]
I FIXED IT! Okay setting `show_foldtext = false` solved the issue 🚀 
@nyngwang thanks a lot for your help ❤️

**Comment by nyngwang** [comment]
@MariaSolOs Yes, I set it to `false` too, thanks for your sharing. No one can solve your own config (no metaphor for life :P).

**Comment by lukas-reineke** [comment]
This should be handled automatically in version 3 now.

**Comment by M4D-A** [comment]
I have had a simillar problem with [AstroNvim](https://github.com/AstroNvim/AstroNvim) distribution (with v3 IBL and UFO).
Adding following lines to user configuration  `.config/nvim/lua/user/init.lua` worked for me:

``` lua
polish = function()
  require("ibl").setup {
    indent = { priority = 12 },
  }
end, 
```
