### ISSUE TITLE
Overwrite IndentBlanklineSpaceChar and IndentBlanklineSpaceCharBlankline highlight groups

### ISSUE THREAD

**Issue by tummetott** [lukas-reineke/indent-blankline.nvim#535]
Hello,

I've tried clearing the `IndenBlanklineSpaceChar` and `IndenBlanklineSpaceCharBlankline` hl-group as following:

```lua
local group = vim.api.nvim_create_augroup('indentblankline-hl', { clear = true })

vim.api.nvim_create_autocmd('ColorScheme', {
    callback = function()
        vim.api.nvim_set_hl(0, 'IndentBlanklineSpaceChar', {})
        vim.api.nvim_set_hl(0, 'IndentBlanklineSpaceCharBlankline', {})
    end,
    group = group,
})
```

However I noticed that `IndentBlankline` uses an autocmd too to create this two default highlight groups. How can I make sure that my autocmd is executed last?

I've tried `vim.schedule()` but it does not seem to work as expected.

x Tummetott

**Comment by lukas-reineke** [comment]
Why do you want to clear the highlight groups?

**Comment by tummetott** [comment]
When I turn on cursorline and define the cursorline highlight as underline
```lua
vim.api.nvim_set_hl(0, 'CursorLine', {underline = true})
```
there is a gap in the underline:

![image](https://user-images.githubusercontent.com/19708025/216593416-ac3cab6e-6ed2-49e6-b0d4-f7506d606135.png)

When i clear the both mentioned highlight groups, by running
```
hi clear IndenBlanklineSpaceChar
```

the underline is consistent:
![image](https://user-images.githubusercontent.com/19708025/216594384-89a49ea0-8e22-42d7-85cf-c6109065f57d.png)

**Comment by lukas-reineke** [comment]
I see..
There is currently no way to turn the creation of highlight groups off.
Autocommands are run in the order they are defined. You should be able to overwrite this when you put your code into `:help after-directory`

I'll think about how I can make this more user friendly.

**Comment by tummetott** [comment]
I'm already using v3 but I can't get a consistent underline. What am I missing?
<img width="737" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/19708025/a75f59c7-24a9-478e-aff6-e0b945d4d4f4">
