### ISSUE TITLE
Don't show IndentBlanklineContextStart when the cursor is on the same line

### ISSUE THREAD

**Issue by DasGandlaf** [lukas-reineke/indent-blankline.nvim#536]
Hi!
Thanks for the great plugin, I love it!
One thing that I have been noticing, is when my cursor is on a function signature f.e., it highlights it as the IndentBlanklineContextStart:
![image](https://user-images.githubusercontent.com/63406944/216824804-55dc05d9-27ec-4dad-950b-5d52e5b68c8c.png)
(Ignore the squiggly line)
My cursor is on the function signature, and that gets highlighted. Shouldn't it highlight the indent parent as context start? If it's intended, is there a way I can change this behaviour, because I cannot read the text that well because of the highlight.
Thank you!

**Comment by abulwafa** [comment]
@DasGandlaf  Set the following option to false:

show_current_context_start_on_current_line = true,

**Comment by DasGandlaf** [comment]
Oh, wow how did I miss that? Thank you 👍
