### ISSUE TITLE
Blankline only shows first identation level

### ISSUE THREAD

**Issue by elC0mpa** [lukas-reineke/indent-blankline.nvim#540]
I am a having this issue, I don´t know if I am missing some config but I think blankline should show me also these identation levels, is this ok?

![image](https://user-images.githubusercontent.com/53531665/218112466-f71305c5-8f04-41f5-98eb-95a942633768.png)

Something I am noticing is that when I insert a new line the identation level is not the one supposed:
[Screencast from 2023-02-10 09-12-40.webm](https://user-images.githubusercontent.com/53531665/218113274-ad1eaa9a-df32-4fe4-83b3-3f02b600e58d.webm)

Here I let you my blankline and treesitter config (maybe tree sitter is the responsible)

```
require("indent_blankline").setup {
     enabled = true,
     show_current_context = true,
     char = "|",
     char_blankline = '┆',
     use_treesitter = false,
     context_char = '*',
     use_treesitter_scope = false,
}
```

```
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "html", "css", "scss", "vue", "javascript", "typescript", "tsx", "svelte", "json" },
  highlight = {
    enable = true,
    use_languagetree = true,
  },
  indent = {
    enable = false
  }
}
```

**Comment by lukas-reineke** [comment]
what is `:set shiftwidth` set to?
