### ISSUE TITLE
Avoid line "bold" in current context

### ISSUE THREAD

**Issue by leandrocunha** [lukas-reineke/indent-blankline.nvim#541]
![image](https://user-images.githubusercontent.com/1820920/218785684-d3b28168-978a-4606-971a-3fc60cfeb38a.png)

There is any way to change the line for the current context to still no bold, like the regular out of the current context?
For example, I would like to this line keep pink or white lighter but not "bold" like you can see at the screenshot

**Comment by lukas-reineke** [comment]
by default it uses the same character as the normal indent char.

**Comment by lukas-reineke** [comment]
You can change the color by setting `:help hl-IndentBlanklineContextChar`

**Comment by leandrocunha** [comment]
![image](https://user-images.githubusercontent.com/1820920/219357116-9d683717-f64e-469e-a26a-0d209bbe0a77.png)

@lukas-reineke I tried set like screenshot above, but as you can see it affects all indentline instead of only the current context. What I did do wrong?

**Comment by lukas-reineke** [comment]
Nothing, this shouldn't happen. Maybe some other plugin or your colorsheme is messing with things.

in indent-blankline those are 2 separate highlight groups.

You can check from where they are set with
`:verbose hi IndentBlanklineChar`
`:verbose hi IndentBlanklineContextChar`

**Comment by windowsrefund** [comment]
I came across this thread when I wanted to do something similar and figured I'd share where I landed as I really like what's happening. Aside from the configuration, I just needed to set the colors.

`vim.cmd [[highlight IndentBlanklineContextChar guifg=#352f2d guibg=#352f2d]]
`

![Screenshot_2023-04-23_00-06-20](https://user-images.githubusercontent.com/512222/233819351-15a3885d-0b1d-49fc-afae-c7856e265a33.png)
