### ISSUE TITLE
`show_current_context` overrides `char`

### ISSUE THREAD

**Issue by jryom** [lukas-reineke/indent-blankline.nvim#542]
With `show_current_context` set to `true`, the value of `char` is ignored for the current context:

https://user-images.githubusercontent.com/2834949/219592108-726ce378-dfc4-49a9-b31c-cf7837bbcfe6.mp4

**Comment by lukas-reineke** [comment]
This happens because you try to lazy load.
For legacy reasons this is not really supported and leads to edge cases like this.
