### ISSUE TITLE
Identation behavior

### ISSUE THREAD

**Issue by noisyBrain** [lukas-reineke/indent-blankline.nvim#544]
Hi! 
Is there a way to hide that indent lines?
![1](https://user-images.githubusercontent.com/95882962/220508324-3ff11ec8-a819-46eb-96dd-1076c7abe99a.png)

Thanks in advance!

**Comment by lukas-reineke** [comment]
yes, set `:help g:indent_blankline_show_trailing_blankline_indent` to false

**Comment by noisyBrain** [comment]
Thank you!!
