### ISSUE TITLE
indent-blankline is overwriting characters in mixed space/tab indented files when shiftwidth does not equal tabstop

### ISSUE THREAD

**Issue by gautaz** [lukas-reineke/indent-blankline.nvim#547]
Hello,

To reproduce the issue, use a YAML test file with the following content:
```yaml
test:
    test1: |
        [section]
        	key = "value"
# vim: shiftwidth=4 tabstop=2
```
:warning: All the file is indented with 4 spaces but there is one tabulation before `key`.

The `indent-blankline` configuration used is: 
```lua
require('indent_blankline').setup{
  show_current_context = true,
  show_current_context_start = true,
}
```

**Without** `indent-blankline`, the file is displayed this way in neovim:
```
test:
    test1: |
        [section]
          key = "value"
# vim: shiftwidth=4 tabstop=2
```

This complies with the modeline.

**With** `indent-blankline`, the file is displayed this way in neovim:
```
test:
|   test1: |
|   |   [section]
|   |   |   y = "value"
# vim: shiftwidth=4 tabstop=2
```

It also complies with the modeline but if you look closely, the `key` word is missing its two first letters and only `y` remains.

**Comment by lukas-reineke** [comment]
:+1: mixed indentation like this is not well supported.
I want to implement this differently in v3. It probably won't get fixed in the current verison, sorry

**Comment by gautaz** [comment]
Hello @lukas-reineke, thanks for your answer :+1:.
No problem, no need for apologies, you and the other contributors are the ones providing the effort :slightly_smiling_face:.

In the meantime, this issue might remind people to ensure that `shiftwidth` needs to equal `tabstop` to avoid strange behaviors like this.
Do you mind if this issue it is kept opened until v3?

You might perhaps also have some space where you are already tracking the items envisioned for v3?
Do you mind referencing this space here if this is the case?

**Comment by lukas-reineke** [comment]
> You might perhaps also have some space where you are already tracking the items envisioned for v3?
Do you mind referencing this space here if this is the case?

I have, and it is already on the list for v3 `Use tabstop and shiftwidth per indent level instead of global for the whole buffer`
https://github.com/lukas-reineke/indent-blankline.nvim/discussions/462#discussion-4254869

**Comment by gautaz** [comment]
Does anyone know a vim/nvim plugin or any other way to ensure that `shiftwidth` = `tabstop`?
That would help working around the issue in the meantime.

I am currently using `vim-sleuth` to configure these settings automatically but it does not provide a way to ensure this equality.

**Comment by lukas-reineke** [comment]
mixed indentation is now supported with version 3
