### ISSUE TITLE
have different configurations for different filetypes

### ISSUE THREAD

**Issue by sirlan-ff00ff** [lukas-reineke/indent-blankline.nvim#549]
I may be weird, but have different preferences for how to show indentation on different languages (say, as vertical bars on something like Rust, but as dots on something like Haskell)
I at least tried with `filetype` and `filetype_exclude` and couldn't really get it to work

Is there a way to do it right now, or would it need to be an addition? If so, would be interesting being something like

```lua
require('indent_blankline').setup_ft({
    rust = { --[[...]] },
    haskell = { --[[...]] },
    default = { --[[ everything else ]] }
})
```
or maybe
```lua
require('indent_blankline').setup({
     --[[ normal config ]],
    ft_override = {
        rust = { --[[...]] },
        haskell = { --[[...]] }
    }
})
```

**Comment by lukas-reineke** [comment]
You can do this by setting buffer local variables.

eg. put `vim.b.indent_blankline_char = "H"` in `ftplugin/lua.vim` and the indent char for lua files will be `H`
