### ISSUE TITLE
The colors of indent-blankline are being reset by :set background=dark

### ISSUE THREAD

**Issue by rootex-** [lukas-reineke/indent-blankline.nvim#553]
Hi, thanks for your plugin 🤝

**Description**
While trying to setup your indent-blankline plugin, I've encountered the following issue. 
The color of the indent-blankline turns plain white every time I re-set the background to dark or light. 

**Steps to reproduce:**
1. Setup gruvbox theme & indent-blankline plugin (repro.lua file).
2. Run: `$ nvim -u repro.lua repro.lua` to run and view repro.lua demo.
3. Lazy installs all plugins.
4. Gruvbox theme & indent-blankline successfully loaded. 
5. The color of vertical tab lines is ghostly gray.
6. Now `:set background=dark`
7. The color of vertical tab lines is now plain white. 
8. Thus, the color resets every time you reset the background. 
9. Only running this command manually will recover the colors `:lua vim.cmd [[highlight IndentBlanklineIndent1 guifg=#434343 ]]`

**Run this lua file to reproduce**
```
$ nvim -u repro.lua repro.lua
```

**repro.lua**
```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    'ellisonleao/gruvbox.nvim',
    priority = 1000,
    lazy = false,
    config = function()
      require("gruvbox").setup({
      colorscheme = require("gruvbox").load()
    })
    end
  },
  {
    "lukas-reineke/indent-blankline.nvim",
    lazy = false,
    event = "BufReadPre",
    config = function()
        vim.opt.termguicolors = true
        vim.cmd [[highlight IndentBlanklineIndent1 guifg=#434343 gui=nocombine]] -- gray color of the line
        vim.opt.list = true
        require("indent_blankline").setup {
          char_highlight_list = {
            "IndentBlanklineIndent1",
          },
        }
    end
  }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Neovim**
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

**OS**
```
Macos 12.6.3
```

**Animation**
![2023-03-24 18 54 49](https://user-images.githubusercontent.com/8237030/227577980-9cc5cd50-23aa-463a-a728-7ec99300b99b.gif)

**Comment by DarkCat5501** [comment]
i'm also having the same problem, i've just installed the plugin and was setting it up to use, but it doesn't seem to be working, until I tried running it manualy after all plugins started.

**Comment by DarkCat5501** [comment]
I thing the problem is that the plugin also has an autocommand to reset its colors when the colorscheme is set
so I just added an autocommand whenever the colorscheme reloads and it does the job

```lua
vim.api.nvim_create_autocmd("ColorScheme", {
          desc = "Refresh indent colors",
          callback = function()
            vim.cmd [[hi IndentBlanklineIndent1 guifg=#E06C75 gui=nocombine]]
            vim.cmd [[hi IndentBlanklineIndent2 guifg=#E5C07B gui=nocombine]]
            vim.cmd [[hi IndentBlanklineIndent3 guifg=#98C379 gui=nocombine]]
            vim.cmd [[hi IndentBlanklineIndent4 guifg=#56B6C2 gui=nocombine]]
            vim.cmd [[hi IndentBlanklineIndent5 guifg=#61AFEF gui=nocombine]]
            vim.cmd [[hi IndentBlanklineIndent6 guifg=#C678DD gui=nocombine]]
          end,
        })
```

**Comment by lukas-reineke** [comment]
Should not be a problem in version 3 anymore
