### ISSUE TITLE
Config doesn't load automatically in Lunarvim

### ISSUE THREAD

**Issue by shellheim** [lukas-reineke/indent-blankline.nvim#554]
I am using lunarvim based on the lastest version of Neovim and every time I open a file, my config doesn't work and I get no indent lines. I have to write and source my config.lua and wait quite a few seconds to get it working. 

### My config 

--Indent Line Configuration
require("indent_blankline").setup({
        char = "┃",
        space_char_blankline = " ",
        char_highlight_list = {
                "IndentBlanklineIndent1",
                "IndentBlanklineIndent2",
                "IndentBlanklineIndent3",
                "IndentBlanklineIndent4",
                "IndentBlanklineIndent5",
                "IndentBlanklineIndent6",
        },
})
vim.opt.termguicolors = true
vim.cmd([[highlight IndentBlanklineIndent1 guifg=#E06C75 gui=nocombine]])
vim.cmd([[highlight IndentBlanklineIndent2 guifg=#E5C07B gui=nocombine]])
vim.cmd([[highlight IndentBlanklineIndent3 guifg=#98C379 gui=nocombine]])
vim.cmd([[highlight IndentBlanklineIndent4 guifg=#56B6C2 gui=nocombine]])
vim.cmd([[highlight IndentBlanklineIndent5 guifg=#61AFEF gui=nocombine]])
vim.cmd([[highlight IndentBlanklineIndent6 guifg=#C678DD gui=nocombine]])

It's from [here](https://github.com/lukas-reineke/indent-blankline.nvim#with-custom-gindent_blankline_char_highlight_list), I have only removed the three lines in the middle that add additional characters.

**Comment by lukas-reineke** [comment]
This config looks fine, it should work.
The problem is probably somewhere else.
