### ISSUE TITLE
Treesitter context stops working after first edit

### ISSUE THREAD

**Issue by ReubenM** [lukas-reineke/indent-blankline.nvim#555]
With "use_treesitter_scope" and "show_current_context" both enabled, the scope appears to work correctly at first within a python buffer. The indentline highlight indicates scope of functions, classes, etc. But once an edit is made to the buffer, from that point on the scope highlight just follows the indentation as it would if the "use_treesitter_scope" option were not enabled.

**Comment by ReubenM** [comment]
Found same issue in lua, so not a python specific issue.

**Comment by lukas-reineke** [comment]
Can you make a minimal config to reproduce the issue?

**Comment by ReubenM** [comment]
Ok, I was worried that it would be hard to re-produce in a minimal setup. But I was able to cut it down to just Lazy, nvim-treesitter, and indent-blankline.

```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable",
		lazypath,
	})
end
vim.opt.rtp:prepend( lazypath )

vim.o.termguicolors = true

require( 'lazy' ).setup({
	{
		'lukas-reineke/indent-blankline.nvim',
		dependencies = { 'nvim-treesitter/nvim-treesitter' },
		config = function()
			require( 'indent_blankline' ).setup {
				char                 = '┆',  
				context_char         = '┆',
				use_treesitter       = true,
				use_treesitter_scope = true,
				show_current_context = true,
				show_end_of_line     = true,
			}
		end
	},
})
```

This init reproduces on my system. So for example if you open this init file, and move the cursor into the "require" section the context indicator remains on the "config = function" indent level. But make an edit and the context starts to follow indentation.

Interesting thing is, if I comment out the "use treesitter = true" line, it no longer breaks the context tracking after making an edit. But it's not as simple as just something wrong with the indent_blankline settings. If I go back to my original init and comment out the line, it doesn't fix the issue. But sometimes it may or may not work depending on what other plugins are disabled that also use treesitter. I think this has something to do with multiple interactions with nvim-treesitter from different sources that somehow mess up the treesitter context tracking state in your plugin (or something to that effect).

**Comment by lukas-reineke** [comment]
Sorry, I still can't reproduce the issue. Everything is working fine for me with this config.


https://user-images.githubusercontent.com/12900252/229390362-f4df03d5-9fe1-45f8-815d-86b7dc21c55a.mp4

**Comment by ReubenM** [comment]
The issue does not manifest itself till after modifying the buffer, see attached recording:


https://user-images.githubusercontent.com/45847/229417064-14030538-b51b-4b3e-8341-bb2010bd921e.mp4

**Comment by lukas-reineke** [comment]
Ah I see, now I understand. And I can reproduce it.
But this is not a bug in indent-blankline. This is what treesitter returns as the current scope. It's something in https://github.com/nvim-treesitter/nvim-treesitter

Basically this is what indent-blankline calls. And nvim-treesitter returns something different after the buffer was modified.
`:lua print(require("nvim-treesitter.locals").containing_scope(require("nvim-treesitter.ts_utils").get_node_at_cursor(), 0):range())`

**Comment by ReubenM** [comment]
yes, and the odd part is, if you remove the line "use_treesitter = true" (and then restart neovim with the edited file opened) the issue is no longer reproducible  after making an edit.
