### ISSUE TITLE
Indentation lines stop at preprocessor directives

### ISSUE THREAD

**Issue by ichirou2910** [lukas-reineke/indent-blankline.nvim#556]
As the title says, when I put directives (e.g. `#define`, `#if`) it would stop the identation lines, which means all lines below it doesn't have indentation lines. Is it possible to skip these "irregular lines" and keep the identation going down?
![image](https://user-images.githubusercontent.com/51302893/229093449-754dd26d-5093-404f-849b-ef61ace9a44e.png)

**Comment by lukas-reineke** [comment]
can you share the example code for which this happens, and the indent-blankline config you are using?

**Comment by ichirou2910** [comment]
Here is a sample c# snippet

```cs
class TestClass
{
    void TestMethod(bool testArg)
    {
#region Test code
        if (testArg)
            Console.WriteLine(
                @"Hello,
This is a paragraph
with multiple lines"
            );
        else
        {
            Console.WriteLine("Hello, this is a single line");
        }
#endregion
    }

    void AnotherMethod()
    {
        Console.WriteLine("Ohhhhhhh!");
    }
}
```

which will be shown like this

![image](https://user-images.githubusercontent.com/51302893/229404125-6387cb56-db6c-4d0b-b3a6-80e704976713.png)

My current config:

```lua
require("indent_blankline").setup({
    viewport_buffer = 100,
    char = "▏",
    context_char = "▏",
    filetype_exclude = {
        -- ...
    },
    context_highlight_list = {
        -- ...
    },
    context_start_highlight_list = {
        -- ...
    },
    space_char_blankline = " ",
    use_treesitter = true,
    show_current_context = true,
    show_current_context_start = true,
    show_trailing_blankline_indent = false,
    show_first_indent_level = true,
    show_foldtext = false,
    strict_tabs = true,
    max_indent_increase = 1,
})
```

**Comment by lukas-reineke** [comment]
You have `max_indent_increase` set to 1, but the indent level in the `Test code` region increases by 2.
Remove `max_indent_increase`, or set it to a higher value, and it should work.

**Comment by ichirou2910** [comment]
Ohhhh it works well now. Thanks a lot!
