### ISSUE TITLE
Bug with <a> tag with VueJS

### ISSUE THREAD

**Issue by Elteoremadebeethoven** [lukas-reineke/indent-blankline.nvim#557]
I already ruled out that this is due to treesitter, it only happens with the <a> tags, with the others it works fine, it happens with all the themes I have:

![t1](https://user-images.githubusercontent.com/43224662/229122065-e7b68b2c-8d4b-4dbd-a01f-31be83766682.gif)
![t2](https://user-images.githubusercontent.com/43224662/229122069-c4751909-bf96-4a9a-a52a-4b5a006950f1.gif)

My config with Lazy:
```lua
 -- Installation
  { 
    'lukas-reineke/indent-blankline.nvim',
    opts = {
      char = '│',
      show_trailing_blankline_indent = false, -- if i delete this nothing happens
    },
  }
-- Config:
local status_indent, indent_line = pcall(require, 'indent_blankline')
if (not status_indent) then
  print("Indent blankline not added")
else
  indent_line.setup {
    space_char_blankline = " ",
    show_current_context = true,
  }
end

```

And this also happens with LunarVim and NvChad.

And if I put the configuration directly in Lazy the same thing happens.

My hypothesis is that this would be solved if in Treesitter we remove the option to draw the underline, but I have not found how to do that.

**Comment by Elteoremadebeethoven** [comment]
Got it, almost all problems are solved by looking at the source code.

The problem is this:

```lua
-- some-theme.groups.lua
groups = {
...
      ["@text.uri"] = { link = "Underline" },
...
}
```
If you change this value to something else it solves the problem, but I still think this bug should be solved here, and should not affect Treesitter, so I'll leave this as a temporary fix for anyone who cares.

**Comment by lukas-reineke** [comment]
Can you make a minimal config to reproduce this?
