### ISSUE TITLE
Feature request: Don't add indent lines inside strings and block comments

### ISSUE THREAD

**Issue by Hubro** [lukas-reineke/indent-blankline.nvim#559]
Since indent-blankline.nvim is already powered by Treesitter, I think it would be cool if it could use this to prevent adding indent-lines inside multi-line strings and block comments.

Here is an example:

![image](https://user-images.githubusercontent.com/597206/230158494-0fb6cc61-7b1c-46ac-9d03-76d33f0ab67d.png)

These indentation lines don't provide any value an just add noise.

**Comment by lukas-reineke** [comment]
:+1: I will consider this for version 3.

FYI you can set `max_indent_increase = 1` to get a similar result already.

**Comment by Hubro** [comment]
That actually solves the problem completely in this particular case :smile:

**Comment by lukas-reineke** [comment]
This should now work in version 3
