### ISSUE TITLE
Don't show indentation in dashboard.nvim

### ISSUE THREAD

**Issue by TroySigX** [lukas-reineke/indent-blankline.nvim#566]
I have the following error when opening [dashboard.nvim](https://github.com/nvimdev/dashboard-nvim) startup page:
![image](https://user-images.githubusercontent.com/88051085/234989781-3d329dbd-d844-43ac-836e-7bd71b1b41fe.png)

The indentation is showing up after [this commit](https://github.com/nvimdev/dashboard-nvim/commit/a8ffd675976e466400a4b649a79269a666057931).

**Comment by lukas-reineke** [comment]
It shows up now because dashboard.nvim removed `buftype=nofile`

You can still exclude it by changing one of `:help g:indent_blankline_filetype_exclude`, `:help g:indent_blankline_buftype_exclude`, or `:help g:indent_blankline_bufname_exclude`. Or you ask dashboard.nvim to put `nofile` back.
