### ISSUE TITLE
Underlining with context indent highlighted by treesitter not working

### ISSUE THREAD

**Issue by StefanoDalMas** [lukas-reineke/indent-blankline.nvim#567]
At the moment I'm trying to have both the lines rainbow like and I want to be able to underline the function name that I'm in like in the example shown in the Readme file, but I can't. I'm using NVChad and TreeSitter is correctly working
<img width="1440" alt="Screenshot 2023-04-28 alle 16 04 28" src="https://user-images.githubusercontent.com/95777850/235169436-fa30104f-fb24-47aa-b520-39b07799ac06.png">

These are the configurations given to the setup function at the moment. These are in the NVChad setup
M.blankline = {
  indentLine_enabled = 1,
  filetype_exclude = {
    "help",
    "terminal",
    "lazy",
    "lspinfo",
    "TelescopePrompt",
    "TelescopeResults",
    "mason",
    "nvdash",
    "nvcheatsheet",
    "",
  },
  buftype_exclude = { "terminal" },
  show_trailing_blankline_indent = false,
  show_first_indent_level = false,
  show_current_context = true,
  show_current_context_start = true,
}

And I add
space_char_blankline = " ",
            show_current_context_start = true,
            char_highlight_list = {
                "IndentBlanklineIndent1",
                "IndentBlanklineIndent2",
                "IndentBlanklineIndent3",
                "IndentBlanklineIndent4",
                "IndentBlanklineIndent5",
                "IndentBlanklineIndent6",
            },
            Giving for IndentBlanklineIndent the colors I want in the tab

**Comment by StefanoDalMas** [comment]
These are the configurations given to the setup function at the moment. These are in the NVChad setup
M.blankline = {
  indentLine_enabled = 1,
  filetype_exclude = {
    "help",
    "terminal",
    "lazy",
    "lspinfo",
    "TelescopePrompt",
    "TelescopeResults",
    "mason",
    "nvdash",
    "nvcheatsheet",
    "",
  },
  buftype_exclude = { "terminal" },
  show_trailing_blankline_indent = false,
  show_first_indent_level = false,
  show_current_context = true,
  show_current_context_start = true,
}

And I add
space_char_blankline = " ",
            show_current_context_start = true,
            char_highlight_list = {
                "IndentBlanklineIndent1",
                "IndentBlanklineIndent2",
                "IndentBlanklineIndent3",
                "IndentBlanklineIndent4",
                "IndentBlanklineIndent5",
                "IndentBlanklineIndent6",
            },
            Giving for IndentBlanklineIndent the colors I want in the tab

**Comment by lukas-reineke** [comment]
You don't need the `indentLine_enabled`, otherwise your config looks fine.
The position the cursor is in the screenshot would not underline any function.

**Comment by mayakrunal** [comment]
had similar issue, setting the IndentBlanklineContextStart hightlight did the trick. 

highlight IndentBlanklineContextStart guisp=#00FF00 gui=underline

make sure you have set  `vim.opt.termguicolors = true `
