### ISSUE TITLE
buftype_exclude ignored: still seeing indent guides

### ISSUE THREAD

**Issue by mjlbach** [lukas-reineke/indent-blankline.nvim#57]
I'm on the lua branch, I have the following settings configured:

```
vim.g.indent_blankline_char = "┊"
vim.g.indent_blankline_filetype_exclude = { 'help' }
vim.g.indent_blankline_buftype_exclude = { 'terminal', 'nofile', 'packer'}
vim.g.indent_blankline_char_highlight = 'LineNr'
```

Yet I'm still getting indent guides in my packer window:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/13316262/110999561-6707c580-8335-11eb-9aee-bca7a922a6bd.png">

I also tried toggling indent guides with `:IndentBlanklineDisable`/`:IndentBlanklineRefresh` and `:redraw` but was not able to clear the lines.

This previously used to work, so I'm not sure if something has changed. I can bisect at some point but wanted to open the issue.

**Comment by lukas-reineke** [comment]
I am not that familiar with packer.nvim, but wouldn't `packer` be the filetype, not the buftype?
Can you confirm that it is buftype, `set buftype`

Also not sure why `IndentBlanklineDisable` wouldn't work :thinking:

**Comment by mjlbach** [comment]
> I am not that familiar with packer.nvim, but wouldn't packer be the filetype, not the buftype?

Oof that was it, I feel like this used to work so not sure what happened.

> Also not sure why IndentBlanklineDisable wouldn't work

Yes, that confused me as well, but I'll close since the main issue was a mistake on my part :) Sorry for the noise!
