### ISSUE TITLE
Chars disappear after code formatting

### ISSUE THREAD

**Issue by am-on** [lukas-reineke/indent-blankline.nvim#572]
In elm using `Zaptic/elm-vim` plugin.

https://github.com/lukas-reineke/indent-blankline.nvim/assets/8530224/d3fc1bd3-0d2a-4924-aeee-0b23a2ada790

**Comment by lukas-reineke** [comment]
I need more information to help

**Comment by MarcoBuess** [comment]
I guess its somewhat related to #241. I just had a similar issue in a `.gitconfig` file which is indented with `tabs` (`> `) by default. First char after `tab` is hidden there as well. Disabling the plugin or converting indentation to spaces solves the issue for me. I'm to unexperienced with nvim though so I'm not able to figure out what the issue with `listchars` might or the plugin might be.
