### ISSUE TITLE
show_current_context_start not working for me

### ISSUE THREAD

**Issue by vadymbiliuk** [lukas-reineke/indent-blankline.nvim#573]
Hey. I'm trying to achieve view of my indent-blanklline exactly like on the screenshot in readme
![](https://user-images.githubusercontent.com/12900252/188080732-5b7d98b9-3cb8-4789-b28d-67cad0bfbcde.png)

But i'm getting a bit wrong behaviour
<img width="1625" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/29184291/6f963dee-1690-4ee0-ab8b-e36b569342d9">

**My font**: JetBrainsMono Nerd Font
**My terminal**: Kitty
**Kitty config**: 
font_family                   JetBrainsMono Nerd Font 
bold_font                        JetBrainsMono Nerd Font Bold
italic_font                        JetBrainsMono Nerd Font Italic
bold_italic_font              JetBrainsMono Nerd Font Bold Italic
font_size                         16
modify_font                     strikethrough_position 120%
modify_font                     strikethrough_thickness 250%
modify_font                     underline_position 125%
modify_font                     underline_thickness +1
modify_font                     cell_height 105%
undercurl_style               thin-dense

**My config**:
     char = '│',
      show_foldtext = false,
      context_char = '▎',
      char_priority = 12,
      show_current_context = true,
      show_current_context_start = true,
      show_current_context_start_on_current_line = false,
      show_first_indent_level = true,
      -- stylua: ignore
      filetype_exclude = {
        'dbout', 'neo-tree-popup', 'log', 'gitcommit',
        'txt', 'help', 'NvimTree', 'git', 'flutterToolsOutline',
        'undotree', 'markdown', 'norg', 'org', 'orgagenda',
        '', -- for all buffers without a file type
      },

**Comment by nilsherzig** [comment]
this works for me 

```lua
require("indent_blankline").setup {
    char = '│',
    show_foldtext = false,
    context_char = '▎',
    space_char_blankline = " ",
    show_current_context = true,
    show_current_context_start = true,
}
```

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/72463901/16bebc30-850b-4488-9862-82214052ee36)

**Comment by lukas-reineke** [comment]
Your config looks fine, the problem has to be somewhere else

**Comment by vadymbiliuk** [comment]
I found that issue was with theme. Thanks for help
