### ISSUE TITLE
Indent guide issue when conceal is used

### ISSUE THREAD

**Issue by mctwynne** [lukas-reineke/indent-blankline.nvim#574]
When using the following to conceal leading spaces the indentation guides cut off the beginning of the line of code as seen in the screenshots. Is there anything I can do to have these work together? Thank you!

```
syntax match spaces '\v(^( {4})*)@<=( {4})' conceal cchar= " single space indentation
set concealcursor=nvi
set conceallevel=2
```

With the plugin enabled:
<img width="144" alt="broken" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/22352286/eda6a1bd-f881-45b2-a650-ba3caef484e0">

Without the plugin enabled:
<img width="193" alt="working" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/22352286/996b6de3-bcc5-4187-8764-224b8e87b226">

**Comment by lukas-reineke** [comment]
No sorry, calculating all concealed whitespace would be a lot of work. And this looks like a very unusual thing to do.
I won't support this.

**Comment by mctwynne** [comment]
@lukas-reineke No problem! I was mostly curious if it was something you already supported or had a quick fix for. Thanks for taking the time to respond.
