### ISSUE TITLE
Colorizing of indent line is not working

### ISSUE THREAD

**Issue by MannyFay** [lukas-reineke/indent-blankline.nvim#576]
Is there anything wrong with?
I've tried to load it before and after my colorscheme plugin.
~/.config/nvim/lua/user/plugins.lua:
```
-- Show vertical indent lines for blocks:
use({
  'lukas-reineke/indent-blankline.nvim',
  require = function()
    require('user.plugins.indent-blankline')
  end,
})
```

~/.config/nvim/lua/user/plugins/indent-blankline.lua:
```
------------------------------------------------------------------------------
-- Indent Blankline Plugin
------------------------------------------------------------------------------

-- Import Indent Blankline with a protected call:
local indent_blankline_status_ok, indent_blankline = pcall(require, 'indent_blankline')
if not indent_blankline_status_ok then
  return
end


------------------------------------------------------------
-- Appearance

-- Set color of indent-blankline plugin for vertical lines:
vim.cmd([[highlight IndentBlanklineChar guifg='#252525' gui=nocombine]])

indent_blankline.setup({
  char_highlight_list = {
    -- Call color variable:
    'IndentBlanklineChar',
  },
    filetype_exclude = {
    'help',
    'terminal',
    'dashboard',
    'packer',
    'lspinfo',
    'TelescopePrompt',
    'TelescopeResults',
  },
  buftype_exclude = {
    'terminal',
    'NvimTree',
  },
  show_trailing_blankline_indent = false,
  show_first_indent_level = true,
})
```
...termguicolors is already activated.
If I manually source `indent-blankline.lua`, my color works. But not if I start Neovim regularly.

**Comment by bradfordleak** [comment]
I was having the same problem and setting the highlight groups in `after/plugin` works for me.  For example, I have the following file: `after/plugin/colors.lua`

```
vim.api.nvim_set_hl(0, "IndentBlanklineIndent1", {fg = "#E06C75"})
vim.api.nvim_set_hl(0, "IndentBlanklineIndent2", {fg = "#E5C07B"})
```
etc, etc
This enables the colors on start of opening the buffer rather than re-sourcing indent-blankline (I'm using lazy plugin manager but not sure if that matters)

**Comment by MannyFay** [comment]
Hi @bradfordleak :)
Thanks for your reply!!

I've tried that (I'm using Packer). It doesn't work for me :/

I've created `~/.config/nvim/after/colors.lua` which schould work properly too.  
Then I've tried:  
`vim.api.nvim_set_hl(0, 'IndentBlanklineIndent', { fg = '#252525 })`  
and  
`vim.cmd([[highlight IndentBlanklineChar guifg=#252525]])`  

Both doesn't work, so I've put it in [my own color scheme](https://github.com/MannyFay/mannydark.nvim/blob/main/lua/mannydark/theme.lua) on line 17.

Now it works. I don't understand why. I've switched the order of loading the color scheme and indent-blankline in my plugins.lua in all circumstances without any success. ..crazy behavior?!

**Comment by lukas-reineke** [comment]
This is not really related to indent-blankline. Whatever highlight group is set last takes priority. If you get a wrong color, it means there is an issue with the order you set the highlight groups.
When you load indent-blankline doesn't matter.

You can check where a highlight group was last set with `:verbose highlight IndentBlanklineChar`

I'll close this ticket, this is nothing I can fix. It's a problem with your config.

**Comment by MannyFay** [comment]
Thanks for the hint and the command, @lukas-reineke :)

No I'm able to go fishing :)

**Comment by v3s1e** [comment]
@MannyFay Did you figure this out?

I am having the same issue. I tried defining the highlight groups I want before and after sourcing the plugins with no success.

I can get it to stay only by setting it in a callback passed to `vim.schedule()`.

**Comment by lukas-reineke** [comment]
> I tried defining the highlight groups I want before and after sourcing the plugin with no success.

When you source indent-blankline does not make a difference.
It is probably your color scheme that overwrites the highlight groups, you want to define them after you load that.
