### ISSUE TITLE
Indent guides on wrapped lines

### ISSUE THREAD

**Issue by musjj** [lukas-reineke/indent-blankline.nvim#577]
Word wrapping tend to cause the rendered guidelines to be broken up:

![image](https://user-images.githubusercontent.com/72612857/232233546-a46d7da1-062c-4ac7-a8d2-2f548eb3663d.png)

This used to be impossible to fix, but a recent PR made it so that you can now draw virtual text on wrapped lines with `virt_text_win_col`: 

- https://github.com/neovim/neovim/issues/23108#issuecomment-1565890709
- https://github.com/neovim/neovim/pull/23759.

It would be nice if this plugin can take advantage of this new feature.

Related issue: https://github.com/lukas-reineke/indent-blankline.nvim/issues/149

**Comment by lukas-reineke** [comment]
This is now available with the latest Neovim nightly version.
Thanks @luukvbaal
