### ISSUE TITLE
[Lua branch] Option to disable indent-blankline when in `diff` mode

### ISSUE THREAD

**Issue by bluz71** [lukas-reineke/indent-blankline.nvim#58]
Hello,

Just testing out the latest version as a full indentLine replacement. Looking great except for diff mode.

I use Neovim as my git diff viewer, and I have always found indentLine distracting whilst diffing so I disabled it with this snippet:

```
    if &diff
        :IndentLinesDisable
    endif
```

That worked.

But I can't achieve the same effect with indent-blankline.

Ideally I would like something like:

```
let g:indent_blankline_diff_exclude = v:true
```

Is something like possible?

Best regards.

**Comment by lukas-reineke** [comment]
I can totally see that an option like that would be useful. But on the other side I'd like to avoid adding a bunch of very specific options.

Maybe a user provided function to extend `set_indent_blankline_enabled` would be nice.
But all the config currently happens in vimscript land for legacy reasons. If I add that, I would want that function to be lua, and there is no good way I know of to pass a lua function through vimscript.


I don't think I will add an option specific for diff mode. But it is a good idea to make disabling the plugin more extendable. I will think about it.

**Comment by bluz71** [comment]
If there was a function that could universally disable indent-blankline instantly in all visible windows then that would be enough for me since I could do as I did with indentLine.vim:

```viml
function! diff#Styling() abort
    if &diff
        :IndentBlanklineDisableEverywhereNow
    endif
endfunction

autocmd VimEnter * windo call diff#Styling()
```

The current indent-blankline disable functions don't kick in like the indentLine disable function does in the above scenario. I still see indent guides in diffs which I really don't want.

So maybe not a `diff` specific option, but a `IndentBlankLineDisable` that could works if invoked as above.

**Comment by lukas-reineke** [comment]
Global commands is definitely a good idea. :+1: 

I pushed an update now, so you can add `!` to all the commands to make them global.

I still also think user defined functions for enabled/disabled would be nice. Just need to figure out a good way to implement it.

**Comment by bluz71** [comment]
Question, why does `:IndentBlanklineDisable!` not work when invoked from `VimEnter`?

```viml
autocmd VimEnter * :IndentBlanklineDisable!
```

If I invoke it interactively after Neovim has started it works, but not from the autocmd. If I could get it working from `VimEnter` autocmd then I could totally solve this issue.

Note, the equivalent indentLine disable function does work from `VimEnter`.

Maybe we are not far away?

**Comment by bluz71** [comment]
Here are screenshots.

Current diff behaviour (with indent markers):

![Diff_1](https://user-images.githubusercontent.com/11382509/111421772-ac673100-8741-11eb-947c-d7fc9421251e.png)

And how I want it to look with indent guides disabled (just for diff):

![Diff_2](https://user-images.githubusercontent.com/11382509/111421807-b8eb8980-8741-11eb-8eb3-ac7b7d6ff3bb.png)

**Comment by lukas-reineke** [comment]
It should work fine on `VimEnter`

**Comment by bluz71** [comment]
It doesn't from my testing.

```viml
autocmd VimEnter * if &diff | :IndentBlanklineDisable!
```

I don't understand why that doesn't work.

**Comment by lukas-reineke** [comment]
I think I found the problem.
`VimEnter` and `Syntax` autocomands both triggered, and depending on which one was faster, the indent lines show up or they don't.
So it works on a big file, because `Syntax` takes longer, but not on a small file.

I just removed `Syntax` from the list of autocommands now, it is not really needed anyways.
Can you try again?

**Comment by bluz71** [comment]
@lukas-reineke,

Awesome! That works perfect.

Thank you very very much.

**Comment by lukas-reineke** [comment]
Sorry I actually have to break this again.
I have to add `BufWinEnter` to the autocommands, or the toggle doesn't work after switching windows.

I tried to find a different solution for `diff`, but I don't think it's possible. The window option `diff` is not set in time, so even with a dedicated plugin option it wouldn't work.
I would need to change the whole enabling/disabling logic, which I do not want to do. 

If you don't care about toggle not working properly on switching windows (re-enabling the plugin and switching to a different window will not update the window, until you scroll or manually update)
you can just overwrite the autocommand to exclude `BufWinEnter`

```vim
augroup IndentBlanklineAutogroup
    autocmd!
    autocmd OptionSet shiftwidth,tabstop IndentBlanklineRefresh
    autocmd FileChangedShellPost,TextChanged,TextChangedI,WinScrolled * IndentBlanklineRefresh
    autocmd VimEnter * call s:IndentBlanklineInit()
augroup END
```

**Comment by bluz71** [comment]
Good news, the following works well:

```viml
autocmd BufReadPost * if &diff | :IndentBlanklineDisable!
```

Good enough for my use case.

Thanks for a great plugin.

**Comment by bluz71** [comment]
Folks reading this, you don't need to do the above autocmd hacks, this `vimrc` or `init.vim` statement is simpler and works better:

```viml
if &diff
    let g:indent_blankline_enabled = v:false
endif
```
