### ISSUE TITLE
Feature request: Special support for tab characters

### ISSUE THREAD

**Issue by Jasha10** [lukas-reineke/indent-blankline.nvim#583]
Is it possible to have tabs be visually distinct from spaces?

As mentioned in issue #502, you can do `let g:indent_blankline_char = ""` to use the built-in `listchars` setting. However, this solution seems to prevent indent-blankline from handling space-indentation in a nuanced way, and it makes `g:indent_blankline_char` have no effect.

**Comment by Jasha10** [comment]
Nevermind, I've had some success combining `b:indent_blankline_char = ""` with `setlocal listchars+=tab:▸\ ` and `g:indent_blankline_char_list = ['|', '¦', '┆', '┊']`.

**Comment by lukas-reineke** [comment]
> As mentioned in issue https://github.com/lukas-reineke/indent-blankline.nvim/issues/502, you can do let g:indent_blankline_char = "" to use the built-in listchars setting

You misunderstood what I wrote in #502. If you have listchars on, it will be used by default. Setting `g:indent_blankline_char = ""` is not related to that. You can set it to something else.
