### ISSUE TITLE
Current context stops being highlighted after a number of lines

### ISSUE THREAD

**Issue by Froloket64** [lukas-reineke/indent-blankline.nvim#584]
I have noticed, that once I move `45` lines down from the current context start, the context stops being highlighted. This happens both when I move in and out of nested contexts (also on all layers) and when there's no nesting.
It reappears if I move `27` lines up.

https://github.com/lukas-reineke/indent-blankline.nvim/assets/59119389/3521083c-4a7c-4502-95b4-4ccf89139b81

Here's the config:
```lua
require("indent_blankline").setup {
    char = "▏",
    context_char = "▏",
    show_current_context = true,
    show_current_context_start = false,
    context_highlight_list = { "Warning" },
    context_patterns = {
        -- Defaults
        "class",
        "^func",
        "method",
        "^if",
        "while",
        "for",
        "with",
        -- ...other patterns...
    },
    show_trailing_blankline_indent = false,
    max_indent_increase = 1,
    use_treesitter = false,
}

```

Neovim: `v0.9.1`
indent-blankline: 7075d7861f7a6bbf0de0298c83f8a13195e6ec01

**Comment by lukas-reineke** [comment]
That is expected behavior, take a look at `:help g:indent_blankline_viewport_buffer` to configure this.

**Comment by Froloket64** [comment]
Oh thanks, I somehow overlooked it when going through `:h indent-blankline`, my bad)
