### ISSUE TITLE
 Intereference with Latex

### ISSUE THREAD

**Issue by AbdullahZubair-UW** [lukas-reineke/indent-blankline.nvim#585]
Whenever I load a new .tex document buffer it does not render the initial column of the entire file. So for example, `\begin{defn}` gets rendered as `gin{defn}` and the former part is just blank. What could this be?

**Comment by lukas-reineke** [comment]
I need more information to help you. Please make a minimal configuration to reproduce the issue.

**Comment by AbdullahZubair-UW** [comment]
Here is my config file (Im using Lazy as a package manager)
`local M = {
  "lukas-reineke/indent-blankline.nvim",
  event = "BufReadPre",
}

M.opts = {
  char = "▏",
  show_trailing_blankline_indent = false,
  blankline_indent_level = 4,
  show_first_indent_level = true,
  use_treesitter = true,
  show_current_context = true,
  buftype_exclude = { "terminal", "nofile" },
  filetype_exclude = {
    "help",
    "packer",
    "NvimTree",
  },
}

return M
`

**Comment by lukas-reineke** [comment]
Just this does not reproduce the issue for me

**Comment by AbdullahZubair-UW** [comment]
Sorry I am fairly new to GitHub. What exactly am I supposed to do to give you a minimal config?

**Comment by AbdullahZubair-UW** [comment]
Actually my problem is very similar to #572.

**Comment by lukas-reineke** [comment]
I need a fully working, minimal `init.lua` file that causes this error.
It is most likely a combination of settings and or plugins you use.

Start with this

```lua
-- init-min.lua
local lazypath = "/tmp/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system {
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable",
        lazypath,
    }
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup {
    "lukas-reineke/indent-blankline.nvim",
    opts = {
        char = "▏",
        show_trailing_blankline_indent = false,
        blankline_indent_level = 4,
        show_first_indent_level = true,
        use_treesitter = true,
        show_current_context = true,
        buftype_exclude = { "terminal", "nofile" },
        filetype_exclude = {
            "help",
            "packer",
            "NvimTree",
        },
    },
}
```

And run it with `nvim --clean -u init-min.lua`

Now you have a clean instance of Neovim with only indent-blankline.
From there, describe what I need to do, or what setting I need to add, to get the same issue.

**Comment by AbdullahZubair-UW** [comment]
Okay, so after playing around with it extensively, it turns out that when I have `vim.opt.shiftwidth` set to any non-zero value, it causes the rendering glitch to occur. If I set it to zero, then it does not occur. Of course I would like this value to be non-zero.

**Comment by lukas-reineke** [comment]
Please describe step by step what I need to do to get the issue, with the above config, and with what latex text.

`shiftwidth` defaults to a non zero value, this is not the cause for this error, or everyone would have it.

**Comment by lukas-reineke** [comment]
Thank you, now I understand what you are doing.

Your configuration does not make sense. Your file is indented with tabs, and you set tabs to be just one character wide with `tabstop`. But you set `expandtab` to true, which indent-blankline interprets as you want to indent with spaces. And you set the width of spaces to 4 with `shiftwidth`.

So to fix this, set `expandtab` to false if you want to indent with tabs.
