### ISSUE TITLE
with context indent highlighted by treesitter don't work.

### ISSUE THREAD

**Issue by enesemreaydogan** [lukas-reineke/indent-blankline.nvim#587]
I want to make it work with context indent highlighted by treesitter.
that's my config file.
what did i wrong ?

I use Arch Linux and kitty term. my neovim version is 0.10
![2023-07-04_15-03](https://github.com/lukas-reineke/indent-blankline.nvim/assets/137614305/eb7b62c6-c4af-47c8-b750-16252f19c3af)

**Comment by enesemreaydogan** [comment]
I set show_first_indent_level to false. my mistake. But i want to know why active context become grey and others colorized ?

**Comment by lukas-reineke** [comment]
Context uses a different highlight group, see `:help hl-IndentBlanklineContextChar` and `:help hl-IndentBlanklineContextSpaceChar`
