### ISSUE TITLE
Bug: Cursor flicker when undoing after changing a line

### ISSUE THREAD

**Issue by Subjective** [lukas-reineke/indent-blankline.nvim#589]
Changing a line with `cc` and undoing leads to a weird visual artifact where a cursor (or indent virtual text?) seems to appear for a brief moment at the end of the line before disappearing. 

![Screen Recording 2023-07-05 at 6 57 31 PM](https://github.com/lukas-reineke/indent-blankline.nvim/assets/56745535/b4e01b91-8b3f-408b-8b6a-6bb89fc40bf8)

Edit: it seems like this also happens when performing `cc` on a blank line.

![Screen Recording 2023-07-05 at 7 35 52 PM](https://github.com/lukas-reineke/indent-blankline.nvim/assets/56745535/2805c191-3ca1-4ec9-9f19-8f9758caab5c)

**Comment by lukas-reineke** [comment]
This is a limitation of how virtual text works, there is no way to fix this.
