### ISSUE TITLE
latest change causes annoying "no parser for '<lang>'" warnings

### ISSUE THREAD

**Issue by aikow** [lukas-reineke/indent-blankline.nvim#591]
Commit 43298ff0 added the `local cursor_node = vim.treesitter.get_node()` line in `utils.lua`, which will fail for every buffer that doesn't have a tree-sitter parser, including buffers for nvim-cmp, diffview.nvim, neo-tree, etc. I'm not sure whether this behavior was intended or not, and I'm not sure what the best way to suppress the message is. But adding all of those filetypes to an `exclude_filetype` list would be quite tedious.

**Comment by sajibt** [comment]
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/56519002/242e3b0b-2de1-4c0e-bfc2-4be20299c897)

How to fix this Error ? It's so annoying. even if i exclude the text the warning always shows up on  Non-lsp filetype

**Comment by aikow** [comment]
I'd recommend going back to the previous version using whatever package manager you're using.

**Comment by stefanmihoc** [comment]
`version = "2.20.7"` in Lazy plugin definition fixed it for me for now.

**Comment by 256k** [comment]
same issue for me. reverting back to 2.20.7 fixed issue for now.

**Comment by lukas-reineke** [comment]
Sorry about that, I should have tested the PR better

Fix is released now

**Comment by tomasky** [comment]
my plugin is latest,but report this also ,
`indent-blankline: .../nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:94: no parser for 'javascript' l
anguage, see :help treesitter-parsers
`

**Comment by lukas-reineke** [comment]
Sorry, stuff was still broken... I reverted everything back to 2.20.7 until I have time to fix it properly.
