### ISSUE TITLE
How to get rid of inserting hyphen chars while inserting space or tab chars?

### ISSUE THREAD

**Issue by rv-ragul** [lukas-reineke/indent-blankline.nvim#595]
I made the following changes in config.

```lua
set.list = true
set.listchars:append "eol:↴"

require('indent_blankline').setup {
    char = '│',
    show_trailing_blankline_indent = false,
    show_end_of_line = true,
}

```

Now eol characters are inserted as expected. But hyphens are inserted when inserting space or tab chars.
I added a screenshot for reference.

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/85612319/f5366487-bda4-45ff-9dbf-57f57b7812d7)

**Comment by lukas-reineke** [comment]
Answered you here 594
