### ISSUE TITLE
lsp_lines integration

### ISSUE THREAD

**Issue by TheSast** [lukas-reineke/indent-blankline.nvim#596]
**This issue is complementary to [lsp_lines #42](https://todo.sr.ht/~whynothugo/lsp_lines.nvim/41)**

Would it be possible for the plugin to implement some sort of interface so that `lsp_lines.nvim` and `indent-blankline.nvim` can communicate to correctly show indent guides on the diagnostic lines? And would someone be willing to implement it?

**Comment by lukas-reineke** [comment]
I am currently working on v3 for indent-blankline.
Exposing an api for other plugins to influence the indentation, and or get indentation is planned.

I still have not started looking into this, so I'm not sure yet if and how it will work.

Also no ETA, might take some time, sorry

**Comment by lukas-reineke** [comment]
All the building blocks are available in IBL to make this work. But the actual implementation would need to be in lsp_lines.
I'm closing the ticket here.
