### ISSUE TITLE
Indent-blankline appears to disable the splash screen in nvim and go straight to an empty buffer

### ISSUE THREAD

**Issue by Ttibsi** [lukas-reineke/indent-blankline.nvim#597]
I've found that recently the nvim splash screen [this](https://cdn.discordapp.com/attachments/712311177710927914/1131934380571512852/image.png) no longer appears when indent-blankline is installed. It's nothing to do with the config in question, although this is what I'm using:

```lua
local function init()
	vim.opt.termguicolors = true
	vim.cmd([[highlight IndentBlanklineIndent1 guifg=#E06C75 gui=nocombine]])
	vim.cmd([[highlight IndentBlanklineIndent2 guifg=#E5C07B gui=nocombine]])
	vim.cmd([[highlight IndentBlanklineIndent3 guifg=#98C379 gui=nocombine]])
	vim.cmd([[highlight IndentBlanklineIndent4 guifg=#56B6C2 gui=nocombine]])
	vim.cmd([[highlight IndentBlanklineIndent5 guifg=#61AFEF gui=nocombine]])
	vim.cmd([[highlight IndentBlanklineIndent6 guifg=#C678DD gui=nocombine]])

	vim.opt.list = true
	vim.opt.listchars:append("space: ")

	require("indent_blankline").setup({
		space_char_blankline = " ",
		char_highlight_list = {
			"IndentBlanklineIndent1",
			"IndentBlanklineIndent2",
			"IndentBlanklineIndent3",
			"IndentBlanklineIndent4",
			"IndentBlanklineIndent5",
			"IndentBlanklineIndent6",
		},
	})
end
```

I've tried searching the issue tracker, but I can't find anything relevant in there. For the record, my nvim is 0.9.1, and I'm seeing this on both MacOS and PopOS. If there's anything else I need to inform you of, please just let me know. If there's a config for this, I must have missed it -- please point me in the right direction. THank you

**Comment by lukas-reineke** [comment]
I can't reproduce this. It is very likely something else in your config.

**Comment by Ttibsi** [comment]
Looks like I incorrectly debugged which plugin it is (lualine) -- sorry about wasting your time
