### ISSUE TITLE
Support for hex values in `listchars`

### ISSUE THREAD

**Issue by k98kurz** [lukas-reineke/indent-blankline.nvim#599]
## Describe the bug

Sometimes the utf-8 char I specified for spaces appears as "·", other times as "\xb7". Note that this does not happen in normal vim with the same config, nor did it happen with neovim with this config prior to installing this repository.

![image](https://github.com/nvim-lua/kickstart.nvim/assets/4357561/b7668c08-3811-4f4d-951e-720216b6b020)

## To Reproduce

1. Install nvim v0.9.1 from the appimage.
2. Install ~this config~ [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim) from source using the `git clone` method.
3. Add `let &listchars = 'tab:-> ,space:\xb7'` and `set list` to a file somewhere, e.g. `~/.vimrc`.
4. Add `vim.cmd('source ~/.vimrc')` or whatever the file path was to `~/.config/nvim/init.lua`. (I have experimented with which line to put it on, and the behavior does not change.)
5. Open `~/.config/nvim/init.lua` with nvim and scroll down.

## Desktop

- OS: Ubuntu 22.04
- Terminal: GNOME Terminal version 3.44.0 for GNOME 42

## Neovim Version

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

Copied from https://github.com/nvim-lua/kickstart.nvim/issues/378.

**Comment by lukas-reineke** [comment]
The plugin currently does not support hex values. But you can just use the unicode character as the value directly and it should work.

**Comment by k98kurz** [comment]
Is there no way to just invoke whatever code parses the `init.vim` file when `init.lua` doesn't exist? Not really sure why a plugin would change how the default config parser works, but I'm not overly familiar with neovim internals. Did you write the code that handles the `lua.cmd('source ~/.file/path')` function call? Suddenly very curious about this.

**Comment by lukas-reineke** [comment]
This has nothing to do with the config parser. indent-blankline just reads the values of `listchars` and uses them as is.
Internally, when Neovim uses the values it converts hex to utf-8, but that function is not exposed, so I can't just use it. I would have to re implement it in lua. Which of course is possible, but I don't know if I will. There is an easy workaround by just using the utf-8 char directly, and you are the first person to ask for this.

I'd be happy to except a PR

**Comment by k98kurz** [comment]
I see. I'll take a look at the code and see if I can figure out a solution. If I can get code working for converting escape sequences to unicode chars, I'll check back in to get some guidance on testing it.

**Comment by lukas-reineke** [comment]
:+1: 

This is how Neovim does it

https://github.com/neovim/neovim/blob/7668f89d5be6d463bf6ab0c2d3a0393e3ec26e7f/src/nvim/optionstr.c#L2269-L2297

You would need to write the same function, but in lua. Or call that function directly with [luajit ffi](https://luajit.org/ext_ffi.html)

**Comment by lukas-reineke** [comment]
was not easy.. but I added support for this now

**Comment by k98kurz** [comment]
Ngl, that looks like a nightmare to have figured out. Thanks.
