### ISSUE TITLE
Double lines with C#

### ISSUE THREAD

**Issue by ggsvr** [lukas-reineke/indent-blankline.nvim#600]
I think it's assuming that C# indents with 2 spaces, but standard formatting tools like `dotnet format` use 4 spaces for indenting. I didn't see any logic for language-specific stuff in the source code, so maybe it's something in `tree-sitter`?

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/57045797/59b5351a-aa13-4c7c-a208-d997c567979a)

**Comment by lukas-reineke** [comment]
> I think it's assuming that C# indents with 2 spaces

It's not, it is using `:help shiftwidth`. You can set it to 4 spaces with `:set shiftwidth=4`
