### ISSUE TITLE
``vim.opt.ambiwidth = 'double'`` causes indent display issues.

### ISSUE THREAD

**Issue by szne** [lukas-reineke/indent-blankline.nvim#601]
## Describe the bug

When setting the 'ambiwidth' option in NeoVim to 'double', the indent display becomes incorrect, and the text is no longer visible as the indentation gets deeper. This issue can be seen in the image below.

- Normal.
<img width="349" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/84981684/92b00440-6b4d-4e7b-82e5-9869f550973b">

- If ``vim.opt.ambiwidth = 'double'`` is enabled.
<img width="359" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/84981684/d47ba75f-3465-4b43-ab61-3b912155e363">

## To Reproduce

Add the following option to the lua file where the settings are written: ``vim.opt.ambiwidth = 'double'``

## Environment

OS: ArchLinux (on WSL)

NeoVim:
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

(I'm a beginner Japanese user, so I'm sorry if the format is wrong.)

**Comment by lukas-reineke** [comment]
Hm this would be pretty difficult to support I think.
In your example, how should 2 space indentation look like, if the space character is already 2 cells wide, and adding the indent char would be 3? There is not enough room.

Could you use setcellwidths() to set the width of the utf8 char you use as space to 1? That would probably be the easiest solution.

**Comment by szne** [comment]
I had never heard of the setcellwidths() option before. I actually tried it and found that the cause of this display error was "│"(0x2502), which I was able to solve by setting it as follows.

```diff
return{
  "lukas-reineke/indent-blankline.nvim",
  event = { "BufReadPost", "BufNewFile" },
  opts = function()
++    vim.fn.setcellwidths {
++      {0x2502, 0x2502, 1},
++    }

    vim.opt.list = true,
    vim.opt.listchars:append "space:⋅",
    --vim.opt.listchars:append "eol:↴"

    require("indent_blankline").setup {
      space_char_blankline = " ",
      show_current_context = true,
      show_current_context_start = true,
    }
  end
}

```

**Comment by lukas-reineke** [comment]
Awesome
I'll add this to the documentation
