### ISSUE TITLE
Context highlight does not work on a computer of mine

### ISSUE THREAD

**Issue by tan-wei** [lukas-reineke/indent-blankline.nvim#603]
It is very strange for me. I've worked hard to configure `indent-blankline.nvim` on a computer which runs archlinux. The context highlight does not work. And then I find it works very well on my other computers (Windows, archlinux, etc.). For example, on Windows (and it is actually the configure code for `indent-blankline.nvim`):
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/28227509/29d87407-e02a-4e55-8392-3c82b796257c)
version:
```
NVIM v0.10.0-dev-835+gdd09630a2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

But not work in the computer I've wokred hard:
![图片](https://github.com/lukas-reineke/indent-blankline.nvim/assets/28227509/c6b122f1-59ef-4bb5-b0ee-d0dee83dcacb)
version:
```
NVIM v0.10.0-dev-836+g6d93bdd458
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

**Comment by tan-wei** [comment]
The versions are all nightly (almost)，because I install neovim-nightly with scoop on Windows and neovim-git with paru on archlinux, one commit difference here. You can see they are almost the same version.
So why behaves differently? Fonts? Terminals? (BTW, an other computer with archlinux works well, and I can give a screen snapshot later).

**Comment by lukas-reineke** [comment]
context is using treesitter, make sure you have treesitter set up correctly

**Comment by tan-wei** [comment]
OK. It is the problem indeed. Thanks very much.
