### ISSUE TITLE
Characters disppearing

### ISSUE THREAD

**Issue by madhur** [lukas-reineke/indent-blankline.nvim#604]
After applying this plugin, first few characters are disappeared from my pom.xml.

See screenshot below for reference

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/509431/060fe7b5-5c14-4f22-8da0-d5fd0a6bb33e)

Config:
```lua
local status_ok, ib = pcall(require, "indent_blankline")
if not status_ok then
  vim.notify("indent_blankline not found")
  return
end


ib.setup {
    -- for example, context is off by default, use this to turn it on
    show_current_context = true,
    show_current_context_start = true,
}
```

**Comment by lukas-reineke** [comment]
You probably have inconsistent settings for `shiftwidth`, `tabstop` and `expandtab`

**Comment by fredizzimo** [comment]
I just reported a very similar issue here https://github.com/neovim/neovim/issues/25011. But the offending commit was merged only yesterday, and it only seems to affect Neovim Gui applications.
