### ISSUE TITLE
highlight groups get reset if I only set `ctermfg`

### ISSUE THREAD

**Issue by ramojus** [lukas-reineke/indent-blankline.nvim#606]
If in my colorscheme I set, for example:
```lua
vim.api.nvim_set_hl(0, 'IndentBlanklineChar', { ctermfg = 8 })
```
with `vim.opt.termguicolors = false`, the highlight get's reset by this plugin in `require("indent_blankline.utils").reset_highlights()` function.

I've tried to debug this and I'm really not sure why. It seems like some highlight groups that only have `ctermfg` get defined later? Which doesn't make any sense. Specifically this seems to be happening with `IndentBlanklineContextChar` group – in `reset_highlights` function, this group is empty, even though I define it in my colorscheme.
This seems to be a neovim issue.
For all highlight groups, `vim.fn.synIDattr(current_highlight, "fg")`, doesn't return anything after `colorscheme` call from my vimrc. But after `colorscheme` call from within neovim, everything works as it should. I'm confused.

Anyways, I believe there is an easy solution for this. The `reset_highlights` function could only be called on `ColorSchemePre` event. Then there would also be no need to check if the highlights are already defined, the function would just reset them and let the colorscheme override any of them if needed. I could make a PR.

**Comment by ramojus** [comment]
Turns out I was using wrong `ctermfg` value for `IndentBlanklineContextChar` group. Now simply having this additional check in `reset_highlights` function fixes my issue:
```diff
        if
            vim.fn.synIDattr(current_highlight, "fg") == ""
            and vim.fn.synIDattr(current_highlight, "bg") == ""
            and vim.fn.synIDattr(current_highlight, "sp") == ""
+           and vim.fn.synIDattr(current_highlight, "fg", "cterm") == ""
+           and vim.fn.synIDattr(current_highlight, "bg", "cterm") == "" -- for completeness

```
I still think that previously proposed solution would be nicer, but that's obviously not for me to decide

**Comment by lukas-reineke** [comment]
Using `ColorSchemePre` is not an option. It needs to run after a colorscheme is set, to make defaults for any highlight groups that are not explicitly set in the colorscheme.

But I'd be happy to merge a PR for adding the `cterm` check
