### ISSUE TITLE
show_trailing_blankline_indent is not consistent

### ISSUE THREAD

**Issue by gruvw** [lukas-reineke/indent-blankline.nvim#609]
After reading #55 and #7, I still have an issue with "VSCode-like" indentation on last blank lines.

### Issue

VSCode Reference:
![VSCode Reference](https://github.com/lukas-reineke/indent-blankline.nvim/assets/63407038/3cc06ed5-1df0-4e05-8e0d-14a7a0838de8)

With `show_trailing_blankline_indent = true` (default):
![show_trailing_blankline_indent true](https://github.com/lukas-reineke/indent-blankline.nvim/assets/63407038/6906a5d6-00ce-4c27-802d-8e6f0bc96f62)

With `show_trailing_blankline_indent = false` (VSCode-like indentation with one level less):
![show_trailing_blankline_indent false](https://github.com/lukas-reineke/indent-blankline.nvim/assets/63407038/19bf76eb-cc7a-4330-9e1a-828a838b7028)

On the last picture, we can notice a "hole" in the indentation line (yellow).  
It is not present in the VSCode indentation (which is probably more natural), nor on the second picture (where `show_trailing_blankline_indent = true`) as the yellow line is contiguous till `}`.

I was only able to reproduce this issue on the last empty line at the end of an indent block.

### Code snippet used

```python
def main():

    for i in range(5):
        return {

            "hey",
            i

        }
```

(Don't mind the code, it doesn't make sense, but it shows the abnormal behavior, also detected in many other languages)

JSON example:
```json
{
    "1": [
        "this"

    ]
}
```
Same issue here, on the line right before `]` the indent line is missing.

### Config used

```lua
-- https://github.com/lukas-reineke/indent-blankline.nvim
{
  "lukas-reineke/indent-blankline.nvim",
  config = function()
    require("indent_blankline").setup({
      char = "│",
      show_end_of_line = true,
      show_trailing_blankline_indent = false,
      char_highlight_list = {
        "IndentBlanklineIndent1",
        "IndentBlanklineIndent2",
        "IndentBlanklineIndent3",
        "IndentBlanklineIndent4",
        "IndentBlanklineIndent5",
        "IndentBlanklineIndent6",
      },
      filetype_exclude = {
        "lspinfo",
        "packer",
        "checkhealth",
        "help",
        "man",
        "",
      },
    })
  end
}
```

**Comment by lukas-reineke** [comment]
This is a limitation of the current implementation.
But I have already fixed that for version 3.
Please wait a couple of weeks until v3 is ready.

**Comment by lukas-reineke** [comment]
Fixed in version 3 now

**Comment by Iron-E** [comment]
Is it just enabled by default now? I couldn't find any mention of `show_trailing_blankline_indent` in either `:h ibl` or the [migration guide](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3), but I could be missing something

**Comment by lukas-reineke** [comment]
`show_trailing_blankline_indent` is no longer relevant, it's always off
