### ISSUE TITLE
Bracket scope highlighting on all levels

### ISSUE THREAD

**Issue by kristijanhusak** [lukas-reineke/indent-blankline.nvim#61]
Hi, 

I found out about bracket scope highlights from this reddit discussion https://www.reddit.com/r/neovim/comments/m9jxkt/bracket_pair_scope_highlight_like_vscode_does_it/. 

It's something that I was also looking for, but I thought it's not possible. It's working fine, which is great!

I was wondering if you considered highlighting any scope, without providing the list of contexts?
If you tried it, is it too hard on performance?

I provided custom list of node types to highlight, but it seems it's not always highlighting the proper level. For example, I have this settings:

```lua
vim.g.indent_blankline_show_current_context = true
vim.g.indent_blankline_context_patterns = {'class', 'function', 'method', 'if', 'while', 'for'}
```

For example, this chunk of code doesn't highlight the `if` block but `for`:

![if-on-whitespace](https://i.imgur.com/Cp15S8l.png)

And this one doesn't highlight any level:

![if-on-word](https://i.imgur.com/slN786x.png)

But the `if` outside the `for` loop works fine:

![if-ok](https://i.imgur.com/W49vxA5.png)

**Comment by lukas-reineke** [comment]
You found a bug with the `if` that didn't work. Lua and off by one errors :disappointed_relieved:. I pushed a fix now.

There should be no performance difference with how many node types you highlight. But you do need to provide a list, or the current smallest node would always win. Things like `statement` or `variable_declaration`, which don't span over multiple lines.

Also be careful with the patterns. They are lua patterns, so `if` would also match `identifier` `ident"if"er`
You should use `^if`

**Comment by kristijanhusak** [comment]
It's much better now, thanks.
Also providing `^if` instead of `if` fixes the 2nd screenshot issue where cursor is on word.

I would like to always highlight the closest indent block, no matter what type is it. Is there a way to achieve that?

**Comment by ahmedkhalf** [comment]
@kristijanhusak I know this is not related to the issue but which terminal emulator allows you to have the indent chars pass through the lines like that without getting cut (considering you have high padding in between the lines...)

**Comment by kristijanhusak** [comment]
@ahmedkhalf It's Kitty terminal, with this indent char: 
```lua
vim.g.indent_blankline_char = '▏'
```

**Comment by nathanaelkane** [comment]
> I would like to always highlight the closest indent block, no matter what type is it. Is there a way to achieve that?

This is exactly what I would like too, i.e. highlight the current (right most) indent guide for the line you're on.

**Comment by kristijanhusak** [comment]
@nathanaelkane try settings from my previous https://github.com/lukas-reineke/indent-blankline.nvim/issues/61#issuecomment-803613439. Works for me more less ok.

**Comment by lukas-reineke** [comment]
It really depends on what languages you need. In Gloang for example there is also `func_literal` for anonymous functions.

Not sure how realistic it is to support all possible language variations. Also not even sure if "all levels" is a good default or not.
But I am open for suggestions.

**Comment by nathanaelkane** [comment]
@kristijanhusak Thanks, I will definitely give it a try once I switch over to treesitter for syntax highlighting.

I guess I was picturing a "highlight current indent" solution that worked without treesitter, but I don't know enough about treesitter or this plugin to know if that's possible.

**Comment by akinsho** [comment]
Could the logic just be based on cursor position and highlighting the closest indent before the current cursor column? Maybe that's different from the original feature request though 🤷🏿‍♂️

**Comment by kristijanhusak** [comment]
@lukas-reineke If it's possible to always track the nearest indent line and highlight it, I think it should be implemented and set behind the opt in setting.

**Comment by nathanaelkane** [comment]
> Could the logic just be based on cursor position and highlighting the closest indent before the current cursor column? Maybe that's different from the original feature request though 🤷🏿‍♂️

Yea that's what I was picturing and you're right, it's different than the `indent_blankline_show_current_context` feature.

**Comment by lukas-reineke** [comment]
Doing it without treesitter is actually more complex.
Treesitter gives me the start and end of the context, and I can just add the highlight as I loop over the lines.

Doing it without, I would need to calculate all the indentation levels first, determine the range the cursor is in, and then loop over those lines again to actually add the highlight.
It's possible, but it would be slower and less accurate than treesitter. And quite a bit of effort to write.

I don't think that would be a good solution. I'd rather have a good default for the highlighted treesitter nodes and good documentation of possible nodes.

**Comment by akinsho** [comment]
I can definitely get close to the deepest level of indentation being highlighted using the current implementation and tweaking the list of nodes so that's fine. It might be worth adding `block` to the list of defaults since I think this is common for most languages.

**Comment by nathanaelkane** [comment]
> Doing it without treesitter is actually more complex.
> Treesitter gives me the start and end of the context, and I can just add the highlight as I loop over the lines.

Yep, totally makes sense 👍 

> @kristijanhusak Thanks, I will definitely give it a try once I switch over to treesitter for syntax highlighting.

I just realised that with treesitter I can disable the syntax highlighting but still use it for the `indent_blankline_show_current_context` feature with @kristijanhusak's suggested `indent_blankline_context_patterns` values. Seems to work pretty well, but I need to tweak the values for Ruby.

**Comment by sQVe** [comment]
@lukas-reineke How much performance implications does many patterns have here? I grepped base types listed in https://github.com/tree-sitter/tree-sitter-typescript/blob/4c20b54771e4b390ee058af2930feb2cd55f2bf8/tsx/src/node-types.json and did some manual removal and ended up with:

```lua
    vim.g.indent_blankline_context_patterns = {
        "abstract_class_declaration", "abstract_method_signature",
        "accessibility_modifier", "ambient_declaration", "arguments", "array",
        "array_pattern", "array_type", "arrow_function", "as_expression",
        "asserts", "assignment_expression", "assignment_pattern",
        "augmented_assignment_expression", "await_expression",
        "binary_expression", "break_statement", "call_expression",
        "call_signature", "catch_clause", "class", "class_body",
        "class_declaration", "class_heritage", "computed_property_name",
        "conditional_type", "constraint", "construct_signature",
        "constructor_type", "continue_statement", "debugger_statement",
        "declaration", "decorator", "default_type", "do_statement",
        "else_clause", "empty_statement", "enum_assignment", "enum_body",
        "enum_declaration", "existential_type", "export_clause",
        "export_specifier", "export_statement", "expression",
        "expression_statement", "extends_clause", "finally_clause",
        "flow_maybe_type", "for_in_statement", "for_statement",
        "formal_parameters", "function", "function_declaration",
        "function_signature", "function_type", "generator_function",
        "generator_function_declaration", "generic_type", "if_statement",
        "implements_clause", "import", "import_alias", "import_clause",
        "import_require_clause", "import_specifier", "import_statement",
        "index_signature", "index_type_query", "infer_type",
        "interface_declaration", "internal_module", "intersection_type",
        "jsx_attribute", "jsx_closing_element", "jsx_element", "jsx_expression",
        "jsx_fragment", "jsx_namespace_name", "jsx_opening_element",
        "jsx_self_closing_element", "labeled_statement", "lexical_declaration",
        "literal_type", "lookup_type", "mapped_type_clause",
        "member_expression", "meta_property", "method_definition",
        "method_signature", "module", "named_imports", "namespace_import",
        "nested_identifier", "nested_type_identifier", "new_expression",
        "non_null_expression", "object", "object_assignment_pattern",
        "object_pattern", "object_type", "omitting_type_annotation",
        "opting_type_annotation", "optional_parameter", "optional_type", "pair",
        "pair_pattern", "parenthesized_expression", "parenthesized_type",
        "pattern", "predefined_type", "primary_expression", "program",
        "property_signature", "public_field_definition", "readonly_type",
        "regex", "required_parameter", "rest_pattern", "rest_type",
        "return_statement", "sequence_expression", "spread_element",
        "statement", "statement_block", "string", "subscript_expression",
        "switch_body", "switch_case", "switch_default", "switch_statement",
        "template_string", "template_substitution", "ternary_expression",
        "throw_statement", "try_statement", "tuple_type",
        "type_alias_declaration", "type_annotation", "type_arguments",
        "type_parameter", "type_parameters", "type_predicate",
        "type_predicate_annotation", "type_query", "unary_expression",
        "union_type", "update_expression", "variable_declaration",
        "variable_declarator", "while_statement", "with_statement",
        "yield_expression"
    }
```

**Comment by sQVe** [comment]
👇🏼 seems to match *a lot* of things, using the general groups. Probably missing something but this is a promising start at least.

```lua
    -- Patterns: https://github.com/tree-sitter/tree-sitter-typescript/blob/master/tsx/src/node-types.json
    vim.g.indent_blankline_context_patterns = {
        "declaration", "expression", "pattern", "primary_expression",
        "statement", "switch_body"
    }
```

**Comment by lukas-reineke** [comment]
It should be pretty fast, but I haven't tried with this many patterns yet.

>  seems to match a lot of things, using the general groups.

Thanks for this :+1:
I am thinking of adding a section in the readme for suggested patterns per language.

**Comment by sangdth** [comment]
@sQVe Thanks, your list saved my day. With it I can make it works with JSX!
