### ISSUE TITLE
v3: Guides not shown when adding lines in insert mode

### ISSUE THREAD

**Issue by MariaSolOs** [lukas-reineke/indent-blankline.nvim#615]
I'm so excited for v3! However, while dogfooding it I found an issue (I apologize if this is actually configurable, I looked all over the docs for this).

In `master`:

https://github.com/lukas-reineke/indent-blankline.nvim/assets/62502207/a6c4339d-21ca-4977-a75b-ad6227b6d724

In `v3`:

https://github.com/lukas-reineke/indent-blankline.nvim/assets/62502207/981e5e38-ce14-4eaf-a182-7ec4c25a2d35

The videos also show the respective configurations I'm using.

In addition, sometimes indent guides will be displayed at the end of the line when in insert mode (specially when accepting a Copilot suggestion). I don't know if this is intended, but how could I disable it?

<img width="729" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/62502207/6bff8fa1-f7ce-4a9c-b072-092883647a8e">

**Comment by lukas-reineke** [comment]
Thanks, I pushed a fix, can you check please?

**Comment by MariaSolOs** [comment]
Yep! It was the exact same fix from my PR hehe

**Comment by hinell** [comment]
Working for me as well.
