### ISSUE TITLE
v3: All windows are affected when entering an excluded filetype

### ISSUE THREAD

**Issue by MariaSolOs** [lukas-reineke/indent-blankline.nvim#616]
I disable `indent-blankline` in `noice` windows. However, in v3 whitespace characters from included windows also get removed when a window from an excluded filetype is opened.

In `master`:

https://github.com/lukas-reineke/indent-blankline.nvim/assets/62502207/f7211a3f-dd36-4e41-bb57-1d910d2f15fd

In `v3`:

https://github.com/lukas-reineke/indent-blankline.nvim/assets/62502207/90a6f937-5fa8-4ac5-9f02-c8c0193d35f4

**Comment by lukas-reineke** [comment]
Interesting :thinking: 
I can't reproduce that.

Are you doing anything special with `listchars`?
Can you run `:lua =require "ibl.utils".get_listchars()` before and after and see if the output changes?

**Comment by MariaSolOs** [comment]
I actually spent a while debugging this because I thought it was interesting indeed.
I have this configuration for `noice` in `after/ftplugin/noice.lua`:

```lua
-- Disable line numbers.
vim.wo.nu = false
vim.wo.rnu = false

-- Don't show whitespace.
vim.opt_local.list = false
```

And in `init.lua` I have these settings:
```lua
-- Show whitespace.
vim.opt.list = true
vim.opt.listchars = { space = '⋅', trail = '⋅', tab = '  ' }
```

**Comment by MariaSolOs** [comment]
As for running the `require "ibl.utils".get_listchars()`, here's the output before:
```
{
  space_char = "⋅",
  tab_char_end = "",
  tab_char_fill = " ",
  tab_char_start = " ",
  tabstop_overwrite = false,
  trail_char = "⋅"
}
```

And after:
```
{
  space_char = " ",
  tab_char_fill = " ",
  tabstop_overwrite = false
}
```

**Comment by lukas-reineke** [comment]
I pushed a commit, can you check if that fixes it?

**Comment by MariaSolOs** [comment]
Works great! Thanks a lot <3
