### ISSUE TITLE
Doesn't seem to work with react.

### ISSUE THREAD

**Issue by FormalSnake** [lukas-reineke/indent-blankline.nvim#621]
![Screenshot 2023-09-05 at 15 43 25](https://github.com/lukas-reineke/indent-blankline.nvim/assets/90651091/55d800f9-0f79-4a57-a66d-936e8b51d891)

And also highlighting the current indent I am in does not seem to work. I am using catppuccin

**Comment by FormalSnake** [comment]
it does give a slight highlight though
![Screenshot 2023-09-05 at 15 46 14](https://github.com/lukas-reineke/indent-blankline.nvim/assets/90651091/68c07085-7d5d-4ebc-9859-0a9c5055282d)

**Comment by lukas-reineke** [comment]
I need a lot more information to help you.

Is this for version 2 or 3?
What does your config look like?
Are you sure indent-blankline is installed correctly?

**Comment by FormalSnake** [comment]
Yes, I am using the latest version using lazy.nvim

And this is my config
```lua
vim.opt.list = true
vim.opt.listchars:append "space:⋅"
vim.opt.listchars:append "eol:↴"

require("indent_blankline").setup {
	space_char_blankline = " ",
	show_current_context = true,
	show_current_context_start = true,
	show_end_of_line = true,
	show_trailing_blankline_indent = false,
}

```
In lua files:
<img width="1767" alt="Screenshot 2023-09-06 at 10 08 53" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/90651091/246358f1-5755-498b-ba76-3c7aa9aaeca5">
In react files:
<img width="1767" alt="Screenshot 2023-09-06 at 10 09 15" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/90651091/4f8f768d-5df4-478a-bb5f-939ac725755d">
(it looks faded because of a macos screenshot limitation)

**Comment by FormalSnake** [comment]
it has the dots, the end of line, etc. but not the line function indicator thing

**Comment by lukas-reineke** [comment]
> Yes, I am using the latest version using lazy.nvim

You are one version 2

What's the output of ':set expandtab', ':set shiftwidth', and ':set tabstop'?

**Comment by FormalSnake** [comment]
https://github.com/FormalSnake/neovim

**Comment by lukas-reineke** [comment]
Sorry, you have to add `?` to get the value `:set expandtab?` `:set shiftwidth?`

**Comment by FormalSnake** [comment]
expandtab returns expandtab and shiftwidth returns shiftwidth=8

**Comment by lukas-reineke** [comment]
> shiftwidth=8

That's why then, you need to set the shiftwidth to what you are actually using. `:set shiftwidth=2`

**Comment by FormalSnake** [comment]
and it stopped working afterwards

**Comment by lukas-reineke** [comment]
> but for some reason they dont higlight

what do you mean by that? What highlight?

> and it stopped working afterwards

after what?

**Comment by FormalSnake** [comment]
I kinda managed to fix it using this config, but still no color
```lua
vim.opt.list = true
vim.opt.listchars:append "space:⋅"
vim.opt.listchars:append "eol:↴"

require("indent_blankline").setup {
	show_current_context = true,
	show_current_context_start = true,
	show_end_of_line = true,
	show_trailing_blankline_indent = true,
}
```

**Comment by lukas-reineke** [comment]
You have to have https://github.com/nvim-treesitter/nvim-treesitter and the treesitter grammar for each language installed for context to work.

**Comment by FormalSnake** [comment]
which treesitter grammar do you use? I am using treesitter already and this is my config

```lua
require("nvim-treesitter").setup({
	ensure_installed = { "c", "lua", "rust", "ruby", "vim", "typescript", "tsx" },
	sync_install = true,
	auto_install = true,
	highlight = {
		enable = true,
		use_languagetree = true,
		-- disable = function(lang, buf)
		-- 	local max_filesize = 100 * 1024 -- 100 KB
		-- 	local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(buf))
		-- 	if ok and stats and stats.size > max_filesize then
		-- 		return true
		-- 	end
		-- end,
	},

	indent = { enable = true },
})
```

**Comment by FormalSnake** [comment]
turns out, something went severely wrong migrating from packer to lazy, and things like my theme broke.
![Screenshot 2023-09-09 at 19 49 13](https://github.com/lukas-reineke/indent-blankline.nvim/assets/90651091/f1c5c976-062d-4246-a497-8effa2d99a37)
and while the lines are not visible in react still, there is still block highlight.
