### ISSUE TITLE
v3: debounced refresh independent of key presses

### ISSUE THREAD

**Issue by jbarap** [lukas-reineke/indent-blankline.nvim#624]
Hello, first of all, v3 is looking great!

I just had a question regarding the debounced refresh. It looks like it's using a uv timer to execute a refresh every `debounce` ms, which is great, but I noticed that the timer seems to reset on every key press. Normally this wouldn't be a problem when vertically navigating a buffer with `c-u` and `c-d`, but it does result in a noticeable refresh delay when using `j` or `k`, in the case where your key repeat time is less than your configured `debounce`.

This situation can be seen below when indents "pop" when you stop pressing the `j` key (ignore the janky asciinema).

[![asciicast](https://asciinema.org/a/FKlpFE8RgLKO2iBCav8Qglolu.svg)](https://asciinema.org/a/FKlpFE8RgLKO2iBCav8Qglolu)

So my question  is: Is this a neovim limitation or is there a way to have the refresh timer independent of key presses?

Thank you for the great work.

**Comment by lukas-reineke** [comment]
Yeah, I think I can improve this.
What really should happen is

- First call to refresh triggers immediately
- Subsequent calls get debounced, but the timer does not get rest, so there is a refresh ever `deboucne`ms

Should be doable

**Comment by lukas-reineke** [comment]
I pushed a new version, let me know what you think.

**Comment by jbarap** [comment]
Just tried it out, it works great. Thank you!
