### ISSUE TITLE
v3:  `hide_first_space_indent_level` doesn't apply to tabs

### ISSUE THREAD

**Issue by rawhat** [lukas-reineke/indent-blankline.nvim#625]
I'm not sure if there is a configuration option I'm missing for this hook, but it doesn't seem to want to apply to tabs.  The only `hooks.type` that seems relevant is `WHITESPACE`, which I'd expect to work?  But I see the following:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/2095509/90e03d82-887e-44aa-b509-f8eef6515714)

Let me know if you need any more info!  And thank you for maintaining this :)

**Comment by lukas-reineke** [comment]
I made it explicitly not for tabs because conceptually it's a bit weird there, I think.
But I can add a hook for tabs as well.

**Comment by lukas-reineke** [comment]
done, there is now `hide_first_tab_indent_level` as well.

**Comment by rawhat** [comment]
Amazing, thank you!
