### ISSUE TITLE
Current context is only updated via scrolling the window not by moving the cursor

### ISSUE THREAD

**Issue by akinsho** [lukas-reineke/indent-blankline.nvim#63]
![indent_blankline](https://user-images.githubusercontent.com/22454918/111977117-4dffd100-8afa-11eb-9c0d-ca11de43d9a0.gif)

When using the newly added (and excellent) current context feature. I've noticed that the scope is only highlighted when the section of the buffer is scrolled to but not when the cursor moves into a different scope. I'm not sure if this is because it'd be expensive to calculate on `CursorHold` or something, maybe it could be debounced or ignored if the scope doesn't change etc.

In the GIF above the bigger movements are scroll events and the smaller ones are me spamming j,k.

**Comment by lukas-reineke** [comment]
If you set `g:indent_blankline_show_current_context` to true, it should trigger an update on ever `CursorMoved`

https://github.com/lukas-reineke/indent-blankline.nvim/blob/3ee2365b113d582bb78d0519f80a244b5cecf3ff/plugin/indent_blankline.vim#L78-L83

Maybe it's a problem with the order in which you load things?

It's not ideal how it is now. I am planning to clean this up, add commands to toggle the context on and off and update the autocommand on the fly.

**Comment by akinsho** [comment]
@lukas-reineke did some digging and it turns out it was because I was lazy loading indent blankline. I think the `plugin` dir isn't sourced but that's an issue with `packer` which I can raise over there. Seems to work fine once I remove the lazy loading. FWIW (despite it definitely being premature optimisation) the plugin seems to take 5ms to load which is slower than plenary, which is much bigger. Obviously 4ms is negligible to me personally but seems high still.

<img width="424" alt="Screen Shot 2021-03-22 at 12 05 33" src="https://user-images.githubusercontent.com/22454918/111987263-e9973e80-8b06-11eb-8439-ef46f10873a7.png">

**Comment by akinsho** [comment]
Will close this out though since the main issue is resolved

**Comment by akinsho** [comment]
In case it's useful to know (although my memory is fuzzy) I believe `get` is a suprisingly expensive function in vimscript, and I think those `g:` var checks might be better done on init in lua somewhere rather than vimscript

**Comment by lukas-reineke** [comment]
> I believe get is a suprisingly expensive function in vimscript

I didn't know that! 5ms really is surprisingly slow. I never checked this.
I can probably move most of that into lua. Thanks
