### ISSUE TITLE
v3: Cpp scope not highlighting

### ISSUE THREAD

**Issue by MomePP** [lukas-reineke/indent-blankline.nvim#631]
From the scope of languages, it seems that C++ (Cpp) needs to be extended from the C parser.

<img width="600" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/13793017/fd29a78b-1afb-44b6-878e-315e1dc46e64">

I've tried this by adding the following line to `scope_languages.lua`, and it works:
``` lua
M.cpp = vim.tbl_extend("keep", M.c, M.cpp)
```

<img width="600" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/13793017/0c421692-e4d4-46f6-9001-c4c68fd5b37a">

I've read the plugin doc, and it appears that you can configure the exclusion of node types but I'm not sure if it can override node types using a hook. Can it override node types with the use of a hook?

**Comment by lukas-reineke** [comment]
Was a bug that it didn't extend c, should be fixed now.

**Comment by MomePP** [comment]
Thanks, updating to the latest commit seems to have fixed it. 🎉
