### ISSUE TITLE
v3: Context different between v2 and v3

### ISSUE THREAD

**Issue by kristijanhusak** [lukas-reineke/indent-blankline.nvim#632]
Hey!

I'm giving v3 a test, and I noticed that context is working differently between the old (v2) and new (v3) versions.
Old version:
![old-version](https://i.imgur.com/zzu2PE6.png)

New version:
![new-version](https://i.imgur.com/aWkOluF.png)

I saw this in the help:
```
 The scope is *not* the current indentation level! Instead, it is the
 indentation level where variables or functions are accessible. This depends
 on the language you are writing.
```

And I'm assuming this is by design.
Is there a way to get the old behavior with the new version? I couldn't find anything in the config besides `exclude` that does the opposite.

**Comment by lukas-reineke** [comment]
Yeah, it's by design, and there isn't a way to get the old behavior. The way this worked by default in v2 wasn't great. And it only worked for some languages.
I also think the new behavior is much more useful.

I could add a hook for the scope, but there is quite a bit of complex logic for getting it right. I'm a bit afraid people will use it wrong. :thinking:

**Comment by lukas-reineke** [comment]
You could monkey patch `:lua =require("ibl.scope_languages")` to add any scope you want, but that would be a massive amount of maintenance you need to do for all the languages.
Maybe it's fine if you use only a couple languages.

Maybe I can add an include for scope for that.
Still would be a lot of work for the end user, so not sure how useful that would be.

**Comment by kristijanhusak** [comment]
`include` scope that works similarly to `exclude` would be perfectly fine. I'm aware it can be maintenance heavy, but since I work with only a few languages on a daily basis, I think I'll be able to manage those.

I have this from a very old version of indent blankline :)
```
vim.g.indent_blankline_context_patterns = {'class', 'function', 'method', '^if', '^while', '^for', '^object', '^table', 'block', 'arguments'}
```

**Comment by lukas-reineke** [comment]
I'm fine with that. Adding include doesn't hurt. :+1: 
I've implemented it already, but I also added some changes today that crash Neovim on nightly without a fix from ~5 hours ago, so I won't push it until some time tomorrow, I think.

**Comment by lukas-reineke** [comment]
pushed now

**Comment by kristijanhusak** [comment]
Works like a charm!
In case anyone needs it, here's what I set for lua and typescript for now:
```lua
{
          node_type = {
            lua = {
              'chunk',
              'do_statement',
              'while_statement',
              'repeat_statement',
              'if_statement',
              'for_statement',
              'function_declaration',
              'function_definition',
              'table_constructor',
              'assignment_statement',
            },
            typescript = {
              'statement_block',
              'function',
              'arrow_function',
              'function_declaration',
              'method_definition',
              'for_statement',
              'for_in_statement',
              'catch_clause',
              'object_pattern',
              'arguments',
              'switch_case',
              'switch_statement',
              'switch_default',
              'object',
              'object_type',
              'ternary_expression',
            },
          },
        }
```

**Comment by sgon00** [comment]
Thanks for this issue. Right now, I am using wildcard and working so far because I only need indentation highlight instead of scope.

```lua
     scope = {
        include = {
          node_type = { ["*"] = { "*" } },
        },
      },
```
