### ISSUE TITLE
Gets Rid of Neovim's Default Startup Screen

### ISSUE THREAD

**Issue by Pandoks** [lukas-reineke/indent-blankline.nvim#635]
### Problem

The Neovim startup screen doesn't show when indent-blankline loads. 
![2023-09-28 02 27 20](https://github.com/lukas-reineke/indent-blankline.nvim/assets/35944715/1d658f57-150c-451f-975b-ca7061b65325)
Occasionally will flicker the default startup screen as seen in the last Neovim opening of the gif.

It seems to be happening when indent-blankline loads. I tried it with `lazy = false` and the behavior persisted, but when I either deleted the plugin or set `lazy = "VeryLazy", the startup screen would be there.

### Steps to reproduce

Reproduction steps:

config:
```lua
return {
	"lukas-reineke/indent-blankline.nvim",
	config = function()
		require("ibl").setup({
			scope = {
				show_start = false,
			},
		})
	end,
}
```

In any directory, open nvim with: `nvim`
Results should be the same as the gif in the above section.

This config works though, but indent-line is not loaded when opening a file for the first time:
```lua
return {
	"lukas-reineke/indent-blankline.nvim",
        lazy = "VeryLazy",
	config = function()
		require("ibl").setup({
			scope = {
				show_start = false,
			},
		})
	end,
}
```

### Expected behavior

When opening neovim to a no name empty buffer (typing the `nvim` command with no file or directory) it should show:
<img width="497" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/35944715/52a27ed0-894f-41c8-9b16-a8d5cda7b235">

### Neovim version (nvim -v)

0.9.2

**Comment by lukas-reineke** [comment]
Yeah sorry I can reproduce it now.
It seems scheduling some things, like setting highlight groups causes this.

Should be fixed now
