### ISSUE TITLE
No indent lines after v3 upgrade

### ISSUE THREAD

**Issue by konart** [lukas-reineke/indent-blankline.nvim#637]
### Problem

Even with empty config 

```lua
{
 "lukas-reineke/indent-blankline.nvim", 
  main = "ibl",
  opts = {},
}
```

nothing is displayed.

Adding `config = function() require("ibl").setup() end` also does nothing.

PS: On  dirty config  you can see a suggestion to read  a readme on how to migrate, alas readme provides  no such info.

### Steps to reproduce

Use default config. Open any  file with indents.

### Expected behavior

Indentation lines are visible.

### Neovim version (nvim -v)

0.9.2

**Comment by lukas-reineke** [comment]
I moved the migration guide here https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3
I'll update the error message :+1: 

But I need more information about the indents not showing up. Please use [the reproduction template](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template)

**Comment by JZsmitty** [comment]
For those wanting a quick workaround until version 3 is supported, you can set the version in the init.lua

version = '2.20.8',

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/146256518/9587d5f8-1c57-449b-89db-c603bc914389)

**Comment by konart** [comment]
> I moved the migration guide here https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3 I'll update the error message 👍
> 
> But I need more information about the indents not showing up. Please use [the reproduction template](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template)

After playing around with minimal config I've figured it out (more or less):

I have these options:
```lua
vim.opt.list = true
vim.opt.listchars = { tab = "-->", space = "·", precedes = "…", extends = "…", conceal = "", eol = "↴" }
```

I can see indent (works as expected) in two cases:

1. Spaces are used for indentation
2. I turn list off.

**Comment by lukas-reineke** [comment]
When `list` is set, tabs default to what you have set in `listchars`. Either set tab for `listchars` to start with the indent guide, or set `:help ibl.config.indent.tab_char`

**Comment by Joarell** [comment]
Hi everyone!
First, this V3 has a huge update!
Congratulation for this great plug-in and all efforts added to it.
However, I'd like to ask you a help to have the same result with `space` using `tab`.
I have in my config: 
```Lua
vim.opt.shifttwidth = 4
vim.opt.softtabstop = 4
vim.opt.tabstop = 4
```
I have read `help ibl.config.ident.tab_char`, but I can't have the same single vertical line with `space` indentation using `tab`, instead I'm having the char `>` in place.
Additionally, I've tried to set `tab_char` with '|', but the result is not one single vertical line the editor shows many segments of pipes one below the others.

Sorry if I misunderstood how to set properly with tabs. Even though, I would appreciate your help to sort this out.
Have a nice day!

![IBL](https://github.com/lukas-reineke/indent-blankline.nvim/assets/42722369/786943f0-90db-4ced-b66d-ab301fea2d14)

**Comment by l00sed** [comment]
I'm having a similar issue after upgrading.

OS: MacOS 14 Sonoma
Neovim: 0.9.2
LuaJIT: 2.1.0-beta3
indent blanklink: v3

Using Lazy for plugins:
```lua
...
  -- Pretty/interactive indentlines
  {
    "lukas-reineke/indent-blankline.nvim",
    main = "ibl",
    opts = {},
    config = function()
      require("plugins.indent-blankline")
    end,
  },
...
```

In `./plugins/indent-blankline.lua`, I'm using the `.setup()` method:
```lua
require("ibl").setup({
  indent = {
    char = { "│", "-" },
    highlight = highlights,
    smart_indent_cap = false
  },
  scope = {
    enabled = true,
    char = "│",
  },
  exclude = {
    filetypes = {
      'lspinfo',
      'packer',
      'lazy',
      'startify',
      'checkhealth',
      'help',
      'man',
      'gitcommit',
      'TelescopePrompt',
      'TelescopeResults',
      ''
    },
    buftypes = {
      'terminal',
      'nofile',
      'quickfix',
      'prompt',
      'help',
      'packer',
      ''
    }
  }
})
```

I'm not seeing any indent lines at all. Tried `:IBLToggle` and `:IBLEnable`.
Am I doing any of the setup incorrectly? My `highlights` variable is a Lua array of strings, `{ 'IndentBlankLine1', 'IndentBlankLine2', ... }`

Been fussing around with it for a while, but nothing's stuck...

**Comment by l00sed** [comment]
Ah, you know what, I just figured it out. I think the `''` in my excludes were acting like wildcards. I was trying to exclude empty or null filetype/buftype. Removing the `''` options causes the indentlines to display properly.

<img width="159" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/23065167/547b8da0-8f85-4e61-8240-70dcf44b1f66">

Not sure if that'd be considered a bug or if there's a way to exclude indentline from files with null/empty filetypes...

**Comment by lukas-reineke** [comment]
> I've tried to set tab_char with '|', but the result is not one single vertical line the editor shows many segments of pipes one below the others.

Make sure you are using the correct unicode character `▎`

**Comment by lukas-reineke** [comment]
> I just figured it out. I think the `''` in my excludes were acting like wildcards.

That's not the case, `''` is in the default excluded filetypes. And it works like you would expect to only exclude files with no filetype.

**Comment by lukas-reineke** [comment]
That's because buftype is empty for normal buffers. So if you add `''` to excluded buftypes, you are saying turn indent-blankline off for all normal buffers. It works like it should.

`:help 'buftype'`
