### ISSUE TITLE
Unnecessary Lines

### ISSUE THREAD

**Issue by adishourya** [lukas-reineke/indent-blankline.nvim#64]
Really Loving the new vim.g.indent_blankline_char_highlight_list option btw.

I am getting a few unnecessary indent line when I have empty lines

Below I have attached a screenshot. (func bar is the expected behaviour even with empty lines)
(func foo has those extra lines)

And my indent line configuration has : 

![2021 03 22-18 59 18 screenshot](https://user-images.githubusercontent.com/46932291/111998849-6dbae780-8b42-11eb-90c1-4190d81d11eb.png)

```lua


vim.g.indent_blankline_char = '│'
vim.g.indent_blankline_strict_tabs = true
-- Custom Highlight group
vim.g.indent_blankline_char_highlight_list = {'aqua_ind' , 'grey_ind', 'yellow_ind','algea_ind'}
vim.g.indent_blankline_use_treesitter = true


```

**Comment by andrevmatos** [comment]
I've also noticed this, only with treesitter (0.19.3, if that matters). It seems treesitter is giving indentation width (in characters) and this plugin is interpreting it as indentation levels, because on deeper blanklines, I can see more indentation levels from this plugin being shown. Notice on the first blank line, whch should be level=1, I got 2 levels, 4 spaces, while on the blank lines between `wait`s, I should have level=3, but got 6 levels, 12 spaces (I've using `set et,ts=2,sw=2`).
Great plugin btw, thank you very much.

**Comment by lukas-reineke** [comment]
Treesitter fixed their indent logic :+1:

https://github.com/nvim-treesitter/nvim-treesitter/commit/be9c4ab36ded5adb8c30c3d6a89322e2ec1d8da3#diff-e74a724c7cadfe54a404b163bbbc659418f342b175ead2369c8bd9baec6f7987

Pushed an update now, that should fix it. Can you check?

**Comment by adishourya** [comment]
Definetly better but should there be a second line 

![Uploading 2021.03.22-20.06.52.screenshot.png…]()

**Comment by adishourya** [comment]
Definetly Better . But there still seems to be 1 extra line 

![2021 03 22-20 06 52 screenshot](https://user-images.githubusercontent.com/46932291/112008002-21c07080-8b4b-11eb-8555-e331db6fdb6a.png)
![2021 03 22-20 12 26 screenshot](https://user-images.githubusercontent.com/46932291/112008021-2553f780-8b4b-11eb-8666-65f4d8d084a0.png)

**Comment by lukas-reineke** [comment]
> But there still seems to be 1 extra line

That looks correct to me. The indent lines are up to the current level.

You can turn off trailing blankline indents with `let g:indent_blankline_show_trailing_blankline_indent = v:false`

**Comment by adishourya** [comment]
Oh yeah . Totally forgot that I had it on. Thankyou for fixing this so quickly

**Comment by TornaxO7** [comment]
Yeah! That's nice! I was looking up that as well :) We can close this issue than, right?

**Comment by adishourya** [comment]
Yes
