### ISSUE TITLE
v3: Add indentscope example to the migration guide

### ISSUE THREAD

**Issue by abeldekat** [lukas-reineke/indent-blankline.nvim#642]
### Problem

In version 2, using LazyVim, I could disable plugin `mini.indentscope`, and replace its highlighting of the current scope using `indent-blankline`.

Using [stock lazyvim starter](https://github.com/LazyVim/starter):

`plugins/blankline.lua`:
```lua
return {
  {
    "LazyVim/LazyVim",
    version = "6.4.0", -- before migrating to blankline v3
  },

  {
    "lukas-reineke/indent-blankline.nvim",
    version = "2.20.8",
    opts = {
      show_current_context = true,
      show_current_context_start = false,
    },
  },

  {
    "echasnovski/mini.indentscope",
    enabled = false,
  },
}
```

Using v3, having read `:h indentblankline`, I cannot figure out how to achieve this behaviour.
I added `scope = { enabled = true },` to no avail.

Would it be possible to add a solution for this problem to the [migration guide](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3)?

Also, I borrowed and changed some code from `nvchad`, adding `[i` and `]i` motions:

```lua
  { -- adding "[i", "]i", replacing mini.indentscope
    "lukas-reineke/indent-blankline.nvim",
    opts = {
      show_current_context = true, -- now removed from lazyvim
      show_current_context_start = false, -- added myself
    },
    config = function(_, opts)
      local function current_context()
        return require("indent_blankline.utils").get_current_context(
          vim.g.indent_blankline_context_patterns,
          vim.g.indent_blankline_use_treesitter_scope
        )
      end
      local function add_go_to_indent_scope_key(context_callback, keymap, desc)
        vim.keymap.set({ "n", "x" }, keymap, function() -- nvchad
          local ok, move_to = context_callback()
          if ok then
            vim.api.nvim_win_set_cursor(vim.api.nvim_get_current_win(), { move_to, 0 })
            vim.cmd([[normal! _]])
          end
        end, { desc = desc })
      end

      require("ibl").setup(opts)
      add_go_to_indent_scope_key(function()
        local ok, node_start = current_context()
        return ok, node_start
      end, "[i", "Go to indent scope top")
      add_go_to_indent_scope_key(function()
        local ok, _, node_end = current_context()
        return ok, node_end
      end, "]i", "Go to indent scope bottom")
    end,
  },
``` 

Is this still possible in v3?

### Expected behavior

Perhaps, the migration guide could be updated, describing a solution for the problem above.

Best regards!

**Comment by lukas-reineke** [comment]
> Would it be possible to add a solution for this problem to the [migration guide](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3)?

Scope should work out of the box, as long as you have treesitter working.

You can get the current scope with this

```lua
local bufnr = vim.api.nvim_get_current_buf()
local config = require("ibl.config").get_config(bufnr)
local scope = require("ibl.scope").get(bufnr, config)
if scope then
    print(scope:range())
end
```

Or use https://github.com/nvim-treesitter/nvim-treesitter-textobjects the scope text object there is the same.
