### ISSUE TITLE
Current scope is not highlighted after the upgrade to v3

### ISSUE THREAD

**Issue by anatskiy** [lukas-reineke/indent-blankline.nvim#643]
### Problem

This may be not a bug, but I couldn't find an answer in the documentation (by text search, at least) about how to highlight the current scope. Treesitter is, of course, configured in the main config.

<img width="501" alt="Screenshot 2023-09-28 at 11 25 52" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7281783/8a339fbb-bfef-401c-842d-d7bbc2ca4a90">

### Steps to reproduce

`nvim --clean -u ./min-init.lua min-init.lua`

### Expected behavior

The current scope's indent line is bold or something.

### Neovim version (nvim -v)

0.9.2

**Comment by lukas-reineke** [comment]
Please use the [minimal config template](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template#minimal-config) to provide a fully reproducible example.

**Comment by fcancelinha** [comment]
I'm also facing this issue, but I've noticed that "Scope" only applies to where variables are reachable, and it's language gnostic.
So my question is, how do I highlight the current scope I'm at , regardless ?

**Comment by lukas-reineke** [comment]
> So my question is, how do I highlight the current scope I'm at , regardless ?

You can add additional node types with `:help ibl.config.scope.include`

**Comment by fcancelinha** [comment]
> > So my question is, how do I highlight the current scope I'm at , regardless ?
> 
> You can add additional node types with `:help ibl.config.scope.include`

Thank you, and this plugin is great, thank you for your hard work.

**Comment by Pandoks** [comment]
This is my config right now:
```lua
return {
	"lukas-reineke/indent-blankline.nvim",
	main = "ibl",
	opts = {
		scope = {
			show_start = false,
			include = {
				node_type = { "*" },
			},
		},
		indent = {
			char = "│",
		},
	},
}
```
<img width="357" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/35944715/45750c1e-4c2c-40f3-9c3e-cc64b3b691e1">

I'm working with [`catppuccin`](https://github.com/catppuccin/nvim#integrations) colorscheme. How do I make the line highlighted for the old versioned "scope" or "context"?

**Comment by fcancelinha** [comment]
> This is my config right now:
> 
> ```lua
> return {
> 	"lukas-reineke/indent-blankline.nvim",
> 	main = "ibl",
> 	opts = {
> 		scope = {
> 			show_start = false,
> 			include = {
> 				node_type = { "*" },
> 			},
> 		},
> 		indent = {
> 			char = "│",
> 		},
> 	},
> }
> ```
> 
> <img alt="image" width="357" src="https://user-images.githubusercontent.com/35944715/271352431-45750c1e-4c2c-40f3-9c3e-cc64b3b691e1.png">
> I'm working with [`catppuccin`](https://github.com/catppuccin/nvim#integrations) colorscheme. How do I make the line highlighted for the old versioned "scope" or "context"?

you can use something like this

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/48698009/d71668d1-d0e6-4d38-afa0-8cdb80d4d988)

You may find the highlight node_types by doing :InspectTree

**Comment by fcancelinha** [comment]
@lukas-reineke Would it be possible to implement a wild character as a value of the wild character table to indicate that all scopes should be highlighted ? Would performance be impacted considerably ?

**Comment by Pandoks** [comment]
Seems to be a colorscheme issue with catppuccin. It works without a colorscheme. I'll open either an issue or pr on their repo.
<img width="336" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/35944715/52e56027-8c24-48c2-9b51-fc451831b515">

**Comment by fcancelinha** [comment]
@Pandoks you need to setup the highlight groups 

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/48698009/b60c1fdd-19d1-4cc0-a7fd-2ac1047e8e67)

like so

**Comment by OneOfOne** [comment]
IMO It should default to all scopes like it used to then have an option to disable them, not the other way around, for now I'm sticking to mini.indentscope.

**Comment by Pandoks** [comment]
> @Pandoks you need to setup the highlight groups
> 
> for example:
> 
> ![image](https://user-images.githubusercontent.com/48698009/271359679-b60c1fdd-19d1-4cc0-a7fd-2ac1047e8e67.png)
> 
> Check the documentation by typing `:help indent-blankline`

What is `"Function"` and `"Local"`?

**Comment by lukas-reineke** [comment]
> IMO It should default to all scopes like it used to then have an option to disable them, not the other way around

That is not the point of scope. The scope is the actual program scope, as in https://en.wikipedia.org/wiki/Scope_(computer_science)
This is explained in the documentation as well `:help ibl.config.scope`

> Would it be possible to implement a wild character as a value of the wild character table to indicate that all scopes should be highlighted ?

I added this in https://github.com/lukas-reineke/indent-blankline.nvim/releases/tag/v3.2.0 but it can lead to weird behavior, use it with a grain of salt.

> What is "Function" and "Local"?

They are `:help highlight-groups`

**Comment by anatskiy** [comment]
> Seems to be a colorscheme issue with catppuccin. It works without a colorscheme. I'll open either an issue or pr on their repo. <img alt="image" width="336" src="https://user-images.githubusercontent.com/35944715/271359068-52e56027-8c24-48c2-9b51-fc451831b515.png">

There's indeed a problem with mismatching highlight groups in `indent-blankline` v3.x and `catppuccin`. This can be fixed by adding the following to the `catppuccin`'s config table (colors correspond to the old ones for `indent-blankline` v2):

```lua
local config = {
  custom_highlights = function(colors)
    return {
      IblIndent = { fg = colors.surface0 },
      IblScope = { fg = colors.text },
    }
  end,
}
```

These fixes combined with the most recent wildcard change in `indent-blankline` v3.2 bring back the desired behavior:

<img width="424" alt="Screenshot 2023-09-29 at 08 38 32" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7281783/bf3c4319-3125-46b8-a363-a23bad12170d">

Thanks @lukas-reineke for a very nice plugin!

P.S. In the original issue description, I used one of the standard built-in color schemes, which doesn't even have the needed highlight groups at all, thus, no highlighting of the current indentation level. No surprise here.

**Comment by nyngwang** [comment]
What should I do to remove this?

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/24765272/5e2fb2e8-554f-4068-8b1b-fca74e618c05)
