### ISSUE TITLE
Don't display the context highlighting in version 3

### ISSUE THREAD

**Issue by piotr-marendowski** [lukas-reineke/indent-blankline.nvim#647]
### Problem

The context highlighting seems to be on by default and I don't know how to disable it. Docs don't include the word `context` (maybe it was renamed?). In version 2 it is disabled by default, so I reverted to it. I know that this version is WIP, but I would really appreciate it. Thanks for the help.

### Steps to reproduce

Run the version 3

### Expected behavior

Don't display the context highlighting.

### Neovim version (nvim -v)

0.9.1

**Comment by Danielkonge** [comment]
If I understand what you want correctly, I think you just need to include 
```lua
scope = { enabled = false }
```
in your `ibl.setup{ ... }` (or opts if you use lazy to call `setup`).
