### ISSUE TITLE
What happened to `show_current_context` in version 3.1?

### ISSUE THREAD

**Issue by pedro757** [lukas-reineke/indent-blankline.nvim#648]
### Problem

What happened to `show_current_context` in version 3.1?

### Steps to reproduce

What happened to `show_current_context` in version 3.1?

### Expected behavior

What happened to `show_current_context` in version 3.1?

### Neovim version (nvim -v)

0.10

**Comment by lukas-reineke** [comment]
please read [the migration guide](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3)

**Comment by HendrikPetertje** [comment]
Wondering about this too, the migration guide doesn't really go in detail about the state of the currently highlighted context (in the past the current indentation level you were on would highlight and you could even apply `show_current_context_start` (which i disabled, but would highlight the start of the indentation context. 

highligting contexts was a really really nice feature of this plugin especially in larger Python control flows.

**Comment by lukas-reineke** [comment]
It doesn't hurt, but most of that config is just setting the default values again, you can reduce this to just

```lua
{
  scope = {
    highlight = { "SpecialKey", "SpecialKey", "SpecialKey" },
    show_start = false
  }
}
```

And it will do the same
