### ISSUE TITLE
Neovim closes when scrolling a file

### ISSUE THREAD

**Issue by rwxmad** [lukas-reineke/indent-blankline.nvim#652]
### Problem

Neovim closes when scrolling a file when plugin is enabled
indent-blankline config: 
```
require('ibl').setup({
  exclude = {
    filetypes = {
      'help',
      'dashboard',
      'neo-tree',
      'Trouble',
    },
    buftypes = {
      'nofile',
      'terminal',
    },
  },
})
```
In lazy plugins section:
```
  {
    'lukas-reineke/indent-blankline.nvim',
    main = 'ibl',
    config = function()
      require('rwxmad.config.indent-line')
    end,
  },
```

### Steps to reproduce

nvim main.ts
then scroll

### Expected behavior

If you disable the plugin, the error disappears

### Neovim version (nvim -v)

v0.10.0-dev-772+g0211f889b-

**Comment by lukas-reineke** [comment]
Your version of Neovim nightly is too old.
Only 0.9.2 and the latest nightly version are supported
