### ISSUE TITLE
Rounded scope corner

### ISSUE THREAD

**Issue by MariaSolOs** [lukas-reineke/indent-blankline.nvim#653]
### Problem

It would be nice to have a way to configure rounded corner between the vertical scope guide and the underlined first line.

<img width="256" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/62502207/c0747ca1-cb50-45d2-8018-2a1e4d519642">

### Expected behavior

Instead of the sharp connection between the guides, I envision something like the rounded borders in floating windows.

**Comment by lukas-reineke** [comment]
Yeah would be nice, but it's not possible.
The horizontal line is not a unicode character, it's underline. There is no way to render this differently.
To get corners like the floating window border, there would need to be a whole extra line.

**Comment by MariaSolOs** [comment]
I understand. Thanks anyway!
