### ISSUE TITLE
dashoboard

### ISSUE THREAD

**Issue by jiaxinaoliao** [lukas-reineke/indent-blankline.nvim#654]
### Problem

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/98008397/b8d1c114-4aaf-4a97-8b7a-6f76644159a9)

已经排除dashboard了，但是仍然出现了

### Steps to reproduce

 ![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/98008397/f975195d-7bd5-4c9a-85bb-c9f62f8af138)

### Expected behavior

 为什么会这样呢

### Neovim version (nvim -v)

nvim -v 0.9.2

**Comment by TuanNN-Kaopiz** [comment]
Duplicate https://github.com/lukas-reineke/indent-blankline.nvim/issues/644

However, it's my config

```
require("ibl").setup {
    exclude = {
        filetypes = {
            "dashboard",
        },
    },
}
```

Hope this helps.

**Comment by lukas-reineke** [comment]
`dashboard` is a `filetype`, not a `buftype`

**Comment by jiaxinaoliao** [comment]
> Duplicate #644
> 
> However, it's my config
> 
> ```
> require("ibl").setup {
>     exclude = {
>         filetypes = {
>             "dashboard",
>         },
>     },
> }
> ```
> 
> Hope this helps.

Thanks for your help, that's right

**Comment by jiaxinaoliao** [comment]
> `dashboard` is a `filetype`, not a `buftype`

Yes, and I didn't put it inside `exculde`
