### ISSUE TITLE
Crashes NVIM

### ISSUE THREAD

**Issue by stefanmihoc** [lukas-reineke/indent-blankline.nvim#656]
### Problem

Hi,

Ever since one of the latest of version 2 and persisting with version 3, whenever I scroll vertically rapidly in a buffer it crashes NVIM. No matter the configuration, tried everything.

I use a Mac (Ventura), NVIM v0.9.2 in Kitty terminal 0.30.0, and the following plugins (just disabled indent-blankline and it doesn't crash anymore, no matter what).

<img width="1553" alt="Screenshot 2023-09-29 at 11 37 52" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7522957/85c084f6-8073-4e39-b041-9bda5304db3f">

Thanks!

### Steps to reproduce

Scroll with the mouse in a long buffer.

### Expected behavior

Doesn't crash

### Neovim version (nvim -v)

0.9.2

**Comment by lukas-reineke** [comment]
I can't reproduce this, but Neovim crashing is very likely a bug with Neovim itself.

Can you use the [minimal reproduction template](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template) to remove all other variables from your config. And can you also check if the latest nightly version of Neovim behaves the same?

**Comment by stefanmihoc** [comment]
I tried that, of course, it still crashes. Not all the time, but randomly, for example in a buffer with more than a 1000 lines and maybe a lot of nesting (eh, functional programming), when rapidly scrolling up/down with the mouse (very rapidly - Apple Magic Mouse).

I updated everything to the latest, upgraded/downgraded Kitty, didn't work. **If I disable the plugin, crashes go away**, even with several splits side by side, each with thousands of lines (one with 30.000, some autogenerated stuff, eh).

It all started a few versions ago, maybe a month ago or around then. With Lazy as a plugin manager it's so easy to update the plugins often, so I do that every few days.

Thing is, the setup I have now is the most awesome one ever, with NVIM in kitty it really flies. I thought it could be something with Kitty, with it rendering everything in the GPU, but it wasn't. I kind of like scrolling up/down rapidly, it's a tic of mine that I do whenever I try to solve something hard, or I am in long meetings.

**Comment by stefanmihoc** [comment]
I apologise for the issue.

After more testing I managed to crash it again (only harder), without indent-blankline.
I looked further, disabled/reenabled some more plugins, only to find that the treesiter-context plugin is the true culprit. I reenabled indent-blankline and it's fine now. Might be something with the combination of them, since it really was harder crash without it?

Thanks again, and please excuse my wasting of your time.

**Comment by stefanmihoc** [comment]
I apologise for the issue.

After more testing I managed to crash it again (only harder), without indent-blankline.
I looked further, disabled/reenabled some more plugins, only to find that the treesiter-context plugin is the true culprit. I reenabled indent-blankline and it's fine now. Might be something with the combination of them, since it really was harder crash without it?

Thanks again, and please excuse my wasting of your time.

**Comment by lukas-reineke** [comment]
:+1: all good

You can try enabling tracebacks and open an issue in the Neovim repo. Crashes are almost always caused by a bug in core. https://github.com/neovim/neovim/wiki/FAQ#debug

**Comment by stefanmihoc** [comment]
Thanks!
I'll look into it!

**Comment by erlonbie** [comment]
Sorry to reopen it, but I'm facing the same issue. I'm not sure if the treesitter-context plugin that @stefanmihoc mentioned is the `context_commentstring = { enable = false, enable_autocmd = false}` option in my treesitter config, but I disabled it for testing, and the issue persists.

 In my case is realy easy to reproduce: I press 'o' to create a new line, press 'esc' and then press 'j' or 'k' to scroll up and down really fast. I takes 1 or 2 seconds to happen.
 
 I'm on x11 Qtile with the config: `xset r rate 200 60` for fast keyboard repeat rate. I tried  `xset r rate 660 25` but the bug still happens in the same way.
 

my current config for this plugin:

 ```
vim.api.nvim_set_hl(0, "RainbowRed", { fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, "RainbowYellow", { fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, "RainbowBlue", { fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, "RainbowOrange", { fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, "RainbowGreen", { fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, "RainbowViolet", { fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, "RainbowCyan", { fg = "#d3d3d3" })

return {
    "lukas-reineke/indent-blankline.nvim",
    enabled = true,
    dependencies = { "HiPhish/rainbow-delimiters.nvim" },
    -- opts = {},
    config = function(_, opts)
        local highlight = {
            "RainbowRed",
            "RainbowYellow",
            "RainbowBlue",
            "RainbowOrange",
            "RainbowGreen",
            "RainbowViolet",
            "RainbowCyan",
        }

        require("ibl").setup {
            indent = { char = '┊' },
            scope = {
                highlight = highlight,
            }
        }
    end
}


```

https://github.com/lukas-reineke/indent-blankline.nvim/assets/50176483/588d3081-2926-453d-9e9d-c7cfc50c4deb

**Comment by lukas-reineke** [comment]
I can only tell you the same thing, enable tracing and open an issue in Neovim core.
This is not a bug in indent-blankline.
It's possible indent-blankline triggers it somehow, but it's not a bug in this codebase

**Comment by AdamOrmondroyd** [comment]
Sorry to kick up an old issue, but looks like I'm in a similar boat to @stefanmihoc and @erlonbie , except I've managed to trigger this without treesitter-context, and happens more often in diff mode. Did either of you reach a good fix?

**Comment by AdamOrmondroyd** [comment]
Not exactly a fix, but I realised that nvim suddenly became much more responsive when plugged into battery. It turns out that Iterm is set to disable gpu rendering on battery power; turning this off seems to have sorted it!
