### ISSUE TITLE
Hard requirement for Neovim v0.9+

### ISSUE THREAD

**Issue by mehalter** [lukas-reineke/indent-blankline.nvim#658]
### Problem

Currently the new v3 is using the very recently added `vim.api.nvim_get_hl`. This was added in Neovim v0.9 and many people still use older versions of Neovim which only have `vim.api.nvim_get_hl_by_name`. Could this be added into the code to support older versions of Neovim? Most plugins support Neovim v0.7+ rather than requiring only the most up to date release.

### Steps to reproduce

Just start neovim with version 0.8 with any amount of minimal configuration that just adds the plugin:

```sh
nvim --clean -u min-init.lua
```

### Expected behavior

I would expect support for a relatively recent version of Neovim rather than requiring the strict most recent. Or at least make this clear in the requirements since v2 supported older versions and v3 dropped all older neovim version support.

Thanks so much for your work on this project!

### Neovim version (nvim -v)

0.8.2

**Comment by mehalter** [comment]
AstroNvim has a function similar to what you would want to update the highlight file to to help get this started: https://github.com/AstroNvim/AstroNvim/blob/main/lua/astronvim/utils/init.lua#L113-L131

I can make a PR to add more compatibility early next week if you don't get a chance to :)

**Comment by lukas-reineke** [comment]
No, sorry. The maintenance overhead supporting older versions is incredibly high.

Version 2 supports old versions, you can stick with that until you can update.

**Comment by mehalter** [comment]
Totally understandable. Definitely unfortunate, but appreciate the insight! If I make a PR to add this would you be interested? I'm just asking as the core AstroNvim maintainer and enjoy using this plugin and don't want to drop it or stay on an unmaintained version.

**Comment by lukas-reineke** [comment]
I just can't guarantee that there is not something else that breaks in earlier versions. Or that I make a commit tomorrow that does.

How do you handle this with other plugins? Telescope for example is also v0.9+

**Comment by mehalter** [comment]
This actually isn't the case. Telescope supports back to Neovim 0.7 according to their release notes (https://github.com/nvim-telescope/telescope.nvim/releases/tag/0.1.2). They don't enable all of the features and focus all new features to be with 0.9 but it does function just fine back to Neovim 0.7. Currently this is the only plugin that doesn't support 0.8. We only officially support 0.8+ so it hasn't been a problem so far. We also pin plugins. So it's totally fine for me to just pin indent blankline to v2 until we release the next major release with breaking changes in a few months which will drop 0.8 support

**Comment by lukas-reineke** [comment]
I would be okay merging the PR, but I won't officially support 0.8. Did you try it to see if there is anything else?

**Comment by lukas-reineke** [comment]
PR is merged, but like I said no guarantees.
I won't be testing for support other than latest stable and nightly.

**Comment by lukas-reineke** [comment]
@mehalter your fix doesn't work #687

This is what I mean with maintenance effort :sweat_smile: it's so difficult to cover all edge cases on old versions

**Comment by mehalter** [comment]
Ah yeah, I do think supporting old versions of nightly Neovim releases is easy to consider out of scope 😂

**Comment by mehalter** [comment]
I'll make a PR to fix this :)
