### ISSUE TITLE
How to set colors in g:indent_blankline_char_highlight_list

### ISSUE THREAD

**Issue by TornaxO7** [lukas-reineke/indent-blankline.nvim#66]
Hello! Can I only use the highlighting groups like `Error` or `Function` or can I specify the color explicitely with hex values like `#00ff00` for green. Something like that:
```vim
let g:indent_blankline_char_highlight_list = [`#00ff00`]
```

**Comment by lukas-reineke** [comment]
Its highlight groups, like `Error` and `Function`

If you want to set a custom color, just create a new highlight group like this:

```vim
highlight IndentColor guifg=#00ff00
let g:indent_blankline_char_highlight_list = ['IndentColor']
```

**Comment by TornaxO7** [comment]
Nice! Thank you :)
