### ISSUE TITLE
still having trouble migrating

### ISSUE THREAD

**Issue by jam1015** [lukas-reineke/indent-blankline.nvim#660]
### Problem

My two issues:

# not sure how to integrate V3 with my `list` settings.

I previously had

```
local set = vim.opt
set.list = true
set.listchars = ''
set.listchars = set.listchars + 'trail:␣'
set.listchars = set.listchars + 'lead:·'
set.listchars = set.listchars + 'extends:»'
set.listchars = set.listchars + 'precedes:«'
set.listchars = set.listchars + 'tab:   '
set.listchars = set.listchars + 'nbsp:⣿'
```

and used v2 of blankline with no problems.

Now I can delete the `list` settings from my config and blankline works, but I like my trailing spaces listchars.  If I have list and include trailing space list characters but not tabs, it looks messed up. It is not immediately clear how to integrate your new version with the `list` and `listchars` setting.  I can set a vertical bar in my tab listchars setting above, but I'm having trouble getting the smooth line with no breaks that was the default in the old versions.  Some examples in the documentation could help.

 It could be helpful to be more specifict about the meaning of `list`, whether referring to a lua list in the code or the base vim/neovim list/listchars setting. 

# higlighting is different

It is cool that the guides light up, but I'm not immediately sure how to turn this off.  I eventually will explore all the settings but this is a pretty big exercise, reading more documentation.  The documentation could be more verbose as well; I understand that the best people in tech pick up terse things quickly, but that's not everyone!

### Expected behavior

I know that updates can introduce breaking changes, but I would like a more thorough migration explanation that addresses the issues above.  I want to be more specific, but I'm in a time crunch. Thanks for making a great plugin, but I'm going back to the commit before v3 for now!

**Comment by lukas-reineke** [comment]
> I eventually will explore all the settings but this is a pretty big exercise, reading more documentation. The documentation could be more verbose as well

Come on, you can't say the documentation is not verbose enough if you haven't even read it. All your questions are answered in the documentation.

For how tab chars work, and how they are affected by `list`, see `:help ibl.config.indent.tab_char`

The scope highlight can be turned off with `:help ibl.config.scope.enabled`, and this is also covered in the [migration guide](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3)

**Comment by chrboesch** [comment]
> Come on, you can't say the documentation is not verbose enough if you haven't even read it. All your questions are answered in the documentation.

No, not really. I tried the examples, but got often some error messages. After several hours I give up now, to enabling "show context" with Zig.  I'm not a lua developer but I think you think that every one who wants to use your plugin must. Sorry, but I want to switch back to version 2. But there is no explanation what branch I have to specify in packer to do that. 
I think that you can't imaging how frustrating that is. I got the update to version 3 without any questions or hints about the problems I'll get. But I gave this version a chance. I also took a look at your dot files, hopefully to find some hints. Nada. You've only have an old version published. 
So, what's your suggestion, what shall I do?
