### ISSUE TITLE
Filetype '' not excluded

### ISSUE THREAD

**Issue by TroySigX** [lukas-reineke/indent-blankline.nvim#662]
### Problem

Even though I set to exclude the `''` filetype, `indent-blankline` still shows indent in this ft.

### Config:
```lua
  require('ibl').setup({
    exclude = {
      filetypes = {
        'lspinfo',
        'packer',
        'checkhealth',
        'help',
        'man',
        'dashboard',
        '',
      },
      -- filetypes = vim.g.exclude_filetypes,
    },
  })
```

### Steps:
1. Enter `nvim`
2. Go to insert mode and press `Tab` a few times
3. Go to new line, press `Tab` a few more times

### Expected behavior

`indent-blankline` doesn't show indents

### Neovim version (nvim -v)

0.9.2

**Comment by lukas-reineke** [comment]
Was a bug, released a fix now. Thanks
