### ISSUE TITLE
Unexpected difference in behavior between tabs and spaces with `list` enabled

### ISSUE THREAD

**Issue by B14CK313** [lukas-reineke/indent-blankline.nvim#665]
### Problem

When enabling `list` (`:set list`) tab characters are shown as specified in `listchars` and just highlighted different, but spaces are shown as `ibl.indent.char`.

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/22134010/0ad86306-4cee-43cc-ae6b-07af6c2a147b)

Is this a misunderstanding on my side, did I miss a config option, or is this working as intended?

### Steps to reproduce

- add `vim.opt.listchars = { space = "·", leadmultispace = "◦···", tab = "⇥ " }` to min-init.lua
- open file indented with tabs and spaces
- `:set list`

### Expected behavior

I'd expect ibl to treat spaces the same as tab characters by just changing the highlight and not the character shown, or expressed differently, respect `lcs-space` / `lcs-multispace` / `lcs-lead` / `lcs-leadmultispace` also for space characters.

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/22134010/9dc7034b-7d97-4a05-87e1-7a0d94b7eccf)

### Neovim version (nvim -v)

v0.10.0-dev-1249+gdc6d0d2daf

**Comment by lukas-reineke** [comment]
This is the expected behavior, please take a look at `:help ibl.config.indent.tab_char`

**Comment by hinell** [comment]
A workaround:

```lua

config = function()
		local config = require("ibl.config").default_config
		config.indent.tab_char = config.indent.char
		require("ibl").setup(config)
end
```
