### ISSUE TITLE
V3: replicate v2 show_current_context_start = false

### ISSUE THREAD

**Issue by catgoose** [lukas-reineke/indent-blankline.nvim#666]
### Problem

I like to not show the first blankline:

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/21010072/733ba8b3-986f-46e4-9141-7ac5912595de)

But with v3, when I am on a line in the most outer scope, I get a highlight for that initial blankline:

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/21010072/76b04e0b-0a2c-4062-811f-6920e5e1963a)

### Steps to reproduce

My v3 config:

```lua
local opts = {
	indent = {
		highlight = { "LineNr" },
	},
	whitespace = {
		enable = false,
		remove_blankline_trail = true,
		highlight = { "IndentBlanklineSpaceChar" },
	},
	exclude = {
		filetypes = {
			"checkhealth",
			"help",
			"terminal",
			"markdown",
		},
		buftypes = {
			"terminal",
			"nofile",
		},
	},
	scope = {
		enabled = true,
		char = "▎",
		show_start = false,
		show_end = false,
		injected_languages = true,
		highlight = { "IndentBlanklineContextChar" },
		priority = 1024,
	},
}

local config = function()
	local hooks = require("ibl.hooks")
	hooks.register(hooks.type.WHITESPACE, hooks.builtin.hide_first_space_indent_level)
	hooks.register(hooks.type.WHITESPACE, hooks.builtin.hide_first_tab_indent_level)
	require("ibl").setup(opts)
end

return {
	"lukas-reineke/indent-blankline.nvim",
	opts = opts,
	config = config,
	event = "BufReadPre",
	main = "ibl",
}
```

### Expected behavior

I tried using

```lua
	hooks.register(hooks.type.SCOPE_HIGHLIGHT, hooks.builtin.hide_first_space_indent_level)
```
But this generates errors every time I move the cursor:

```
Error executing lua callback: .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/hooks.lua:248: attempt to index local 'whitespace_tbl' (a number value)
stack traceback:
        .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/hooks.lua:248: in function 'fn'
        ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:353: in function 'refresh'
        ...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:45: in function <...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:39>
```

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1254+g386bc23e4-dirty

**Comment by lukas-reineke** [comment]
> hooks.register(hooks.type.SCOPE_HIGHLIGHT, hooks.builtin.hide_first_space_indent_level)

The type is wrong, `hide_first_space_indent_level` is a `WHITESPACE` hook

`hooks.register(hooks.type.WHITESPACE, hooks.builtin.hide_first_space_indent_level)`

**Comment by catgoose** [comment]
Yes, but how do I hide the scope if it is the outer-most scope?  I shouldn't need an indication that I am there.

Thanks!

**Comment by lukas-reineke** [comment]
That's not supported out of the box, but you can write your own hook for that
