### ISSUE TITLE
Too many indent characters...

### ISSUE THREAD

**Issue by ahmedkhalf** [lukas-reineke/indent-blankline.nvim#67]
Hello, I think there are too many indent characters in places where they shouldn't be necessary...

Consider this screenshot for example:
![image](https://user-images.githubusercontent.com/36672196/112031651-02c6dc00-8b55-11eb-9fbf-09c06c0b8949.png)

I want it to behave like vscode where the indent chars only appear within scopes:

![image](https://user-images.githubusercontent.com/36672196/112031850-373a9800-8b55-11eb-860f-b4491b364e56.png)

**Comment by lukas-reineke** [comment]
There is a setting for this.
`let g:indent_blankline_show_trailing_blankline_indent = v:false` should turn them off.

**Comment by ahmedkhalf** [comment]
Wow perfect.
