### ISSUE TITLE
Provide an ability to disable the horizontal line scope highlight

### ISSUE THREAD

**Issue by dmtrKovalenko** [lukas-reineke/indent-blankline.nvim#678]
### Problem

I do like the ability to highlight the scope vertically but I hate this horizontal underline in the top of the scope block.

<img width="847" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/16926049/e86e28d6-01fb-4c1d-a94e-27a873124821">

### Expected behavior

I'd like to have the option to disable underline highlight and leave only the left. I thought that having 

```lua
      scope = {
        enabled = false
      }
```

will do the thing but instead it turns off all the highlight

**Comment by gutomotta** [comment]
Hey @dmtrKovalenko, maybe the options `scope.show_start` and `scope.show_end` will do the trick for you (it did for me):

```lua
require("ibl").setup({
  scope = {
    show_start = false,
    show_end = false,
  },
)
```

**Comment by lukas-reineke** [comment]
Correct, you are looking for `:help ibl.config.scope.show_start` and `:help ibl.config.scope.show_end`
