### ISSUE TITLE
Error when starting nvim: module 'ibl' not found

### ISSUE THREAD

**Issue by Noah4ever** [lukas-reineke/indent-blankline.nvim#683]
### Problem

I get this error when starting nvim:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/66632359/84b6cb2e-a4ed-4706-967b-408cd1578b83)

### Steps to reproduce

We are using kickstart.nvim and this is the config in the `init.lua`:
```lua
...
  {
    'lukas-reineke/indent-blankline.nvim',
    main = "ibl",
    opts = {
      char = '┊',
      show_trailing_blankline_indent = false,
    },
  },
...
```

### Expected behavior

Start without error.

### Neovim version (nvim -v)

v0.10.0-dev

**Comment by xcarolan** [comment]
This is still an issue:

NVIM v0.10.0-dev-25cfe3f
Build type: RelWithDebInfo
LuaJIT 2.1.1697887905
Compilation: /usr/bin/gcc-10 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/runner/work/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/runner/work/neovim/neovim/.deps/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Failed to run `config` for indent-blankline.nvim

...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:361: module 'ibl' not found:
^Ino field package.preload['ibl']
cache_loader: module ibl not found
cache_loader_lib: module ibl not found
^Ino file './ibl.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1/ibl.lua'
^Ino file '/usr/local/share/lua/5.1/ibl.lua'
^Ino file '/usr/local/share/lua/5.1/ibl/init.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/ibl.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/ibl/init.lua'
^Ino file './ibl.so'
^Ino file '/usr/local/lib/lua/5.1/ibl.so'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/ibl.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - init.lua:67
Pr

**Comment by recallmenot** [comment]
@xcarolan @Noah4ever [https://github.com/nvim-lua/kickstart.nvim/issues/271#issuecomment-1785032667](solution found)

**Comment by thienandangthanh** [comment]
> @xcarolan @Noah4ever
> 
> [solution found](https://github.com/nvim-lua/kickstart.nvim/issues/271#issuecomment-1785032667)

It helps!
Thank you very much, @recallmenot!
