### ISSUE TITLE
Invalid highlight name

### ISSUE THREAD

**Issue by likern** [lukas-reineke/indent-blankline.nvim#687]
### Problem

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/842306/07a8671b-d3f8-415d-986d-a8949842da50)

### Steps to reproduce

run fresh installation of LazyVim

### Expected behavior

Successfully load plugin without errors

### Neovim version (nvim -v)

v0.9.0-dev-746+g42e9a09a4

**Comment by lukas-reineke** [comment]
Your Neovim version is too old, please update to at least the latest stable version.

**Comment by likern** [comment]
Sorry, indeed, after updating to `v0.9.2` it's working. Thanks!
