### ISSUE TITLE
Additional line highlighted when cursor is on matching pair

### ISSUE THREAD

**Issue by kristijanhusak** [lukas-reineke/indent-blankline.nvim#69]
When cursor is on matching pair (curly bracket in my example), other pair sometimes highlights additional row. It's hard to explain, so here's the gif (line 52):

![indentline-multiline-highlight](https://user-images.githubusercontent.com/1782860/112334807-ff9a3000-8cbb-11eb-8ade-3935fbdd424e.gif)

As you see on gif, when I disable indentline, it doesn't happen.

**Comment by ratheesh** [comment]
Even I have observed this issue. This is seen when the following line of the current line is empty.

**Comment by lukas-reineke** [comment]
This is the same issue as #59 

I opened a bug in nvim here: https://github.com/neovim/neovim/issues/14209

Thank you for the information, this helped me reproduce it.

I'll close this ticket, let's use #59 for any updates
