### ISSUE TITLE
I am getting error when running kickstart.nvim with default indent-blankline setup

### ISSUE THREAD

**Issue by rp-nz** [lukas-reineke/indent-blankline.nvim#694]
I am using the following configuration file:
https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua

When I run nvim I get following error message just for indent-blankline module.

How do I fix this please. 

Failed to run `config` for indent-blankline.nvim                                                                                                                                                         
...e/nvim/lazy/indent-blankline.nvim/lua/ibl/highlights.lua:22: attempt to call field 'emtpy_dict' (a nil value)                                                                                         
\# stacktrace:                                                                                                                                                                                            
  - /indent-blankline.nvim/lua/ibl/highlights.lua:22 _in_ **get**                                                                                                                                        
  - /indent-blankline.nvim/lua/ibl/highlights.lua:40 _in_ **setup_builtin_hl_groups**                                                                                                                    
  - /indent-blankline.nvim/lua/ibl/highlights.lua:60 _in_ **setup**                                                                                                                                      
  - /indent-blankline.nvim/lua/ibl/init.lua:44 _in_ **setup**                                                                                                                                            
  - /indent-blankline.nvim/lua/ibl/init.lua:59 _in_ **setup**                                                                                                                                            
Press ENTER or type command to continue                                                                                                                                                                  
  - init.lua:67                                                                                                                                                                                          
Press ENTER or type command to continue

**Comment by lukas-reineke** [comment]
What version of Neovim are you using?

**Comment by rp-nz** [comment]
> What version of Neovim are you using?

NVIM v0.9.0-dev

**Comment by lukas-reineke** [comment]
That version is too old, please update to at least the latest stable version, 0.9.2

**Comment by rp-nz** [comment]
> That version is too old, please update to at least the latest stable version, 0.9.2

Hi there I have updated and that fixed this issue, thanks. Also I now cannot see the the end of line marks and also the "dot" char for each space. How do I enable  this, this is my default config  
 {
    -- Add indentation guides even on blank lines
    'lukas-reineke/indent-blankline.nvim',
    -- Enable `lukas-reineke/indent-blankline.nvim`
    -- See `:help indent_blankline.txt`
    main = "ibl",
    opts = {},
  },

**Comment by rp-nz** [comment]
> > That version is too old, please update to at least the latest stable version, 0.9.2
> 
> Hi there I have updated and that fixed this issue, thanks. Also I now cannot see the the end of line marks and also the "dot" char for each space. How do I enable this, this is my default config { -- Add indentation guides even on blank lines 'lukas-reineke/indent-blankline.nvim', -- Enable `lukas-reineke/indent-blankline.nvim` -- See `:help indent_blankline.txt` main = "ibl", opts = {}, },

That is based in the lazy config shown here: 
https://github.com/folke/lazy.nvim

**Comment by lukas-reineke** [comment]
eol and dot for spaces are a Neovim feature `:help list`and `:help listchars`.

But indent guides take priority over them.

**Comment by rp-nz** [comment]
> eol and dot for spaces are a Neovim feature `:help list`and `:help listchars`.
> 
> But indent guides take priority over them.

Thanks for your help.
