### ISSUE TITLE
scope not being underlined

### ISSUE THREAD

**Issue by exoess** [lukas-reineke/indent-blankline.nvim#696]
### Problem

I have show_start(end) set to true, but for some reason the scope horizontal line isn't appearing, how can I fix this?

### Steps to reproduce

this config with default theme
```
return {
    "lukas-reineke/indent-blankline.nvim",
    main = "ibl",
    opts = {
        scope = {
            enabled = true,
            show_start = true,
            show_end = true,
        },
    },
    config = function(_, opts)
        require("ibl").setup(opts)
    end
}
```

### Expected behavior

Characters inside the scope being underlined

### Neovim version (nvim -v)

v0.9.2

**Comment by lukas-reineke** [comment]
Can you check that your terminal supports underline? Try to run this in your shell `echo -e "\033[35m\033[4;31mhello world\033[0m"`

**Comment by uxodb** [comment]
echo -e "\033[35m\033[4;31mhello world\033[0m"

works for me, but show_end doesnt work for me either. my config looks alright, disabling scope or show_start for example works

**Comment by lukas-reineke** [comment]
The config you posted above is correct.
Try to use the [minimal reproduction template](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template) and see if it works there.

**Comment by exoess** [comment]
i apologize for my stupidity, but i forgot ts, i didn't realize it was required lol

**Comment by sgon00** [comment]
Hi, sorry to interrupt you. I am having the same issue. There is no underline. What do you mean by "forgot ts"? Thanks a lot.

**Comment by sgon00** [comment]
Please ignore my last comment. I think it's something wrong about how NvChad handles the theme. I tried pure neovim without NvChad, it works. Anyway, I give up underlines, because I need to use NvChad.
