### ISSUE TITLE
Getting Error during the start

### ISSUE THREAD

**Issue by yelinaung** [lukas-reineke/indent-blankline.nvim#697]
### Problem

Hello,
I am getting this error after I updated the plugin to the latest version
```
Failed to run `config` for indent-blankline.nvim

.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:18: 'char' is not a valid key of ibl.config

# stacktrace:
  - /indent-blankline.nvim/lua/ibl/utils.lua:18 _in_ **validate**
  - /indent-blankline.nvim/lua/ibl/config.lua:111 _in_ **validate_config**
  - /indent-blankline.nvim/lua/ibl/config.lua:271 _in_ **set_config**
  - /indent-blankline.nvim/lua/ibl/init.lua:59 _in_ **setup**
  - .config/nvim/init.lua:66
 ```

This is the neovim version
```
~ nvim -v
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

I am using lazy.nvim to manage the plugin.
Thanks!

### Steps to reproduce

The plugin config
```
  { -- Add indentation guides even on blank lines
    'lukas-reineke/indent-blankline.nvim',
    -- Enable `lukas-reineke/indent-blankline.nvim`
    -- See `:help indent_blankline.txt`
    main = "ibl",
    opts = {
      char = '┊',
      show_trailing_blankline_indent = false,
    },
  },
```

### Expected behavior

Error should not appear during the nvim starts.

### Neovim version (nvim -v)

NVIM v0.10.0-dev

**Comment by lukas-reineke** [comment]
That error is correct, both `char` and `show_trailing_blankline_indent` are not valid options. They are options from version 2.
Take a look at the [migration guide](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3)
