### ISSUE TITLE
Invalide 'opts' key

### ISSUE THREAD

**Issue by bavo96** [lukas-reineke/indent-blankline.nvim#698]
### Problem

When I first installed install indent-blackline, I got an error like this: 
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/27908949/fa438130-f3b2-4989-aeb6-3483c2bd0713)
This error only happens when I open .lua file, but when I open other files like .py (python), it doesn't show any error.

### Steps to reproduce

my min-init.lua
```lua
local lazypath = "/tmp/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system { "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath }
end
vim.opt.rtp:prepend(lazypath)
vim.opt.termguicolors = true

require("lazy").setup ({
    {
        "lukas-reineke/indent-blankline.nvim",
        config = function()
            require("ibl").setup {}
        end,
    },
    -- uncomment this if the problem is related to scope
    -- {
    --     "nvim-treesitter/nvim-treesitter",
    --     build = ":TSUpdate",
    --     config = function()
    --         require("nvim-treesitter.configs").setup {
    --             ensure_installed = { "rust" }, -- change this to the language you use
    --         }
    --     end,
    -- },
}, { root = "/tmp/lazy" })
```
open a lua file (with indent):

```bash
nvim --clean -u min-init.lua
:edit lua-file.init
```
result in min-init.lua
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/27908949/4eb36d50-9f8a-47b7-a5ee-449d5ff29c2e)

### Expected behavior

There should be no error and show indent normally.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1237+gaccdb0104

**Comment by lukas-reineke** [comment]
Your Neovim version is too old. Please update to at least the latest stable version, v0.9.2

**Comment by bavo96** [comment]
Many thanks, the issue is gone :heart:
