### ISSUE TITLE
Error on load with Lazy and neovim 0.9.2

### ISSUE THREAD

**Issue by crisdegraciadev** [lukas-reineke/indent-blankline.nvim#700]
### Problem

I have copied the setup from the documentation and I'm getting this error every time I open neovim

```
Failed to run `config` for indent-blankline.nvim

...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:362: module 'ibl' not found:
^Ino field package.preload['ibl']
cache_loader: module ibl not found
cache_loader_lib: module ibl not found
^Ino file './ibl.lua'
^Ino file '/usr/share/luajit-2.1/ibl.lua'
^Ino file '/usr/local/share/lua/5.1/ibl.lua'
^Ino file '/usr/local/share/lua/5.1/ibl/init.lua'
^Ino file '/usr/share/lua/5.1/ibl.lua'
^Ino file '/usr/share/lua/5.1/ibl/init.lua'
^Ino file './ibl.so'
^Ino file '/usr/local/lib/lua/5.1/ibl.so'
^Ino file '/usr/lib/lua/5.1/ibl.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
```

The plugin seems to work, but it's so disgusting to see this message every time I open my editor.

### Steps to reproduce

Setup the plugin with Lazy config

### Expected behavior

The error should not appear

### Neovim version (nvim -v)

0.9.2

**Comment by lukas-reineke** [comment]
It probably means you still have version 2 installed. Make sure you update to the latest version

**Comment by yart** [comment]
> It probably means you still have version 2 installed. Make sure you update to the latest version

I have the same issue too, and it looks like my Lazy plugin manager downloaded the last version:

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/470045/0cefcc88-06d3-4a29-b357-ae9701f6c8a1)

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/470045/a261503d-6544-4e28-8171-debfe52a9ba1)

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/470045/c89b3dc6-7df3-41e7-97c7-8a737d0c3ff7)

**Comment by lukas-reineke** [comment]
From the lazy.nvim issue you linked it looks like you get a different error.

> 'show_first_indent_level' is not a valid key of ibl.config

This error is correct, version 3 does not have  `show_first_indent_level`. Your configuration is wrong. Please read [migration guide](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3) and the documentation.

**Comment by yart** [comment]
Thank you, @lukas-reineke! I've removed this line and the plugin works without errors now.
