### ISSUE TITLE
Virtual text moving when file is formatted

### ISSUE THREAD

**Issue by ribru17** [lukas-reineke/indent-blankline.nvim#701]
### Problem

When formatting a file, the virtual text is sometimes not recalculated and covers up the actual text of the file. For instance, when formatting the following with `prettierd`:
Before formatting:
![iblbeforebug](https://github.com/lukas-reineke/indent-blankline.nvim/assets/55766287/a2e8ad8f-9959-4a1b-a853-ba7a175d65e0)
After formatting:
![afteriblbug](https://github.com/lukas-reineke/indent-blankline.nvim/assets/55766287/8903467e-c8d0-4762-ab2e-857e7a295c8e)
The `ibl` character remains in the middle of the text. Yanking the two characters (the context character and the whitespace after it) show that `</` are indeed the actual text content, they are just hidden by the virtual text.

### Steps to reproduce

1. `nvim --clean -u min-init.lua test.html`
2. `:w`

`min-init.lua`:
```lua
local lazypath = '/tmp/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable',
    lazypath,
  }
end
vim.opt.rtp:prepend(lazypath)
vim.opt.termguicolors = true

require('lazy').setup({
  {
    'lukas-reineke/indent-blankline.nvim',
    config = function()
      require('ibl').setup {}
    end,
  },
  {
    'stevearc/conform.nvim',
    config = function()
      require('conform').setup {
        format_on_save = {
          timeout_ms = 1000,
          lsp_fallback = true,
          quiet = true,
        },
        formatters_by_ft = {
          -- must also have `prettierd` installed on your machine
          html = { 'prettierd' },
        },
      }
    end,
  },
}, { root = '/tmp/lazy' })
```

`test.html`:
```html
<div>
  hi
</div>
```

### Expected behavior

The formatted text does not have any virtual text covering it

### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.1694285958

**Comment by lukas-reineke** [comment]
Thanks, should be fixed now
