### ISSUE TITLE
Indent char changes to italics

### ISSUE THREAD

**Issue by 1bharat** [lukas-reineke/indent-blankline.nvim#71]
I have this config for indent-blankline
```
  use {
    'lukas-reineke/indent-blankline.nvim',
    branch = 'lua',
    opt = true,
    event = 'VimEnter *',
    config = function()
      vim.g.indent_blankline_filetype_exclude = { 'NvimTree' }
    end
  }

```
That is all the config for indent-blankline. The char changes to italics when using with react files.

![image](https://user-images.githubusercontent.com/6837979/112397653-a29f8800-8d56-11eb-9a39-5f066a7f7cb0.png)

**Comment by lukas-reineke** [comment]
hmm not sure :thinking:

Can you try to create a simple `init.vim` file that reproduces this?

**Comment by 1bharat** [comment]
I solved it by adding this to my config. 
`vim.g.indent_blankline_char = '│'`

It must be something with my font. Adding the above line fixes it.

**Comment by lukas-reineke** [comment]
FYI this was actually a bug. I commented more info in #72 

Should be fixed now
