### ISSUE TITLE
Also Error on load with Lazy and neovim 0.9.2,.

### ISSUE THREAD

**Issue by myegdfz** [lukas-reineke/indent-blankline.nvim#710]
### Problem

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/48350357/d0d17a46-bf1c-424d-965e-20a04a51e729)

### Steps to reproduce

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/48350357/dc6cc523-75c2-4a05-bf13-cd163887aee7)
Setup the plugin with Lazy config

maybe same to _https://github.com/lukas-reineke/indent-blankline.nvim/issues/700#issue-1927882676_
but i have no idea to fix it. 
removing `show_first_indent_level = true` is not work.

### Expected behavior

The error should not appear

### Neovim version (nvim -v)

0.9.2

**Comment by baddate** [comment]
update your plugin, it has been fixed, see the commit https://github.com/lukas-reineke/indent-blankline.nvim/commit/877c1db2bf957300097dd5348a665666a4d900cb

**Comment by myegdfz** [comment]
@Couto ψ(._. )> yeah, maybe it is, i didn't notice this commit.  my bad.😂
