### ISSUE TITLE
Version 3: Is there a way to disable `the first indent level` in `indent` and `scope`?

### ISSUE THREAD

**Issue by OliverChao** [lukas-reineke/indent-blankline.nvim#713]
### Problem

Version 2 has some features like `show_first_indent_level` and `show_current_context_start`.
And I have checked the version 3 manual and failed to figure out one way  in Version 3.
Is there some plan to support those features? 

### Expected behavior

Just like Version 2.

**Comment by lukas-reineke** [comment]
There is a hook to replace `show_first_indent_level`, see `:help ibl.hooks.builtin.hide_first_space_indent_level`

The equivalent of `show_current_context_start` for scope is `:help ibl.config.scope.show_start`
