### ISSUE TITLE
How to make indent-blankline display EOL (End Of Line) characters?

### ISSUE THREAD

**Issue by ItsTerm1n4l** [lukas-reineke/indent-blankline.nvim#715]
Before v3 i could make indent-blankline display an EOL `↴` character at the end of each line, how do I accomplish the same thing in v3?   
I have tried 
```
vim.opt.list = true   
vim.opt.listchars:append "space:⋅"
vim.opt.listchars:append "eol:↴"
```
but that makes neovim display its default tab character even though I do not have `vim.opt.listchars:append "tab: >"` in my config, and I do not want the tab character at all.   
Please could you show me the best way to get EOL characters and space characters in v3.   
Thank you.

**Comment by lukas-reineke** [comment]
EOl characters only come from Neovims `listchars`, this was the case in version 2 as well. You have to turn `list` on if you want them.

You can change how tabs are displayed with `:help lsc-tab` and `:help ibl.config.indent.tab_char`

**Comment by ItsTerm1n4l** [comment]
Ok.. I don't know how I had EOL characters then,
Thanks anyway!

**Comment by ItsTerm1n4l** [comment]
Fixed it! setting `tab_char = "¦"` stopped Nvim from using its own tab characters.
