### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by buddhiko1** [lukas-reineke/indent-blankline.nvim#716]
### Problem

First, thank you to the author of this open source plugin. I have been using this plugin for a while.

About neovim plugins, I have a question. Why do simple plugins often have major version upgrades? Upgrading requires me to carefully read the documentation again, and then reconfigure. It is also easy to make mistakes. From version 2 to version 3, my configuration file often crashes for no reason. I think this is completely unnecessary. It is a waste of time and effort for both the author and the user.

In the end, I found that the solution to this contradiction is to try not to use plugins. It seems that it does not affect my use. Maybe this is the feature of neovim, and this is why I am going to replace neovim with helix. A suggestion, thank you again.

### Expected behavior

Don't upgrade.

**Comment by buddhiko1** [comment]
Although I no longer use this plugin, still have a suggestion. The new default style in the dark theme makes it impossible to focus on the code itself.

**Comment by lukas-reineke** [comment]
Good luck with helix, please don't ever come back ❤️
