### ISSUE TITLE
Blankline highlighting isn't showing full indent levels

### ISSUE THREAD

**Issue by RRethy** [lukas-reineke/indent-blankline.nvim#717]
### Problem

Blank lines in v3 are not showing the rightmost indent guide which was present in v2.

indent-blankline v3:
<img width="798" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/21000943/466a6501-9488-4c81-95ca-8113001dafaa">

indent-blankline v2:
<img width="795" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/21000943/ed751770-c87b-4acb-aaf6-d5881118c896">

### Steps to reproduce

Using your [minimal init.lua preamble](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template#minimal-config), no config overrides are required.

```lua
require("ibl").setup({})
```

1. `nvim --clean -u min-init.lua`
2. Open the following Lua file:

```lua
if true then
    if false then
        print("hello")
    end

    print("world")
end
```

3. Observe the lack of indent guide under the first `end`, there will be one while v2 had two.

### Expected behavior

I would expect an indent guide directly under the `e` from the first `end`.

### Neovim version (nvim -v)

NVIM v0.9.2

**Comment by lukas-reineke** [comment]
This is the expected behavior now.

You can replicate the behavior from version 2 with this hook.

```lua
        require("ibl").setup {
            whitespace = {
                remove_blankline_trail = false,
            },
        }

        local hooks = require "ibl.hooks"
        local whitespace = require("ibl.indent").whitespace
        hooks.register(hooks.type.WHITESPACE, function(_, bufnr, row, whitespace_tbl)
            local line = vim.api.nvim_buf_get_lines(bufnr, row, row + 1, false)[1]
            if line == "" then
                table.insert(whitespace_tbl, whitespace.INDENT)
            end
            return whitespace_tbl
        end)
```
