### ISSUE TITLE
Disable IBL for local window

### ISSUE THREAD

**Issue by tummetott** [lukas-reineke/indent-blankline.nvim#719]
### Problem

Hey there,

It looks like with IBL v3, they've done away with the `require('indent_blankline.commands').disable(false)` function. I did stumble upon the `IBLDisable` command, but it seems to disable the indentation guides for all windows. Is there any way to disable them only for local windows?

Thanks a lottt!

### Steps to reproduce

as above

### Expected behavior

as above

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

**Comment by lukas-reineke** [comment]
You can use `:help ibl.setup_buffer()`
```lua
require "ibl".setup_buffer(0, { enabled = false })
```

**Comment by tummetott** [comment]
Thank you ❤️
