### ISSUE TITLE
Errors related to "unexpected key: hl_name"

### ISSUE THREAD

**Issue by jayzerbeam** [lukas-reineke/indent-blankline.nvim#727]
### Problem

When editing Lua or JavaScript files, I'm constantly seeing errors related to `indent-blankline.nvim/lua/ibl/inlay_hints.lua:17`:

![2023-10-13_13-28](https://github.com/lukas-reineke/indent-blankline.nvim/assets/9667667/0bfa4a39-7544-426b-97b5-41cf35f86909)

I haven't seen this error while editing C# files. 

### Steps to reproduce

```
return {
	"lukas-reineke/indent-blankline.nvim",
	main = "ibl",
	opts = {},
	config = function(_, opts)
		require("ibl").setup(opts)
	end,
}
```

### Expected behavior

The error is not present. 

### Neovim version (nvim -v)

0.8.3 release

**Comment by lukas-reineke** [comment]
Your Neovim version is too old. Please update to at least the latest stable version, which is v0.9.4 currently.
