### ISSUE TITLE
v3 Zig does not show context

### ISSUE THREAD

**Issue by chrboesch** [lukas-reineke/indent-blankline.nvim#728]
### Problem

Since v3, the "show context" feature no longer works when scrolling through Zig's source code:

![Selection_019](https://github.com/lukas-reineke/indent-blankline.nvim/assets/48591413/5e0de295-8b6f-49c0-8499-76cabc1b3c5f)

### Steps to reproduce

```lua
require("ibl").setup {
    indent = {
		char = "▏",
	},
	scope = {
		enabled = true,
		show_start = true,
		show_end = false,
		exclude = {
			language = {
				"help"
			}
		},
	},
}
```

### Expected behavior

Same like v2.

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.0-beta3

**Comment by lukas-reineke** [comment]
Scope is based on https://github.com/nvim-treesitter/nvim-treesitter scope. And there is no zig support.

But it would be relatively easy to add support, all that needs to happen is to add every treesitter node type that is a scope to https://github.com/lukas-reineke/indent-blankline.nvim/blob/master/lua/ibl/scope_languages.lua

But I don't know zig. You can make a PR if you want.

**Comment by lukas-reineke** [comment]
Oh i just saw you made a PR 😅

I'll merge it tomorrow, thanks
