### ISSUE TITLE
Can't disable on quickfix

### ISSUE THREAD

**Issue by coffebar** [lukas-reineke/indent-blankline.nvim#730]
### Problem

I can't disable indent-blankline.nvim for quickfix buffers 

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/3100053/3e230c53-1e71-4a81-887d-8f85cc161c5a)

spaces highlighted with dots 

### Steps to reproduce

My config opt with Lazy: 
```lua
    opts = {
      indent = { char = "▏" },
      exclude = {
        buftypes = {
          "help",
          "nofile",
          "prompt",
          "quickfix", ---<
          "terminal",
        },
        filetypes = {
          "qf", ---<
        },
      },
    },
```

Open quickfix from lua:

```lua
vim.fn.setqflist({}, "r", { title = "Diff: " .. dir, lines = {"Line 1", "Line 2"} })
vim.api.nvim_command("copen")
vim.api.nvim_buf_set_option(0, "filetype", "qf")
```

- see spaces highlighted with dots 

If open qf from :vimgrep ... copen, - result is the same

### Expected behavior

Expected invisible (transparent) spaces

### Neovim version (nvim -v)

v0.9.4

**Comment by lukas-reineke** [comment]
Spaces displayed as dots is not indent-blankline. This is a built in feature, see `:help 'list'` and `:help 'listchars'`

**Comment by coffebar** [comment]
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/3100053/296dea00-0db5-49e0-85e4-1c2fc7dce310)

Why does it go away when I disable the plugin?

**Comment by lukas-reineke** [comment]
Because in your config you enable list and set the listchars in the indent-blankline init call.

https://github.com/coffebar/dotfiles/blob/42e11f660b1614cce236e1b03fe50fd9ad09601d/.config/nvim/lua/coffebar/plugins.lua#L192-L194

But this is not indent-blankline. Those are native Neovim options.
