### ISSUE TITLE
line appears between empty lines in yaml and toml files

### ISSUE THREAD

**Issue by gmr458** [lukas-reineke/indent-blankline.nvim#732]
### Problem

As you can see in the images there is an indentation line that does not need to be there, this did not happen in the previous version.

YAML file
![20231015_21h44m37s_grim](https://github.com/lukas-reineke/indent-blankline.nvim/assets/53343401/57b3c8bc-fa16-4fe6-b6ca-fea384ad3113)

TOML file
![20231015_21h44m44s_grim](https://github.com/lukas-reineke/indent-blankline.nvim/assets/53343401/1b5deec7-00cb-47af-900a-7b25f56078b3)

It is fixed in YAML when the cursor is in two levels of indentation, in TOML it only happens in the current table under the cursor.

YAML file
![20231015_21h53m44s_grim](https://github.com/lukas-reineke/indent-blankline.nvim/assets/53343401/d2acaefe-a7d4-4785-91c3-d7900f108251)

TOML file
![20231015_21h56m35s_grim](https://github.com/lukas-reineke/indent-blankline.nvim/assets/53343401/c34e06d6-5466-4ef5-a9d2-eda38f56a0a7)

### Steps to reproduce

```lua
require("ibl").setup({
  scope = {
    enabled = true,
    show_start = false,
    show_end = false,
    include = {
      node_type = {
        lua = {
          "table_constructor",
        },
        go = {
          "import_spec_list",
          "field_declaration_list",
          "literal_value",
          "interface_type",
          "var_declaration",
          "const_declaration",
        },
        rust = {
          "field_initializer_list",
        },
        javascript = {
          "parenthesized_expression",
          "object",
        },
        python = {
          "argument_list",
          "list",
          "import_from_statement",
          "parenthesized_expression",
          "if_statement",
          "for_statement",
          "try_statement",
        },
      },
    },
  },
  indent = {
    char = "│",
  },
})
```
Open a yaml and toml file.

### Expected behavior

That in YAML the line disappears when there are no lines of code at that indentation level and in TOML I think it should only appear when you have an array of multiples lines.

### Neovim version (nvim -v)

NVIM v0.9.4

**Comment by lukas-reineke** [comment]
I do not get this behavior.
Please use the [minimal reproduction template](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template) and describe how to reproduce this.
![2023-10-16_12-55](https://github.com/lukas-reineke/indent-blankline.nvim/assets/12900252/7d4e8631-dc19-4423-8994-a00eee8c618a)
![2023-10-16_12-53](https://github.com/lukas-reineke/indent-blankline.nvim/assets/12900252/5d9070ef-f950-4c5a-ba08-f1acb0f6d7ac)

**Comment by lukas-reineke** [comment]
Ah I see this is for scope.
Both `yaml` and `toml` just don't work that well with scope, the concept just doesn't really make sense there.
`yaml` currently includes the whole document as scope, I will remove that, but it won't address all your points.

You can either live with it, or remove `yaml` and `toml` from scope using `:help ibl.config.scope.exclude.language`

**Comment by polyzen** [comment]
`rst` (reStructuredText) is also in this boat. `markdown` looks fine however it seems.

**Comment by lukas-reineke** [comment]
`rst` also had the document as a valid scope. I made a new release now that removes that.
`markdown` just doesn't have scope at all.
