### ISSUE TITLE
Not loading using packer and v3

### ISSUE THREAD

**Issue by AdrianRibao** [lukas-reineke/indent-blankline.nvim#735]
### Problem

The plugin v3 is not being loaded using packer config:

### Steps to reproduce

Packer config:
```
use({ "lukas-reineke/indent-blankline.nvim", module = "ibl" }) 
```

The setup:

```
local config = {
	indent = {
		char = "|",
	},
	scope = {
		enabled = true,
		show_start = false,
		show_end = false,
	},
}

require("indent_blankline").setup(config)
```

### Expected behavior

I expected the plugin to be loaded. Ex I can call `:IBLEnable`

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1696795921

**Comment by AdrianRibao** [comment]
It doesn't work either.

Do you think that `module="ibl"` is right in packer?

**Comment by AdrianRibao** [comment]
After I removed the `module="ibl"`from packer and used `require("ibl").setup(config)` it works!

Thanks!

**Comment by lukas-reineke** [comment]
> Do you think that module="ibl" is right in packer?

Yeah, that's correct.

If it still doesn't work then there is something else wrong in your config. Do you get any errors?
