### ISSUE TITLE
Unable to recreate Mixed Indentation

### ISSUE THREAD

**Issue by Alexander-Garcia** [lukas-reineke/indent-blankline.nvim#736]
### Problem

<img width="742" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/31865557/d9cdf894-f19a-461a-8c16-8aa90947fb57"> 

There is whitespace that is not include between indents or spaces between words in general. I have tried a few different config options passing into blankline but have been unable to recreate the Mixed Indentation. Apologies if I'm missing something obvious. Also, my vim otps are set to expandtab to spaces so I don't technically have a tab character but I should still see · between words and indentation levels?

### Steps to reproduce

<img width="418" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/31865557/a78501e4-6f75-4631-b7dc-87088c6c0b53"> 

Here is my config

lazy colorscheme config since catppuccin has integrations for blankline (although these should be default values anyway, added them just to make sure)
<img width="852" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/31865557/5b5fa3d1-3629-41b2-8e56-5cc4abf40489">  

### Expected behavior

<img width="846" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/31865557/2d48f64c-ac14-465c-953d-483c768261cf">  

Expected to see · character in whitespace between words like example.
 
 `const · blah · = · () · => {...}`

### Neovim version (nvim -v)

0.9.1

**Comment by lukas-reineke** [comment]
The whitespace characters are not from indent blankline. They are a built-in Neovim feature. Take a look at `:help 'list'`, and `:help 'listchars'`

**Comment by Alexander-Garcia** [comment]
ahhh my fault. Thank you
