### ISSUE TITLE
Broken scope guide with C #define

### ISSUE THREAD

**Issue by MariaSolOs** [lukas-reineke/indent-blankline.nvim#737]
### Problem

A `#define` directive in a C file causes the scope indent guide to suddenly break.

### Steps to reproduce

1. Paste the following code in a C file.
```c
#include <stdio.h>

#define PI 3.1416f

int main(void) {
  float radius = 0.0f;

  return 0;
}
```

2. Install `ibl` with the following configuration.
```lua
return {
    {
        'lukas-reineke/indent-blankline.nvim',
        main = 'ibl',
        event = 'VeryLazy',
        -- For setting shiftwidth and tabstop automatically.
        dependencies = 'tpope/vim-sleuth',
        opts = {
            indent = {
                char = '│',
            },
            scope = {
                show_start = false,
                show_end = false,
            },
        },
    },
}
```

3. Notice the broken guide in line 7:
<img width="285" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/62502207/75b23bae-9345-4878-84a8-136247c2823f">

### Expected behavior

For the scope guide to continue smoothly.

### Neovim version (nvim -v)

v0.10.0-dev-1379+ga8fc94a2f

**Comment by lukas-reineke** [comment]
Thanks, should be fixed now

**Comment by MariaSolOs** [comment]
Wow that was quick, thanks!
