### ISSUE TITLE
broken indent char with `noexpandtab` and `list` enabled

### ISSUE THREAD

**Issue by dm9pZCAq** [lukas-reineke/indent-blankline.nvim#741]
### Problem

with `indentline v3` when `vim.opt.list = true` and `vim.opt.expandtab = true` then it starts mixing indent chars from `indentline` and `listchars`

personally I prefer to set `listchars` to `"tab:  ,trail:·"`, so I need `list` to be enabled for trail to work, but i want tab char to be used from `indentline` and not from `listchars`

### Steps to reproduce

```vim
" nvim --clean -u min-init.lua
:set list
:e test.c
```
`test.c`:
```c
#include <stdio.h>

int main(void) {
	printf("hello, "
	       "world!\n");
	return 0;
}
```
![pic](https://github.com/lukas-reineke/indent-blankline.nvim/assets/46228973/e444d70a-ba1f-441c-992e-e6bf1780f61d)

### Expected behavior

in v2 indentline does not take into account `listachars` for indent character and this is as i understand is expected behavior

so it should looks like this
![pic](https://github.com/lukas-reineke/indent-blankline.nvim/assets/46228973/666f73a6-6ec1-40c9-83d5-5bcdfc5700b5)

### Neovim version (nvim -v)

0.9.4

**Comment by lukas-reineke** [comment]
This is the expected behavior, please read `:help ibl.config.indent.tab_char`

**Comment by dm9pZCAq** [comment]
ok, so the workaround for this to be like before is to set `tab_char = char`

here is how i done this in my `fennel` config is someone will need it:
```fennel
{1 "lukas-reineke/indent-blankline.nvim"
 :main "ibl"
 :config
 (λ [_ opts]
   (let [{: setup : update} (require :ibl)
         {: get_config} (require :ibl.config)]

     (setup opts)

     (-?> (get_config -1)
       (. :indent)
       (. :char)
       (#(when $ (update {:indent {:tab_char $}}))))))
 :opts {}}
```
