### ISSUE TITLE
Lazy Configuration (example)

### ISSUE THREAD

**Issue by kobzar** [lukas-reineke/indent-blankline.nvim#742]
### Problem

Migration is good news but i reaaly cant found any info how to normally setup some moments. 
So, maybe someone can show his configuration? 

The main question for me at this moment is how to make that line for active block was highlited? 
Fit this moment all lines is the same color

```lua
return {
	"lukas-reineke/indent-blankline.nvim",
  lazy = false,
	opts = {
  indent = {
      char = "│",
    },
    scope = {
      enabled = false,
    },
    exclude = {
      filetypes = { "help", "alpha", "dashboard", "Trouble", "lazy", "neo-tree" },
    },
    whitespace = {
      remove_blankline_trail = true,
    },
  },

	main = "ibl",
}
```

Thanks

### Expected behavior

.

**Comment by lukas-reineke** [comment]
> The main question for me at this moment is how to make that line for active block was highlited?

You turned this off with
```lua
scope = {
  enabled = false,
},
```

Just remove that from your config.

**Comment by kobzar** [comment]
The same results
<img width="1046" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/1912842/1e2f24bf-bbcc-49cb-b59b-053464b81be3">

**Comment by lukas-reineke** [comment]
A table in lua is not scope. In that screenshot you will not get scope highlighting.

**Comment by Danielkonge** [comment]
If I understand what you want correctly, it is what will be called `current_indent`, but you need to wait until #743 is merged.

**Comment by kobzar** [comment]
hoho
i am a critsrmass masrtER

**Comment by wookayin** [comment]
How do I add lua table into scope manually? More generally, I need the v2 behavior that highlights the current indentation; is it #743 correct?

**Comment by lukas-reineke** [comment]
Yes, current indentation highlighting is not ready yet.
I'll close this issue
