### ISSUE TITLE
Enable IBL only for some filetypes

### ISSUE THREAD

**Issue by brglng** [lukas-reineke/indent-blankline.nvim#746]
### Problem

Currently the following setup can be used to disable IBL for some filetypes.
```lua
require("ibl").setup {
    enabled = true,
    exclude = {
        filetypes = { "lua" }
    }
}
```
However, there is not a setup option for a "default disabled, but only enabled for some filetypes" setup, without manually adding autocmds.

### Expected behavior

It would be nice if it is possible to disable IBL by default but only enable for some filetypes using only `require("ibl").setup()` without the need to manually adding autocmds.

Thank you!

**Comment by Yoolayn** [comment]
There is a function to setup up only for certain buffers, you can write some ftplugins, for filetypes you want it working on :)

**Comment by lukas-reineke** [comment]
Take a look here https://github.com/lukas-reineke/indent-blankline.nvim/discussions/455#discussioncomment-7154394

**Comment by brglng** [comment]
Thanks.
