### ISSUE TITLE
Indent line doesn't refresh on CursorMoved

### ISSUE THREAD

**Issue by hiddenruins** [lukas-reineke/indent-blankline.nvim#75]
For the option `indent_blankline_show_current_context`, In the help file, it says that the plugin will refresh on `CursorMoved` but it doesn't refresh. When I check the autocommands list, `IndentBlanklineContextAutogroup` is not there.

https://user-images.githubusercontent.com/5569621/112742241-809f4300-8fac-11eb-81ab-419b25332eff.mp4

![image](https://user-images.githubusercontent.com/5569621/112742321-55692380-8fad-11eb-9b1f-ee92ef6e0ee3.png)

![image](https://user-images.githubusercontent.com/5569621/112742344-847f9500-8fad-11eb-9b83-a1ac435d9b6b.png)

Settings
```lua
vim.g.indent_blankline_char = '┊'
vim.g.indent_blankline_use_treesitter = true
vim.g.indent_blankline_show_current_context = true
vim.g.indent_blankline_filetype_exclude = {'help', 'packer'}
```

**Comment by lukas-reineke** [comment]
Maybe the same issue as #63 ? Are you lazy loading the plugin?
Or it could be an issue with the order you set the variable and load the plugin.

The current system isn't great, I want to update this to use a lua `setup` function, that should fix these issues. Just need to find some time.

If nothing else works, you can also just define the autocommand yourself for now.

```vim
augroup IndentBlanklineContextAutogroup
    autocmd!
    autocmd CursorMoved * IndentBlanklineRefresh
augroup END
```

**Comment by hiddenruins** [comment]
> Maybe the same issue as #63 ? Are you lazy loading the plugin?

I was lazy loading the plugin and requiring it on attach.
```lua
local custom_on_attach = function(client, bufnr)
  require'plugins._indent-blankline'
end
```
> Or it could be an issue with the order you set the variable and load the plugin.

This was the issue. Moving `vim.cmd[[packadd indent-blankline.nvim]]` at the end solved it. Thanks :)
