### ISSUE TITLE
Indent blank line appears on line count

### ISSUE THREAD

**Issue by u16rogue** [lukas-reineke/indent-blankline.nvim#751]
### Problem

Indent line seems to appear and start on where the line numbers are.
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/61908580/81b1a34f-f4df-4ea9-a61d-6057a015996c)

### Steps to reproduce

* write lines on a fresh buffer

### Expected behavior

The green indent should be after the line numbers

### Neovim version (nvim -v)

NVIM v0.9.4

**Comment by lukas-reineke** [comment]
That is not indent-blankline.

It's probably https://github.com/lewis6991/gitsigns.nvim

**Comment by u16rogue** [comment]
oops my bad, got the two confused as the former disappears as soon as IBL appears. Apologies.
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/61908580/21c68871-8136-4f79-8530-faebefe11695)
