### ISSUE TITLE
Ibl outputs an error while trying to clear already deleted buffer

### ISSUE THREAD

**Issue by festeh** [lukas-reineke/indent-blankline.nvim#756]
### Problem

Hi! I occasionally have errors on [this](https://github.com/lukas-reineke/indent-blankline.nvim/blob/master/lua/ibl/inlay_hints.lua#L17) line, which is saying `Invalid bufffer id ...`. This is probably due to I have a buffer auto-close plugin (`hbac.nvim`). I'd propose to add a check if a buffer exists here, if you want I can work on a PR. 

### Steps to reproduce

It's a bit involved to reproduce it, I guess it's easier just to fix with a buffer check.

### Expected behavior

If a buffer is already deleted, nothing is happened.

### Neovim version (nvim -v)

0.9.2

**Comment by lukas-reineke** [comment]
thanks, should be fixed now
