### ISSUE TITLE
tab character shown on blank line when in current scope

### ISSUE THREAD

**Issue by HumblePresent** [lukas-reineke/indent-blankline.nvim#758]
### Problem

I recently updated to version 3 of the plugin and noticed some odd tab characters on blank lines in C++ files. I simplified the code that produces the issue as seen in the images below.

In the first image a tab character is shown on line 8, a blank line, when the line is in the current scope.
![ibl_issue_1](https://github.com/lukas-reineke/indent-blankline.nvim/assets/60856003/95fde65a-d1dc-480e-97e2-d55b9c88a7d2)
In the second image the tab character disappears when line 8 is no longer included in the current scope.
![ibl_issue_2](https://github.com/lukas-reineke/indent-blankline.nvim/assets/60856003/56dbe5be-938f-451d-8da7-597f24b612da)
I believe the issue has something to do with the fact that the blank line is followed by the `private:` label which "interrupts" the indent guide characters. If the `private:` label is indented the blank line is filled with an indent character and no tab characters are shown.

### Steps to reproduce

- `nvim --clean -u min-init.lua` where scope is enabled and the `cpp` treesitter parser is installed
- `:set lcs+=tab:⟶ `
- `:edit ibl_tab_issue.cpp` where the file contains the following
```cpp
class MyClass
{
public:
    MyClass(int var)
        : var_(var)
    {
    }

private:
    int var_;
};
```
- move the cursor into the scope of the class

### Expected behavior

I expect blank lines to either be blank or have an indent guide character and not show any tab characters.

### Neovim version (nvim -v)

0.9.4

**Comment by FollieHiyuki** [comment]
If you just want to show an indent guide character instead of the tab character, look at `:help ibl.config.indent.tab_char` (simply set it to the same character as the indent character).

Though, I also prefer the ***"showing nothing in a blank line"*** option.

**Comment by HumblePresent** [comment]
Changing the `indent.tab_char` does work for my purposes, although I still think it is strange that the`tab_char` is used on a blank line with no tab indentation. It is also strange that the character only appears when the line is within the current scope.

**Comment by lukas-reineke** [comment]
That `tab_char` fixes it is coincidence, this is a bug.
When extending scope over lines that didn't have normal indentation, the code just checks if the line has space indentation, if not it uses tab indentation. But in this case it's neither.

I don't have time today, I'll look into this tomorrow.

**Comment by JonathanCroenen** [comment]
It happens in other cases with "abnormal" indentation too. I just stumbled on this example:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/44034156/8dd399d5-86ef-4196-9290-12edac47af98)
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/44034156/d1342883-e81e-4246-b0b2-f51f65a937b2)
(It seems to follow the last "abnormal" indent)

**Comment by lukas-reineke** [comment]
Released a fix for this now
