### ISSUE TITLE
Missing lines if open file from directory

### ISSUE THREAD

**Issue by adrianofoschi** [lukas-reineke/indent-blankline.nvim#76]
If I open a php file directly with `neovim mydir/myfile.php` I see all expected lines, it works.

![screenshot](https://user-images.githubusercontent.com/4822527/112762479-2af48600-9000-11eb-8338-f70df5840cc2.png)

If I open nvim inside a folder with `neovim mydir` and next, inside neovim, I open the file `myfile.php` via netrw or fzf etc. I dont see all lines:
As you can see I miss a line on `public function..`

![screenshot](https://user-images.githubusercontent.com/4822527/112762298-34c9b980-8fff-11eb-9c03-46ab48d409b6.png)

I'm using the lua branch on neovim 5.0 and linux os.
My configuration:
```
vim.bo.tabstop = 4
vim.bo.softtabstop = 4
vim.bo.shiftwidth = 4
vim.bo.autoindent = true
vim.g.indentLine_enabled = 1
vim.g.indent_blankline_char = "▏"
```

**Comment by lukas-reineke** [comment]
I can't reproduce this, can you check that `tabstop` (or `shiftwidth` if you are using `expandtab`) is set correctly?
Just run `:tabstop`

**Comment by adrianofoschi** [comment]
I don't have `tabstop` command

![screenshot](https://user-images.githubusercontent.com/4822527/112813087-22429500-907e-11eb-89ff-8182147ce7ed.png)

**Comment by lukas-reineke** [comment]
sorry, it's `:set tabstop`

**Comment by adrianofoschi** [comment]
> sorry, it's `:set tabstop`

in "direct file edit" it is 4 
in "directory file edit" it is wrong, 8

**Comment by adrianofoschi** [comment]
Sorry I solved, it was my fault.

I used `vim.bo.tabstop = 4` instead `vim.o.tabstop = 4`

Thanks you
