### ISSUE TITLE
Indent characters cut off LSP diagnostic underlines

### ISSUE THREAD

**Issue by jaywonchung** [lukas-reineke/indent-blankline.nvim#761]
Awesome plugin, thanks a lot.

Below is a screenshot of indent-blankline with an LSP error diagnostic that spans multiple lines.

<img width="536" alt="Screen Shot 2023-10-30 at 7 01 17 PM" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/29395896/8ba32435-ed4e-4bef-8779-2e6226739073">

You can see that the indent characters are cutting off the underlines, but ideally, it would be nice if the underlines can continue (i.e., the indent characters are somehow underlined, too).
Would there be a good way to achieve this?

**Comment by lukas-reineke** [comment]
No, it's not possible, sorry.
