### ISSUE TITLE
C scope highlight problem with newlines in if statements

### ISSUE THREAD

**Issue by Danielkonge** [lukas-reineke/indent-blankline.nvim#766]
### Problem

Scope highlighting doesn't have the expected behavior with certain formatting styles.

This is the expected behavior:

<img width="221" alt="Screenshot 2023-11-08 at 16 54 42" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7075380/c1bed668-eaf0-4640-9f96-973840ac1863">
<img width="210" alt="Screenshot 2023-11-08 at 16 57 07" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7075380/747f777f-e7e3-414a-a952-7d6887957e89">
<img width="322" alt="Screenshot 2023-11-08 at 16 57 23" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7075380/4464b2f1-b590-4636-abcf-2a0dac795d42">

I think these are also all okay, but I am not sure about the exact scopes here:
<img width="230" alt="Screenshot 2023-11-08 at 16 53 51" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7075380/e97ded2e-5276-4d89-b443-a4901aa08a99">
<img width="222" alt="Screenshot 2023-11-08 at 16 54 11" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7075380/3e2d1fa1-03fa-4a00-9554-968625e2dd54">
<img width="224" alt="Screenshot 2023-11-08 at 16 54 19" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7075380/a24859dd-50f8-4fec-803d-91dc64689edf">
<img width="220" alt="Screenshot 2023-11-08 at 16 54 33" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7075380/d91efa6c-928e-4d86-9093-de8bdfc37201">

This is wrong:
<img width="223" alt="Screenshot 2023-11-08 at 16 54 25" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7075380/962cb58d-7c15-4d11-bde8-4dc736d6b187">

As shown in the first few pictures, this highlighting can be fixed by changing the formatting a bit, but hopefully the code should still work correctly in this case. 

### Steps to reproduce

`nvim --clean -u min-init.lua` keeps giving errors when I run it with the [minimal config file](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template#minimal-config), so I don't have the minimal config, but I don't think the issue is hard to reproduce. 

Make a `c` file with:
```c
int main(int arg1,
         char **arg2,
         char **arg3
         )
{
  if (arg1 == 4
    && arg2 == arg3) {
    int tmp = 1;
    // comment
  } else {
    int tmp  = 2;
    // comment
  }
}
```
Move the cursor around different lines and look at the scope highlights. 

### Expected behavior

<img width="223" alt="Screenshot 2023-11-08 at 16 54 25" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7075380/abf2ac97-60ab-4079-b083-049db51f8de7">

In this picture the scope should highlight the second indentation guide to the left of the cursor. 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1451+g20dd9f3a2-Homebrew

**Comment by lukas-reineke** [comment]
Isn't this just a duplicate of #752

**Comment by Danielkonge** [comment]
I didn't think it was the same problem because the indent guides looked different, but looking at it again I think that is just because of `smart_cap_indent`. I think you are right that this is a duplicate, so I will close this issue and make a comment in the other issue instead. I think I might have a way to solve this after `current_indent` is committed (I would use that the calculation loop and drawing loop are different then).
