### ISSUE TITLE
Can't reproduce V2 config in V3 for python configuration

### ISSUE THREAD

**Issue by zippeurfou** [lukas-reineke/indent-blankline.nvim#767]
### Problem

I used to have this configuration which allowed me to have the highlight that I really liked for python.
```
 { 'lukas-reineke/indent-blankline.nvim',
    config = function()
      require("indent_blankline").setup({
        show_current_context = true,
        show_current_context_start = true,
        char = '┊',
        show_trailing_blankline_indent = false,
        use_treesitter = false,
      })
    end,
  },
```
If I recall when I was doing the configuration the biggest thing was to not enable treesitter as it didn't work well with python.
I tried to reproduce this configuration as much as I could doing this configuration:
```
  { 'lukas-reineke/indent-blankline.nvim',
     main = "ibl", opts = {
        indent = { char =  '┊',smart_indent_cap=false },
        scope = { include = { node_type = {["*"] = {'*'}}}},
    }
```
However the output is just different and I really don't enjoy it.
I'd like to know how could I reproduce exactly the same configuration with the v3 or if not possible how can I configure Lazy to use a version that works for me.

### Steps to reproduce

Update with the latest version and get lost ^^

### Expected behavior

As mentioned before I'd like to be able to have the exact same configuration.
I'd welcome any help :)

### Neovim version (nvim -v)

NVIM v0.9.1

**Comment by lukas-reineke** [comment]
Version 3 works differently, you can't get the exact same result.
You can use version 2 by specifying the tag in lazy
