### ISSUE TITLE
whitespace warning only in Lua and Python not in Clojure

### ISSUE THREAD

**Issue by TimoKramer** [lukas-reineke/indent-blankline.nvim#768]
### Problem

Hi,
I am seeing the warning of whitespaces at the end of lines or lines with only whitespaces in Lua and similar messages in Python but none of these in Clojure. I wonder what is responsible in the toolchain that I am not seeing these messages in Clojure. Is it an issue with the linter?

### Steps to reproduce

I am using nvim-kickstart and installed:

- clojure-lsp
- lua-language-server
- luacheck
- python-lsp-server
- stylua

Sorry, I don't know a more minimal reproduction.

### Expected behavior

I would like to see blankline and whitespace warnings in Clojure.

I just want to know where indent-blankline takes the warnings from. Is it a missing feature in Clojure?

### Neovim version (nvim -v)

0.9.4

**Comment by lukas-reineke** [comment]
indent-blankline adds indentation guides, it doesn't have anything to do with warnings.

The warnings are most likely from your LSP. Look into the documentation of the language server.
