### ISSUE TITLE
Chugs perfomance on big files with rainbow-delimiters.nvim integration

### ISSUE THREAD

**Issue by mister-choo** [lukas-reineke/indent-blankline.nvim#769]
### Problem

Nvim starts chugging in complicated scenarious and/or large files. 
profile.nvim showed that program spends majority of the time in ibl functions

### Steps to reproduce

Pretty much the rainbow-delimiters.nvim integration example

### Expected behavior

For this not to happen

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1506+g610f50dda Build type: Release LuaJIT 2.1.1699392533

**Comment by lukas-reineke** [comment]
There isn't anything I can do about this. The logic in ibl is very simple. The time is spent in treesitter and `vim.inspect_pos`, sorry.
