### ISSUE TITLE
Indent lines not showing with conceallevel 0

### ISSUE THREAD

**Issue by alexander-born** [lukas-reineke/indent-blankline.nvim#77]
I cannot get the indent lines to show without the dependency `Yggdroot/indentLine`. Am I missing some configuration? Didn't find anything in the docs.
But `Yggdroot/indentLine` is only working with `conceallevel` 1 or 2.

`conceallevel` is removing the `"` symbol in jsons and this messes up cursor collumn line. I prefer to keep the `"` symbols.

See screenshot:
![image](https://user-images.githubusercontent.com/61082865/113117693-002c4c80-920f-11eb-9520-99d53c34588e.png)

**Comment by alexander-born** [comment]
I got it fixed by using the `lua` branch.

**Comment by lukas-reineke** [comment]
:+1: glad you got it to work.


Also FYI, you can set `let g:vim_json_syntax_conceal = 0` to turn off json concealing `"`, so you can still use conceal in json files for other things.
