### ISSUE TITLE
After updating from 2.20.4, the indented blank lines are not marked anymore

### ISSUE THREAD

**Issue by nicemicro** [lukas-reineke/indent-blankline.nvim#772]
### Problem

I'm using vim to code in Python.
With 2.20.4 version of the plug-in, the indented lines are marked with | symbols.

Once I update to the current version, the indentation marks disappear.

(if I checkout 2.20.8, it works, the braking change seems to be introduced at 3.0.0)

### Steps to reproduce

I update the plugin using :PlugUpdate (I use vim-plug) to 3.3.7

### Expected behavior

Keep marking the indented lines with the | symbol

### Neovim version (nvim -v)

0.9.4

**Comment by lukas-reineke** [comment]
Version 3 had breaking changes, please read the [migration guide](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3)

**Comment by nicemicro** [comment]
I just used the plug-in without any additional configuration, so I don't even have an idea where to start configuring this. Thanks for pointing to the wiki anyways.

**Comment by lukas-reineke** [comment]
You need to add `:help ibl.setup() ` to your config. If you don't have any other configuration, that should be enough.

```lua
require "ibl".setup()
```
