### ISSUE TITLE
Whitelist individual file types?

### ISSUE THREAD

**Issue by HiPhish** [lukas-reineke/indent-blankline.nvim#773]
### Problem

I like this plugin, but I only want to use it in specific languages. In the old version there was an option named `filetype` where I could list the file types. It would be good to get something like this back.

### Expected behavior

 Maybe you could use the existing `enabled` setting?

- `true`: enabled for all (current behaviour)
- `false`: disabled for all (current behaviour)
- list of strings: enabled but only for the listed file types

**Comment by lukas-reineke** [comment]
Take a look here https://github.com/lukas-reineke/indent-blankline.nvim/discussions/455#discussioncomment-7154394
