### ISSUE TITLE
support `show_first_indent_level` again

### ISSUE THREAD

**Issue by Valentin271** [lukas-reineke/indent-blankline.nvim#777]
### Problem

Going from v2 to v3, it seems the config `show_first_indent_level` was dropped.

I really miss this option as I don't consider the first indentation ever being useful. See attached example screenshot.

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/36198422/d23eb230-a201-4cd2-a532-0ac74d5df85c)

I didn't find anything in the help, migration guide or issues. Is there a workaround? Would you consider re-adding this feature (or maybe something more flexible)?

### Expected behavior

Expected behavior is to have the first indent line removed.

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/36198422/a28ed8a9-50f1-48da-acaf-8e02271f5aed)

# Possible solution

- An option `ibl.config.indent.show_first_level` `(boolean)`
OR
- Some kind of list to define which level to show or not show

I have no experience with this codebase and thus don't know if this is feasible.

**Comment by lukas-reineke** [comment]
There are hooks for this now

`:help ibl.hooks.builtin.hide_first_space_indent_level` and `:help ibl.hooks.builtin.hide_first_tab_indent_level`

**Comment by Valentin271** [comment]
Exactly what I was looking for, thanks a lot!

I didn't thought I would find this features in hooks, should have made a global search.
