### ISSUE TITLE
indent line added when no indent present during fold

### ISSUE THREAD

**Issue by mhartington** [lukas-reineke/indent-blankline.nvim#78]
👋  hi there! was trying this plugin out and came across this odd error. i have the following html

```html
<body>

  <div>
    <div>
      <div>
        <p>test</p>
      </div>
    </div>
  </div>

  <a href="">one line tag</a>
</body>
</html>
````

<img width="429" alt="Screen Shot 2021-03-31 at 9 24 52 PM" src="https://user-images.githubusercontent.com/2835826/113230679-8aa09a80-9267-11eb-968f-70aac104f2a7.png">

between the last div and the start of the 'a' tag, there's a misplaced indent guide when there's no indent. worth mentioning that im on the lua branch.

**Comment by lukas-reineke** [comment]
If I understand your issue correctly, this indent line is "correct" there. Everything inside body is on the second level indent.
But there is an option to turn these trailing indents off for people who don't want them. `g:indent_blankline_show_trailing_blankline_indent`

**Comment by mhartington** [comment]
oh interesting. Ok , that makes sense. Thanks!
