### ISSUE TITLE
Space between lines

### ISSUE THREAD

**Issue by ShelpAm** [lukas-reineke/indent-blankline.nvim#785]
When I use wsl with a line-height greater than 1.3, it looks wierd like this:
# Actual behavior:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/77189208/b7e13498-9d2b-4005-9578-317626f3e58f)

# Expected behavior:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/77189208/e5588eab-ede6-4900-91fc-2ad210eedc5a)
but with a greater line-height.

### My configuration:
``` lua
require("ibl").setup({
  indent = { char = '▏' },
})
```

**Comment by lukas-reineke** [comment]
That's a limitation of your terminal. Some terminals like Kitty can render box drawing characters over the full cell, even with line height over 1. But if your terminal can't, it will look like this. There is nothing I can do here to fix that.
