### ISSUE TITLE
indent tab_char not working properly, after any characters.

### ISSUE THREAD

**Issue by TanawatJukmongkol** [lukas-reineke/indent-blankline.nvim#792]
### Problem

As the title suggests, the tab_char settings is not working properly.

![2023-12-10-045312_hyprshot](https://github.com/lukas-reineke/indent-blankline.nvim/assets/73843267/d66cd651-6607-4030-80b1-6f7ec003340d)

My config:

```vim
set		smartindent
set		noexpandtab
set		tabstop=4
set		shiftwidth=4
set		backspace=indent,eol,start
syntax	on
set		nu
```

```lua
require("ibl").setup {
	indent = {
		char = "→",
		tab_char = "→",
	},
	whitespace = {
		remove_blankline_trail = false,
	},
}
```

### Steps to reproduce

-

### Expected behavior

the ">" should have been swapped out with "→"

### Neovim version (nvim -v)

v0.9.4

**Comment by lukas-reineke** [comment]
> after any characters

indent-blankline only does indentation. Tabs after other characters are not indentation, so they won't get changed.  
`tab_char` is for when you want to change the way tabs for indentation look, but leave the rest as they are.  
If you want to change all tab characters, use the built-in Neovim feature `:help 'listchars'` instead.
