### ISSUE TITLE
[Question] Show indent line ontop of whitespace character

### ISSUE THREAD

**Issue by myzb** [lukas-reineke/indent-blankline.nvim#797]
### Problem

I hope this is the right way to ask questions.

I would kind of like to set up my nvim indentation similarly to how it is done in some IDE's, where the vertical "|" separator does not "consume" a character slot.

In the below pictures I have vscode set up on the left with 4-space indentation. On the right side nvim with indent-blankline, also 4-space indentation. For nvim I have set up my whitespace characters as follow:

```
vim.opt.listchars = { space = '·', tab = '→ ' }
```

What I wanted to ask if it is possible to set up indent-blankline to also show the 4 dot characters (instead of 3) if I have indented with 4-spaces. If this could also be made to work if I indent with a tab (so the tab shows) it would also be great. Basically the "|" would kind of have to use the same character slot on screen as the "." for the first space.

![vscode](https://github.com/lukas-reineke/indent-blankline.nvim/assets/6280154/9ba101b9-c5e9-4c86-9e02-5e30befa7aeb) ![nvim](https://github.com/lukas-reineke/indent-blankline.nvim/assets/6280154/3fc29ec0-51bc-4231-831a-d057d7808b1f)

Any ideas on how to achieve this?

Cheers and regards

### Expected behavior

Indent blankline showing indent "|" + X space characters for X space indentation. Instead of X-1.

**Comment by lukas-reineke** [comment]
Terminals are cell based, it is not possible to render anything in between two cells like it is in GUI applications.
