### ISSUE TITLE
Typo in `lua/ibl/config.lua`

### ISSUE THREAD

**Issue by heavyjoost** [lukas-reineke/indent-blankline.nvim#801]
`dispaly` should be `display` on this line: https://github.com/lukas-reineke/indent-blankline.nvim/blob/master/lua/ibl/config.lua#L91

**Comment by lukas-reineke** [comment]
:+1: 
Do you want to make a PR to fix it?
If not, I'll do it sometime this week.

**Comment by heavyjoost** [comment]
Added PR https://github.com/lukas-reineke/indent-blankline.nvim/pull/804
