### ISSUE TITLE
Golang Templ support? 

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [lukas-reineke/indent-blankline.nvim#806]
### Problem

Wondering if we can get golang templ support
[templ.guide](url)

Here is how it looks at the moment.
<img width="629" alt="Screenshot 2023-12-21 at 17 57 44" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/17408117/23a410fc-9e45-45d2-8f85-a76c7d5640a7">

Also scope does not work either.

### Expected behavior

Feature request.

**Comment by lukas-reineke** [comment]
I can't reproduce your screenshot, can you please use the [minimal reproduction template](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template)

For scope to work, there needs to be treesitter support for this.

**Comment by JonnyLoughlin** [comment]
This was a bug in `templ fmt` fixed [here](https://github.com/a-h/templ/pull/346).  Update templ and the issue should be fixed.

**Comment by JamesTiberiusKirk** [comment]
Sorry completly forgot about this issue. and yeah templ fmt works (but it is buggy)

sorry, it does seem like its an issue with templ formatter and not your plugin @lukas-reineke
