### ISSUE TITLE
Spaces cover text when scrolling to the right.

### ISSUE THREAD

**Issue by WhyNotHugo** [lukas-reineke/indent-blankline.nvim#81]
I sometimes have lines that don't fit in the current window:

![image](https://user-images.githubusercontent.com/730811/113346544-7fab4000-9323-11eb-9954-d138e27ca598.png)

When scrolling to the right, the indentation spaces from the left seem to overlap the code and cover it:

![image](https://user-images.githubusercontent.com/730811/113346616-9baee180-9323-11eb-8f80-2bf081569313.png)

**Comment by lukas-reineke** [comment]
This is a duplicate of #51

**Comment by WhyNotHugo** [comment]
It is, thanks.

--
Hugo Osvaldo Barrera
