### ISSUE TITLE
Does this work for vim? 

### ISSUE THREAD

**Issue by palladium-o** [lukas-reineke/indent-blankline.nvim#818]
### Problem

I installed this using pathogen tried to do 
```
lua
require "ibl".setup()
```

But got errors saying ibl isn't in any of the homebrew dirs, I have a plugin for neovim work with vim, it was for markdown [markdown-previewnvim](https://github.com/iamcco/markdown-preview.nvim), all I had to do to get it working was cd to `~/.vim/bundle/markdown-preview.nvim` then `npm install`

### Expected behavior

- Have this working with vim.
- Or at least a workaround like how I did with the neovim plugin I mentioned above. 

This is the only plugin which displays indent guides as thin lines without any breaks which is what I want.

**Comment by lukas-reineke** [comment]
No, sorry. This plugin does not, and probably will never, work in vim. It uses features that are only available in Neovim.
