### ISSUE TITLE
Highlight leading whitespace with dots as in screenshots

### ISSUE THREAD

**Issue by mohelm** [lukas-reineke/indent-blankline.nvim#819]
Hi Lukas - many thanks for the great plugin. 

I have a quick question: In my config I do not manage to get leading whitespace highlighted with dots as in the screens shots. 

Is this at all managed by the plugin? How can I enable this? 

Thanks!

**Comment by Danielkonge** [comment]
Look into `:h 'list'` and `:h 'listchars'`. E.g. something like
```lua
vim.opt.list = true
vim.opt.listchars = { lead = '.', tab = '|.' }
```
will give you something like what you are asking for. (But you probably want a centered dot instead of period and a better tab symbol.)
