### ISSUE TITLE
Terminal buffers aren't excluded

### ISSUE THREAD

**Issue by stsewd** [lukas-reineke/indent-blankline.nvim#82]
Hi, thanks for this plugin!

Minimal init.vim

```vim
call plug#begin('~/.local/share/nvim/plugged')              

Plug 'lukas-reineke/indent-blankline.nvim', {'branch': 'lua'}

call plug#end()                                               
                                                                                            
let g:indent_blankline_buftype_exclude = ['terminal', 'nofile', 'help']
```

Steps:

- `:terminal`
- `:echo b:indent_blankline_enableb` -> `v:true`

In help files it gets disabled, so maybe something special with terminal buffers. I think this was working some weeks ago.

**Comment by lukas-reineke** [comment]
Thanks for the ticket. I pushed a fix.

Can you check if it works now?

**Comment by stsewd** [comment]
It's working now, thanks!
