### ISSUE TITLE
Disable lines on "Dashboard Nvim" plugin

### ISSUE THREAD

**Issue by rafaeljacov** [lukas-reineke/indent-blankline.nvim#825]
### Problem

Lines are showing on dashboard-nvim
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/110229646/bdb2c95b-22b9-4df9-84b1-cc436fea1550)

### Expected behavior

The lines should be hidden when the dashboard nvim opens when opening nvim for the first instance.

**Comment by lukas-reineke** [comment]
You can use `:help ibl.config.exclude.filetypes` to disable the plugin for buffers like your dashboard.
