### ISSUE TITLE
Indent highlight doesn't work

### ISSUE THREAD

**Issue by alex35mil** [lukas-reineke/indent-blankline.nvim#828]
### Problem

After upgrade to v3, I can't change indent line color.

If I set default highlight, it is ignored. If I set a custom highlight, plugin errors out that the provided highlight doesn't exist, although I set it in my local theme. I tried to use `hooks`, but it has no effect. It seems like it's the loading order issue, but I can't load theme before the plugins, since I build theme with `lush`. I tried to load `ibl` on `VeryLazy` event, but it didn't work either.

Commit with update: https://github.com/alex35mil/dotfiles/commit/2a940d4537dae7370b403091e0336b7c3dcf6355
[Plugin config](https://github.com/alex35mil/dotfiles/blob/2a940d4537dae7370b403091e0336b7c3dcf6355/home/.config/nvim/lua/plugins/indent-blankline.lua)
[Theme with highlight](https://github.com/alex35mil/dotfiles/blob/2a940d4537dae7370b403091e0336b7c3dcf6355/home/.config/nvim/lua/theme/highlights.lua#L171)

Screenshots:

![CleanShot 2024-01-16 at 13 14 24@2x](https://github.com/lukas-reineke/indent-blankline.nvim/assets/4244251/41fbe120-f7a4-4fe4-8442-042aa42d4f97)

![CleanShot 2024-01-16 at 13 01 15@2x](https://github.com/lukas-reineke/indent-blankline.nvim/assets/4244251/2c061184-e7a8-4d2f-8f65-cfd045b2bda5)

### Steps to reproduce

My config: https://github.com/alex35mil/dotfiles/tree/2a940d4537dae7370b403091e0336b7c3dcf6355/home/.config/nvim

### Expected behavior

Indent highlight works.

### Neovim version (nvim -v)

v0.9.2

**Comment by alex35mil** [comment]
Yeah, if I start `nvim` with plugin disabled, and then `IBLEnable`, it picks up the highlight.

**Comment by lukas-reineke** [comment]
If you want to use highlight groups from your color scheme, you need to load the color scheme first.

**Comment by alex35mil** [comment]
[Workaround](https://github.com/alex35mil/dotfiles/commit/4e94a9998bfc6a228c35eba3e9d8c8ed38652583)

**Comment by romgrk** [comment]
Also seeing this issue. If it's really impossible to fix, it could use a note in the docs.
