### ISSUE TITLE
indentation breaks with breakindent set true

### ISSUE THREAD

**Issue by sdx6** [lukas-reineke/indent-blankline.nvim#829]
### Problem

when using these options
```lua
vim.opt.wrap = true
vim.opt.breakindent = true
vim.opt.linebreak = true
```
the indentation lines end up like this
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/133609845/efc733e2-6594-4bd9-b336-29de3e1cb6a9)

### Steps to reproduce

```
:set wrap
:set breakindent
:set linebreak
```
write some stuff with an indent in between and let it wrap line

### Expected behavior

i edited the image to what it should be like
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/133609845/0577d379-c8e5-4eb0-b0ef-eabab2c6dbe7)

### Neovim version (nvim -v)

0.9.5

**Comment by lukas-reineke** [comment]
Neovim 0.9.5 does not support this.
But this is working on nightly, please either use that, or wait for the next Neovim release.

**Comment by sdx6** [comment]
> Neovim 0.9.5 does not support this. But this is working on nightly, please either use that, or wait for the next Neovim release.

thanks! i upgraded to `neovim-git` and its working fine now :)
