### ISSUE TITLE
question: how to manage overlap background colors

### ISSUE THREAD

**Issue by xzbdmw** [lukas-reineke/indent-blankline.nvim#833]
### Problem

Sorry new to neovim , Is it possible to make indent color lowest priority so cursorline background color is in top?
<img width="1225" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/97848247/388c0192-63b5-42ff-8bdf-7838339cdc0f">

### Expected behavior

dont overlap

**Comment by xzbdmw** [comment]
or is it possible to behave like this ?
<img width="1436" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/97848247/c7998946-b3cd-4731-b536-e56934d21ffc">

**Comment by lukas-reineke** [comment]
No sorry, Neovim has no way to do that at the moment.
