### ISSUE TITLE
Guides Not Showing Correctly

### ISSUE THREAD

**Issue by ztroop** [lukas-reineke/indent-blankline.nvim#836]
### Problem

I'm not seeing indent lines (or whitespace dots) with the default configuration. It does show the indent highlight on the current scope. If I highlight it with my cursor, I can see the other indents - no dots still.

<img width="912" alt="Screenshot 2024-02-02 at 10 44 25 PM" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/5018339/bb75af59-0b27-4dae-b4c6-9716cdc0e54e">

If I run `:highlight IndentBlanklineChar`, I do see what I expect:
<img width="422" alt="Screenshot 2024-02-02 at 10 57 24 PM" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/5018339/c81ee5e9-fcd4-4f16-af87-1a164c2bbcca">

### Steps to reproduce

```lua
return {
  "lukas-reineke/indent-blankline.nvim",
  config = function()
    require("ibl").setup({
      whitespace = {
        remove_blankline_trail = true,
      },
    })
  end,
}
```

Other NVIM Configuration: https://github.com/ztroop/dotfiles/tree/master/nvim

### Expected behavior

To see guides and dots.

### Neovim version (nvim -v)

0.9.5

**Comment by lukas-reineke** [comment]
Make sure `IndentBlanklineChar` is set before you initialize indent-blankline.

**Comment by ztroop** [comment]
@lukas-reineke Do you mean setting the following?
```
vim.g.indent_blankline_char= '┊'
vim.g.indent_blankline_use_treesitter = true
vim.g.indent_blankline_show_current_context = true
```
If so, it does seem to change the result.

**Comment by lukas-reineke** [comment]
Sorry I didn't notice you used old highlight group. It should be `:help hl-IblIndent`

**Comment by ztroop** [comment]
I didn't find the documentation too helpful with regards to configuration. I'm using a modified configuration based on "multiple indent colours" from the `README.md`. I can see the other indents now.

I still cannot see the "dot" whitespace characters, even after experimenting with `whitespace` configuration options. I can live without it, so I'm closing the issue.

**Comment by lukas-reineke** [comment]
> I'm still unable to view the "dotted" whitespace characters.

That is not a feature of indent-blankline. It's a native Neovim option, `:help 'list'` and `:help 'listchars'`
