### ISSUE TITLE
slow call to `vim.split`

### ISSUE THREAD

**Issue by ces42** [lukas-reineke/indent-blankline.nvim#839]
### Problem

This plugin is kind of slow, and one of the reasons seems to be a slow function call to `vim.split` inside the hot loop on line 45 of `lua/ibl/indent.lua`: https://github.com/lukas-reineke/indent-blankline.nvim/blob/12e92044d313c54c438bd786d11684c88f6f78cd/lua/ibl/indent.lua#L41-L49

I have no idea why this is slow, but here's a profile (using [profile.nvim](https://github.com/stevearc/profile.nvim))
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/19842517/f1ff8890-fbb6-4141-b1a0-6a271e856610)

Each call to `vim.split` is taking ~0.1 ms for every line on the screen, several times per second. 

### Neovim version (nvim -v)

0.10.0 commit f6042d5c300c00

**Comment by ces42** [comment]
Actually the tracing profiler I used might be exaggerating the impact of `vim.split` a bit here. I tried using a sampling profiler and `vim.split` still shows up a lot but it's maybe only 10-15%. I still think it's worth avoiding it in the hot loop though.
![ibl_orig](https://github.com/lukas-reineke/indent-blankline.nvim/assets/19842517/26dc84b8-5314-4640-8b60-032e7b5e4576)

**Comment by lukas-reineke** [comment]
Thanks
`vim.split` itself isn't the problem, it's `vim.validate`. Validate is super slow. I made a new release that is using `vim.split` without validate now.
