### ISSUE TITLE
Does not work for CSS & Vue

### ISSUE THREAD

**Issue by ynhhoJ** [lukas-reineke/indent-blankline.nvim#844]
### Problem

Does not work indent highlight for CSS code.

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/22500212/4432757c-bbee-4495-8287-9c64527197ef)

### Steps to reproduce

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {}

body {
  .test {
    color: black;
  }
}
```

Config:
```lua
-- lazy
{
  "lukas-reineke/indent-blankline.nvim",
  event = "BufReadPre",
  main = "ibl",
  config = function()
    require("ibl").setup {
      indent = { char = "▏" },
      scope = {
        include = {
          node_type = {
            css = {
              "arguments",
              "block",
              "class_name",
            },
          },
        },
      },
    }
  end,
}
```
`TSModuleInfo`:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/22500212/af7e6e6b-58af-4e04-890c-4ee768a0692e)

### Expected behavior

Indent highlight current selected level

Example:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/22500212/5e9d992b-d027-48f5-b703-331f3279b4dc)

### Neovim version (nvim -v)

v0.10.0-dev-2526+g6525832a8

**Comment by ynhhoJ** [comment]
It seems that not all languages is supported. I expect same problem with `Vue.js`

**Comment by nyngwang** [comment]
I have a similar or severe problem:

<img src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/24765272/20d3a003-c879-48b5-86e4-71a6d0c774bb" width="400">
