### ISSUE TITLE
Old scope highlight looks better.

### ISSUE THREAD

**Issue by stulzer** [lukas-reineke/indent-blankline.nvim#846]
I've upgraded recently from 2 to 3.

On v2 the scope highlight looks like the following:

<img width="517" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/771492/0653c069-1fd6-46b1-9354-8890dea5afea">

Pay attention on the `def show`.

On the newest version is just an underline.

<img width="383" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/771492/6fd643a6-ccac-4120-83b8-0ccf6d564dfa">

Is there a way to make it look as good as it were on v2? Couldn't find in the documentation.

**Comment by lukas-reineke** [comment]
It's currently not supported, see #754
