### ISSUE TITLE
Indenline still shows on terminal 

### ISSUE THREAD

**Issue by siduck76** [lukas-reineke/indent-blankline.nvim#85]
![image](https://user-images.githubusercontent.com/59060246/113505245-32191800-955b-11eb-82d1-6eb23e5e43e3.png)

my config : vim.g.indent_blankline_filetype_exclude = {"help", "terminal"}

**Comment by lukas-reineke** [comment]
Terminal doesn't set a `filetype`. It sets a `buftype`.
This should work `vim.g.indent_blankline_buftype_exclude = {"terminal"}`

**Comment by siduck76** [comment]
thanks that works!
