### ISSUE TITLE
Indents only shown for the current context

### ISSUE THREAD

**Issue by alwaysamer** [lukas-reineke/indent-blankline.nvim#850]
### Problem

The Indents are only shown for the current context ( i suppose thats the correct word ). 
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/22222279/9d8bd507-03b2-473b-ae48-2b01bd43bb4d)

### Steps to reproduce

```
return {
    "lukas-reineke/indent-blankline.nvim",
    main = "ibl",
    opts = {},
    config = function()
        require("ibl").setup()
    end,
}
```
This is the config i use.

### Expected behavior

I would expect the Indents to be shown for every context.
Just like here
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/22222279/378692bb-2a44-4c2e-92e2-a5263e600a98)

### Neovim version (nvim -v)

0.9.5

**Comment by lukas-reineke** [comment]
I suspect the lines are the same color as your background. IBL takes the colors from existing highlight groups, check `:help ibl.highlights`.

**Comment by alwaysamer** [comment]
Yep that was it. Didn't think of that. 

Thanks! I will close the Issue then :)
