### ISSUE TITLE
Wrong underline/highlight

### ISSUE THREAD

**Issue by akaralar** [lukas-reineke/indent-blankline.nvim#852]
### Problem

The indent guides are correct but the underline and highlighting are incorrect

<details><summary>Image </summary>

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/309655/57392a09-f00d-45f3-9a63-7893ecfbf752)

</details>

### Steps to reproduce

```bash
git clone https://github.com/akaralar/nvim-blankline-bug
cd nvim-blankline-bug

nvim --clean -u min-init.lua 
:e WeSplit/ContentView.swift
```

<details><summary>min-init.lua</summary>

```lua

local lazypath = "/tmp/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system { "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath }
end
vim.opt.rtp:prepend(lazypath)
vim.opt.termguicolors = true

require("lazy").setup ({
    {
        "lukas-reineke/indent-blankline.nvim",
        config = function()
            require("ibl").setup {}
        end,
    },
    -- uncomment this if the problem is related to scope
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        config = function()
            require("nvim-treesitter.configs").setup {
                ensure_installed = { "swift" }, -- change this to the language you use
            }
        end,
    },
}, { root = "/tmp/lazy" })

```

</details>

### Expected behavior

The underline and highlighted scope should be the scope starting with `Picker`, not `ForEach`

### Neovim version (nvim -v)

0.9.5 stable

**Comment by lukas-reineke** [comment]
This is an issue with the swift treesitter grammar.
It sets the scope up until the next closing bracket.
![20240401_11h18m51s_grim](https://github.com/lukas-reineke/indent-blankline.nvim/assets/12900252/49c77d57-f0ce-4d28-a292-617f04684534)
