### ISSUE TITLE
[QUESTION] How to migrate from v2 to v3 using packer? Please improve documentation

### ISSUE THREAD

**Issue by AndresMpa** [lukas-reineke/indent-blankline.nvim#853]
### Problem

I already read the migration guide, I also searched for information on Reddit, but I have seen something about packer yet.

I'm intalling ibl like this:

```lua
-- Plugins
return require("packer").startup(function(use)
  use("lukas-reineke/indent-blankline.nvim")
end)
```

Then I have a config file called identation

```lua
require("ibl").setup({
  --buftype_exclude = { "terminal" },
  --filetype_exclude = { "dashboard", "NvimTree", "packer", "lsp-installer" },
  --show_current_context = true,
  --show_end_of_line = true,
})
```

### Expected behavior

I want to erradicated this

```
Error detected while processing /home/andresmpa/.config/nvim/init.lua:
You are trying to call the setup function of indent-blankline version 2, but you have version 3 installed.
Take a look at the GitHub wiki for instructions on how to migrate, or revert back to version 2.
```

**Comment by lukas-reineke** [comment]
Your config is correct, you should not get any errors.
Make sure there is no other config left anywhere else. I don't use packer so I can't help you there, sorry.

**Comment by AndresMpa** [comment]
Sorry for the delay, @lukas-reineke was right I was using 2 different .lua files to config the ibl
