### ISSUE TITLE
Enhancement for low cursor visibility

### ISSUE THREAD

**Issue by romgrk** [lukas-reineke/indent-blankline.nvim#854]
Follow-up of https://github.com/lukas-reineke/indent-blankline.nvim/issues/346

Do you think it would be possible to disable the indent lines for the current cursor line (or even character) as the cursor moves? If you're not interested in doing the work, would you accept a PR for it?

**Comment by lukas-reineke** [comment]
No, I don't think I will add this, sorry.
It would add a lot of complexity, to work around a problem that can easily be fixed at the source by configuring the terminal correctly.
