### ISSUE TITLE
How do I disable the plugin only on certain filetypes?

### ISSUE THREAD

**Issue by eeec-cal** [lukas-reineke/indent-blankline.nvim#855]
Hello, I'm currently making a Neovim config but the plugin enables on my splash screen for some reason. I'd like to know how to disable it only on certain filetypes. Here's a screenshot:
![20240405_19h08m05s_grim](https://github.com/lukas-reineke/indent-blankline.nvim/assets/165475152/677b2fe0-96d2-46cb-9d0f-a696b810c53a)

**Comment by befedo** [comment]
You might have a look [here](https://github.com/lukas-reineke/indent-blankline.nvim/blob/3d08501caef2329aba5121b753e903904088f7e6/lua/ibl/config.lua#L66-L83) which let's you disable based on file-/buftype.

**Comment by lukas-reineke** [comment]
Take a look at `:help ibl.config.exclude`
