### ISSUE TITLE
indent_blankline_show_first_indent_level = false ignores first char from indent_blankline_char_list

### ISSUE THREAD

**Issue by horseinthesky** [lukas-reineke/indent-blankline.nvim#86]
I have these chars set up
```
vim.g.indent_blankline_char_list = {"|", "¦", "┆", "┊"}
```
and
```
vim.g.indent_blankline_show_first_indent_level = false
```

As a result, it completely ignores the first char from the table
![image](https://user-images.githubusercontent.com/19948672/113519464-10d51d80-9595-11eb-80ea-68599313627c.png)

Expected the same behavior as `Yggdroot/indentLine`
![image](https://user-images.githubusercontent.com/19948672/113519492-3c580800-9595-11eb-8365-9e8181249176.png)

**Comment by lukas-reineke** [comment]
Thanks. I pushed a fix.

**Comment by horseinthesky** [comment]
Thank you.
