### ISSUE TITLE
Stuck when moving around

### ISSUE THREAD

**Issue by ShelpAm** [lukas-reineke/indent-blankline.nvim#862]
### Problem

When I pressed 'i', 'j', 'k' or 'l', the neovim got stuck, and the pressed key, like 'j', showed in lower right corner. And the pressed letter just left there without neovim moving the cursor.

~~Sorry that I am having some issue uploading the problem image.~~
The problem image is shown in next comment.

### Steps to reproduce

1. My config:
```lua
return {
  {
    "lukas-reineke/indent-blankline.nvim",
    event = 'BufEnter',
    config = function()
      require("ibl").setup({
        scope = {
          show_start = false,
          show_end = false,
        },
      })
    end
  },
}
```

2. nvim --clean -u min-init.lua :edit foo

### Expected behavior

neovim should interact with moving keys normally.

### Neovim version (nvim -v)

NVIM v0.9.5

**Comment by ShelpAm** [comment]
![Snipaste_2024-04-21_19-33-23-nvim-ibl-issue](https://github.com/lukas-reineke/indent-blankline.nvim/assets/77189208/837c1bb7-fe16-4111-afcd-eac3d2c43520)
This is the problem image.

**Comment by ShelpAm** [comment]
It seems that after disabling the plugin, the neovim gets stuck again...

**Comment by lukas-reineke** [comment]
I am very confident this is not caused by indent-blankline. I can't help you with this, sorry.

**Comment by ShelpAm** [comment]
Thank you...

**Comment by ShelpAm** [comment]
> I am very confident this is not caused by indent-blankline. I can't help you with this, sorry.

But after i disabled the plugin, neovim's behaviors came normal.

**Comment by lukas-reineke** [comment]
If you are sure it is IBL, please use the [reproduction-template](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template) and provide step by step instructions on how to reproduce the issue.
