### ISSUE TITLE
Unable to disable higlights

### ISSUE THREAD

**Issue by KnownBlackHat** [lukas-reineke/indent-blankline.nvim#864]
### Problem

I don't like highlight at all and so i wanted to disable it but even after setting it to null i m getting highlights

i don't want this underline highlight
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/65008967/13bacc26-ee3b-43f8-af6e-50ef310e736a)

### Steps to reproduce

```lua
require('ibl').setup {
    indent = {char = '│', highlight = None},
    whitespace = {remove_blankline_trail = false}
}
```

### Expected behavior

i don't want underline highlight

### Neovim version (nvim -v)

NVIM v0.10.0-dev-741+g996dd36c7 Build type: Debug LuaJIT 2.1.0-beta3

**Comment by morhaham** [comment]
Sadly this is currently not supported: https://github.com/lukas-reineke/indent-blankline.nvim/issues/846

**Comment by lukas-reineke** [comment]
> Sadly this is currently not supported: https://github.com/lukas-reineke/indent-blankline.nvim/issues/846

That is not true.

You are both misunderstanding what highlight is. Please read `:help :highlight`. Setting highlight groups changes the color of the indentation guides and the scope guide and underlines.

If you want to disable the underline, you can set `:help ibl.config.scope.show_start` and `:help ibl.config.scope.show_end` to false. If you don't want to use scope at all, you can disable it with `:help ibl.config.scope.enabled`

**Comment by morhaham** [comment]
> > Sadly this is currently not supported: #846
> 
> That is not true.
> 
> You are both misunderstanding what highlight is. Please read `:help :highlight`. Setting highlight groups changes the color of the indentation guides and the scope guide and underlines.
> 
> If you want to disable the underline, you can set `:help ibl.config.scope.show_start` and `:help ibl.config.scope.show_end` to false. If you don't want to use scope at all, you can disable it with `:help ibl.config.scope.enabled`

Sorry my bad, thank you! 
for the `show_end`, I am not able to see the underline when setting this to true:
```lua
  {
    "lukas-reineke/indent-blankline.nvim",
    main = "ibl",
    opts = {},
    config = function()
      local ibl = require("ibl")
      ibl.setup({
        scope = {
          show_start = false,
          show_end = true,
        },
      })
    end,
  },
```

<img width="953" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/3867713/d9d4710d-06ac-4816-b741-4ec0acf4a764">

**Comment by KnownBlackHat** [comment]
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/65008967/1fd9702b-08d1-42ee-8ecf-062ba32e3ff4)
Thanks! didn't knew about this
