### ISSUE TITLE
Warning: vim.tbl_flatten is deprecated, use vim.iter(…):flatten():totable() instead.

### ISSUE THREAD

**Issue by Aqa-Ib** [lukas-reineke/indent-blankline.nvim#866]
### Problem

 vim.tbl_flatten is deprecated. Neovim made this change in a recent commit.

### Steps to reproduce

Build Neovim from git main branch and launch it while using indent-blankline.

### Expected behavior

Use vim.iter(…):flatten():totable() instead.

Thank you very much.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-3+g4b02916334

**Comment by lukas-reineke** [comment]
Fixed in latest version
