### ISSUE TITLE
Show only the leading space

### ISSUE THREAD

**Issue by lucastrvsn** [lukas-reineke/indent-blankline.nvim#87]
Hello! Thanks for this plugin, I'm pretty happy using it. I just have a question about show only the  `leading space` of lines. My current config works (almost) for this:

```lua
vim.cmd([[
  let g:indent_blankline_char = '·'
  let g:indent_blankline_space_char = '·'
  let g:indent_blankline_use_treesitter = v:true
  let g:indent_blankline_show_trailing_blankline_indent = v:false
]])
```

But, this config show spaces on blanklines too. I don't want to show any others characters and I don't want to show any indentline on blanklines. Just want to show the leading spaces, like in indentLine plugin:

![image](https://user-images.githubusercontent.com/8826449/113864706-9d443380-9781-11eb-94c0-4db26e650bef.png)

How can I achive this? Right now with my settings look like this:

![Captura de Tela 2021-04-07 às 09 15 18](https://user-images.githubusercontent.com/8826449/113864850-c6fd5a80-9781-11eb-82a6-59d13a65b6db.png)

Thanks!

**Comment by lukas-reineke** [comment]
If you just want to display leading spaces, you can just do it with `listchars`. No need to use any plugin.
`set listchars=lead:·`

**Comment by lucastrvsn** [comment]
@lukas-reineke Thank you so much! I didn't know neovim have this option. Works the way I expected. Thank you so much and sorry for this issue.
