### ISSUE TITLE
A highlight group for trailing blankline indent

### ISSUE THREAD

**Issue by vufly** [lukas-reineke/indent-blankline.nvim#88]
Thank you very much for this excellent plugin. I have configured it to look close to the [indent-rainbow](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow) extension of VSCode.

It would be nice if there was a highlight group for trailing blankline indent, so that it can blend with the background.

![image](https://user-images.githubusercontent.com/20252099/113865869-d064e200-97d6-11eb-8a6d-1a49d3c00f55.png)

**Comment by vufly** [comment]
This is my current config:
```
let g:indent_blankline_char = '▏'
let g:indent_blankline_show_end_of_line = v:true
let g:indent_blankline_use_treesitter = v:true
let g:indent_blankline_filetype_exclude = ['help','dashboard','dashpreview','NvimTree','coc-explorer','startify','vista','sagahover']

highlight IndentBlanklineChar1 guibg=#4E5F00 guifg=#788898 gui=nocombine
highlight IndentBlanklineChar2 guibg=#005A00 guifg=#788898 gui=nocombine
highlight IndentBlanklineChar3 guibg=#53005C guifg=#788898 gui=nocombine
highlight IndentBlanklineChar4 guibg=#004B4F guifg=#788898 gui=nocombine
highlight IndentBlanklineSpaceChar1 guibg=#4E5F00 gui=nocombine
highlight IndentBlanklineSpaceChar2 guibg=#005A00 gui=nocombine
highlight IndentBlanklineSpaceChar3 guibg=#53005C gui=nocombine
highlight IndentBlanklineSpaceChar4 guibg=#004B4F gui=nocombine

let g:indent_blankline_char_highlight_list = ['IndentBlanklineChar1', 'IndentBlanklineChar2', 'IndentBlanklineChar3', 'IndentBlanklineChar4']
let g:indent_blankline_space_char_highlight_list = ['IndentBlanklineSpaceChar1', 'IndentBlanklineSpaceChar2', 'IndentBlanklineSpaceChar3', 'IndentBlanklineSpaceChar4']
```

**Comment by lukas-reineke** [comment]
I see, you want to display the trailing indent line, but don't want the highlighting. I hadn't thought of that.

I'll see if I can add a solution for this.
For now, the best option is to disable the trailing indentation with `let g:indent_blankline_show_trailing_blankline_indent = v:false`

**Comment by vufly** [comment]
Thanks, I think disable the trailing blankline indent make it looks good enough.
