### ISSUE TITLE
Failed config for indent-blankblne

### ISSUE THREAD

**Issue by Barmaley0** [lukas-reineke/indent-blankline.nvim#882]
### Problem

An error occurred after the update. Please tell me what is the problem?

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/133758633/5b774311-edee-4805-bac0-212d9ed0a047)

### Steps to reproduce

nvim 0.9.5
Windows 10
Lazy.lua
The error occurs immediately after opening the file.

### Expected behavior

Indent-blankblne Inactive

### Neovim version (nvim -v)

0.9.5

**Comment by fschlegelone** [comment]
Same for me. Seems that v3.6.0 was a breaking change, so I pinned it to tag v3.5.0 which works for me.

**Comment by Barmaley0** [comment]
I also rolled back. v3.5.0

**Comment by fschlegelone** [comment]
@Barmaley0 got fixed today -> v3.6.1
