### ISSUE TITLE
In nvim 0.10 dev attempt to call method 'flatten' 

### ISSUE THREAD

**Issue by theSafdarAwan** [lukas-reineke/indent-blankline.nvim#888]
### Problem

I was getting same issue with *nvim-lspconfig* but was resolved by changing nvim version caluse but in the indent blank line it doesn't work.

Issue in [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/issues/3172)

```
.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:429: attempt to call method 'flatten' (a nil value)

# stacktrace:
  - /indent-blankline.nvim/lua/ibl/utils.lua:429 _in_ **tbl_join**
  - /indent-blankline.nvim/lua/ibl/config.lua:253 _in_ **merge_configs**
  - /indent-blankline.nvim/lua/ibl/config.lua:276 _in_ **set_config**
  - /indent-blankline.nvim/lua/ibl/init.lua:57 _in_ **setup**
  - ~/.config/nvim/lua/safdar/setup/ui/indent-blankline-nvim/config.lua:15 _in_ **config**
  - ~/.config/nvim/lua/safdar/setup/ui/indent-blankline-nvim/init.lua:9 _in_ **config**

```

### Steps to reproduce

Update to nvim 0.10 dev.

### Expected behavior

..

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1336+g9c2270b83

**Comment by Benjscho** [comment]
Seeing this issue too

**Comment by Benjscho** [comment]
Quick datapoint: I switched back to [Version 3.4.2](https://github.com/lukas-reineke/indent-blankline.nvim/releases/tag/v3.4.2) and didn't see the same issue

**Comment by Benjscho** [comment]
I think this is a related issue and fix in dap: 
- https://github.com/rcarriga/nvim-dap-ui/issues/362
- https://github.com/rcarriga/nvim-dap-ui/commit/334cf3038c4756e6ab999cbac67c847fb654c190

**Comment by lukas-reineke** [comment]
Please make sure you are on the latest version of Neovim nightly, or stable.
Your version is already 8 months old and not supported.
