### ISSUE TITLE
lazy.nvim plugin import

### ISSUE THREAD

**Issue by shawnmuzick** [lukas-reineke/indent-blankline.nvim#889]
### Problem

This lazy.nvim plugin file fails to load properly:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/55474353/28de7661-a407-406c-92a9-e866298cd6e3)

I can't supply the setup() call in that file like I would for most other lazy plugins. I instead have to call it from init.lua. 

The above config file produces this error:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/55474353/c25cbae4-9826-4372-91b8-4209613d5b02)

For comparison of the plugin file format, I've provided my lualine config, which executes the setup() call as expected:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/55474353/4d437033-ce2b-4794-82fb-4e08cb5cc0c5)

### Steps to reproduce

```
return {
	{ "lukas-reineke/indent-blankline.nvim",
		main = "ibl",
		opts = {}
	},
	config = function()
		require('ibl').setup()
	end
}
```

### Expected behavior

the plugin loads without error

### Neovim version (nvim -v)

0.95

**Comment by lukas-reineke** [comment]
You have an extra pair of `{}` in your config that causes the issue.

**Comment by shawnmuzick** [comment]
> You have an extra pair of `{}` in your config that causes the issue.

That did it, Thanks!
