### ISSUE TITLE
[lua-branch] indent_blankline_show_current_context stops when start of context scrolls out of view

### ISSUE THREAD

**Issue by ReubenM** [lukas-reineke/indent-blankline.nvim#89]
I have it configured to use treesitter

When scrolling through python code, and the function is too large to fit within the pane, the context coloring works so long as the beginning of the function is in view. Once the beginning of the context is out of view the context indication no longer works.

Might look at https://github.com/nvim-treesitter/nvim-treesitter-refactor
It has an option "highlight_current_scope" which is a similar context indicator that does not stop when the start of context is out-of-view.

**Comment by lukas-reineke** [comment]
This is for performance reasons, but there is an option to set how far back from the current view the plugin will look.
`g:indent_blankline_viewport_buffer`
The default is 10 lines, you can set it higher. But it might make the plugin slower.

I also just noticed that this option is not in the docs, I'll update that.

**Comment by ReubenM** [comment]
Ah, that works. Thanks.
