### ISSUE TITLE
Adds wrong indentline in nested functions

### ISSUE THREAD

**Issue by MystikReasons** [lukas-reineke/indent-blankline.nvim#891]
### Problem

The bug shows itself in functions that are relatively big (more than 100 lines) and if it has many nestings.
In the middle of scrolling it adds a new indentline which absolutely does not make sense.
I've tested the same file in VSCode and there it is working as expected.

### Steps to reproduce

- Load my test.php file (just some garbage but a long function, 120 lines of code with many nestings).
- Scroll down
- If you scroll past line 88, a new indentline should appear and if you scroll up again, it disappears

Please find attached my test file (I needed to zip it since I can't upload .php files). It just contains a function which is around 120 lines long and has many nestings (5 nestings maximum)
[test.zip](https://github.com/user-attachments/files/15550738/test.zip)

### Expected behavior

This is how it should look like (before line 88):
![grafik](https://github.com/lukas-reineke/indent-blankline.nvim/assets/18333048/e10d950a-5941-4c19-b92c-efc63f508a88)

This is how it looks after line 88:
![grafik](https://github.com/lukas-reineke/indent-blankline.nvim/assets/18333048/b4a5d250-8266-42e9-96c9-d28bafedafa5)

### Neovim version (nvim -v)

0.10.0

Can someone reproduce this issue?

**Comment by lukas-reineke** [comment]
Your `shiftwidth` is not set correctly.
Take a look [here](https://github.com/lukas-reineke/indent-blankline.nvim/discussions/861#discussioncomment-9182871) for a more detailed explanation.

**Comment by MystikReasons** [comment]
Hi @lukas-reineke 
Thank you for the quick reply. I also noticed the same behaviour in Lazyvim (indent-blankline ist the default app). Does that mean it is also configured wrong there?

**Comment by lukas-reineke** [comment]
Yeah, out of the box, you can only set it to one value. There are plugins that set it automatically per buffer, like https://github.com/tpope/vim-sleuth
