### ISSUE TITLE
Only enabled on few filetypes

### ISSUE THREAD

**Issue by eeeXun** [lukas-reineke/indent-blankline.nvim#892]
### Problem

I know there is `ibl.config.exclude.filetypes`. But I want to disable all filetypes and enable on few filetypes like python.

To achieve this, I have to provide a lot of filetypes in `ibl.config.exclude.filetypes`. I don't think this makes sense.

### Expected behavior

Provide the setting `ibl.config.include.filetypes`. When setup this, all filetypes will be disabled. Only the list in this setting will be enabled.

**Comment by lukas-reineke** [comment]
You can use `:help ibl.hooks.cb.active()` for this. Read up on hooks with `:help ibl.hooks`.

**Comment by fionn** [comment]
For future searchers: this is a way to only enable it for a specified filetype.
```lua
local hooks = require("ibl.hooks")
hooks.register(hooks.type.ACTIVE, function(bufnr)
    return vim.opt_local.filetype:get() == "yaml" -- for example
end)
```

A drawback is that this is inflexible, for instance `:IBLEnable` will fail on non-specified filetypes because this hook will return `false`.

**Comment by lukas-reineke** [comment]
If you want the setting less strict and be able to use `IBLEnable` in buffers that are excluded by default, I'd do it differently.

You can setup IBL disabled globally, and then use `:help ibl.setup_buffer()` from `:help ftplugin` to turn it on for specific filestypes.

**Comment by fionn** [comment]
Yep, good point. Can do the same with an autocommand.
```lua
require("ibl").setup {
    enabled = false,
    -- etc.
}

vim.api.nvim_create_autocmd("FileType", {
    desc = "Enable indent guides",
    pattern = "yaml", -- for example
    group = vim.api.nvim_create_augroup("ibl", {clear = true}),
    callback = function()
        require("ibl").setup_buffer(0, {enabled = true})
    end,
})
```

In my case, I want to enable it when the indent width is small, so
```lua
vim.api.nvim_create_autocmd("BufEnter", {
    desc = "Enable indent guides",
    group = vim.api.nvim_create_augroup("ibl", {clear = true}),
    callback = function()
        if vim.lsp.util.get_effective_tabstop(0) < 4 then
            require("ibl").setup_buffer(0, {enabled = true})
        end
    end,
})
```
works well. Personally I'm happy with the inflexible solution, although this might be more performant. (Might move `setup` inside the autocommand too.)
