### ISSUE TITLE
Thick!

### ISSUE THREAD

**Issue by kaykhan** [lukas-reineke/indent-blankline.nvim#895]
I don't have any custom config for ibl so i'm not sure why  my indents really thick -  I am assuming it might be from some other plugin. 

Do you know what i need to do to change the thickness and/or (highlight) color?

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/5202527/2d792b35-c439-4f7e-b869-9582b6522c83)

**Comment by lukas-reineke** [comment]
This is the default thickness, it just stands out a lot because it's white.
You can change the character with `:help ibl.config.indent.char` and the color with `:help ibl.config.indent.highlight`
