### ISSUE TITLE
attemp to call method 'flatten' (a nil value)

### ISSUE THREAD

**Issue by 4t8dd** [lukas-reineke/indent-blankline.nvim#896]
### Problem

![Screenshot 2024-06-20 at 10 11 55 AM](https://github.com/lukas-reineke/indent-blankline.nvim/assets/66897975/27e092cb-23ad-4227-a13f-28be2804b1fe)

### Steps to reproduce

I use latest nvim and lazyvim.

### Expected behavior

everything works well.

### Neovim version (nvim -v)

0.10

**Comment by lukas-reineke** [comment]
> I use latest nvim

I don't think you are. `flatten` is available in both stable 0.10 and nightly.
Please make sure your Neovim version is actually up to date.

**Comment by 4t8dd** [comment]
Oh, I think so. just confirm:

```NVIM v0.10.0-dev-1025+g0e11bf0e1```

No wonder I got many issues these days. I will have the stable version.
