### ISSUE TITLE
Indent lines missing partially on first level

### ISSUE THREAD

**Issue by Racle** [lukas-reineke/indent-blankline.nvim#90]
~~Arrows shows extra lines (screenshot with gruvbox, same issue with minimal config).~~
~~Those lines are unnecessary there.~~ 

Fixed by adding `vim.g.indent_blankline_show_trailing_blankline_indent = false`

Missing `|` before last `}`. 

![image](https://user-images.githubusercontent.com/759091/114388582-8bf19180-9b9c-11eb-967f-063f79720cfb.png)

## How to reproduce:

Neovim: NVIM v0.5.0-dev (latest from ubuntu unstable ppa)

minimal vimrc: (requires vim-plug to be installed)

```vim
call plug#begin(stdpath('data') . '/plugged')
  Plug 'lukas-reineke/indent-blankline.nvim', { 'branch': 'lua' }
call plug#end()

set tabstop=2

lua << EOF
  vim.g.indentLine_enabled = 1
EOF
```

Open JS file containing this
```js
function test() {


  if (true) {

    return true
  }


}
```

**Comment by vufly** [comment]
You can turn if off with `let g:indent_blankline_show_trailing_blankline_indent = v:false`

**Comment by Racle** [comment]
> You can turn if off with `let g:indent_blankline_show_trailing_blankline_indent = v:false`

Works perfectly for extra lines, so only issue is still missing indent lines between last and second last `}`

**Comment by lukas-reineke** [comment]
The default "algorithm" to figure out the indentation for blank lines is to take the indentation of the next non-blank line.
This works in 95% of the cases and is very fast.

But it doesn't look as good in some cases, like you have here.
To make it look better, the indentation needs to be language aware. It needs to know that that line is still inside the function body.
To do that, there is support to change the logic on how to calculate the indentation of blank lines to use treesitter.
You can set `let g:indent_blankline_use_treesitter=v:true` and it should fix your issue.

But this comes with a slight cost in performance.

**Comment by Racle** [comment]
@lukas-reineke Thanks, that works. I'll close this Issue.
And because that treesitter workaround, I don't think it's necessarily to make default algorithm any better, because that is fast in 95% of cases and it might affect it performance. And I've encountered my case very rarely.

And for documentation purposes (if someone else has same problem): 

1. I did install [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) 
    - This helps installing parsers automatically. I think you can do this also manually with latest neovim nightly.
1. Add this to my config (with that ` vim.g.indent_blankline_use_treesitter = true`). Highlight is extra, but I added that to my config.
```lua
require("nvim-treesitter.configs").setup {
    ensure_installed = {
        "bash",
        "css",
        "go",
        "html",
        "javascript",
        "json",
        "lua",
        "php"
    },
    highlight = { 
        enable = true,
        use_languagetree = true
    }
}

```
