### ISSUE TITLE
Support for drawing over folded lines using `foldtext=''`

### ISSUE THREAD

**Issue by akinsho** [lukas-reineke/indent-blankline.nvim#901]
### Problem

In nvim 0.10 (as you probably know) users are now able to set `foldtext=''` this has the benefits of drawing a fold pretty much like all other editors i.e. full highlighting, as well as extmarks etc. I've noticed using this new mode though that indent line no longer draws it's indicator over the folds probably as it's a different implementation. I wanted to ask if it was possible to tweak it's implementation to accommodate this or if it's too different to support

<img width="394" alt="Screenshot 2024-06-25 at 11 57 21" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/22454918/40dd9270-bd9f-48e9-bfe6-3979cbcbe0dd">

### Expected behavior

I'd hope that it could just draw the indentline over the space like it used to when the draw over foldtext option existed

**Comment by lukas-reineke** [comment]
Released a new version that should support this now.

**Comment by akinsho** [comment]
Awesome thanks 🙏🏾
