### ISSUE TITLE
Strange background

### ISSUE THREAD

**Issue by ray-x** [lukas-reineke/indent-blankline.nvim#91]
Hi, I would like to try this plugin.
<img width="224" alt="Screen Shot 2021-04-15 at 7 51 14 am" src="https://user-images.githubusercontent.com/1681295/114785461-149c4780-9dc0-11eb-8acb-00a903f74b0a.png">
But after install with the default setup, I only got strange indent char in every empty line. Are there any conflicts with nvim setup?
It seems to relate to https://github.com/lukas-reineke/indent-blankline.nvim/issues/59, but colorcolumn=99999 does not fix

**Comment by lukas-reineke** [comment]
Are you using the master branch?
If you are on Neovim 0.5, you should use the lua branch.

**Comment by ray-x** [comment]
Thanks. I did not read Readme.md careful enough. Great plugin!
