### ISSUE TITLE
Indent lines highlight over insert cursor when using iTerm2

### ISSUE THREAD

**Issue by j-krl** [lukas-reineke/indent-blankline.nvim#913]
### Problem

I'm not even sure if this is an indent lines or an iTerm2 bug, but thought I'd ask here anyway. I get some weird behaviour with the insert cursor.

If I use the default indent line character, when I go into insert mode my cursor disappears. It's like the indent line has higher priority than the cursor itself. In the screenshots below the cursor is over the exact same character.
<img width="194" alt="Screenshot 2024-08-03 at 3 08 28 AM" src="https://github.com/user-attachments/assets/f5b3b5a5-30ed-4ed8-a385-c7c376747e98">
<img width="220" alt="Screenshot 2024-08-03 at 3 08 38 AM" src="https://github.com/user-attachments/assets/1316ebd0-01d9-41d3-bf7d-f4e74caf2af8">

When I set indent lines to a custom character I can at least see the cursor, but you can see the indent line is displaying over top of insert cursor, but not the block cursor.
<img width="397" alt="Screenshot 2024-08-03 at 5 58 21 PM" src="https://github.com/user-attachments/assets/076cc8d8-a497-4770-9089-4d814cfbb8ac">
<img width="386" alt="Screenshot 2024-08-03 at 5 58 35 PM" src="https://github.com/user-attachments/assets/1bacd6f6-4d80-4dea-9b04-c900cc2da4e9">

I've tried messing with the priority setting to no avail. Any ideas?

### Steps to reproduce

Use the plugin in iTerm2 on macOS 14.5

### Expected behavior

I expect the cursor to have higher priority than the indent line

### Neovim version (nvim -v)

0.10.1

**Comment by lukas-reineke** [comment]
This is not a bug in IBL.
IBL has no control over the cursor at all. This is Neovim core, or your terminal emulator.
