### ISSUE TITLE
How to make indent-blankline.nvim overrule headlines.lua

### ISSUE THREAD

**Issue by snoblenet** [lukas-reineke/indent-blankline.nvim#917]
My `indent-blankline.nvim` config:

```lua
return {
  'lukas-reineke/indent-blankline.nvim',
  config = function()
    local highlight = {
      'IndentOrange',
      'IndentTeal',
      'IndentOrange',
      'IndentTeal',
      'IndentOrange',
      'IndentTeal',
      'IndentOrange',
      'IndentTeal',
    }

    local hooks = require('ibl.hooks')

    hooks.register(hooks.type.HIGHLIGHT_SETUP, function()
      vim.api.nvim_set_hl(0, 'IndentOrange', { fg = '#D08770' })
      vim.api.nvim_set_hl(0, 'IndentTeal', { fg = '#8FBCBB' })
    end)

    require('ibl').setup({
      indent = {
        char = "▏",
        highlight = highlight,
      }
    })
  end,
}
```

My `headlines.lua` config:

```lua
return {
  "lukas-reineke/headlines.nvim",
  dependencies = "nvim-treesitter/nvim-treesitter",
  config = function()
    require("headlines").setup({
      org = {
        bullets = { "🔅" },
        dash_string = "󰐰",
        fat_headlines = false,
      },
    })
  end,
}

```

Both work, but when both try to change the appearance of the same cell, `headlines.lua` wins.

How do I make `indent-blankline.nvim` win, so I get an indentation guide at the start of line 20? 

(And at the start of line 19 for that matter.)

![image](https://github.com/user-attachments/assets/ba2d1fd3-32dc-41b9-907b-f07c52889584)

**Comment by lukas-reineke** [comment]
This is not supported. Making IBL take priority would also cut off the background highlight, which would look bad.  
It would theoretically be possible to write some integration between the two to combine the highlight of that one cell, but that would be a lot of work for such a small thing.
