### ISSUE TITLE
No context indent highlight when cursor is on a comment.

### ISSUE THREAD

**Issue by hiddenruins** [lukas-reineke/indent-blankline.nvim#92]
Hi there, there is no indent highlight when the cursor in on a comment.

https://user-images.githubusercontent.com/5569621/114969920-16860980-9e99-11eb-953e-1edff339f0c5.mp4

Settings
```lua
vim.g.indent_blankline_char = '┊'
vim.g.indent_blankline_use_treesitter = true
vim.g.indent_blankline_show_current_context = true
vim.g.indent_blankline_context_patterns = {'class', 'function', 'method', '^if', '^while', '^for', '^object', '^table', 'block', 'arguments'}
vim.g.indent_blankline_filetype_exclude = {'help', 'packer'}
```

**Comment by lukas-reineke** [comment]
Looks like an issue in treesitter. It can't handle `get_node_at_cursor` on comments in bash.

![Screen Capture_select-area_20210416144304](https://user-images.githubusercontent.com/12900252/114977129-282fd700-9ec2-11eb-8346-1e450cf2e132.png)

Not something I can fix, you can open an issue in the treesitter repo

**Comment by denstiny** [comment]
![图片](https://user-images.githubusercontent.com/57088952/228711957-5cf3ffb7-bf1e-4e9e-ac9f-05bf85b5f6d5.png)
In the CPP file already ok
