### ISSUE TITLE
Scope highlight doesn't unset when folding the current scope

### ISSUE THREAD

**Issue by exzolink** [lukas-reineke/indent-blankline.nvim#921]
### Problem

I set a background for scope.underline.#, and it doesn't reset when folding the scope, even if I move the cursor to a different scope

![Screenshot_1](https://github.com/user-attachments/assets/d829b23c-ccdc-4ec5-89d0-ccedddefb038)
![Screenshot_2](https://github.com/user-attachments/assets/b527a736-1cda-4a23-a279-8cd82cbee630)

### Steps to reproduce

-

### Expected behavior

Reset current scope highlight and show only fold bg color

### Neovim version (nvim -v)

NVIM 0.11.0

**Comment by lukas-reineke** [comment]
Directly modifying `@ibl` highlight groups is not supported. It will lead to bugs like this.

**Comment by exzolink** [comment]
What you suggest?

**Comment by exzolink** [comment]
> Directly modifying `@ibl` highlight groups is not supported. It will lead to bugs like this.

No overriding
![Screenshot_1](https://github.com/user-attachments/assets/940a86fc-7447-4991-97f1-907315027790)
