### ISSUE TITLE
Use `CursorLine` instead of `NonText` when line is selected

### ISSUE THREAD

**Issue by tkr-sh** [lukas-reineke/indent-blankline.nvim#922]
### Problem

Spaces before text are their style bg being `NonText`.
Which is fine, but not when there is `vim.opt.cursorline = true`.
Because that means that this will be colored, above the `CursorLine`, and will give results like:

![image](https://github.com/user-attachments/assets/b7064132-e41e-4eb6-a9e2-8a7575ecfe89)
(or with a theme more coherent)
![image](https://github.com/user-attachments/assets/a251f95c-63e0-44eb-a223-e03fc2fe18c1)

which shouldn't be the case.

### Steps to reproduce

Install `indent-blankline` and set `hi` for CursorLine and NonText.

### Expected behavior

Have the spaces being colored with CursorLine when they are on the current line and that there is `vim.opt.cursorline = true
`

### Neovim version (nvim -v)

v0.10.1

**Comment by lukas-reineke** [comment]
IBL does not use `NonText`, the highlight defaults to `Whitespace`. See `:help ibl.highlights`
If you don't want a background color, don't set a background color for `Whitespace`, or change the highlight groups `:help ibl.config.indent.highlight` and `:help ibl.config.whitespace.highlight` to a highlight groups without background color.
