### ISSUE TITLE
Makes my neovim unusable and bricks the installation after adding it to 0.10.1 neovim

### ISSUE THREAD

**Issue by parz3val** [lukas-reineke/indent-blankline.nvim#924]
### Problem

Hello,

Recently tried to switch to blankline from other plugin I was using because it looked cool. That was my biggest mistake. I copied the config from the READE and now my neovim installation is broken. I am using lazy as plugin manager.

I am getting this error on every key-press in neovim after I open neovim.

```bash
Error detected while processing :source (no file):
E5108: Error executing lua ...e/nvim/lazy/indent-blankline.nvim/lua
/ibl/highlights.lua:65: No highlight group 'CursorColumn' found
stack traceback:
        [C]: in function 'error'
        ...e/nvim/lazy/indent-blankline.nvim/lua/ibl/highlights.lua
:65: in function 'setup'
        ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua
:41: in function 'setup'
        ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua
:57: in function 'setup'
        [string ":source (no file)"]:4: in main chunk
        
        Error detected while processing CursorMoved Autocommands for "*":
Error executing lua callback: ...re/nvim/lazy/indent-blankline.nvim
/lua/ibl/virt_text.lua:95: attempt to index a nil value
stack traceback:
        ...re/nvim/lazy/indent-blankline.nvim/lua/ibl/virt_text.lua
:95: in function 'get'
        ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua
:426: in function 'refresh'
        ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua
:127: in function 'debounced_refresh'
        ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua
:143: in function 'debounced_refresh'
        ...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua
:27: in function <...are/nvim/lazy/indent-blankline.nvim/lua/ibl/au
tocmds.lua:26>

```

This is the config I am using
```lua
local highlight = {
     "CursorColumn",
    "Whitespace",

}
require("ibl").setup {
    indent = { highlight = highlight, char = "" },
    whitespace = {
        highlight = highlight,
        remove_blankline_trail = false,
    },
    scope = { enabled = false },
}

```
I do get indent lines on the code but I can't use neovim. I get the mentioned error on either keypress on every few milliseconds. Neovim becomes unusable until I remove the loading of the plugin from my init.lua.  Maybe docs needs updating or something? 
Tested on: Arch Linux, Lenovo Legion 5 pro, neovim 0.10.1 
latest commit hash for the plugin lock for lazy: 18603eb949eba08300799f64027af11ef922283f 

Can you point me the right direction so I can fix the issue?

### Steps to reproduce

local lazypath = "/tmp/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system { "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath }
end
vim.opt.rtp:prepend(lazypath)
vim.opt.termguicolors = true

require("lazy").setup ({
    {
        "lukas-reineke/indent-blankline.nvim",
        config = function()
            require("ibl").setup {}
        end,
    },
    -- uncomment this if the problem is related to scope
    -- {
    --     "nvim-treesitter/nvim-treesitter",
    --     build = ":TSUpdate",
    --     config = function()
    --         require("nvim-treesitter.configs").setup {
    --             ensure_installed = { "rust" }, -- change this to the language you use
    --         }
    --     end,
    -- },
}, { root = "/tmp/lazy" })
local highlight = {
     "CursorColumn",
    "Whitespace",

}
require("ibl").setup {
    indent = { highlight = highlight, char = "" },
    whitespace = {
        highlight = highlight,
        remove_blankline_trail = false,
    },
    scope = { enabled = false },
}

### Expected behavior

The plugin should work and not throw any erorrs.

### Neovim version (nvim -v)

0.10.1

**Comment by parz3val** [comment]
I was able to fix the issue by using 

``` highlight = "IblIndent" ``` instead of those two values 

Can I get more info on why this worked and other one didn't? 
I want to make the rainbow braces work with this.

**Comment by lukas-reineke** [comment]
`CursorColumn` is a built in highlight group, see `:help hl-CursorColumn`. If it doesn't exist, it means something in your config is broken. Maybe you are using a colorscheme that is not working correctly.

This is not a bug of indent-blankline
