### ISSUE TITLE
How not to highlight empty lines?

### ISSUE THREAD

**Issue by metra118** [lukas-reineke/indent-blankline.nvim#925]
hi!
thanks a lot for this plugin!

could you pls help me with config?
how do I get behaviors from version 2 to version 3?
![image](https://github.com/user-attachments/assets/19900a15-c337-46c6-9054-5d4a717f72e7)

[rep](https://github.com/metra118/ibl-question) with configs

**Comment by lukas-reineke** [comment]
You can use `:help ibl.hooks.cb.skip_line()`

```lua
local hooks = require "ibl.hooks"
hooks.register(hooks.type.SKIP_LINE, function(_, _, _, line)
    return #line == 0
end)
```
