### ISSUE TITLE
Haskell (or "new" language) support for scope + surprising scope behavior

### ISSUE THREAD

**Issue by guibou** [lukas-reineke/indent-blankline.nvim#926]
### Problem

I've tried to add `node_type` for `haskell` without any result, until I manually edited `lua/ibl/scope_languages.lua` to add an empty reference for `haskell`.

Once it was done, I was able to have scope logic for a few node, but the support is partially bugged, some nodes do not works at all, some are partially displayed, more details in "Step to reproduce". I don't know if that's something `indent-blankline` can fix or if this is related to the treesitter support for haskell.
Nothing changed in the file

### Steps to reproduce

Let's assume the following haskell file:

```haskell
main = do
  print "hello"

  let
    x = 10
    y = 20

  res <- do
    print "hi"
    print "ho"
    pure 10
  
  pure ()

  where
    a = 1
    b = 2

blurk = do
  print "yoto"
```

Here is what I add to my `setup()`:

```
      include = {
          node_type = { haskell = { "do" } },
      },
```

The `do` node is located where `res <- do` is.

Without any other action, there is no change of highlight in my editor (note that scope works fine for rust, python, ...).

The following makes it work:

```
diff --git a/lua/ibl/scope_languages.lua b/lua/ibl/scope_languages.lua
index 496fcb3..c577666 100644
--- a/lua/ibl/scope_languages.lua
+++ b/lua/ibl/scope_languages.lua
@@ -1,6 +1,8 @@
 -- from nvim-treesitter/queries/{lang}/locals
 
 local M = {
+    haskell = {
+    },
     ada = {
         compilation = true,
         package_declaration = true,
```

So first, I suspect that the `include.node_type` configuration option only works for languages which are already listed in `scope_languages.lua`.

Now it works fine for `do` blocks:

![image](https://github.com/user-attachments/assets/8aa17d80-6b6d-4394-b657-b2cbedaa11e4)

And for the "top level":

![image](https://github.com/user-attachments/assets/a14e2bbf-7784-4363-9140-2c500a72ba1f)

I also wanted to scope the `where` and `let` clauses. I thought that `local_binds` node would be perfect for that:

![image](https://github.com/user-attachments/assets/563dc52b-bdf0-47ca-b042-7d2b64cd8877)

However, the result is not as expected (after adding `local_binds` in my `node_type` list):

On the first line of the `where` close, it matchs nothing:

![image](https://github.com/user-attachments/assets/2989d657-40a5-4e78-a945-613abd32aaaa)

On the second line, it actually see something (see the "start" line displayed), but it does not highlight the indentation guide.

![image](https://github.com/user-attachments/assets/90d2f9ee-6fe5-4fe4-9e21-8d068c127311)

In the `let` block, it is similar, with the difference that the first line matchs the parent `do` block:

![image](https://github.com/user-attachments/assets/2644e2de-907d-4a69-a419-c0912173fdde)

And the second line actually "start" on the first line, but do not highlight the indentation:

![image](https://github.com/user-attachments/assets/b965f898-bf10-4465-8470-dbb9e6d0adc9)

This maybe linked to the fact that the `local_binds` blocks starts after the indentation in the treesitter grammar, so maybe this could be upstreamed to the haskell treesitter project.

For reference, here is the grammar of this file:

```lisp
(haskell ; [0, 0] - [20, 0]
  declarations: (declarations ; [0, 0] - [20, 0]
    (bind ; [0, 0] - [16, 9]
      name: (variable) ; [0, 0] - [0, 4]
      match: (match ; [0, 5] - [12, 9]
        expression: (do ; [0, 7] - [12, 9]
          statement: (exp ; [1, 2] - [1, 15]
            (apply ; [1, 2] - [1, 15]
              function: (variable) ; [1, 2] - [1, 7]
              argument: (literal ; [1, 8] - [1, 15]
                (string)))) ; [1, 8] - [1, 15]
          statement: (let ; [3, 2] - [5, 10]
            binds: (local_binds ; [4, 4] - [5, 10]
              decl: (bind ; [4, 4] - [4, 10]
                name: (variable) ; [4, 4] - [4, 5]
                match: (match ; [4, 6] - [4, 10]
                  expression: (literal ; [4, 8] - [4, 10]
                    (integer)))) ; [4, 8] - [4, 10]
              decl: (bind ; [5, 4] - [5, 10]
                name: (variable) ; [5, 4] - [5, 5]
                match: (match ; [5, 6] - [5, 10]
                  expression: (literal ; [5, 8] - [5, 10]
                    (integer)))))) ; [5, 8] - [5, 10]
          statement: (bind ; [7, 2] - [10, 11]
            pattern: (variable) ; [7, 2] - [7, 5]
            expression: (do ; [7, 9] - [10, 11]
              statement: (exp ; [8, 4] - [8, 14]
                (apply ; [8, 4] - [8, 14]
                  function: (variable) ; [8, 4] - [8, 9]
                  argument: (literal ; [8, 10] - [8, 14]
                    (string)))) ; [8, 10] - [8, 14]
              statement: (exp ; [9, 4] - [9, 14]
                (apply ; [9, 4] - [9, 14]
                  function: (variable) ; [9, 4] - [9, 9]
                  argument: (literal ; [9, 10] - [9, 14]
                    (string)))) ; [9, 10] - [9, 14]
              statement: (exp ; [10, 4] - [10, 11]
                (apply ; [10, 4] - [10, 11]
                  function: (variable) ; [10, 4] - [10, 8]
                  argument: (literal ; [10, 9] - [10, 11]
                    (integer)))))) ; [10, 9] - [10, 11]
          statement: (exp ; [12, 2] - [12, 9]
            (apply ; [12, 2] - [12, 9]
              function: (variable) ; [12, 2] - [12, 6]
              argument: (unit))))) ; [12, 7] - [12, 9]
      binds: (local_binds ; [15, 4] - [16, 9]
        decl: (bind ; [15, 4] - [15, 9]
          name: (variable) ; [15, 4] - [15, 5]
          match: (match ; [15, 6] - [15, 9]
            expression: (literal ; [15, 8] - [15, 9]
              (integer)))) ; [15, 8] - [15, 9]
        decl: (bind ; [16, 4] - [16, 9]
          name: (variable) ; [16, 4] - [16, 5]
          match: (match ; [16, 6] - [16, 9]
            expression: (literal ; [16, 8] - [16, 9]
              (integer)))))) ; [16, 8] - [16, 9]
    (bind ; [18, 0] - [19, 14]
      name: (variable) ; [18, 0] - [18, 5]
      match: (match ; [18, 6] - [19, 14]
        expression: (do ; [18, 8] - [19, 14]
          statement: (exp ; [19, 2] - [19, 14]
            (apply ; [19, 2] - [19, 14]
              function: (variable) ; [19, 2] - [19, 7]
              argument: (literal ; [19, 8] - [19, 14]
                (string))))))))) ; [19, 8] - [19, 14
```

### Expected behavior

- "simple" and relevant to this project: `include.node_type` should work without having to manually add new languages in `lua/ibl/scope_languages.lua`.
-  "complex" and maybe not relevant to this project: I don't really know of to formulate it, but it seems that nodes which are not including the first indentation could not correctly highlight their indentation guide.

For the second point, I've ran a small experience:

![image](https://github.com/user-attachments/assets/2888a7ab-3232-4547-b1b0-468202223216)

Here I've indented `b` and `c` (this is not valid haskell anymore) and when on `b` and `c`, it matchs on the `local_binds` node and correctly highlight the "now visible" indentation column.

### Neovim version (nvim -v)

NVIM v0.11.0-nightly+e0efbc6

**Comment by lukas-reineke** [comment]
I released a new version that fixes the first issue.

But like you suspect, the other one is a problem with the haskell treesitter grammar. There is nothing I can do here to fix it.

**Comment by guibou** [comment]
@lukas-reineke thank you. I've created https://github.com/lukas-reineke/indent-blankline.nvim/pull/928 in order to fix a small remaining error, with that MR it works as expected.

Thank you.

I will continue on the treesitter parser for haskell in order to have a nicer support for scope.
