### ISSUE TITLE
How to set up background highlighting?

### ISSUE THREAD

**Issue by weeman1337** [lukas-reineke/indent-blankline.nvim#94]
How can I set up the background highlighting like in this screenshot?:  
https://github.com/lukas-reineke/indent-blankline.nvim/tree/lua#with-custom-background-highlight

(I would then contribute and add something about that to the README or doc.)

**Comment by lukas-reineke** [comment]
Set `g:indent_blankline_char_highlight_list` and `g:indent_blankline_space_char_highlight_list` to highlights with a background color.

And you should also turn off `g:indent_blankline_show_trailing_blankline_indent`

**Comment by weeman1337** [comment]
Thanks for the hint @lukas-reineke .

To have the indent char disappear I have to set `vim.g.indent_blankline_char = ""`.

Unfortunately the indent backgrounds disappear if I enable my coloescheme (vim-one). Do you have any idea how I can get it working together?

**Comment by lukas-reineke** [comment]
> To have the indent char disappear I have to set vim.g.indent_blankline_char = "".

you have to set it to `" "`, it needs to have a width

**Comment by weeman1337** [comment]
> you have to set it to " ", it needs to have a width

Okay  - got that ✓

Still the backgrounds don't appear if I enabled [the colorscheme](https://github.com/rakr/vim-one).

**Comment by lukas-reineke** [comment]
What highlight groups do you use?
And if you define them yourself, when do you do it?

Most color schemes clear all existing highlight groups, so you have to define them after you set color

**Comment by Mte90** [comment]
thanks this works :-D

**Comment by lukas-reineke** [comment]
@franklouwers please open a new issue next time.
Most colorshemes clear all the highlighting, so your only option is to run your command after the colorscheme.
You can use an autocommand if just putting it at the end of your init.vim does not work

```
autocmd ColorScheme * highlight IndentOdd guifg=NONE guibg=NONE gui=nocombine
autocmd ColorScheme * highlight IndentEven guifg=NONE guibg=#0000ff gui=nocombine
```

**Comment by franklouwers** [comment]
Yeah that's what I did, but I was wondering if there was a way without using `autocmd`, anyway, works now :)

**Comment by fuelen** [comment]
I've tried the snippet above. Is this expected behaviour?
![image](https://user-images.githubusercontent.com/588762/124379723-581c9880-dcc1-11eb-9232-ff0d89e40930.png)
these lines do not contain any symbol

**Comment by lukas-reineke** [comment]
@fuelen please open a new issue
