### ISSUE TITLE
When using the plugin, deleting a whole line sometimes causes Neovim to crash

### ISSUE THREAD

**Issue by harrydayexe** [lukas-reineke/indent-blankline.nvim#944]
### Problem

When this plugin is in use, occasionally, deleting a line of text (say using dd) will cause the entire editor to crash. This does not always occur on every line, but from my testing it seems to occur at least 80% of the time. On some lines it is every time, other lines it will never occur. I assume this is due to the tree sitter. Try enough lines or select all lines and this will normally cause a crash

### Steps to reproduce

local lazypath = "/tmp/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system { "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath }
end
vim.opt.rtp:prepend(lazypath)
vim.opt.termguicolors = true

require("lazy").setup({
    {
        "lukas-reineke/indent-blankline.nvim",
        config = function()
            require("ibl").setup {}
        end,
    },
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        config = function()
            require("nvim-treesitter.configs").setup {
                ensure_installed = { "go" }, -- change this to the language you use
            }
        end,
    },
}, { root = "/tmp/lazy" })

### Expected behavior

The editor should not crash

### Neovim version (nvim -v)

v0.10.2

**Comment by jordangarcia** [comment]
The same thing is happening to me, particularly the combination of treesitter + indent-blankline.

**Comment by harrydayexe** [comment]
Yep, seems to be something wrong with the tree sitter + indent-blankline plugin. Interestingly I did not notice this previous to today, however I upgraded laptops from an older Intel based MacBook Pro to the new M4 MacBook Pro. Not sure if this is the root of the issue but may be something to keep in mind. @jordangarcia what OS/hardware are you running on?

**Comment by lukas-reineke** [comment]
Can you provide a backtrace for the crash?
`:help dev-tools-backtrace`

**Comment by harrydayexe** [comment]
Do I run that command before or after triggering the crash with the behavior? Because if its after no can do, the entire program freezes and I have to manually close my terminal to recover

**Comment by jordangarcia** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/5501

There is an issue in the `tree-sitter` package in homebrew.  This was causing issues when trying to figure out the current scope, which is why this plugin and `mini.indentscope` have been crashing.

**Comment by lukas-reineke** [comment]
Right, it doesn't crash, it just freezes.

Can you make sure you are on the latest version of the plugin? This sounds a lot like #930, which should be fixed already.

**Comment by carlocab** [comment]
If you're using Homebrew, you'll need to do `brew update && brew reinstall tree-sitter` to pick up the backported fix for https://github.com/tree-sitter/tree-sitter/issues/3930.

**Comment by jordangarcia** [comment]
Yep this is resolved for me by installing the newest tree-sitter.  Thanks @lukas-reineke

**Comment by harrydayexe** [comment]
Yep you're right, my bad for not seeing the fixed issue
