### ISSUE TITLE
Using this plugin breaks `set list`

### ISSUE THREAD

**Issue by WhyNotHugo** [lukas-reineke/indent-blankline.nvim#95]
`set list` is broken when using this plugin, but works without it.

I'm using the `lua` branch, and using the following works as expected without the plugin, but has no effect if the plugin is installed (e.g.: these characters are not rendered):

```vim
set listchars=tab:>-,trail:·,extends:>,precedes:<
set list
```

**Comment by WhyNotHugo** [comment]
Oh, I updated to the latest `lua` version. In this case, only _leading_ spaces are hidden. I tried using `indent_blankline_space_char`, but is messes up tabs (shows them as spaces).

The `master` version seems to work fine though.

**Comment by lukas-reineke** [comment]
There is already an issue for this #74
I will add options for this, just didn't have time to implement it yet.

**Comment by WhyNotHugo** [comment]
Ah, didn't notice that one, thanks.
