### ISSUE TITLE
Support for Horizontal Indent Lines to Create Tree-Like Structure

### ISSUE THREAD

**Issue by themuuln** [lukas-reineke/indent-blankline.nvim#956]
### Problem

Currently, indent-blankline.nvim supports vertical indent lines, but it lacks the ability to render horizontal lines, which would make code with nested structures easier to visualize. For example, in Flutter projects with deeply nested Widgets, the tree-like structure of the code could be better represented with a combination of horizontal and vertical lines.

### Expected behavior

Introduce the ability to add horizontal lines (─) in combination with vertical lines (│, ├, └) to create a tree-like visual representation of nested code. This feature should:
	1.	Integrate seamlessly with existing Treesitter-based context detection.
	2.	Dynamically render horizontal lines where needed (e.g., between sibling blocks or branching points in code).
	3.	Support customization of characters used for horizontal and vertical lines.
	4.	Enhance the readability of deeply nested code structures in languages like Dart (used in Flutter), JSON, and YAML.

This feature would significantly improve the plugin’s utility for developers working with complex nested code, making it easier to understand the hierarchy at a glance.

Is it worth the cost? Yes, as this feature would extend the usability of the plugin for a broader range of users and use cases, particularly in frameworks like Flutter or configurations using YAML/JSON files.

**Comment by lukas-reineke** [comment]
Sorry, this is out of scope for this plugin.
