### ISSUE TITLE
How to do dynamic custom background highlighting

### ISSUE THREAD

**Issue by oscarmorrison** [lukas-reineke/indent-blankline.nvim#959]
@lukas-reineke would love to be able to add this to the wiki? or maybe add an examples section to the repo.
Spent a long time working this out:

# Dynamic Background Stripes with `indent-blankline.nvim`

This guide explains how to set up alternating background stripes for indentation levels in Neovim using `indent-blankline.nvim`. The configuration dynamically adapts the background colors based on the active colorscheme, ensuring seamless integration with both dark and light themes.

---

## Features
- **Dynamic Highlight Groups**: Automatically adjusts colors for both dark and light themes.
- **Alternating Background Stripes**: Provides subtle visual cues for nested indentation levels using background colors.
- **No Characters**: Relies on background highlights instead of displaying visible characters, maintaining a clean and minimal aesthetic.
- **Dynamic Colorscheme Support**: Automatically updates the colors when switching between themes.

---

### Lua Code
(lazyvim in a /plugins/indent-blank.lua
```lua
return {
  {
    "lukas-reineke/indent-blankline.nvim",
    main = "ibl",
    event = { "BufReadPre", "BufNewFile" },
    config = function()
      -- Function to dynamically calculate colors based on the background
      local function setup_highlight_groups()
        local background = vim.o.background -- 'dark' or 'light'
        if background == "dark" then
          -- Dark theme colors
          vim.api.nvim_set_hl(0, "IndentStripe1", { bg = "#1B2B34" }) -- Original dark background
          vim.api.nvim_set_hl(0, "IndentStripe2", { bg = "#232E38" }) -- Slightly lighter
        else
          -- Light theme colors
          vim.api.nvim_set_hl(0, "IndentStripe1", { bg = "#FDF6E3" }) -- Light theme background
          vim.api.nvim_set_hl(0, "IndentStripe2", { bg = "#F6EFD9" }) -- Slightly darker
        end
      end

      -- Set up highlight groups for the current colorscheme
      setup_highlight_groups()

      -- Autocmd to update highlight groups when the colorscheme changes
      vim.api.nvim_create_autocmd("ColorScheme", {
        callback = setup_highlight_groups,
      })

      -- Configure indent-blankline.nvim
      require("ibl").setup({
        indent = {
          highlight = { "IndentStripe1", "IndentStripe2" }, -- Alternating subtle backgrounds
          char = "", -- No character, only background
        },
        whitespace = {
          highlight = { "IndentStripe1", "IndentStripe2" },
          remove_blankline_trail = false,
        },
        scope = { enabled = false },
      })
    end,
  },
}
```

### Dynamic Background Colors
The configuration dynamically detects the current theme using `vim.o.background`:
- **Dark Themes**:
  - `IndentStripe1`: `#1B2B34` (dark base color)
  - `IndentStripe2`: `#232E38` (slightly lighter)
- **Light Themes**:
  - `IndentStripe1`: `#FDF6E3` (light base color)
  - `IndentStripe2`: `#F6EFD9` (slightly darker)

![image](https://github.com/user-attachments/assets/3e300e79-574d-400e-8691-c37533d3752c)

![image](https://github.com/user-attachments/assets/a3d04f99-aaf1-416a-af39-1c8fa0f5dde5)

**Comment by lukas-reineke** [comment]
Thanks, but setting highlight groups based on the background setting is not specific to indent-blankline.  
And your indent-blankline configuration [is already covered in the readme](https://github.com/lukas-reineke/indent-blankline.nvim?tab=readme-ov-file#background-color-indentation-guides).

So I don't think there is anything to add to the documentation in this repo.
