### ISSUE TITLE
Buffer-local settings

### ISSUE THREAD

**Issue by Shatur** [lukas-reineke/indent-blankline.nvim#96]
Hi! Thank you a lot for the awesome plugin. I use your lua branch.

**Introduction**

I would like to suggest adding the ability to specify local buffer settings. For example, I have NvimTree rendered like this:
![изображение](https://user-images.githubusercontent.com/22453358/115468101-3de32a80-a23b-11eb-92e7-7268a97608da.png)
But I would like to set `vim.g.indent_blankline_space_char = ' '` for this buffer to make it look like this:
![изображение](https://user-images.githubusercontent.com/22453358/115468176-5d7a5300-a23b-11eb-9b2a-de9cbe5e958c.png)

**Implementation details**

Vim have a built-in functionality to specify filetype-specific options - just need to create a file with filetype name file inside `after/ftplugin` with buffer-local variables. Example of such file:

```vim
setlocal formatoptions-=cro
setlocal nowrap
let b:my_awesome_var = 2
```

So could you just check for a buffer-local variable first (prefixed with b, example: `b:indent_blankline_filetype`)?
In theory, this would also allow to get rid of `g:indent_blankline_filetype` / `g:indent_blankline_buftype_exclude`, because this configuration can be done in the "native" way.

**Comment by lukas-reineke** [comment]
I thought about this already :+1:
I also think it's a good idea to support. I plan on refactoring how the settings work anyways to move it into lua. I'll probably add it then.

But I don't think I will remove `g:indent_blankline_filetype` (but you can already turn the plugin off and on with ftplugin, `b:indent_blankline_enabled` is already supported)
