### ISSUE TITLE
Indent lines sometimes shown inside Treesitter Context window

### ISSUE THREAD

**Issue by asiryk** [lukas-reineke/indent-blankline.nvim#960]
### Problem

When scrolling inside deeply nested structures, sometimes indent-blankline draws guides inside the Treesitter Context window.

It does reproduce either with Onedark theme, and default Neovim theme.

I'm using Neovim 0.10.3, and latest version of the plugin.

https://github.com/user-attachments/assets/0acdbc6f-b6e2-43b6-830c-bc96c82fe7c9

https://github.com/user-attachments/assets/4a4bcab7-1640-4b5b-92c1-27404bb0748c

### Steps to reproduce

I'm openin file `neovim/src/nvim/mouse.c` from Neovim repo on commit 487c48ec86.
1. Put cursor at line 530
2. Scroll down with <C-e> till the line ~538
3. Observe indent guides inside TSContext window

I've the following configs for indent-blankline, and for treesitter-context.

```lua
  {
    "lukas-reineke/indent-blankline.nvim",
    main = "ibl",
    opts = {
      scope = { enabled = false },
      debounce = 10,
      indent = {
        char = "│",
        tab_char = "║",
        smart_indent_cap = false,
      },
    }
  },
```

```lua
require("treesitter-context").setup({
  enable = true,
  max_lines = 10, -- How many lines the window should span. Values <= 0 mean no limit.
  patterns = { -- Match patterns for TS nodes. These get wrapped to match at word boundaries.
    default = {
      "function",
      "method",
      "for",
      "while",
      "if",
      "switch",
      "case",
    },
    rust = {
      "loop_expression",
      "impl_item",
    },
    typescript = {
      "class_declaration",
      "abstract_class_declaration",
      "else_clause",
    },
  },
})
```

### Expected behavior

indent-blankline guides shoud not be drawn inside treesitter-context window.

### Neovim version (nvim -v)

0.10.3

**Comment by asiryk** [comment]
I am not sure whether this is an issue with treesitter context, or with the indent-blankline, and I would appreciate any help towards resolving the issue.

**Comment by lukas-reineke** [comment]
This is not a bug in indent-blankline, IBL does not know anything about other plugins.  
You can take a look at `:help ibl.config.exclude` to see how to disable IBL for specific buffers. Not much else I can help you with, sorry.

**Comment by asiryk** [comment]
Ok, got it. Thanks anyway

**Comment by asiryk** [comment]
Okay, so I've checked the buffer that Treesitter Context creates. Its buftype is "nofile", which should be excluded from the indent-blankline. I have default exclude options. When I added exclude buftype "nofile", the issue was still present.


https://github.com/user-attachments/assets/6f93973e-7048-4ccb-b6a3-25d6b0a3be4e
