### ISSUE TITLE
Indent characters not tightly connected between lines

### ISSUE THREAD

**Issue by bool3max** [lukas-reineke/indent-blankline.nvim#97]
* using both `indent-blankline.nvim` and `indentLine` on `neovim 0.5`
* the only setting I've set is `let g:indentLine_char="|"` (standard ASCII vertical line)
* also tried setting `let g:indent_blankline_char="|"`
* also tried a couple different terminal emulators and fonts, same results

The lines however are not tightly connected as they are in the "default settings" screenshot in your `README.md`. How do I achieve that?

![image](https://user-images.githubusercontent.com/12991998/115634171-57eb3e80-a309-11eb-8739-cbe7fd0e6711.png)

**Comment by lukas-reineke** [comment]
> using both indent-blankline.nvim and indentLine on neovim 0.5

If you are on neovim 0.5, you should use the lua branch of indent-blankline.nvim and not use indentLine at all.
It is not needed anymore.

For your problem, if your terminal emulator has line spacing, the normal ascii vertical line doesn't connect.
You can either turn of line spacing in your terminal, or use a different character that is longer. I use this one `│`

**Comment by bool3max** [comment]
Thank you!
