### ISSUE TITLE
GO context patterns

### ISSUE THREAD

**Issue by ahmedkhalf** [lukas-reineke/indent-blankline.nvim#98]
Hello, first, thank you for making this plugin.
I am a native golang speaker, and while editing the list of context patterns to match every possible golang senario I stumbled upon an issue. Assume `let g:indent_blankline_context_patterns = ['if']`.

![image](https://user-images.githubusercontent.com/36672196/116275033-4637ea00-a794-11eb-8ee2-53ff09f8df69.png)

As you can see I am trying to select the if statement, but because of the weird treesitter parsing, it selects **all** if statements. After looking at the TSPlayground I figured I needed to get the `consequence` that was *inside* of the if statement. How can I do this? ALSO, could you please give me some details, or put more docs as to how the patterns work? Because right now im just putting names like function, method and crossing my fingers it gives me good results....

**Comment by lukas-reineke** [comment]
> I figured I needed to get the consequence that was inside of the if statement

Yes that is what you need to do. But you need to add the type of that node, which is `block`.
`consequence` is one of the field names of `if_statement`, and it points to the child node of type `block`.
You can read more about this here, https://tree-sitter.github.io/tree-sitter/using-parsers#node-field-names
Basically, `indent_blankline_context_patterns` matches node types, nothing else. So you want to use the purple names.

As to how it matches, as the name suggests (I hope) it uses lua patterns.
https://www.lua.org/manual/5.1/manual.html#5.4.1
It's similar to regex. You can do things like, `^if`, to only match node types that _start_ with `if`.
No other magic there, it starts at the cursor and walks up the tree until it finds a node type that matches any pattern in the list.

I will add more explanation to the docs to make this clearer.

**Comment by ahmedkhalf** [comment]
Oh wow, I did not know it uses lua patterns, tnx for letting me know, will have a look at the website later this afternoon.
But now my question is: when I try to select block it selects all the blocks such as in for loops, how can I make select blocks that are only inside if statements.

**Comment by lukas-reineke** [comment]
> when I try to select block it selects all the blocks such as in for loops, how can I make select blocks that are only inside if statements.

If they are the same treesitter node type, then there is no way to differentiate them, sorry.

**Comment by ahmedkhalf** [comment]
Okay, I hope things get better, because the way that show context works now is irritating.
